### ISSUE TITLE
path = folders[0]  IndexError: list index out of range

### ISSUE THREAD

**Issue by pasa13142** [serengil/deepface#1]
Hey ! Thanks for this amazing project , I got this error in your functions.py line 74 in detectface, Any idea ?

deepface/commons/functions.py", line 74, in detectFace
    path = folders[0]

IndexError: list index out of range

**Comment by serengil** [comment]
Is opencv installed on your environment? Could you try to run the following code and share the outputs?

import cv2
opencv_home = cv2.__file__
print("opencv_home: ",opencv_home )
folders = opencv_home.split("\\")[0:-1]
print("folders: ",folders)
path = folders[0]
print("path: ",path)

**Comment by serengil** [comment]
Oke, I think I understand the issue. You are running the code on linux, right? Operating system seperator is written for Windows as hard coded. I'll fix this issue tonight.

**Comment by pasa13142** [comment]
Sorry I had to specify that, It is ubuntu 16.04. Looking forward for expansion, 

Sincerely,

**Comment by BalajiB197** [comment]
@serengil Even I faced the above issue I fixed it myself by adding OpenCV face haarcascade path statically.
Now I am facing a different issue, whenever I change the model from default to something else like **OpenFace** or **Facenet** I face the below error.

 fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

OS: Ubuntu 18.04
Installed deepface using setup.py

**Comment by serengil** [comment]
Oke, I understand the problem

In OpenFace.py the url should be url = 'https://drive.google.com/uc?id=1LSe1YCV1x-BfNnfb7DFZTNpv_Q9jITxn'

Similarly, in Facenet.py the url should be https://drive.google.com/uc?id=1971Xk5RwedbudGgTIrGAL4F7Aifu7id1

I'm going to fix those errors tonight. You can run setup.py not to wait.

**Comment by BalajiB197** [comment]
@serengil 
still, I am facing the same issue. Let me know where I am wrong.
Thanks

**Comment by serengil** [comment]
Could you delete file under your home folder + ".deepface/weights/". It seems that it is using the interrupted file. BTW, I assume that you updated the Facenet and OpenFace urls.

**Comment by serengil** [comment]
I updated the pypi distribution. Could you also update your deepface package?

**Comment by serengil** [comment]
Solved in v0.02. I am closing this issue. If the problem still occurs, please reopen the issue.
