### ISSUE TITLE
Get error from "from deepface.commons import distance"

### ISSUE THREAD

**Issue by yasaman-y** [serengil/deepface#1008]
I have no problem until today that I get this error :

Today, for this line in my code, I get following  error:
from deepface.commons import distance
 cannot import name 'distance' from 'deepface.commons' (/usr/local/lib/python3.10/dist-packages/deepface/commons/__init__.py)

from deepface.commons import functions
 cannot import name 'functions' from 'deepface.commons' (/usr/local/lib/python3.10/dist-packages/deepface/commons/__init__.py)
 
 
 I use google colab and I install deepface with following code,
!pip install deepface

until 4 Feb 2024 I did not have any problem

**Comment by serengil** [comment]
Distance metric calculation moved to verification module

from deepface.modules import verification
x = verification.find_euclidean_distance(...)
