### ISSUE TITLE
Question: Can I use verify() to group faces across two images?

### ISSUE THREAD

**Issue by utility-aagrawal** [serengil/deepface#1013]
Hi,

For my use case, I want to group faces if they are of the same person. I understand that I can use verify() for this purpose but what if I have two images and both have two of the same people. I want to identify that both faces are same between images. Is that something I can do using this library? 

Basically, I want to mimic AWS Rekognition's compare_faces() behavior by comparing all faces in one image to all faces in the other image and based on a similarity threshold value, return a list of matches and mismatches.

If not, do you have any alternative recommendations? Thanks!

**Comment by serengil** [comment]
verify compares the most similar ones in that image pair even if same two person are available.

**Comment by utility-aagrawal** [comment]
@serengil , Thanks for your response! I understand that from the readme. I think what I am asking is if it is possible to do many-to-many comparison and return all the matches.

In the code, I see that we are comparing all the faces between two images but only returning the most similar match based on the best distance: https://github.com/serengil/deepface/blob/3690f329496e27ec003efc03f1a5d26c9a967ed7/deepface/modules/verification.py#L154

I would be willing to open a PR if you think this feature would be useful. One thing I would need to understand is how you came up with hardcoded threshold for different model_name, distance_metric combinations. Thanks!

**Comment by serengil** [comment]
I am very satisfied with the current version of verify function. IMO, that feature would not be helpful. Still, thank you for your interest.

Secondly, you can use the distance in the response instead of verified key if you want to use your own threshold.

**Comment by utility-aagrawal** [comment]
@serengil Thanks!

**Comment by utility-aagrawal** [comment]
@serengil , I would like to get your opinion on my use case. I am trying to build a face detection and tracking platform on video data. The problem is that there could be multiple individuals in a frame and I want to be able to track them all across frames. Is that something I can implement using your library? If not, do you have any alternative recommendations?

**Comment by serengil** [comment]
Please checkout stream function, it does similar task

**Comment by utility-aagrawal** [comment]
Thanks a lot @serengil ! I'll check it out.
