### ISSUE TITLE
In version 0.0.84 the "region" field is calculated incorrectly

### ISSUE THREAD

**Issue by AleksMx** [serengil/deepface#1017]
Hello!

I use the library in the following way:
`DeepFace.analyze(img_path = "...", enforce_detection = False, align = False, actions = ['gender', 'emotion'], detector_backend = 'dlib');`

In the latest version, the value of the "y" parameter of the "region" field produces a value that is too large and seems to be counting with an error. In version 0.0.83 everything is fine. Validates on any image.

**Comment by serengil** [comment]
Think this is happening just for dlib.  Will sort it tomorrow.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1020
