### ISSUE TITLE
OpenCV ASCII safeguard no longer necessary?

### ISSUE THREAD

**Issue by nylocx** [serengil/deepface#1019]
Hi,
I just ran into this error and checked by using `cv2.imread("/path/with/aöu.jpg")` and it worked. Is this bug resolved upstream so the restriction can be removed or should I write my own image read function and pass the result to deepface?

https://github.com/serengil/deepface/blame/3690f329496e27ec003efc03f1a5d26c9a967ed7/deepface/modules/preprocessing.py#L53

Kind regards,
Alex

**Comment by serengil** [comment]
different versions of opencv may still have this issue. enforcing user for english chars for file names is a good practice.

**Comment by nylocx** [comment]
The argument that some versions of OpenCV and maybe even some builds on different OS might still have this issue has merit. But I think a lot of use-cases concerning face detection and recognition will stem from consumer based photo collections where the author using your library won't have control over file naming. So I think in the sense of UX you could add a recommendation to the error message suggesting to provide a preloaded numpy array if control over filenames is not possible as you do for example with the force detection parameter.

Kind regards,
Alex

**Comment by serengil** [comment]
Disagree, because people having that issue are raising issue and I have to deal with them all. Having a meaningful business rule will provide no one having this issue.
