### ISSUE TITLE
Cannot download vgg_face_weights.h5

### ISSUE THREAD

**Issue by nicehiro** [serengil/deepface#102]
Hi, your work is really great!
For some reason, I cannot download the vgg_face_weights.h5 file on a server. I need to download it locally and upload it to the server. So could you tell where should I put this file on? 

Thanks.

**Comment by serengil** [comment]
Hello,

1- Download pre-trained weights manually from this url: https://drive.google.com/uc?id=1CPSeum3HpopfomUEK1gybeuIVoeJT_Eo
 BTW, this url is mentioned in here in the repo: https://github.com/serengil/deepface/blob/master/deepface/basemodels/VGGFace.py

2- Go to your home folder. The following code will return your home folder if you don't know where it is.

```
from pathlib import Path
home = str(Path.home())
print(home)
```

For example, my home folder is C:\Users\Sefik

3- Copy pre-trained weights to C:\Users\IS96273\.deepface\weights

Notice that deepface is a hidden folder and it starts with a dot character.

That's all!
