### ISSUE TITLE
API has convert("BGR") when loading a jpg image?

### ISSUE THREAD

**Issue by AmrRahmy** [serengil/deepface#1023]
i am more familiar with java and c# but while debugging an error in the api endpoint, 
/represent or http://localhost:5000/represent

it seems that if you supply a regular image, it errors out with,
```
{
    "error": "Exception while representing: conversion from RGB to BGR not supported"
}
```

looking into it, it seems the file 'preprocessing.py', function 'def load_image(img: Union[str, np.ndarray]) -> Tuple[np.ndarray, str]:'

```
if img.startswith("http"):
        return (
            np.array(Image.open(requests.get(img, stream=True, timeout=60).raw).convert("BGR")),
            # return url as image name
            img,
        )
```

instead of
```
if img.startswith("http"):
        return (
            np.array(Image.open(requests.get(img, stream=True, timeout=60).raw)),
            # return url as image name
            img,
        )
```

as if it's expecting an opencv compatible image or mat? even if the detector_backend is set to 'retinaface'

http request body tried,

```
{
    "model_name": "Facenet",
    "img": "http://192.168.3.90/sharedDirectory/face.jpg",
    "detector_backend": "retinaface",
    "distance_metric": "cosine"
}
```

```
{
    "img": "http://192.168.3.90/sharedDirectory/face.jpg"
}
```

url is valid and accessible.

**Comment by serengil** [comment]
Would you please share the image? Could it be gray scale?

**Comment by AmrRahmy** [comment]
![face](https://github.com/serengil/deepface/assets/9623123/5102393e-be96-4eb3-8908-1b12f1be4cb2)
it's from celebrity faces dataset

**Comment by serengil** [comment]
Oh I see the root cause of the bug. Will fix this today.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1026
