### ISSUE TITLE
DeepFace.find is not accurate somtimes

### ISSUE THREAD

**Issue by Ray8716397** [serengil/deepface#103]
hi,when I run the DeepFace.find, it offen incorrectly recognize faces as someone else in face db,below is my codes,please help me,did i use it in a wrong way?

DeepFace.find('/home/ray/Desktop/facedb/3847.jpg', '/home/ray/Desktop/facedb', model=vggface_model, model_name='VGG-Face', detector_backend='ssd', distance_metric='euclidean_l2')

**Comment by guijuzhejiang** [comment]
We also found the same problem here. Inputting the face will find the wrong object. Is it possible to add a Face feature comparison model like insightface in the API?

**Comment by serengil** [comment]
Setting detector_backend to mtcnn will increase face detection and alignment accuracies. However, this issue does not help me to solve the issue. Could you share your input image and database images?

**Comment by guijuzhejiang** [comment]
The ssd model does not have face alignment. Understand, it is better to change to mtcnn

**Comment by serengil** [comment]
ssd is very successful at face detection but legacy haar cascade performs face alignment within opencv.

on the other hand, mtcnn provides both face detection and eye locations (face alignment)
