### ISSUE TITLE
Find match from dataset continuosly try to add unrecognized images to pickle

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1030]
Just cloned and set up the project locally (Windows 11)
Run `python  .\stream_py` from tests directory and pickle file `representations_vgg_face.pkl` get built.

![image](https://github.com/serengil/deepface/assets/15280851/d84f297d-dea6-4633-95fc-9bce66837a57)

For whatever reason the image file img39.jpg doesn't get any representation hence not added to the pickle file.
As a result the following log line keeps popping

```
24-02-21 18:28:25 - ⚠️ Items ['dataset\\img39.jpg'] were added into dataset just after data source dataset\representations_vgg_face.pkl created!
```

Which is actually not true.
IMO for every processed file would be worth adding a reference into the pickle file with null representation and all values to zero.

**Comment by serengil** [comment]
This is not an issue. It finds that file is missing file in the pickle, but cannot find its embeddings then. That is why, that warning is printed every run.

You should discard that message, it is just warning.

**Comment by serengil** [comment]
You can also delete that image if you do not want to see in the logs.

**Comment by AndreaLanfranchi** [comment]
Thank you for the quick reply.
Probably the workaround of deleting the unrecognized file is ok even if I'm not sure other models can properly detect the face.
Besides leaving the file in place extends the detection phase as on every loop it tries to add the missing file again.
I can try a PR to solve this if you don't mind.

**Comment by serengil** [comment]
Leave it to me, I am currently working on a PR and it may cause conflicts

**Comment by AndreaLanfranchi** [comment]
Sorry ... opened a PR.
Feel free to discard or to cherry pick.

**Comment by serengil** [comment]
Will be happy to merge...
