### ISSUE TITLE
Custom Model Position

### ISSUE THREAD

**Issue by 2310794041** [serengil/deepface#1033]
Deepface has achieved 99% excellence, but cannot customize the location of model files. I think it is not very user-friendly for users with network issues。
`    home = functions.get_deepface_home()

    if os.path.isfile(home + "/.deepface/weights/openface_weights.h5") != True:
        print("openface_weights.h5 will be downloaded...")

        output = home + "/.deepface/weights/openface_weights.h5"
        gdown.download(url, output, quiet=False)`

**Comment by serengil** [comment]
Home can be set with environment variable.
