### ISSUE TITLE
Double (unneeded) face detection in realtime.py

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1037]
Consider [this snippet](https://github.com/serengil/deepface/blob/v0.0.84/deepface/modules/realtime.py#L413-L421) from realtime.py
```
                        dfs = DeepFace.find(
                            img_path=custom_face,
                            db_path=db_path,
                            model_name=model_name,
                            detector_backend=detector_backend,
                            distance_metric=distance_metric,
                            enforce_detection=False,
                            silent=True,
                        )

```
Notice the param `img_path` is valued with `custom_face` which is already the cropped portion of the face detected in the captured frame. Eventually DeeFace.find will enforce an additional face detection on the already cropped face ([here](https://github.com/serengil/deepface/blob/v0.0.84/deepface/modules/recognition.py#L209-L218)) causing unnecessary overhead.
Probably worth create an overload function signature to pass an already detected face.

**Comment by AndreaLanfranchi** [comment]
Or ... just investigated deeper ... set the detector_backend to "skip" so the whole cropped image is recognized as facial_area

**Comment by serengil** [comment]
Right, custom_face is already containing extracted facial area. Here, we can call find function with skip detector backend.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1038

Thank you for your contribution
