### ISSUE TITLE
fastmtcnn sometimes throws TypeError

### ISSUE THREAD

**Issue by iAnanich** [serengil/deepface#1043]
Encountered peculiar case when using `fastmtcnn` detector backend - it raises TypeError that is not caught by deepface wrapper.

Happens at `deepface/detectors/FastMtCnn.py:47` :
```python
        if len(detections[0]) > 0:
```

at this moment, some local variables:
```python
detections = (None, [None], None)
```

**Comment by serengil** [comment]
Which version are you using? In the latest version, this is already sorted.

https://github.com/serengil/deepface/blob/master/deepface/detectors/FastMtCnn.py#L30

**Comment by serengil** [comment]
Can you share your input image?

**Comment by pythonlearner1025** [comment]
ran into the same issue. the latest version does not solve it. updating the code to the following does:
  ```if detections[0] is not None and len(detections) > 0:```

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1059
