### ISSUE TITLE
Expand facial area logic is expanding the facial area twice of expected

### ISSUE THREAD

**Issue by serengil** [serengil/deepface#1045]
As @AndreaLanfranchi raised, current expand facial area logic is expanding w and h 2 * expand_percentage instead of expand_percentage.

Also, one can understand that w * h should be expanded with the given value, but we are aiming to expand w and h separately with that given value. This should be explained in the docstring.

Ref: https://github.com/serengil/deepface/blob/master/deepface/detectors/DetectorWrapper.py#L106

**Comment by serengil** [comment]
Benchmark study on LFW dataset ignores outer areas of face to evaluate human beings performance. That is why, facial recognition researches discard outer area as well. 

If you still want to use a wider area, library lets you to do it but default should be 0.

**Comment by AndreaLanfranchi** [comment]
The problem arises from empirical observation of realtime detection where the the cropped face from a wider area (+30%) is passed to find with "skip" detection.
This in my experience increase a lot false positives (I'm always recognized as mark Zuckerberg) 
Maybe I'm missing something then

**Comment by almirb** [comment]
> The problem arises from empirical observation of realtime detection where the the cropped face from a wider area (+30%) is passed to find with "skip" detection. This in my experience increase a lot false positives (I'm always recognized as mark Zuckerberg) Maybe I'm missing something then

Did you manage to solve this problem? Thanks!

**Comment by serengil** [comment]
@almirb yeah corresponding PR is mentioned also - https://github.com/serengil/deepface/pull/1047
