### ISSUE TITLE
Fatal Exception with libprotobuf in Feature Extractor on Version 0.85

### ISSUE THREAD

**Issue by aku-ato** [serengil/deepface#1046]
### Description
After upgrading to version 0.85 from 0.81, I encounter a fatal exception related to `libprotobuf` when extracting features using the SFace model. The application terminates unexpectedly during the feature extraction process.

### Steps to Reproduce
1. Upgrade the feature extractor application to version 0.85.
2. Run the feature extraction with the following configuration:
   - Model: SFace
   - Detector: mtcnn
   - Normalization: base
   - File: stage/images_sface/lfw/Hugo_Chavez/Hugo_Chavez_0064.jpg
3. Observe the fatal exception related to `libprotobuf`.

### Expected Behavior
The feature extraction process completes without errors, as it did in version 0.81.

### Actual Behavior
The application terminates with a fatal exception from `libprotobuf`, indicating a failure in a check related to target and size.

### Error Message
```
2024/02/27-07:56:38 INFO Extracting features using model: [SFace] detector [mtcnn] normalization: [base] file: [stage/images_sface/lfw/Hugo_Chavez/Hugo_Chavez_0064.jpg]  app=feature-extractor host=Paolos-MBP.Home
[libprotobuf FATAL google/protobuf/message_lite.cc:353] CHECK failed: target + size == res: 
libc++abi: terminating due to uncaught exception of type google::protobuf::FatalException: CHECK failed: target + size == res: 
```

### Environment
- Feature Extractor Version: 0.85
- Operating System: OSX (Macbook pro M1)
- Additional details: 
loguru==0.7.2
nats-py==2.6.0
PyYAML==6.0.1
pydantic==2.5.3
deepface~=0.0.85
prometheus_client==0.19.0
prometheus-async[aiohttp]==22.2.0
psutil==5.9.7
loki-logger-handler==0.1.1
pynvml==11.5.0
facenet-pytorch==2.5.3

### Code
Exception is raised here : ...site-packages/mtcnn/mtcnn.py:342

### Possible Solution
N/A

I did not encounter this issue in version 0.81. Any insights or suggestions for resolving this would be greatly appreciated.

**Comment by serengil** [comment]
I do not think this is related to changes in v85
