### ISSUE TITLE
Preprocessing.py load_image -> load_base64

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1050]
I believe there _might be_ an inconsistency in the logic of parsing for base64 encoded strings.
The format of input should be something like :

`data:image/jpeg;base64,/9j/4AAQS....`

where the image type is clearly indicated right before the comma.
The parser however does not consider this and, don't know how relevant is, could load any valid image while, for example, in streaming.py only jpg, jpeg, png are considered

**Comment by serengil** [comment]
Right, we should raise an error if type of base64 is not one of these types.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1059
