### ISSUE TITLE
Preprocessing.py load_image -> __load_image_from_web

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1051]
The condition to load an image from web is that `img.startswith("http")`
This however is inaccurate as for example file named `http_image_from_google.png`  (considering the path can be relative) would trigger the load from web (not having any chance to be downloaded) while instead should be loaded from cwd

**Comment by serengil** [comment]
Fair enough

**Comment by AndreaLanfranchi** [comment]
If useful you can extract some hints from my modifications [here](https://github.com/AndreaLanfranchi/deepface/commit/a8b66238b2149006a7ff5fc119db2bee038354a7)

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1059
