### ISSUE TITLE
target_size in extract_faces()?

### ISSUE THREAD

**Issue by utility-aagrawal** [serengil/deepface#1054]
Can you please explain what's the parameter target_size used for here: https://github.com/serengil/deepface/blob/87f489320578dce4376e1725fa9c53ed32035af7/deepface/modules/detection.py#L45?

Thank you!

**Comment by serengil** [comment]
ML models expects fixed size inputs. For instance, inputs must be 224x224 for VGG-Face. If you set this arg to 224x224 then image be transformed to 224x224. It is adding black pixels for the transformation.
