### ISSUE TITLE
Verbosity with error message on verify function 

### ISSUE THREAD

**Issue by sanket-tss** [serengil/deepface#1056]
Given an two images are sent to verfiy function in numpy array or base64 format, if in case if the image is not having a face, it does not mentions which image is not having face whether it is img1_path or img2_path
Error message incase base64 is sent: `Face could not be detected in base64 encoded string.`
Error message incase numpy array is sent: `Face could not be detected in numpy array.`

Having detail message whether img1_path or img2_path or both were not having faces will be better.
For now the only way to know which image is not having a face is by doing extract_faces on individual images.

**Comment by serengil** [comment]
Fair enough

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1059
