### ISSUE TITLE
Efficiency: multiple overlaying copies of data in face detection

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1058]
I noticed the process for faces detecion is quite expensive.
For instance when we call `DeepFace.extract_faces` the call stack is
```
DeepFace.extract_faces
  detection.extract_faces
    DetectorWrapper.detect_faces
        [whateverdetector].detect_faces
```                   

- Face detector returns a `List[FacialAreaRegion]`
- DetectorWrapper.detect_faces gets the results and transofrms into a `List[DetectedFaces]`
- detection.extract_faces grabs the previous results and transforms into a `List[Dict[str, Any]]`

I would advise to uniform the return types so the first results (eventually manipulated by intermediate levels) pop up to caller with no transformation.

**Comment by AndreaLanfranchi** [comment]
I also highly suggest to avoid the confusion amongst `extract_faces` and `detect_faces`. My personal choice is to stick always with `detect_faces`

**Comment by serengil** [comment]
Disagree, each one is responsible for different things

**Comment by AndreaLanfranchi** [comment]
Ok. I won't bother you any longer.
Best :)
