### ISSUE TITLE
Weak pickled representations consistency in `find`

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1061]
I believe there might be several improvements in how embeddings for images are stored in pickle file.
Dropping here for reference should you want to address them :

1. [Here a check](https://github.com/serengil/deepface/blob/ad53a9bb2808b895a17b3b76a55b422322b23d03/deepface/modules/recognition.py#L123-L125) is performed to verify the number of columns for the first item matches the number of colums in `df_cols`. Only the number is checked though: not the proper order nor the effective respondence to a data type.
2. The first column on each record of the pickled file is the `identity` which is the combination of the path + file name. This causes any change in the name of the container (e.g. `dataset` -> `haystack`) to completely rebuild the pickle file (as no file is referenced in the pickle file by identity anymore). Probably making the `identity` relative to the position of the pickle file would help. Just a suggestion.
3. Should an image file in dataset be overwritten (keeping the same name) with a totally different content doesn't trigger the reconstruction of the related representation (new and old files are detected only on behalf ot their name)

**Comment by serengil** [comment]
1- We should definetely store column names in pickle

**Comment by serengil** [comment]
2- most probably, we will not do anything for this, because primary key is changed for that case.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1072
