### ISSUE TITLE
Question: Performance Seems Limited

### ISSUE THREAD

**Issue by aaronsuydam** [serengil/deepface#1064]
To the maintainer: this project has been a godsend. I'm super thankful for the work that you've done on this. 

That being said, I was wondering about the `detect_faces()` function in the `deepface/detectors/DetectorWrapper.py` file. Is it constructing a full model every time the function is called? If so, this seems like a huge performance hit (model construction in your library (based on my limited understanding - I am just a student).

Also, does your library iterate through the pictures to be analyzed sequentially? This seems to be the behavior on my system. If so, would this also not be an area that performance could be dramatically improved, especially on newer hardware?

**Comment by serengil** [comment]
No, a face detection model is built once in its first call.

**Comment by serengil** [comment]
Yes, images are being processed sequantially.

**Comment by AndreaLanfranchi** [comment]
Hi @aaronsuydam (and sorry @serengil for dropping uninvited).

Wrt your questions:

- As @serengil already pointed out all instances of detectors (inherited from `Detector`) as well as other analyzing objects (Recognition and Analysis) are singleton_ish_: actually a single instance is instantiated in the `globals` collector
- The flow of analisys deserves imo a bit of explanation: assuming we search `needle` in `haystack` (where the latter is the collection of images in `dataset`) we reckon two phases: 1) All images in dataset are scanned (yes sequentially) to detect faces (if any) and to extract vectorized representation of the detected faces 2) All vectorized data is eventually collected and stored in a single binary file (.pkl) where every vector is associated to the facial area detected and a name reference to the original image. 3) When an image (`needle`) is provided for search in the haystack it undergoes face detection first and if a face is found its vectorized representation is extracted and eventually compared to all the vectorized representations already available as result of point 2)

There are two points performance critical here :

1. The initial seeding of dataset images which, however, is a one time run and eventually processes only new files (or removes deleted ones) from the collection of vectorized representations
2. The effective search of a vectorized representation into the collection of representations from dataset: here the search is linear and single threaded

I'm actually working on a fork that addresses these concerns (not linking directly for due respect) and I think we could all join forces to even improve this brilliant implementation.

**Comment by serengil** [comment]
@AndreaLanfranchi you are more than welcome

@aaronsuydam if you still have questions, do not hesitate to ask or discuss. I am closing issues if they are not real issues, otherwise it becomes harder to follow to current board of the project.

**Comment by aaronsuydam** [comment]
Hey that's totally fair.

I think was misunderstanding the nature of the find function. 

I wonder though if it makes sense to also have a parallelized path when doing the initial extraction/binary creation part. Personally I have a library of tens of thousands of photos I'm working with, and I have really powerful hardware, multiple GPUs and such. It would be nice for that to scale across those.
