### ISSUE TITLE
Question : target_size <-->expand_percentage

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1068]
I am struggling to understand the relationship amongst `target_size` and `expand_percentage` and how they're used in the detection process.

In `detect_faces` (detection.py) both arguments are passed.
However at the moment `face_objs = DetectorWrapper.detect_faces(...` gets invoked only `expand_percentage` is passed and area detected (if any) by the detector implementation has the target_size specified in the model.
Now ... the `detect_faces` assumes as default `target_size` the value (224, 224) (which is also the value specified for opencv detector): if I call the function `detect_faces` (detection.py) passing an expand_percentage, say, 50% I'd expect to have back a facial area that has height and width increased by 50% wrt the size found by the detector **but** as the adjustment caused by `target_size` are applied **after** we get the expanded results from `DetectorWrapper.detect_faces()` it happens that the resulting face image is reverted back to 224x224

I really can't understand the logic.
Please help

**Comment by serengil** [comment]
No relationship between target size and expand percentage.

Expand percentage is passed to detect face which is responsible for finding the facial area's rectangle.

Target size is being used just after facial area extracted and before feeding facial recognition model.

**Comment by AndreaLanfranchi** [comment]
> Target size is being used just after facial area extracted and before feeding facial recognition model.

I have issues with this. I'm talking only facial **detection**: recognition is out of context now.
The problem I have is that the results of detect_faces are not expanded at all.

**Comment by AndreaLanfranchi** [comment]
Or I don't get the `target_size` defined in, for example, `opencv` detection module

**Comment by serengil** [comment]
As I mentioned, target size is just for making image ready for facial recognition in the detection module.

Besides, no target size in opencv or any other detectors: https://github.com/serengil/deepface/blob/master/deepface/detectors/OpenCv.py
