### ISSUE TITLE
Analyze on a batch of images

### ISSUE THREAD

**Issue by tomer-erez** [serengil/deepface#1069]
Hey guys and girls. Is it possible to call deepface analyze over a batch of images? A whole folder with multiple images? I want to use it to predict ages of an entire folder without for or while loops.

**Comment by tomer-erez** [comment]
Also if there are tips to speed up inference time i would love to hear it

**Comment by pyshen-watson** [comment]
same question

**Comment by serengil** [comment]
No, you cannot use barches.
