### ISSUE TITLE
Unable to run deepface load model for VGG on colab

### ISSUE THREAD

**Issue by PatroxGaurab** [serengil/deepface#107]
vgg_face_weights.h5 will be downloaded...

Downloading...
From: https://drive.google.com/uc?id=1CPSeum3HpopfomUEK1gybeuIVoeJT_Eo
To: /root/.deepface/weights/vgg_face_weights.h5

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

<ipython-input-10-2d89a21419de> in <module>()
----> 1 model = VGGFace.loadModel()
      2 input_shape = model.layers[0].input_shape[1:3]

1 frames

/usr/local/lib/python3.6/dist-packages/gdown/download.py in download(url, output, quiet, proxy, speed, use_cookies)
    183             dir=osp.dirname(output),
    184         )
--> 185         f = open(tmp_file, "wb")
    186     else:
    187         tmp_file = None

FileNotFoundError: [Errno 2] No such file or directory: '/root/.deepface/weights/vgg_face_weights.h51j6aav1ktmp'

**Comment by serengil** [comment]
Try to download h5 file manually with the mentioned link, and put it to the mentioned directory.
