### ISSUE TITLE
Mismatching check of argument "actions" in demography.analyze

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1073]
Considering [this code](https://github.com/serengil/deepface/blob/4b3473e023f01a119108862de6d3543915e89194/deepface/modules/demography.py#L99-L105) :
```python
    # validate actions
    if isinstance(actions, str):
        actions = (actions,)

    # check if actions is not an iterable or empty.
    if not hasattr(actions, "__getitem__") or not actions:
        raise ValueError("`actions` must be a list of strings.")
```
given the signature of the function is
```python
def analyze(
    img_path: Union[str, numpy.ndarray],
    actions: Union[tuple, list] = ("emotion", "age", "gender", "race"),
    detector_backend: str = "opencv",
    align: bool = True,
    expand_percentage: int = 0
) -> List[Dict[str, Any]]:
```

there is no chance `if isinstance(actions, str)` ever results True as it can only be either a tuple or a list.
Either extend the signature as `actions: Union[str, tuple, list]` **and** in case of string use the split() function to have it transformed into a list or remove the check for string. Also the second check `if not hasattr(actions, "__getitem__") or not actions:` is redundant as both tuple and list have this attribute.

After all this block results more than enough
```python
    # For each action, check if it is valid
    for action in actions:
        if action not in ("emotion", "age", "gender", "race"):
            raise ValueError(
                f"Invalid action passed ({repr(action)})). "
                "Valid actions are `emotion`, `age`, `gender`, `race`."
            )
```
with one caveat though : string comparison is case sensitive hence should a user pass "Gender" instead of "gender" would have the function to raise

**Comment by serengil** [comment]
more interestingly, when you try this

```python
DeepFace.analyze(img_path="dataset/img1.jpg", actions=("emotion"))
```
even though actions is tuple here

I also added this line into the demography.py

```python
print(f"actions: {actions} ({type(actions)})")
```

it shows actions in the terminal as

```
actions: emotion (<class 'str'>)
```

as i remember, if you set a variable as a tuple with just one item, interestingly python reads it as string.

**Comment by AndreaLanfranchi** [comment]
I see (still learning).
Nevertheless the first check is wrong.
Given a single string is passed as "age,gender" (possible) then this
```
    # validate actions
    if isinstance(actions, str):
        actions = (actions,)
```
transforms actions from
```
>>> actions
'age,gender'
```
to
```
>>> actions
('age,gender',)
```
where the first element of the list is still a comma separated string.
Doing instead
```
    # validate actions
    if isinstance(actions, str):
        actions = actions.split(',')
```
would result in a more appropriate
```
['age', 'gender']
```

**Comment by AndreaLanfranchi** [comment]
... please 🙏 
don't rush to close issues as soon you give a response. Leave some time for debate.

**Comment by serengil** [comment]
no, first check is not wrong

actions = ("age") -> actions is passed as string here. first check re-transforms it to tuple.

actions = ("age", "gender") -> actions is passed as tuple here

actions = "age,gender" -> this is wrong usage
