### ISSUE TITLE
Preprocessing ascii script check is unsuported for python 3.6 

### ISSUE THREAD

**Issue by PlayerNguyen** [serengil/deepface#1075]
## Issues
I am using Python 3.6 to run DeepFace version 0.0.85 (which supported Python >= 3.5.5 from PyPi). However, I got an error as above:

My code was like
```python3
from deepface import DeepFace
import deepface
import sys

print(deepface.__version__)
print(sys.version) 
print(DeepFace.analyze('image1.png'))
```
Trace
```
0.0.85
3.6.9 (default, Mar 10 2023, 16:46:00) 
[GCC 8.4.0]
Traceback (most recent call last):
  File "/home/ubuntu/.../index.py", line 4, in <module>
    print(DeepFace.analyze('image1.png'))
  File "/usr/local/lib/python3.6/dist-packages/deepface/DeepFace.py", line 222, in analyze
    silent=silent,
  File "/usr/local/lib/python3.6/dist-packages/deepface/modules/demography.py", line 126, in analyze
    expand_percentage=expand_percentage,
  File "/usr/local/lib/python3.6/dist-packages/deepface/modules/detection.py", line 79, in extract_faces
    img, img_name = preprocessing.load_image(img_path)
  File "/usr/local/lib/python3.6/dist-packages/deepface/modules/preprocessing.py", line 47, in load_image
    if img.isascii() is False:
AttributeError: 'str' object has no attribute 'isascii'
```

After a quick research, I know that the `str.isascii()` is only supported for Python >= 3.7, which part is missing on Python 3.6.

## Environment
Running on 
- **Ubuntu 18.04 (arch64)** 
- **Python 3.6.9**
- **DeepFace 0.0.85**
## Solution
- Re-implement an check ascii on string instead of using a built-in function (or change the required Python >= 3.7).

**Comment by serengil** [comment]
Right, we should enforce min python 3.7.

**Comment by PlayerNguyen** [comment]
Ps: A little upset since I am trying to use the library on Jetson Nano (which only supported Python 3.6) and is not operating as expected. Hopefully, the older version can alter this issue.

**Comment by serengil** [comment]
If you need to use the library on jetson, and it has to use 3.6, then we should find a workaround.

**Comment by serengil** [comment]
Just updated setup.py in this commit - https://github.com/serengil/deepface/commit/c09e94ecaa5d3a5ed97182ed9daaad98020a1ac6
