### ISSUE TITLE
YOLOv8 is removed from detector_backend list?

### ISSUE THREAD

**Issue by freedom9393** [serengil/deepface#1076]
I was trying to run the model, YOLOv8 as detector_backend and error popped up:

ValueError: invalid detector_backend passed - yolov8

So, YOLOv8 is removed from detector_backend list?

**Comment by serengil** [comment]
Which version are you using?

**Comment by freedom9393** [comment]
0.0.85

Latest one I guess? I just installed it today with command: `pip install deepface`

**Comment by serengil** [comment]
Please run this command

DeepFace.__version__

Is it returning sane version?

Sent from Gmail mobile


9 Mar 2024 Cmt, saat 07:37 tarihinde Scott ***@***.***> şunu
yazdı:

**Comment by freedom9393** [comment]
It shows 0.0.82 👀

**Comment by AndreaLanfranchi** [comment]
Hi @freedom9393,
can you please check the value of `detector_backend` argument is passed exactly as "yolov8" (all lower case, no trailing spaces) ?

**Comment by serengil** [comment]
Okay your version in 82, should be 85. Most probably, you are using an out dated virtual environment.

**Comment by AndreaLanfranchi** [comment]
> Yolo implementation was not available on 82.

Ouch ... that's strange:
[Here](https://github.com/serengil/deepface/blob/v0.0.82/deepface/detectors/DetectorWrapper.py) it says it was

**Comment by serengil** [comment]
Let me re-check from pip source.

**Comment by serengil** [comment]
Right @AndreaLanfranchi , it still should be available on 82

```python
    backends = {
        "opencv": OpenCv.OpenCvClient,
        "mtcnn": MtCnn.MtCnnClient,
        "ssd": Ssd.SsdClient,
        "dlib": Dlib.DlibClient,
        "retinaface": RetinaFace.RetinaFaceClient,
        "mediapipe": MediaPipe.MediaPipeClient,
        "yolov8": Yolo.YoloClient,
        "yunet": YuNet.YuNetClient,
        "fastmtcnn": FastMtCnn.FastMtCnnClient,
    }
```

**Comment by serengil** [comment]
@freedom9393 can you confirm that no whitespace in the detector backend name?

**Comment by freedom9393** [comment]
@serengil, I solved my problem with just using 85. Now, everything is working perfectly

**Comment by serengil** [comment]
Nice to hear
