### ISSUE TITLE
Inline doc mismatch in DeepFace.verify

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1078]
[This line](https://github.com/serengil/deepface/blob/3da81ce549942a9fc83c88f83b7da3fe8a5bf491/deepface/DeepFace.py#L114):

```
        - 'similarity_metric' (str): The chosen similarity metric for measuring distances.
```

Refers imo to argument `distance_metric` (not similarity_metric)

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1083
