### ISSUE TITLE
Tensorflow Vs Tensorflow GPU Confliction 

### ISSUE THREAD

**Issue by YCAyca** [serengil/deepface#108]
I was using deepface without any problem for a face verification project on my CPU. Then I needed to have the project running on GPU and opened a new environment on anaconda using 

conda create -n deepface_gpu python anaconda
pip install tensorflow-gpu==1.9.0
pip install keras==2.2.0
pip install deepface --no-deps

It seems that I can use with mu gpu now. The problem is when I want to use it on CPU and change my environment to the deepface_cpu, it doesnt work anymore. It get this error

 "C:\Users\aktas\anaconda3\envs\deepface_cpu\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name, UnknownError:  Failed to get convolution algorithm. 
UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

It occurs even if I use 
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1" command to disable gpu and its written USING CPU on the beginning of the program. 

I dont understand why I cant use my deepface_cpu environment now. I didnt change anything on it just created a new environment for gpu usage. Do you have any idea?

Another question is that if it exists any way to choose whether to use gpu or cpu in the same project. Because having different environments are not quite compatible to the real life projects. On the other hand there is a tensorflow & tensorflow_gpu confliction in that case I believe

**Comment by myazann** [comment]
I had the exact same error, and was forced to swith to another Facenet implementation which uses Pytorch.

**Comment by YCAyca** [comment]
Yes I already that one too I doesnt work unfortunately

**Comment by serengil** [comment]
Could you please open an issue for tensorflow? We have to wait until it is solved by TF team.
