### ISSUE TITLE
ValueError: The layer sequential has never been called and thus has no defined input.

### ISSUE THREAD

**Issue by HatScripts** [serengil/deepface#1085]
**Python version:** 3.11.3
**Deepface version:** 0.0.86

I'm trying to run the following:

```py
from deepface import DeepFace
import sys

print(DeepFace.__version__)
print(sys.version)

f1 = r"C:\Users\User\Pictures\obama\1.jpg"
f2 = r"C:\Users\User\Pictures\obama\2.jpg"

result = DeepFace.verify(f1, f2)

print(result)
```

But I'm getting the following stack trace:
```
0.0.86
3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
2024-03-10 14:30:01.356725: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1710041401.364761    2820 service.cc:145] XLA service 0x1ce081d36e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1710041401.365463    2820 service.cc:153]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "c:\Users\User\CodeProjects\compare_faces.py", line 15, in <module>
    result = DeepFace.verify(f1, f2)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepface\DeepFace.py", line 125, in verify
    return verification.verify(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepface\modules\verification.py", line 93, in verify
    model: FacialRecognition = modeling.build_model(model_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepface\modules\modeling.py", line 46, in build_model
    model_obj[model_name] = model()
                            ^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepface\basemodels\VGGFace.py", line 45, in __init__
    self.model = load_model()
                 ^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepface\basemodels\VGGFace.py", line 154, in load_model
    vgg_face_descriptor = Model(inputs=model.input, outputs=base_model_output)
                                       ^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\ops\operation.py", line 216, in input
    return self._get_node_attribute_at_index(0, "input_tensors", "input")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\ops\operation.py", line 247, in _get_node_attribute_at_index
    raise ValueError(
ValueError: The layer sequential has never been called and thus has no defined input.
```

Any ideas what's wrong?

**Comment by kunwar-vikrant** [comment]
+1

**Comment by serengil** [comment]
What is your tf version? Posiibly downgrading it will sort the problem.

**Comment by W1947234** [comment]
![image](https://github.com/serengil/deepface/assets/162877238/f003a46d-2517-4fa8-aa7a-be7debc99ab4)
Installing Deepface automatically installs tensorflow 2.16.1. I am trying to figure out how to downgrade TF to 2.7.0... not accustomed to PyCharm/Python

**Comment by serengil** [comment]
```shell
pip uninstall tensorflow && pip install tensorflow==2.7.0
```

**Comment by W1947234** [comment]
> ```shell
> pip uninstall tensorflow && pip install tensorflow==2.7.0
> ```

I already tried and got this:
![image](https://github.com/serengil/deepface/assets/162877238/a6aa57fe-5f27-4ee2-a01a-746c37537515)
I am on Python 3.12, I am trying to check if a different Python version works because I can't install lower version of tensorflow for some reason...

**Comment by W1947234** [comment]
@serengil 
So I have no clue why, because I am new to Python, but on Python 3.12, with tensorflow 2.16.1, it does not work. On Python 3.11, with tensorflow 2.12.0, it works.

**Comment by serengil** [comment]
Seems tf is broken somehow in 2.16.

Nice to hear that it is working on earlier versions.

**Comment by RobespierreXu** [comment]
Seems a Keras version feature.

See the [release note of 2.16](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#release-2160)
**Keras 3.0 will be the default Keras version. You may need to update your script to use Keras 3.0.**

I don't want to change the Keras API, it's annoying.  I followed the Keras doc [continue using Keras 2.0](https://keras.io/getting_started/#tensorflow--keras-2-backwards-compatibility) and make this issue solved.

In short :

1. Make sure to install tf_keras. Note that TensorFlow does not install it by default.
` pip install tf_keras

2. Export the environment variable TF_USE_LEGACY_KERAS=1.
There are several ways to export the environment variable:
- You can simply run the shell command `export TF_USE_LEGACY_KERAS=1` before launching the Python interpreter.
- You can add export `TF_USE_LEGACY_KERAS=1` to your .bashrc file. That way the variable will still be exported when you restart your shell.
- You can start your Python script with:
`import os;
 os.environ["TF_USE_LEGACY_KERAS"] = "1" `
These lines would need to be before any `import tensorflow` statement.

**Comment by serengil** [comment]
@RobespierreXu 

1- tf use legacy keras environment variable is already set in deepface: https://github.com/serengil/deepface/blob/329606ffe83d5dd2b0ed97bcb1950cd010c93ea2/deepface/DeepFace.py#L8

2- tf-keras is enforced to be installed: https://github.com/serengil/deepface/blob/329606ffe83d5dd2b0ed97bcb1950cd010c93ea2/deepface/commons/package_utils.py#L55

So, if you upgrade deepface its latest, this should be sorted.
