### ISSUE TITLE
Question: basemodel DbLib.py

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1090]
Consider [this line](https://github.com/serengil/deepface/blob/dea697c6ec5b89375cdbc376aa680a10f4231c42/deepface/basemodels/Dlib.py#L67) in DbLib.py
```python
self.layers = [DlibMetaData()]
```

What exactly is this for ? (member layers is not accessed anywhere)

**Comment by serengil** [comment]
In earlier versions of deepface, we were grabbing target size from .layers.input_shape. Keras models have this argument but Dlib does not have. That is why, I added it but it is not being used anymore. 

Same thing is available in SFace, too: https://github.com/serengil/deepface/blob/dea697c6ec5b89375cdbc376aa680a10f4231c42/deepface/basemodels/SFace.py#L84

TLDR: not being used anymore, can be deleted.

**Comment by AndreaLanfranchi** [comment]
Thank you.
