### ISSUE TITLE
Invalid check for cv2 version

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1096]
Consider [this code](https://github.com/serengil/deepface/blob/master/deepface/detectors/YuNet.py#L26-L28) :
```python
        opencv_version = cv2.__version__.split(".")
        if len(opencv_version) > 2 and int(opencv_version[0]) == 4 and int(opencv_version[1]) < 8:
            # min requirement: https://github.com/opencv/opencv_zoo/issues/172
            raise ValueError(f"YuNet requires opencv-python >= 4.8 but you have {cv2.__version__}")
```
It should expect to raise if version < "4.8.x" but :
- Should `cv2.__version__` return anything which is not properly separated by dots (damaged package) this does not raise
- If `cv2.__version__` is like "3.x.x." this does not raise too (in fact it implies major MUST be equal to 4 to enter the condition

imo the proper code should be
```python
opencv_version = cv2.__version__.split(".")
if not len(opencv_version) >= 2:
    raise [...]

opencv_version_major = int(opencv_version[0])
opencv_version_minor = int(opencv_version[1])
if opencv_version_major < 4 or (opencv_version_major == 4 and opencv_version_minor < 8):
    raise [...]
```

**Comment by serengil** [comment]
fair enough

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1103
