### ISSUE TITLE
Unneeded extra image.copy() in YuNet detection

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1097]
Consider [this code](https://github.com/serengil/deepface/blob/master/deepface/detectors/YuNet.py#L66-L75):

```python
        height, width = img.shape[0], img.shape[1]
        # resize image if it is too large (Yunet fails to detect faces on large input sometimes)
        # I picked 640 as a threshold because it is the default value of max_size in Yunet.
        resized = False
        if height > 640 or width > 640:
            r = 640.0 / max(height, width)
            original_image = img.copy()
            img = cv2.resize(img, (int(width * r), int(height * r)))
            height, width = img.shape[0], img.shape[1]
            resized = True
```

`original_image` is assigned a copy (deep) of `img` which creates a new image in memory.
A shallow copy is more than enough like
```python
           [...]
            r = 640.0 / max(height, width)
            original_image = img
            img = cv2.resize(img, (int(width * r), int(height * r)))
```

so `img` is reassigned the resized image while `original_image` keeps reference to original input.

**Comment by AndreaLanfranchi** [comment]
Actually there's not even need to keep `original_image`. It's value (although restored in `img`) is not returned.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1103
