### ISSUE TITLE
model is so large

### ISSUE THREAD

**Issue by bleakie** [serengil/deepface#11]
I think mobilenet-V2 is more useful

**Comment by serengil** [comment]
what is the problem exactly? this framework supports 4 different face recognition models: VGG-Face, Google FaceNet, OpenFace and Facebook DeepFace. You want to adopt different models than these?

**Comment by bleakie** [comment]
I find Facial Attribute Analysis model is so large

**Comment by serengil** [comment]
You got a memory problem?

**Comment by wyuzyf** [comment]
the action: age model is so large , use gpu 14397MiB, why?

**Comment by serengil** [comment]
Please try disable GPU as illustrated below. You should put this block before calling deepface.

import os
os.environ["CUDA_VISIBLE_DEVICES"]=""

**Comment by wyuzyf** [comment]
thank you a lot ,i have solved this problem

**Comment by serengil** [comment]
So, this issue is closed

**Comment by serengil** [comment]
wyuzuf confirmed that issue is solved.

**Comment by bleakie** [comment]
The performance of Facial Attribute Analysis？

**Comment by serengil** [comment]
@bleakie what is your problem exactly? could you share your input and error as well?

**Comment by bleakie** [comment]
The accurate of gender and age(MAE)

**Comment by serengil** [comment]
Age and gender models are based on this tutorial: https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/

Age model has ± 4.65 age error.

Gender model has 97.44% accuracy, 96.29% precision, 95.05% recall.

These results are satisfactory based on the reference academic paper.
