### ISSUE TITLE
Not able to install package from PyPI

### ISSUE THREAD

**Issue by codal-vprajapati** [serengil/deepface#110]
Getting error like this with Python3.5
**ERROR: Could not find a version that satisfies the requirement deepface (from versions: none)
ERROR: No matching distribution found for deepface**

Also getting error like and it stopped executing
**/tmp/tmpgzzshuxx.py changed**

**Comment by serengil** [comment]
Deepface requires python 3.6 min. You have to upgrade your python environment.
