### ISSUE TITLE
Find search with standalone pickle representation file?

### ISSUE THREAD

**Issue by kushthaker** [serengil/deepface#1102]
Dear Sefik, huge thanks for this awesome library!

Quick one, in the find search, is there a way to continue with the created pickle representation file, but remove the image objects in the `db_path` directory? It seems the files still need to be persisted based on the logic in `recognition.py` . Is it possible to create this representation database and continue to use find without reference to the disk images? I'd like to create different representation databases for different test cases without the need for the original disk images. I don't know if this is by design. How do you recommend to achieve this - is it a common request?  

```
    # Enforce data consistency amongst on disk images and pickle file
    must_save_pickle = False
    new_images = list(set(storage_images) - set(pickled_images))  # images added to storage
    old_images = list(set(pickled_images) - set(storage_images))  # images removed from storage
```

**Comment by serengil** [comment]
With current design, pickle is up to date with the images in a folder. If you add, remove or update an image in that folder, pickle will be updated in the next run.

**Comment by serengil** [comment]
You may consider to use a vector database e.g. https://sefiks.com/2024/01/01/billion-scale-fast-vector-similarity-search-with-spotify-voyager/

**Comment by serengil** [comment]
will not fix
