### ISSUE TITLE
dlib weights download fails due to issue with gdown

### ISSUE THREAD

**Issue by goodones-mac** [serengil/deepface#1109]
gdown is checking 'content-type' in requests to handle google docs when the variable is not there for some reason.  The url you generate doesn't need gdown to download your weights bzip file from dlib, it's a raw http url, so you can work around this issue by using requests or something similar to directly download your weights file.  This is what we wrote / run in the terminal of our google collab notebook to work around it:

```
# bug workaround in deepface's model download code for dlib
!cd /root/.deepface/weights
!wget http://dlib.net/files/shape_predictor_5_face_landmarks.dat.bz2
!bzip2 -d shape_predictor_5_face_landmarks.dat.bz2
```

code that ran into the issue
```
result = DeepFace.verify(photo,
                      profile_photo,
                      model_name = 'Facenet512',
                      detector_backend = 'dlib',
                      distance_metric='euclidean_l2',
                      align=True,
                      enforce_detection = False)
```

**Comment by serengil** [comment]
Of course, you can download anything with requests but the reason why I prefer gdown is its simplicity.

I think the issue you have is temporary.

**Comment by serengil** [comment]
Closed because this is not an issue

**Comment by zopieux** [comment]
This is still an issue as of today. Crashes when trying to check content-type header, which might not be present. I don't understand why this is “not a issue”.

**Comment by serengil** [comment]
This is not an issue because backend url is still up. The reason why you cannot download is because of your environment (proxy or firewall). Only tickets requiring code change are opened to follow backlog of the project.
