### ISSUE TITLE
[Question] FastMtCnn detector : _xyxy_to_xywh

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1114]
According to documentation the returned box(es) are represented as x;y coordinates of the top left corner and x:y coordinates of the bottom right corner. However the function _xyxy_to_xywh does this:
```python
def _xyxy_to_xywh(self, xyxy: Union[list, tuple]) -> list:
        """
        Convert xyxy format to xywh format.
        """
        x, y = xyxy[0], xyxy[1]
        w = xyxy[2] - x + 1
        h = xyxy[3] - y + 1
        return [x, y, w, h]
```
which clearly adds 1 point to the width and heigth values.
Why ?

Assuming a box defined as [[5,3],[15,31]] the resulting width and height should be respectively15-5==10 and 31-3== 28
Why are they increased to 11 and 29 respectively ?

**Comment by serengil** [comment]
Yeah, w and h seem to be greater 1 pixel than they should be.

Most probably, that one pixel would not change results but still the calculation is wrong.

**Comment by AndreaLanfranchi** [comment]
> Most probably, that one pixel would not change results but still the calculation is wrong.

Well actually that extra 1 might cause a problem when the coordinates of the bottom right corner coincide with image boundaries. Adding 1 would make the box to lay outside the image dimensions.
Unlikely to happen but nevertheless possible.

**Comment by serengil** [comment]
No I mean it does not mean anything even if it would not change anything. Wrong is wrong. Must be sorted.

**Comment by serengil** [comment]
Handled with PR - https://github.com/serengil/deepface/pull/1115
