### ISSUE TITLE
ValueError: The layer sequential has never been called and thus has no defined input.

### ISSUE THREAD

**Issue by mahmoudsallem** [serengil/deepface#1116]
![Screenshot 2024-03-17 124907](https://github.com/serengil/deepface/assets/77209720/b1615b45-a839-400f-abbf-c1ed88894c22)

**Comment by mahmoudsallem** [comment]
I install the lib using pip command line and when the template is downloaded I get this problem

**Comment by serengil** [comment]
Exception is not coming from deepface, it is coming from keras. Seems your installation is not okay.

**Comment by mahmoudsallem** [comment]
What version of keras does this lib need?

**Comment by serengil** [comment]
Tf 2.9 and keras 2.9 are working for me

**Comment by mahmoudsallem** [comment]
can you apply this in your terminal and send my python version and requirements file

pip install pip-chill

and pip-chill > Desktop\requirements.txt

**Comment by sourenpash** [comment]
side note if you run it on collab you avoid this, its what I ended up doing.
