### ISSUE TITLE
Manually generate embedded vector for a face region

### ISSUE THREAD

**Issue by ilovebioz** [serengil/deepface#1117]
hi,

I would like to ask about how to use deepface project to manually generate the embedded vector for a custom face region. 
I think about this function since I need to add the face manually when the face detection module missing the face during detection.
for the missing face, we can manually identify it and extract the embedded vector.

Thank you very much

**Comment by serengil** [comment]
You can use embedding function: https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L316

If you set its img_path argument to your face region as numpy array, and detector backend to "skip", then it will generate embedding from the feed image.

The keypoint here is that facial recognition models expect fixed size inputs. For instance, your input image must be 224, 224, 3 for [VGG-Face](https://github.com/serengil/deepface/blob/master/deepface/basemodels/VGGFace.py#L47). If you would not resize your region to that expected size, then you will have an exception.
