### ISSUE TITLE
DeepFace.analyze crashes when running it multiple times

### ISSUE THREAD

**Issue by fmarquezg** [serengil/deepface#112]
I tried running this for different pictures (all 400x400) `DeepFace.analyze(dir_file, actions = ['age', 'gender', 'race'])`

I get these warning messages.

`WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000029D348665E8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
`

After few minutes, my terminal will crash

**Comment by serengil** [comment]
You should not call either analyze or verify functions in a for loop. You should pass an array including multiple items instead of for loop.

`objs = DeepFace.analyze(["img1.jpg", "img2.jpg", "img3.jpg"]) `
