### ISSUE TITLE
Possible inconsistency and wrong result in eyes detection for OpenCV detector

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1123]
### Note !! This needs investigation

Consider [this code](https://github.com/serengil/deepface/blob/22eebc0a0134c6f143053c30c05d74fef73e8eeb/deepface/detectors/OpenCv.py#L54-L55):

```python
            for (x, y, w, h), confidence in zip(faces, scores):
                detected_face = img[int(y) : int(y + h), int(x) : int(x + w)]
                left_eye, right_eye = self.find_eyes(img=detected_face)
                facial_area = FacialAreaRegion(
                    x=x,
                    y=y,
                    w=w,
                    h=h,
                    left_eye=left_eye,
                    right_eye=right_eye,
                    confidence=(100 - confidence) / 100,
```

It appears that `self.find_eyes` is **called providing as input the cropped face from original image** not the original image itself.
As a result, I believe, the coordinates of the left and right eye are relative to size of the cropped face which is smaller than the original image but are added to FacialAreaRegion as they are returned from `find_eyes` (i.e. not normalized to the size of the original image). As a result, if the coordinates of the eyes are used to draw circles around the eyes in the original picture, their position would be completely off.

This to me appears as a wrong result as it seems other detectors return the point coordinates of eyes as relative to the dimensions of the original image.

**Comment by serengil** [comment]
The purpose of finding eyes is to align faces according to their positions. Angle calculation is still fine and we are able to align detected faces with the current logic. But eye locations are set incorrectly. We should add the detected face's x and y coordinates to eye coordinates. But as i mentioned, this will not change facial recognition accuracy.

**Comment by serengil** [comment]
After change, eye coordinates can be highlighted correctly on the image.

Before change:

<img width="460" alt="Screen Shot 2024-03-19 at 08 25 39" src="https://github.com/serengil/deepface/assets/18491038/eb806b8b-d206-4d99-a359-a468b5812bbb">

As seen, left and right eyes are not in the detected face.

After change:

<img width="468" alt="Screen Shot 2024-03-19 at 08 30 09" src="https://github.com/serengil/deepface/assets/18491038/4ddc0a37-25ad-4d5f-9180-70f5ff6d849d">

Now, they are in the detected face area.
