### ISSUE TITLE
how to enhancing the working time of verify and find function

### ISSUE THREAD

**Issue by bhushanjha716** [serengil/deepface#1125]
i am working on a project which uses the face recognition on a large dataset i am using deepface library for it but its taking so much time to do in youtube videos you show that way but in new version of deepface no option for it can you answer me @serengil

**Comment by serengil** [comment]
Cannot understand the problem. Be more clear please.

**Comment by bhushanjha716** [comment]
i working on a project called employee attendance with face recognition i am using deepface for face recognition ,when register a new employee it checks in database if this employee registered or not when it check it takes so much time

**Comment by bhushanjha716** [comment]
https://www.youtube.com/watch?v=Hrjp-EStM_s
in this video you showed how to work large scale data but in new version these things are not available

**Comment by bhushanjha716** [comment]
this is the whole code:
import os
import pandas as pd
import numpy as np
from datetime import datetime
import csv
from deepface import DeepFace
import base64
import cv2
def bs64_to_frame(bs64):
        decoded_bytes = base64.b64decode(bs64)
        decoded_image = np.frombuffer(decoded_bytes, dtype=np.uint8)
        decoded_image = cv2.imdecode(decoded_image, flags=cv2.IMREAD_COLOR)
        return decoded_image

def register(bs64,id,name,dept):
    known_ids=[]
    check2=[]
    count=False
    path='dataset'
    excelDataSet='Employee_details.csv'
    l1 = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.jpg')]
    frame=bs64_to_frame(bs64)
    if frame is not None:
        for i in l1:
            known_ids.append(os.path.splitext(os.path.basename(i))[0])
            check=DeepFace.verify(i,frame,model_name='Facenet',normalization='Facenet',detector_backend='dlib')
            print(check)
            check2.append(check['verified'])
        if True in check2:
            return 'your data is already in dd!'
        else:
            if id in known_ids:
                return 'your data is already in dd!!!!!'
            else:     
                count=True
                cv2.imwrite(path+f'/{id}.jpg',frame)  
        if not os.path.exists(excelDataSet):
            with open(excelDataSet,'w') as ff:
                csveriting = csv.writer(ff)
                csveriting.writerow(['EmployeeID','Emp_name','Department'])
                csveriting.writerow([id,name,dept])
        else:
            with open(excelDataSet,'a') as ff:
                csvreading=pd.read_csv(excelDataSet)
                csveriting = csv.writer(ff)
                for i in range(len(csvreading)):
                    if csvreading['EmployeeID'].values[i]==id and count==True:
                        return 'your details already in d'
            
                    else:
                        csveriting.writerow([id,name,dept])
                        break
        df = pd.read_csv(excelDataSet)
        df.to_csv(excelDataSet, index=False)
        print(df)
    else:
        return 'Unable to process image'

    return str("Save") 
its taking so much time to verify on only five to six images

**Comment by bhushanjha716** [comment]
this is the code below:
`import os
import pandas as pd
import numpy as np
from datetime import datetime
import csv
from deepface import DeepFace
import base64
import cv2
def bs64_to_frame(bs64):
        decoded_bytes = base64.b64decode(bs64)
        decoded_image = np.frombuffer(decoded_bytes, dtype=np.uint8)
        decoded_image = cv2.imdecode(decoded_image, flags=cv2.IMREAD_COLOR)
        return decoded_image

def register(bs64,id,name,dept):
    known_ids=[]
    check2=[]
    count=False
    path='dataset'
    excelDataSet='Employee_details.csv'
    l1 = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.jpg')]
    frame=bs64_to_frame(bs64)
    if frame is not None:
        for i in l1:
            known_ids.append(os.path.splitext(os.path.basename(i))[0])
            check=DeepFace.verify(i,frame,model_name='Facenet',normalization='Facenet',detector_backend='dlib')
            print(check)
            check2.append(check['verified'])
        if True in check2:
            return 'your data is already in dd!'
        else:
            if id in known_ids:
                return 'your data is already in dd!!!!!'
            else:     
                count=True
                cv2.imwrite(path+f'/{id}.jpg',frame)  
        if not os.path.exists(excelDataSet):
            with open(excelDataSet,'w') as ff:
                csveriting = csv.writer(ff)
                csveriting.writerow(['EmployeeID','Emp_name','Department'])
                csveriting.writerow([id,name,dept])
        else:
            with open(excelDataSet,'a') as ff:
                csvreading=pd.read_csv(excelDataSet)
                csveriting = csv.writer(ff)
                for i in range(len(csvreading)):
                    if csvreading['EmployeeID'].values[i]==id and count==True:
                        return 'your details already in d'
            
                    else:
                        csveriting.writerow([id,name,dept])
                        break
        df = pd.read_csv(excelDataSet)
        df.to_csv(excelDataSet, index=False)
        print(df)
    else:
        return 'Unable to process image'

    return str("Save") 
`
its taking so much time to verify on only five to six images

**Comment by bhushanjha716** [comment]
```python
import os
import pandas as pd
import numpy as np
from datetime import datetime
import csv
from deepface import DeepFace
import base64
import cv2
def bs64_to_frame(bs64):
        decoded_bytes = base64.b64decode(bs64)
        decoded_image = np.frombuffer(decoded_bytes, dtype=np.uint8)
        decoded_image = cv2.imdecode(decoded_image, flags=cv2.IMREAD_COLOR)
        return decoded_image

def register(bs64,id,name,dept):
    known_ids=[]
    check2=[]
    count=False
    path='dataset'
    excelDataSet='Employee_details.csv'
    l1 = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.jpg')]
    frame=bs64_to_frame(bs64)
    if frame is not None:
        for i in l1:
            known_ids.append(os.path.splitext(os.path.basename(i))[0])
            check=DeepFace.verify(i,frame,model_name='Facenet',normalization='Facenet',detector_backend='dlib')
            print(check)
            check2.append(check['verified'])
        if True in check2:
            return 'your data is already in dd!'
        else:
            if id in known_ids:
                return 'your data is already in dd!!!!!'
            else:     
                count=True
                cv2.imwrite(path+f'/{id}.jpg',frame)  
        if not os.path.exists(excelDataSet):
            with open(excelDataSet,'w') as ff:
                csveriting = csv.writer(ff)
                csveriting.writerow(['EmployeeID','Emp_name','Department'])
                csveriting.writerow([id,name,dept])
        else:
            with open(excelDataSet,'a') as ff:
                csvreading=pd.read_csv(excelDataSet)
                csveriting = csv.writer(ff)
                for i in range(len(csvreading)):
                    if csvreading['EmployeeID'].values[i]==id and count==True:
                        return 'your details already in d'
            
                    else:
                        csveriting.writerow([id,name,dept])
                        break
        df = pd.read_csv(excelDataSet)
        df.to_csv(excelDataSet, index=False)
        print(df)
    else:
        return 'Unable to process image'

    return str("Save") 
``` `

**Comment by serengil** [comment]
That is an old video. You need to call verify function in a for loop.

**Comment by bhushanjha716** [comment]
i am calling verify function in for loop at line 26 , on five to six images its taking around 15 seconds thats to much @serengil

**Comment by serengil** [comment]
Add this somewhere before for loop. Verify will take shorter.

```
_ = DeepFace.build_model("Facenet")
```

**Comment by serengil** [comment]
if your concern is speed, try default detector instead of mtcnn.

```python
check = DeepFace.verify(i, frame, model_name='Facenet')
```

**Comment by bhushanjha716** [comment]
i already do that not so much change here is the output with default detector :
10.64
1.77
Your data is already in!
Execution time: 42.3273 seconds
PS C:\Users\bhushan\Desktop\face_recognition system (2)> 
i saw your that video i mentioned above that logic is very nice that type of something can you tell me @serengil

**Comment by serengil** [comment]
How many images are you processing for that time?

**Comment by bhushanjha716** [comment]
around six to seven

**Comment by serengil** [comment]
In that video, find function is being used not verify. You cannot make this faster until you invest a more powerful hardware.

**Comment by bhushanjha716** [comment]
in new version of deepface find function doesn't have posintional argument for model which is you done that in your video

**Comment by bhushanjha716** [comment]
in other device i run it on gpu but in that device its take around 15 seconds

**Comment by serengil** [comment]
okay, with find function, you will have much faster results.

**Comment by bhushanjha716** [comment]
> you do not have to set model anymore in find function, just set model_name string.

i does but that is not faster anymore in your video it takes less than 2 seconds and here its taking so much time

**Comment by serengil** [comment]
in your first run, yes it is slow. but in second run, if the pickle is ready, then it should be much faster. I can find an identity in 100 faces in just 1-2 seconds.

**Comment by bhushanjha716** [comment]
in my project around 60 to people images are there in dataset and if this that so much time than my project is not so efficient please do something

**Comment by serengil** [comment]
how long find function takes? 1st time and 2nd time results please.

**Comment by bhushanjha716** [comment]
find function duration 36.67322540283203 seconds
1st time it takes this 
find function duration 5.9738850593566895 seconds
2nd time it takes this

**Comment by bhushanjha716** [comment]
yes i am doing that before find function
and opencv as a detector backend?

**Comment by serengil** [comment]
so, that is all what you can do. you cannot decrease time more.

**Comment by bhushanjha716** [comment]
@serengil  thanks sir for your concern its so helpful ,you replied many times thank you for your time
