### ISSUE TITLE
cannot import name 'functions' from 'deepface.commons'

### ISSUE THREAD

**Issue by haseebkhawaja** [serengil/deepface#1132]
I am just working on one of jupyter file namely Face-Recognition-SQL.ipynb and placed in the repo at " https://github.com/serengil/tensorflow-101/blob/master/python/Face-Recognition-SQL.ipynb "
 
but facing a problem of import Error ""(ImportError: cannot import name 'functions' from 'deepface.commons' (/home/gpu-ain/.local/lib/python3.8/site-packages/deepface/commons/__init__.py))""
**the error is at "from deepface.commons import functions"**

I have installed the deepface using "pip install deepface"
and this import is working well from "deepface import DeepFace"

 Looking for the suggestion to resolve ...
thanks

**Comment by serengil** [comment]
That function is retired.

Instead of this

```python
    #detect and align
    facial_img = functions.preprocess_face(facial_img_path, target_size = (160, 160))
    
    #represent
    embedding = model.predict(facial_img)[0]
 ```

You should use this as 

```python
embedding = DeepFace.represent(facial_img_path, model_name="Facenet")[0]["embedding"]
```

**Comment by haseebkhawaja** [comment]
Thanks @serengil
