### ISSUE TITLE
trouble with tensorflow 2.16

### ISSUE THREAD

**Issue by erimsatar** [serengil/deepface#1135]
When I try to use VGG-Face as model ,it cannot download it and here is the issue:
File "site-packages/deepface/modules/modeling.py", line 57, in build_model
    model_obj[model_name] = model()
                            ^^^^^^^
  File "site-packages/deepface/basemodels/VGGFace.py", line 45, in __init__
    self.model = load_model()
                 ^^^^^^^^^^^^
  File "site-packages/deepface/basemodels/VGGFace.py", line 154, in load_model
    vgg_face_descriptor = Model(inputs=model.input, outputs=base_model_output)
                                       ^^^^^^^^^^^
  File "site-packages/keras/src/ops/operation.py", line 228, in input
    return self._get_node_attribute_at_index(0, "input_tensors", "input")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/keras/src/ops/operation.py", line 259, in _get_node_attribute_at_index
    raise ValueError(
ValueError: The layer sequential has never been called and thus has no defined input.

**Comment by serengil** [comment]
what is your deepface version?

**Comment by erimsatar** [comment]
Latest 0.0.89

**Comment by serengil** [comment]
interesting, i was expecting this to be sorted in 89. Can you run the following code please?

```python
from deepface import DeepFace
print(DeepFace.__version__)
```

**Comment by erimsatar** [comment]
0.0.89

**Comment by erimsatar** [comment]
Yes I have tf_keras version 2.16.0.

**Comment by serengil** [comment]
unfortunately, i cannot reproduce the trouble with tf 2.16.

you may consider to downgrade tf to 2.15 not to have that exception.

**Comment by erimsatar** [comment]
I am using tensorflow 2.16.1 and tf_keras 2.16.0. Should I downgrade both?

**Comment by serengil** [comment]
Just tensorflow please

**Comment by serengil** [comment]
Sometimes a virtual environment may have different versions of dependencies. To confirm this is not happening, would you please run the following program?

```python
import tensorflow as tf
assert tf.__version__ == "2.16.1"

import tf_keras
assert tf_keras == "2.16.0"

from deepface import DeepFace
assert DeepFace.__version__ == "0.0.89"
```

**Comment by serengil** [comment]
closed due to inactivity
