### ISSUE TITLE
Using knn or svm for face matching

### ISSUE THREAD

**Issue by nanguantong** [serengil/deepface#1141]
Could you please use the knn or svm for face matching? While the distance_metric euclidean or cosine are not accurate in some cases.

**Comment by serengil** [comment]
Knn is being used in the find function already.

No plan for svm support.

**Comment by nanguantong** [comment]
> Knn is being used in the find function already.
> 
> No plan for svm support.

Not found knn in the find function.

Something like [face_recogonize knn](https://github.com/ageitgey/face_recognition/blob/master/examples/face_recognition_knn.py) to train the base images.
