### ISSUE TITLE
from deepface.commons import distance not working?

### ISSUE THREAD

**Issue by freedom9393** [serengil/deepface#1142]
I wanted to use findCosineDistance, and when I run this:

`from deepface.commons import distance`

it shows:

`ImportError: cannot import name 'distance' from 'deepface.commons' (/home/real/miniconda3/envs/face_recognition_v1/lib/python3.9/site-packages/deepface/commons/__init__.py)`

**Comment by serengil** [comment]
Because it is moved under

from deepface.modules.verification import find_cosine_distance
