### ISSUE TITLE
Question about basemodel's find_embeddings

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1148]
I am struggling to understand the logic for `find_embeddings` implemented in each basemodel.
In detail my doubt is as follows: every model implements an `input_shape` size (for example ArcFace has 112) but, unless I miss something, when face images are passed to the function they're not resized to the expected dimensions. So the question is: do those models perform a resize of the images or should we enforce the resizing of the face image **before** feeding it to `find_embeddings` ?

**Comment by AndreaLanfranchi** [comment]
In other words ... does the model expects the input image to be the expected dimensions ?

**Comment by serengil** [comment]
with current implementation, output of detection module is being fed to represent module. resizing is handled in detection module. 

short answer is yes. model expects the input image resized to expected dimensions.

**Comment by AndreaLanfranchi** [comment]
Sorry but I don't fully understand.

>with current implementation, output of detection module is being fed to represent module. resizing is handled in detection module.

Output is the dimension of the List[float] while input should be the dimension of the image. Is this right ?

> short answer is yes. model expects the input image resized to expected dimensions.

So we need to resize it first ?

**Comment by serengil** [comment]
Yes, we are resizing the image first: https://github.com/serengil/deepface/blob/master/deepface/modules/detection.py#L126

If you feed an image with different shape to a FR model, then you will have an exception.

**Comment by AndreaLanfranchi** [comment]
> Yes, we are resizing the image first: https://github.com/serengil/deepface/blob/master/deepface/modules/detection.py#L126

I don't believe that is right for several reasons.
- target_size is disjoint from input_shape of base models 
- target_size is optional (eventually defaulted to 224/224) which is different from, say, ArcFace where the expected input shape is 112/112)

> If you feed an image with different shape to a FR model, then you will have an exception.

Apparently not true. Due to the above where target size is 224/224 feeding it to a ArcFace model where the input_shape is expected 112/112 does not raise any exception.

**Comment by serengil** [comment]
1- No, it is not disjoint. For instance, in verify function, faces extracted with the models input shape as target size. So, already resized images are being fed to the representation module.

https://github.com/serengil/deepface/blob/master/deepface/modules/verification.py#L231

2- the reason why you are not getting error, resizing guaranteed in representation. If you try to call tensorflow model directly with different shape, you will get exception.

https://github.com/serengil/deepface/blob/master/deepface/modules/representation.py#L66

**Comment by serengil** [comment]
For instance, ArcFace expects 112x112 but we feed 224x224 here

```python
import numpy as np
from deepface import DeepFace

img = DeepFace.extract_faces("target.jpg", target_size=(224, 223))[0]["face"]
img = np.expand_dims(img, axis=0)

# now img is 1,224,224,3

# build ArcFace model - this expects 1,112,112,3 inputs
model = DeepFace.build_model("ArcFace")
model.model.predict(img)
```

This throws ` ValueError: Input 0 of layer "ResNet34" is incompatible with the layer: expected shape=(None, 112, 112, 3), found shape=(None, 224, 223, 3)`

So, if you feed an image with different shape to a FR model, then you will have an exception.

**Comment by serengil** [comment]
Also, when you call verify, find or represent functions then target_size is set by the library. Even if it is optional, it is already set.

**Comment by AndreaLanfranchi** [comment]
Oh I see where is the confusion.
The whole stack includes target_size and therefore have impact on the face picture since its detection (I mean before it's embedding). The detection phase returns the correct bounding_box (facial_area) of the face but what is contained in the `face` key **is not** the result of the cropping from the bounding_box rather the picture already (re)dimensioned for the extraction of the embeddings. Which is, imo, a bit inconsistent.
Would have preferred to have the resizing of the input within the scope of the basemodel to keep isolation.

**Comment by serengil** [comment]
that is why i said "in the current implementation", resize job can be moved to the representation module and I am thinking this for a while - still not sure which will be better.

**Comment by serengil** [comment]
convinced! for separation of concerns, we should apply resizing in the representation module. will create a ticket to follow this.

**Comment by serengil** [comment]
Ticket: https://github.com/serengil/deepface/issues/1149

**Comment by serengil** [comment]
do you mind to close this?
