### ISSUE TITLE
move resizing logic from detection module to representation module

### ISSUE THREAD

**Issue by serengil** [serengil/deepface#1149]
currently, we are applying resizing in the detection module. however, this is not right with respect to the separation of concerns. we should move this logic into representation module and detection module should be responsible for extracting faces.

current resizing logic: https://github.com/serengil/deepface/blob/master/deepface/modules/detection.py#L126

it should be just before calling the FR model: https://github.com/serengil/deepface/blob/master/deepface/modules/representation.py#L100

Related discussion: https://github.com/serengil/deepface/issues/1148

**Comment by AndreaLanfranchi** [comment]
What about embedding the resizing logic directly into base model ?
This way anyone can use the detector they want without the need to pass through the respresentation module

**Comment by serengil** [comment]
if we would do that action in base models, then we should do this for each base model. that has to be called when a new model added. but if we do this in representation, then we should do this once.

doing it in representation module seems better but open to discuss.

**Comment by AndreaLanfranchi** [comment]
This is the fastest way imo. 
In the end you're already handling base models as templates (all implementing the `find_embeddings` method).
The natural step is to have a base class with an abstract method `find_embeddings` and eventually all methods common to any specialization.

**Comment by serengil** [comment]
will decide it later. do you mind to close this?

**Comment by AndreaLanfranchi** [comment]
You have opened the work ticket ... why would you want to close it ?

**Comment by serengil** [comment]
My bad, I was thinking to respond the other issue :/

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1175
