### ISSUE TITLE
Converting embedding vector with `tobytes()`?

### ISSUE THREAD

**Issue by newbiemate** [serengil/deepface#1152]
This is a silly question but I am following [your tutorial on saving the face embeddings](https://github.com/serengil/tensorflow-101/blob/master/python/Face-Recognition-SQL.ipynb) into a sqlite database. Could you help clarify the part where I need to save the embeddings as a BLOB type? I keep getting an error saying the embedding list type has no `tobytes()` function:

```
  df = pd.DataFrame(instances, columns = ["img_name", "embedding"])
  
  for index, instance in df.iterrows():
      img_name = instance["img_name"]
      embeddings = instance["embedding"]

      insert_statement = "INSERT INTO face_meta (ID, IMG_NAME, EMBEDDING) VALUES (?, ?, ?)"
      insert_args = (index, 'test.jpg', embeddings.tobytes())
      cur.execute(insert_statement, insert_args)
```

However this results in an error:
```
    insert_args = (index, 'test.jpg', embeddings.tobytes())
AttributeError: 'list' object has no attribute 'tobytes'
```

If I do `df.head()`, it prints out:

```
   img_name                                          embedding
0  test.jpg  [0.8899126052856445, -1.1766209602355957, -0.1...
1  test.jpg  [0.806894063949585, -0.9386254549026489, -1.22...
2  test.jpg  [0.6343249082565308, -0.8294755220413208, -2.0...
```

The only difference is I'm not using `tqdm` library for the iteration. Is there a special step I'm missing here?

**Comment by serengil** [comment]
Most probably, it was using an old version of deepface. Try to convert embeddings list yo numpy array first.

np.array(embeddings).tobytes()
