### ISSUE TITLE
Help with searching sql with Euclidean distance

### ISSUE THREAD

**Issue by newbiemate** [serengil/deepface#1154]
I was going over your article on face detection and db here: https://sefiks.com/2021/02/06/deep-face-recognition-with-sql/

It's a great article but I'm having trouble getting the same results. I have a group photo of Angelina Jolie and I've created the face embeds using RetinaFace and stored them into the sqlite db like the article states:

![angie_group](https://github.com/serengil/deepface/assets/34783617/208ddd62-afc7-4600-b3da-e4c2973e086c)

```
with conn:
  cur = conn.cursor()


  instances = []
  img_name = "jolie_group.jpg"


  # Build the embeddings
  faces = DeepFace.represent(img_path=img_name, model_name="Facenet", detector_backend="retinaface")
  for index,face in enumerate(faces):

      embeddings = face["embedding"]
      print(f"length = {len(embeddings)}")
      print(embeddings)

      insert_statement = "INSERT INTO face_meta (ID, IMG_NAME, EMBEDDING) VALUES (?, ?, ?)"
      insert_args = (index, img_name, np.array(embeddings).tobytes())
      cur.execute(insert_statement, insert_args)

      for i, embedding in enumerate(embeddings):
         insert_statement = "INSERT INTO face_embeddings (FACE_ID, DIMENSION, VALUE) VALUES (?, ?, ?)"
         insert_args = (index, i, str(embedding))
         cur.execute(insert_statement, insert_args)

      conn.commit()
```

The result will be 9 rows into the `face_meta` table, and 1152 rows for the `face_embeddings` table (each face embed has 128 dimensions). So this is great! The only face it didn't detect was the one looking sideways, but that's fine.

I have a single picture of Jolie that I want to match against the DB, and I would like to get the image name and the related face embedding in the group photo.

![angie_single](https://github.com/serengil/deepface/assets/34783617/3b550fb1-e77a-424e-9c5f-4597741b33cc)

**Using The Server-Side Solution:**

```
with conn:
  cur = conn.cursor()


  # compare
  target_img = "angie_single.jpg"
  target_represent = DeepFace.represent(img_path=target_img, model_name="Facenet", detector_backend="retinaface")[0]
  target_embedding = target_represent["embedding"]
  target_facial_area = target_represent["facial_area"]

  target_statement = ""
  for i, value in enumerate(target_embedding):
      target_statement += 'select %d as dimension, %s as value' % (i, str(value)) #sqlite
      
      if i < len(target_embedding) - 1:
          target_statement += ' union all '

  select_statement = f'''
    select * 
    from (
        select img_name, sum(subtract_dims) as distance_squared
        from (
            select img_name, (source - target) * (source - target) as subtract_dims
            from (
                select meta.img_name, emb.value as source, target.value as target
                from face_meta meta left join face_embeddings emb
                on meta.id = emb.face_id
                left join (
                    {target_statement}  
                ) target
                on emb.dimension = target.dimension
            )
        )
        group by img_name
    )
    where distance_squared < 100
    order by distance_squared asc
'''

  results = cur.execute(select_statement)
  instances = []

  for result in results:
      print(result)
      img_name = result[0]
      distance_squared = result[1]
      
      instance = []
      instance.append(img_name)
      instance.append(math.sqrt(distance_squared))
      instances.append(instance)
  
  result_df = pd.DataFrame(instances, columns = ['img_name', 'distance'])

  print(result_df)
```

However this returns nothing:

```
Empty DataFrame
Columns: [img_name, distance]
Index: []
```

I've tried this with other single photos of Angelina Jolie but it's unable to find any matches. I think I understand the theory going on, using Euclidean distance calculation to find nearest matches and having a cutoff threshold, but looking at the code I'm unsure where it went wrong. 

Could you help me with what I'm missing?

**Comment by serengil** [comment]
Would you please call deepface's verify function and send single photo of angelina as img1_path and group photo as img2_path? This will compare the most similar one in the group photo with angelina's single photo. Even if the verified key is false, you can use distance value to use a tuned threshold.

Finally, none of ml models is perfect. Misclassification for an instance is not a problem with respect to the model.

**Comment by newbiemate** [comment]
Hi Serengil,

I was able to verify the face:

```
{'verified': True, 'distance': 0.22807926891881514, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 241, 'y': 76, 'w': 195, 'h': 283, 'left_eye': (386, 192), 'right_eye': (294, 193)}, 'img2': {'x': 558, 'y': 34, 'w': 63, 'h': 83, 'left_eye': (604, 67), 'right_eye': (575, 71)}}, 'time': 10.1}
```

It looks like it does recognize Angelina Jolie here ^^

I also tried the [**Client Side Solution**](https://sefiks.com/2021/02/06/deep-face-recognition-with-sql/), and curiously enough that returned a match:

```
          img_name                                          embedding                                             target  distance
0  angie_group.jpg  [0.10850527882575989, 0.5568691492080688, 0.81...  [-0.6434235572814941, 0.5883399248123169, 0.29...  8.263514
```

Do you know if the **Server Side Solution** needs an update to the code? I think maybe the sql there isn't working since these other solutions are working fine.
