### ISSUE TITLE
Tensorflow 2.16 installed but deepface not using cuda.

### ISSUE THREAD

**Issue by bill-web7** [serengil/deepface#1159]
I run

from deepface import DeepFace
DeepFace.stream(db_path = "database", time_threshold = 5, frame_threshold = 5, enable_face_analysis = False, detector_backend = "yolov8", model_name = "GhostFaceNet")

jtop reports no gpu usage. It does for other programs.

Some issues suggest installing tensorflow-gpu except you can't anymore since 2.1. Tensorflow was installed and tested well before I installed deepface. 

Python 3.10.12

pip list:
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorflow                   2.16.1
tensorflow-io-gcs-filesystem 0.36.0
tensorrt                     8.6.2
tensorrt-dispatch            8.6.2
tensorrt-lean                8.6.2
termcolor                    2.4.0
tf_keras                     2.16.0
thop                         0.1.1.post2209072238
torch                        2.2.2
torchvision                  0.17.2

**Comment by serengil** [comment]
Deepface does nothing with gpu. It depends tensorflow and tf handles gpu usage. If your tf cannot use gpu, then you may consider to raise a ticket in tensorflow repo.

**Comment by bill-web7** [comment]
Thank you for the fast reply.

**Comment by Lingyun97** [comment]
> Thank you for the fast reply.

looks like the yolov8 require pytorch to run  on gpu, that the model file is a .pt. 
I tried the same and it's same speed with cpu one.
But also tried the facenet h5 file which actually faster.
like the author said, he just didn't do gpu on yolov8.

**Comment by Lingyun97** [comment]
and still strange, the facenet or ghostfacenet is h5 file and there is no speedup in target_embedding_obj = representation.represent()
