### ISSUE TITLE
Sending base64 encoded image to API server

### ISSUE THREAD

**Issue by kk-min** [serengil/deepface#1162]
Hi, thank you for this project. I am trying to access the `analyze` endpoint that is hosted locally (`localhost:5000/analyze`) by providing the base64 encoded image. However, the web server does not seem to recognize the base64 encoded image (unless I am missing something).

Request body:
```json
{
  "img_path": "<base64 string of image>"
}
```

The server returns:
```json
{
    "error": "Exception while analyzing: Confirm that <base64 string of image> exists"
}
```

Is there something I am missing here? A separate value to signal that I'm sending a base64 encoded image?

**Comment by serengil** [comment]
Oh you are sending <base64 string of image>, this should be base64 encoded string.

E.g. data:image/...

**Comment by kk-min** [comment]
> Oh you are sending < base64 string of image >, this should be base64 encoded string.
> 
> E.g. data:image/...

Oh you're right, that was the problem! Thank you for the swift reply.
