### ISSUE TITLE
How to use DeepFace in Electron app

### ISSUE THREAD

**Issue by banx9x** [serengil/deepface#1164]
Hi, I'm trying to build a facial recognition application using Electron and DeepFace, I have a few problems and need help:

- My app needs to run offline, is there a way to pre-download the model (e.g. facenet_weight.h5) and configure deepface to use pre-packaged files instead of downloading it?
- When searching for the first time, it takes a lot of time to parse the entire image folder and create a pickle file, is there a way to create this file before searching?

**Comment by serengil** [comment]
no experience on Electron but try to answer your questions

1- if you install the required model from [here](https://github.com/serengil/deepface_models/releases/tag/v1.0), to ~/.deepface/weights, then deepface will not attempt to download pre-trained weights

2- if you run find function in an external system (even in your laptop), and move the pickle to target system, then deepface will not attempt to create pickle.
