### ISSUE TITLE
[Question] Yolo detector : LANDMARKS_CONFIDENCE_THRESHOLD

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1165]
Is [this still used](https://github.com/serengil/deepface/blob/357a397f1bd2720a98e48d0891dcf71ff356d172/deepface/detectors/Yolo.py#L17-L19) ? Seems like a leftover

**Comment by serengil** [comment]
yeah seems retired

**Comment by serengil** [comment]
Closed with https://github.com/serengil/deepface/pull/1172
