### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by zwep** [serengil/deepface#1167]
I am playing around with the function 'find', like so:

`DeepFace.find(img_path=path1, db_path=os.path.dirname(path1))`

There I found that I can't set db_path to any path I like, since it should contain the image path given in `img_path` (or at least any other file). This seems to me that db_path is redundant. 

Is that correct? or am I missing something?

**Comment by serengil** [comment]
img_path can be exact file path, base64 encoded string, pre-loaded numpy array or an image on web with url.

db_path can be any folder containing images.

```python
DeepFace.find(img_path="/mnt/c/Users/sefik.serengil/Desktop/sefik.jpg", db_path="/home/sefik/db")
```

Long story short, db_path is not redundant.

**Comment by AndreaLanfranchi** [comment]
`DeepFace.find` is a _find a needle in a haystack_ function.
`img_path` is the argument for the needle (the image where to detect a face)
`db_path` is the argument for the haystack (the directory holding all the images with faces where we want to find a match with the needle).

**Comment by zwep** [comment]
> `DeepFace.find` is a _find a needle in a haystack_ function. `img_path` is the argument for the needle (the image where to detect a face) `db_path` is the argument for the haystack (the directory holding all the images with faces where we want to find a match with the needle).

Aha! Of course, that makes it clear to me. (This week I started to read about face recognition/detection/verification/etc.. so I still need to get used to how certain words are used :))
