### ISSUE TITLE
[Question] About logger

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1168]
Just wondering what's the rationale about logger instancing:

- `module` optional argument even if valued is not considered in any log line
- actually all modules where logger is instantiated have their own instance while a singleton should be more than enough

Thank you

**Comment by serengil** [comment]
Yeah, using logger similar to base models with singleton is okay but we will miss the module information in that case. With this approach, we can include module name into log messages easily. That is why, I added it but not used yet.

TLDR: I prefer to adopt the current approach.

**Comment by AndreaLanfranchi** [comment]
Just for the sake of discussion I see some possible improvements with that approach.

1. Providing module name by string constant might break the coupling amongst actual module name and what is written in the instantiation statement if the module gets renamed. Would suggest to provide the module name from `__name__` variable
2. Even implementing a singleton the module name of the function calling any log activity can be easily determined examining the stack. [Here](https://stackoverflow.com/a/1095621) a sample.

This helps a lot reducing the amount of code being written and does not require to _remember_ to update string constants on module renaming (if ever).

**Comment by serengil** [comment]
1- Agree. Instead of string module name __name__ will avoid mistakes. But end user is not using logger at all. So, giving wrong module name should not be happened.

2- suppose that one customize the logger and move logs to kafka instead of console. You will see module name in the event message. So, I think having module name is important in the logger.

**Comment by AndreaLanfranchi** [comment]
> 1- Agree. Instead of string module name '**name**' will avoid mistakes. But end user is not using logger at all. So, giving wrong module name should not be happened.

I don't mean this should impact user experience. I'm considering developer experience and code maintainability. Say you rename GostFaceNet.py to whatever.py ... you'd also need to change this accordingly
```python
logger = Logger(module="basemodels.GhostFaceNet")
```
otherwise, in case the codes printout a logline **with** the module name (useful for debugging and asking for support, you might end up with an inconsistent info

> 2- suppose that one customize the logger and move logs to kafka instead of console. You will see module name in the event message. So, I think having module name is important in the logger.

Not disagreeing on that. I'm only saying you can get the name of the calling module at runtime even using a singleton instance of the logger.

**Comment by serengil** [comment]
I did not disagree. Just thinking out loud.

I will play with the logger then.

Thank you for your comment and feedback.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1177
