### ISSUE TITLE
We are getting Race and age but incorrect gender from the code

### ISSUE THREAD

**Issue by codal-vprajapati** [serengil/deepface#117]
![image](https://user-images.githubusercontent.com/60089613/97080550-d8123f00-1619-11eb-80c3-8418a8e296b4.png)
I have done analysis for 12 year old baby and I get 19 years and gender male which is worng.
Can you fix this issue?

**Comment by serengil** [comment]
deepface can predict ages ±4.6 years, and it can predict gender 97% accuracy, 96.29% precision, 95.05% recall. This is not wrong because this level error is acceptable for machine learning studies.

Tutorial: https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/
