### ISSUE TITLE
Inference time on GPU and CPU is the same.

### ISSUE THREAD

**Issue by namogg** [serengil/deepface#1176]
i have test my inference time with FaceNet 512 and the inference time on both GPU and CPU is ~ 0.15s. However on retina face, my GPU is 10x faster than CPU. I have tried reinstall deepface but the problem still occur. 

This is my inference time on RTX 3060(i confirmed tensorflow-gpu is working properly)
```
NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
2024-04-08 20:09:58.286536: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:424] Loaded cuDNN version 8907
2024-04-08 20:10:00.289380: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:637] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
3.8497848510742188
0.05065727233886719
0.05063915252685547
0.05495166778564453
0.04937434196472168
0.04781007766723633
0.04761481285095215
0.04778146743774414
0.04765510559082031
0.04927825927734375
```

This is my inference time when i set os.environ['CUDA_VISIBLE_DEVICES'] = '0' 
```
tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
1.0225434303283691
0.059471845626831055
0.06543636322021484
0.059601545333862305
0.06534934043884277
0.05704760551452637
```

please help me

**Comment by serengil** [comment]
deepface does nothing with gpu. it depends tensorflow and tensorflow handles gpu usage. if you are having issue with gpu, you may consider to raise an issue to the tensorflow's repo.

**Comment by namogg** [comment]
For my case, tensorflow works perfectly fine with retina face(10X) improvement but not with deepface. Can you suggest any solution
