### ISSUE TITLE
[Question] preprocessing.normalize_input : what for ?

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1178]
I'm puzzled by the meaning of `preprocessing.normalize_input` function.

- seems like it's invoked only in module `representation` function `represent`
- default value `"base"` (which returns the fed image as is) seems never changed all over the project
- other possible values are never used neither is clear whether they should be applied for specific basemodels (the names seem to partially match names of some `basemodel`(s))

Can you clarify what this function is for and whether it is supposed to enhance the outcome of some representation ?

Thank you.

**Comment by serengil** [comment]
Its discussion can be found in the existing issues: https://github.com/serengil/deepface/issues/131

**Comment by AndreaLanfranchi** [comment]
Thank you. However the technicals described in #131 are still a little beyond my full comprehension.
What is not clear to me is : which models do benefit from a normalization technique other than "base" ?

**Comment by AndreaLanfranchi** [comment]
It seems there are no test cases to assert that nor samples describing the effectiveness

**Comment by serengil** [comment]
no models are using these normalization techniques - default behaviour is base. users can choose to use any other normalization techniques from the functions in deepface's interface.

**Comment by serengil** [comment]
Closed because this is not an issue

**Comment by AndreaLanfranchi** [comment]
> no models are using these normalization techniques - default behaviour is base. users can choose to use any other normalization techniques from the functions in deepface's interface.

Actually I do believe this is an issue. 
This software implements normalization techniques (although not used) for which there is apparently no documented reason (beside a reference to a an issue), no test cases asserting any enhancement, nor, again, any binding of a technique to a particular base model.
It seems like it has been dropped there due to _user request_ without thorough explanation: basically the rationale is "it does no harm if not used"
This imo questions the validity.

**Comment by serengil** [comment]
Disagree because with no normalization, accuracy scores of existing models are satisfying. If an user wants to use normalization still, they can use it with an arg update. I cannot see an issue at all.
