### ISSUE TITLE
The best combination of model, backend and metrics

### ISSUE THREAD

**Issue by Naster17** [serengil/deepface#1180]
Hello. I encountered a problem that when analyzing a huge number of faces (when a pickle file becomes larger than 1GB, this is approximately 300k+ faces), when recognizing faces that it used to find easily, now it finds completely different faces that are not similar to what it needs to find.

Here is my configuration:
model_name="GhostFaceNet", distance_metric="cosine", detector_backend = "retinaface"

**Comment by Naster17** [comment]
What do you recommend if the photo is not of very good quality, but is taken by combining frames from the video and I leave the option of selecting faces to the neural network (to distinguish where there is a face and where there is not)

**Comment by mohammadreza-shahpiri** [comment]
Hello,
This is my question too.
What do you recommend if the photos is not of very good quality and also the pickle file is larger than 1GB?

**Comment by serengil** [comment]
@mohammadreza-shahpiri you should set enforce_detection argument to False if they are not in a good quality.

if your facial db size is large, then instead of using find function and its pickle, you should adopt a-nn algorithms as explained here: https://sefiks.com/tag/nearest-neighbor/
