### ISSUE TITLE
Recognition.py : inconsistent pickle file

### ISSUE THREAD

**Issue by AndreaLanfranchi** [serengil/deepface#1183]
Pickle file holding representations for files in directory is named after `model_name` and `detector_backend`.
After an initial pass to extract representations from all the images in the directory, assuming no new files have been added, no file have been changed the representations are loaded directly from the pickle file (without undergoing once again through detection and recognition of each face)

However the `find` not only receives as arguments the model and the detector (which, when changed, change also the pickle file name) **but also the normalization argument** which has an impact on the generated representations.

As a result if I call an initial 
```python
 find(
    [...]
    model_name="VGG-Face",
    detector_backend="opencv",
)
```
A pickle file holding representations with `base` technique is generated.
If after that I call, say, 
```python
 find(
    [...]
    model_name="VGG-Face",
    detector_backend="opencv",
    normalization="Facenet"
)
```
then no representation is recomputed and the results of the find function may be highly unexpected.

**Comment by serengil** [comment]
Good spot. If we add the normalization name into the pickle file, then this will be sorted easily.

**Comment by AndreaLanfranchi** [comment]
`expand_percentage" does not have an impact on representations as those are constrained by fixed size input by each model. I don't think is relevant.

More relevant instead the "align" argument.

**Comment by serengil** [comment]
that is another bug. we should consider expand_percentage while we are finding bulk embeddings here - https://github.com/serengil/deepface/blob/master/deepface/modules/recognition.py#L173

**Comment by AndreaLanfranchi** [comment]
> that is another bug. we should consider expand_percentage while we are finding bulk embeddings here - https://github.com/serengil/deepface/blob/master/deepface/modules/recognition.py#L173

I don't think. Expansion of a facial area doesn't have any impact on representation.
But as you wish ... I only signalled a condition. Won't spend more time on this.

**Comment by serengil** [comment]
Expand percentage has definitely an impact on embeddings.

```python
from deepface import DeepFace

img_path = "target.jpg"

DeepFace.represent(img_path=img_path, model_name="Facenet")[0]["embedding"][0:10]
DeepFace.represent(img_path=img_path, model_name="Facenet", expand_percentage=10)[0]["embedding"][0:10]
```

You can see the representation of same image with different expand_percentage values.

```python
[0.47962263226509094,
 1.0006622076034546,
 1.0271168947219849,
 -0.6997617483139038,
 0.5685179233551025,
 -0.8650573492050171,
 1.301469087600708,
 0.4709436297416687,
 0.6177820563316345,
 1.1736094951629639]
```

```python
[0.07209590077400208,
 1.220704197883606,
 1.0250455141067505,
 -1.0584845542907715,
 0.7029904723167419,
 -0.8850963711738586,
 0.9492990970611572,
 0.7604453563690186,
 0.7631895542144775,
 0.7458571791648865]
```

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1185
