### ISSUE TITLE
issues with large data set

### ISSUE THREAD

**Issue by snehasrav25** [serengil/deepface#119]
when I loop through thousand images like below like below
![image](https://user-images.githubusercontent.com/56207310/97963013-2a1a3980-1d6b-11eb-8797-f3e5ac4da94a.png)

I get this below error message:

"The kernel appears to have died. it will restart automatically"

any help on this ? thanks a lot

**Comment by serengil** [comment]
Do not use for loops to analyze bulk data. You can handle bulk data as illustrated below.

```
objs = DeepFace.analyze(["img1.jpg", "img2.jpg", "img3.jpg"])
print(objs[0]["age"])
print(objs[1]["age"])
print(objs[2]["age"])
```

**Comment by snehasrav25** [comment]
thanks a lot
