### ISSUE TITLE
DeepFace Facial Recognition 

### ISSUE THREAD

**Issue by olstice** [serengil/deepface#1192]
i installed your program DeepFace but can Deepface be used of sending out a picture of someones face and it using a catelog of faces exact or similar to this picture to try and fiture out who the person is? aka reverse image search of finding other images of the exact same person to find out who they are

Because im getting the idea through your videos and the info on github that that is not one of its capabilities?

**Comment by serengil** [comment]
Please check out read me of the repo. Find function is for this.
