### ISSUE TITLE
You are running it in windows instead of python. Run python command in your terminal and then run find command in python.

### ISSUE THREAD

**Issue by olstice** [serengil/deepface#1195]
Your response makes no sense to me

you don’t explain this well at all to someone who is a complete novice to this and that really frustrates me please do not just assume everyone attempting this installation is practicing python and other applications with it all the time and is familiar with these terms so you don’t have to put much detailed instruction

not everyone is practicing this infact people like me have never even attempted something like this until it was something they needed for example I needed this so im trying to follow the instructions exactly only issue is you barely put any detailed instruction for a novice!

Please im begging can you please explain this as if talking to a novice because thats what your speaking to

iv had to google how to run bython command in terminal

i dont even know where deepface is in my file explorer to even add it

![image](https://github.com/serengil/deepface/assets/124982114/f175ae59-a2cf-4547-8131-de2fff7d6a4f)

![image](https://github.com/serengil/deepface/assets/124982114/7b0934e5-a0f9-4e6b-abbd-d4e580579cbc)

**Comment by serengil** [comment]
i explained already what should you do in the previous thread - https://github.com/serengil/deepface/issues/1193#issuecomment-2063093101

**Comment by olstice** [comment]
> i explained already what should you do in the previous thread - [#1193 (comment)](https://github.com/serengil/deepface/issues/1193#issuecomment-2063093101)

All you said is You are running it in windows instead of python. Run python command in your terminal and then run find command in python.

also what python command? all i see is the find command?

right after the face verification command?

**Comment by olstice** [comment]
> i explained already what should you do in the previous thread - [#1193 (comment)](https://github.com/serengil/deepface/issues/1193#issuecomment-2063093101)

![image](https://github.com/serengil/deepface/assets/124982114/efcb481e-a5eb-475e-8327-50eda0c8b939)
