### ISSUE TITLE
No Item found in Database

### ISSUE THREAD

**Issue by merasil** [serengil/deepface#1197]
Hi, was there a recent change in the way Deepface looks for the Images in the Database-Directory?
i havent changed anything in my current project except for updating deepface to the newest version (0.90). Since the update i am getting this error when using the find function:

No Item found in dbs (my database-folder)

And it seems that there is a new pkl-file getting created, with a size of 5 byte, which i think is way too less :)
My Directory-Structure looks like this:
dbs
|_____person1/person1.jpg
|_____person2/person2.jpg

**Comment by serengil** [comment]
in the previous version, we were checking just extension. now, we are checking the content type of the file.

i mean if a webp file has jpg or png extension, we were counting in in the previous version, but we are not counting it anymore.

https://github.com/serengil/deepface/blob/master/deepface/commons/image_utils.py#L35

Most probably both images are not really jpg files. Because this function is checked in unit tests - https://github.com/serengil/deepface/blob/master/tests/test_find.py#L29

**Comment by merasil** [comment]
and what are the conditions for it to be recognized as an image? The pictures that are currently in the database were taken and downloaded from an iPhone. Nothing else was done to them. I have now downloaded a test.jpg that is recognized by image_utils.list_images().
When I file on the images I get the following output:

[xxxxx@xxxxxx xxxxxx]$ file not_working.jpg
not_working.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 20, Exif Standard: [TIFF image data, big-endian, direntries=14, manufacturer=Apple, model=iPhone 12, orientation=upper-right, xresolution=198, yresolution=206, resolutionunit=2, software=16.5.1, datetime=xxxxx yyyy, hostcomputer=iPhone 12], baseline, precision 8, 3088x2316, components 3

[xxxx@xxxx xxxxx]$ file Test.jpg
Test.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 96x96, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=4, xresolution=62, yresolution=70, resolutionunit=2, software=paint.net 4.3.2], baseline, precision 8, 600x274, components 3


I could now compare the magicbytes with a hex editor, but at the moment it looks to me as if the images are ok.

Translated with DeepL.com (free version)

**Comment by serengil** [comment]
Would you please run the following snippet

```python
with Image.open("not_working.jpg") as img:
   print(img.format.lower())
```
