### ISSUE TITLE
I did what you commented and now this happened

### ISSUE THREAD

**Issue by olstice** [serengil/deepface#1198]
![323515070-7b0934e5-a0f9-4e6b-abbd-d4e580579cbc](https://github.com/serengil/deepface/assets/124982114/d5ef070c-d929-49d5-a73a-36c8d2094fd3)

your instructions in the readme arent detailed enough so will you please help me!!!!

**Comment by serengil** [comment]
You can google how to run python programs. I explained it in the previous thread.

**Comment by olstice** [comment]
> You can google how to run python programs. I explained it in the previous thread.

Are you not looking at the image i sent? how exactly am i supposed to google this error? of which i highly doubt ill get any results?

**Comment by olstice** [comment]
> You can google how to run python programs. I explained it in the previous thread.

as you can see i am using terminal this time i did the find command with my info and this happened

**Comment by serengil** [comment]
"You are running it in windows instead of python. Run python command in your terminal and then run find command in python."

You are running find command - which is not a windows command. You should call python command in terminal and then call that find command.

**Comment by olstice** [comment]
> "You are running it in windows instead of python. Run python command in your terminal and then run find command in python."
> 
> You are running find command - which is not a windows command. You should call python command in terminal and then call that find command.

what do you mean call python command in terminal and then call that find command?

i dont understand at all of what your saying maybe im just too retarded to get this

**Comment by olstice** [comment]
> "You are running it in windows instead of python. Run python command in your terminal and then run find command in python."
> 
> You are running find command - which is not a windows command. You should call python command in terminal and then call that find command.

may i just hire you to fix this for me? just give me your amount you wish to be paid of?

i thought i could do this but clearly i cant

**Comment by olstice** [comment]
> "You are running it in windows instead of python. Run python command in your terminal and then run find command in python."
> 
> You are running find command - which is not a windows command. You should call python command in terminal and then call that find command.

![image](https://github.com/serengil/deepface/assets/124982114/2bde0c7b-01e3-4c20-85b1-29a5a8e7e818)


is this what your talking about?

**Comment by olstice** [comment]
> "You are running it in windows instead of python. Run python command in your terminal and then run find command in python."
> 
> You are running find command - which is not a windows command. You should call python command in terminal and then call that find command.

![image](https://github.com/serengil/deepface/assets/124982114/ff51dba6-727f-43d1-ac5c-d40b6e23370c)
i tried this of replacing myscript with deepface it did nothing!!!

**Comment by olstice** [comment]
> "You are running it in windows instead of python. Run python command in your terminal and then run find command in python."
> 
> You are running find command - which is not a windows command. You should call python command in terminal and then call that find command.

![image](https://github.com/serengil/deepface/assets/124982114/f65e4dfe-db94-4a58-a522-91aa32c5029c)


come to think of it i actually dont even know where deepface is on my computer?
