### ISSUE TITLE
i finally got it working! but its taking representation from my files? i thought it was going to cross reference the facial features of this person in the photo of mine with the endless list of people with photos of your facial rec listing?

### ISSUE THREAD

**Issue by olstice** [serengil/deepface#1199]
![image](https://github.com/serengil/deepface/assets/124982114/41e7f7ad-806b-4ef2-890a-1cf2a567b476)

this extracting faces from mutliple files of mine but i only wanted it to scan the photo i gave it to cross reference it with others that you have stored in your facial rec of every person who has uploaded their own pictures on the internet

**Comment by serengil** [comment]
It compares image given in img_path and images in db_path.

**Comment by olstice** [comment]
> It compares image given in img_path and images in db_path.

wait you mean your application isnt going to compare images that it already has instored in it because your application has no stored images?

**Comment by olstice** [comment]
> It compares image given in img_path and images in db_path.

does your application not have all the stored images of every person who ever uploaded their pictures on the internet?

**Comment by serengil** [comment]
Of course no!

**Comment by olstice** [comment]
> Of course no!

wait then how is it a facial rec application?

im talking the facial rec of websites where you can upload a picture and they use their dataspace of all the stored pictures of people who posted theirs online to cross reference the facial features of the one you have giving you a list of potential sourses thus finding out who the person in your picture you uploaded is by the list provided, that has social media and etc of the listed results?
