### ISSUE TITLE
Unable to use the gender model

### ISSUE THREAD

**Issue by nbeili** [serengil/deepface#120]
I was trying to use the Gender model, but I have problem with loading the model:
`models = {}
models["gender"] = Gender.loadModel()` 

I am receiving each time the same error as mentioned in the 1st screenshot and when I checked in stackoverflow, I founded that the google drive has limit bandwidth (2nd screenshot). 
![screenshot 1)](https://user-images.githubusercontent.com/49637264/98005715-a7888d00-1df1-11eb-8cb6-b26de7c5992c.png)
![screenshot 2](https://user-images.githubusercontent.com/49637264/98005726-a9eae700-1df1-11eb-8155-948c4b8bbe77.png)

do you have any idea how I can solve this problem??

**Comment by serengil** [comment]
You can download it manually and copy to HOME/.deepface/weights folder.
