### ISSUE TITLE
error with deepface.stream

### ISSUE THREAD

**Issue by bakhta19** [serengil/deepface#1202]
Hey,
why do i get this error when using DeepFace.stream 
ValueError: The layer sequential_6 has never been called and thus has no defined input.

**Comment by serengil** [comment]
What is your tf, deepface, python versions? Please share full exception message.

**Comment by bakhta19** [comment]
I have already found that you replied to someone else with the same problem and it’s solved, only needed to downgrade tensorflow. Thank you!

**Comment by serengil** [comment]
i expected that it should work with the latest version of deepface without requiring to downgrade tf
