### ISSUE TITLE
Request for support of model conversion like in .onnx or .engine file.

### ISSUE THREAD

**Issue by haseebkhawaja** [serengil/deepface#1206]
### Description

Is there any support available for model conversion like in .onnx or .engine file . Like I want to run inference using tensorRT... ... please guide if available.. Thanks

**Comment by serengil** [comment]
No, it will not be.

**Comment by haseebkhawaja** [comment]
@serengil But, i think there should be need of that support. As, it gives the inference in less time...

**Comment by askerlee** [comment]
yeah currently if there's no GPU, it takes around 20 seconds to compare a pair of images and makes my laptop very slow... (I have GPU workstations, but I evaluate on the laptop in very small scales)
