### ISSUE TITLE
[FEATURE]: extract_faces return face center point info or stop further enlargement if face center point can't be kept at image center

### ISSUE THREAD

**Issue by deepfree2023** [serengil/deepface#1207]
### Description

otherwise a large expand_percentage value will lead to bad results, face will not be centered and stay at one side of the result.

**Comment by serengil** [comment]
extract_faces is already returning facial area as

```python
face_objs = DeepFace.extract_faces(img)
for face_obj in face_objs:
   x = ["facial_area"]["x"]
   y = ["facial_area"]["y"]
   w = ["facial_area"]["w"]
   h = ["facial_area"]["h"]
```

then, face center point is

```python
face_center = (int(y + h/2), int(x + w/2))
```

**Comment by serengil** [comment]
expand_area is also an optional argument and its default value is 0.

i do not think this is a necessary change.

**Comment by deepfree2023** [comment]
The problem can be resolved by using trial and error method to set a valid expand_percentage value. But in batch processing scenario, it's not possible to adjust expand_percentage for each run.

**Comment by serengil** [comment]
I limited the facial area with boundaries if it exceeds in purpose. Because I can monitor that using this approach has an impact on facial recognition accuracy. I prefer not to terminate expanding if it exceeds the boundaries.

**Comment by deepfree2023** [comment]
For different image size, head size, head position, the largest expand_percentage value without changing the face center  position is different, this makes single-expand_percentage-for-all method not working.

**Comment by serengil** [comment]
Customization the source code is fine in your case. But again I do not think that change is required in the source code of the repo.
