### ISSUE TITLE
[suggestion] Change colorspace to RGB using MTCNN

### ISSUE THREAD

**Issue by mbock-ai** [serengil/deepface#121]
Would'nt you get even better results for facedetection and alignment using a colorspace conversion for MTCNN-detector?

img = cv2.cvtColor(cv2.imread("ivan.jpg"), cv2.COLOR_BGR2RGB) as documented at https://github.com/ipazc/mtcnn

Check confidence = detection['confidence'] comparing some reference images.

**Comment by serengil** [comment]
you're right. I'm going to add this in the next release.

**Comment by iamrishab** [comment]
@serengil 
Isn't the RGB colorspace also valid for face embedding models?
I see you have use BGR throughout. TIA!

**Comment by serengil** [comment]
Nope. OpenCV reads images in BGR format. Everything is handled with OpenCV's way.

**Comment by iamrishab** [comment]
Thank you for prompt reply!
Just to clarify again, the  Keras models like FbDeepFace, VGGFace etc, these models also trained on BGR images?

**Comment by serengil** [comment]
to be honest, I am not sure. Possibly, some models trained with RGB and some trained with BGR. I should study on this subject.

**Comment by iamrishab** [comment]
Kindly let me know as well. 
Thank you.

**Comment by serengil** [comment]
This is handled in 0.0.41 version on the code repo. But it is not currently pushed to the pypi.
