### ISSUE TITLE
New api endpoint

### ISSUE THREAD

**Issue by MohamedAbdallah-MA** [serengil/deepface#1211]
### Description

Please , may you add endpoint for find function that takes the path of the image and the path of the dataset that is gonna find the image in 

I tries to add it by my self but unfortunately the end point gives me request time out even i already trained the model before on that dataset

**Comment by serengil** [comment]
Api works with base64 encoded input images. That is why, it does not support find function.

**Comment by MohamedAbdallah-MA** [comment]
cannot make the endpoint take just the path of the dataset and the image and return the paths of the most similar images not the image it self ?

**Comment by serengil** [comment]
If you can access file system, you do not need the ws. You can call python.find directly. Purpose of ws is exposing it yo the web.

**Comment by MohamedAbdallah-MA** [comment]
yes i want to access it through web using the image path and db path and i see it would be good if find endpoint is available using api
