### ISSUE TITLE
Which Billion-Scale Database is the best for Face Recognition Query?

### ISSUE THREAD

**Issue by falkaabi** [serengil/deepface#1214]
### Suggested Changes

Hello,

I've reviewed the examples provided for the `Billion-Scale Fast Vector Similarity Search` using the 5 databases you've tested. Could you please clarify which database is recommended based on your findings? Additionally, it would be helpful to have detailed metrics on both speed and accuracy for each database.

From the materials available, including your videos, I've gathered the following performance metrics:

- **Facebook Faiss:** 0.07031798862731934 seconds
- **Spotify Annoy:** 0.0010027885437011719 seconds
- **Elasticsearch:** (data not available)
- **NMSLIB:** 0.0003199577331542969 seconds
- **Redis:** (data not available)

Could you provide a speed and accuracy comparison between these databases? It would greatly assist in making an informed decision.

Thank you!

**Comment by serengil** [comment]
Closing this cos those are external studies independent from deepface repo.
