### ISSUE TITLE
[FEATURE]: Nix flake deployment mechanism

### ISSUE THREAD

**Issue by a-h** [serengil/deepface#1221]
### Description

A Nix flake is a `flake.nix` file that would be in this repo which includes build instructions for how to package this project for the Nix package manager.

It's similar to the Dockerfile that's already in the root directory, except that it provides reproducible builds by using specific dependency versions, based on commit hashes, and SHA256 hashes of the contents.
 
With a Nix flake, people would be able to:

* Install `deepface` as a Python package into their operating systems or Python app by importing the flake into their Nix setup.
* Run a development shell that contains everything required to work on the deepface project (cloning the repo and running `nix develop`)
* Run the app without manually downloading code, setting up a virtual environment, or installing dependencies (`nix run github:serengil/deepface`).
* Create reproducible Docker builds from the Nix flake.

### Additional Info

I've already built a Flake outside of the repo for my own use, so I'm happy to share it for others to use if you're interested in having it within the project.

Let me know, and I'll raise a PR.

**Comment by serengil** [comment]
do you mind to create a PR?

**Comment by a-h** [comment]
Not at all... 😁

**Comment by a-h** [comment]
See https://github.com/serengil/deepface/pull/1227

**Comment by serengil** [comment]
closed due to inactivity
