### ISSUE TITLE
Dataset used to train models for facial attribute analysis

### ISSUE THREAD

**Issue by kw01sg** [serengil/deepface#123]
Hi, 

What's the dataset used to train the different extended models? I understand each of the extended models have their own pretrained weights that are download from Google Drive, and I'm interested to find out what datasets have been used to train them.

**Comment by serengil** [comment]
read me of the repo will redirect you to the related posts. Train data sets were mentioned there.

**Comment by kw01sg** [comment]
Ah okay I found the links in the readme. Didn't realize the different facial attributes are actually links that can be clicked into. For anyone else that's interested, the link for `facial expression` can be found [here](https://sefiks.com/2018/01/01/facial-expression-recognition-with-keras/).
