### ISSUE TITLE
[More info from find method]: Find method should optionally return full face detection results

### ISSUE THREAD

**Issue by DarinShapiroMS** [serengil/deepface#1230]
### Description

I like the find method because of all the built in features, but I need to be able to draw rectangles on frames with unknown faces as well as the ones identified via current find method.  Would it make sense to include dataframes for all detected faces, but only provide identity information for faces matched in database.   If there's a work around, please let me know.

**Comment by serengil** [comment]
That would not be good for separation of concern. You should call extract_faces to find all faces independent from its identification.

**Comment by DarinShapiroMS** [comment]
If I detect all faces first, then try to identify each one with find, won't it go through extract_faces again unnecessarily?  Also, how would I then correlate the extracted faces that weren't identified?

**Comment by serengil** [comment]
Detected faces' coordinates are available in the returned dataframe.
