### ISSUE TITLE
[FEATURE]: Manual image_file to pkl_representation management

### ISSUE THREAD

**Issue by BrunoMarinhoM** [serengil/deepface#1233]
### Description

- Description:
The Find method would have three extra fields (enforce_disk_consistency (boolean), refresh_database (boolean), and updated_images (list of paths)) that would allow manual image representations management;
When both enforce_disk_consistency and refresh_database are set to True, the behavior would remain the same;

- Differences:
-- refresh_database set to false -> The function is gonna rely only on the already set up pkl representations within the db_path, ignoring all tests to assure that any of the image files were still in the db_path directory;
-- enforce_disk_consistency set to false and refresh_database set to true -> The function would only update (either add, delete or replace) the files within the updated_images list; ignoring all others;

- Advantage: when dealing with cloud computing or large enough set of images, this controlled behavior allow you to rely only on the images pkl representations and not their (possibly large) actual image files. For example, in a API, you could simply upload your database, run the find function once only to create the pkl representations file, and afterwards delete all the image files and would still be able to run the face_recognition with the same database except none of the image files would be in the server.

- Additional Info: I'm already using the lib that way in my personal repo; and it's been a perfect fit for the cloud computing env that I've been using; if you think it could be useful for you project I'd be happy to share.

**Comment by serengil** [comment]
thank you for the recommendation. seems that it would give better user experience. do you mind to create a PR if you already have the enhancement in your branch?

**Comment by BrunoMarinhoM** [comment]
See https://github.com/serengil/deepface/pull/1235. 
:+1: 
:)

**Comment by serengil** [comment]
thanks, added some minor comments. then, will be happy to merge.

**Comment by BrunoMarinhoM** [comment]
Feature added on PR https://github.com/serengil/deepface/pull/1235.
