### ISSUE TITLE
[DOC]: License of Facenet512 model.

### ISSUE THREAD

**Issue by dalematthews1** [serengil/deepface#1236]
### Suggested Changes

It is mentioned in the README that different models have different licenses and links are given for some of the different models. There was a link provided for 'Facenet' but it was not clear to me whether this license covered the Facenet512 model. I think it would be beneficial if there was a list with the name of each model supported by the Deepface API and a link to the license for each model and if it was mentioned which models can be used commercially.

**Comment by serengil** [comment]
updated the license section. thank you for your feedback.

**Comment by Kaan-Karaoglan** [comment]
Where can I find out which license the FaceNet512 model is subject to?
