### ISSUE TITLE
[DOC]: YOLOv8 model

### ISSUE THREAD

**Issue by sank96** [serengil/deepface#1237]
### Suggested Changes

in the code i can see yolov8 support
https://github.com/serengil/deepface/blob/0833da1a4f1392a99aee163b7185fae8bed42519/deepface/detectors/Yolo.py#L13
But can you share more information? why are you downloading the weights from a gdrive folder and not from the official repo? is it a custom model? if yes cna you share more info about the training?

**Comment by serengil** [comment]
In both readme and Yolo.py, repo of reference model is mentioned: https://github.com/derronqi/yolov8-face

You can find more information in that repo
