### ISSUE TITLE
Running api.py error

### ISSUE THREAD

**Issue by bigdavelamb** [serengil/deepface#124]
I receive this error when running the script (on Windows 2012R2, Python version 3.8.0):

c:\Python\Python38\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 5021, in dropout_v2
    raise ValueError("rate must be a scalar tensor or a float in the "ValueError: rate must be a scalar tensor or a float in the range [0, 1), got 1

**Comment by serengil** [comment]
what was your tensorflow version?

could you test it for python 3.6, and tensorflow 1.9.0. it seems an environmental problem and unit tests were done in the versions I mentioned.

**Comment by bigdavelamb** [comment]
I was using a higher version and I could not get version 1.9.0 with my version of Python.

I have installed version 3.6.0 and now I get this:

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by serengil** [comment]
this should be fixed in the latest release. you can test it.
