### ISSUE TITLE
[FEATURE]: filtering based on the threshold in find() function

### ISSUE THREAD

**Issue by gratusrichard** [serengil/deepface#1240]
### Description

instead of just giving out threshold, can we automatically filter the results based on the minimum threshold set in the deepface.find function?

**Comment by serengil** [comment]
Give more details please. As I understand, currently deepface does this.

**Comment by gratusrichard** [comment]
![image](https://github.com/serengil/deepface/assets/78464961/caa17e1a-57c7-476f-b752-651c1d8aa037)
this the output i get when i print the dataframe       
  dfs = DeepFace.find(img_path = imagetofind, db_path = os.path.join(database) , model_name = "ArcFace",detector_backend="retinaface",threshold=0.7)
  print(dfs)
it just says it displays all the images from the database without filtering out the ones that have less distance. am i missing something here? Is this not the right way to do this?

**Comment by serengil** [comment]
@gratusrichard: `it just says it displays all the images from the database without filtering out the ones that have less distance. am i missing something here? Is this not the right way to do this?`

no, find function is already showing the images having smaller threshold. as you can see from the image you shared, all distance values are less than threshold column.
