### ISSUE TITLE
age analysis

### ISSUE THREAD

**Issue by elijahcs1** [serengil/deepface#125]
age model is inaccurate

**Comment by redcodey** [comment]
can you post the pictures and more specific?

**Comment by serengil** [comment]
as mentioned in its tutorial, age model predicts ages plus minus 4 years: https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/ 

errors for some pictures might be greater than this but this is the average and it's acceptable.

**Comment by EinGuterWaran** [comment]
![10038](https://user-images.githubusercontent.com/14865414/212500593-44074492-f672-4a65-a6e7-cebcbb2b4e7a.png)
Her age is estimated to be 29 and her gender is male.
