### ISSUE TITLE
[FEATURE]: Information about pre-trained models (e.g. FaceNet)

### ISSUE THREAD

**Issue by vincent-stadler** [serengil/deepface#1252]
### Description

Could you tell us where you acquired the models used in the deepface library? Especially the FaceNet model. Since the official model was never released by Google, there are a lot of FaceNet models in the open. It would be useful to know which one you used, i.e. which dataset it was trained on to account for possible normalisation.

**Comment by serengil** [comment]
If you follow the read-me carefully, you will find the answer.

**Comment by vincent-stadler** [comment]
Thank you very much for the super quick response!
In Sandbergs repo (https://github.com/davidsandberg/facenet/tree/master?tab=readme-ov-file#pre-trained-models) there also are multiple models, did you just take the latest one? :)

**Comment by serengil** [comment]
20180402-114759 -> Facenet512
20170512-110547 -> Facenet
