### ISSUE TITLE
[FEATURE]: Classify faces as covered or uncovered for robust facial feature extraction.

### ISSUE THREAD

**Issue by annoyingCode** [serengil/deepface#1254]
### Description

First of all, thank you so much for this open-course repository. It is highly appreciated!

It would be great if we have a feature to identify whether a face is covered or not. This is particularly useful for security related face recognition tasks because if a face is uncovered, the feature extraction models like Dlib's ResNet or any other will generate more robust features of the face. Even though models like YOLOv8, and MediaPipe perform very well in detecting faces _(they can detect a face even if most of it is covered)_, facial feature extraction models are trained with the assumption of uncovered faces and because of that, they tend to produce unreliable face embedding.

Let me know if you need more details on this request.

Thank you.

**Comment by serengil** [comment]
extract faces is already returning confidence score and if face is covered, its confidence score will be low. you can discard faces with a confidence score less than a threshold.
