### ISSUE TITLE
[BUG]: <DeepFace Library Integration Issue in Android Application>

### ISSUE THREAD

**Issue by vinayakvigo** [serengil/deepface#1259]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.92

### Python version

3.8.5

### Operating System

windos

### Dependencies

**Summary**
When integrating the DeepFace library with an Android application using Python Chaquopy, the verify function generates an error: list indices must be integers or slices, not str. This issue occurs despite the same code running correctly in a Python interpreter.

**Environment**
DeepFace Library Version: 0.0.92
Python Integration Tool: Chaquopy
Android Application: Custom-built application using Chaquopy for Python integration
Issue Details
Error Description:

**Error Message:** list indices must be integers or slices, not str
**Occurrence:** The error is encountered when invoking the verify function of the DeepFace library within the Android environment.
Behavior:

The code executes without issues in a standalone Python interpreter.
The same code, when executed in the Android application through Chaquopy, results in the mentioned error.
Steps to Reproduce:

Integrate the DeepFace library in an Android application using Chaquopy.
Configure the application and ensure the library is installed successfully.
Execute the verify function with valid image paths or URLs.
Observe the error: list indices must be integers or slices, not str.
Debugging Attempts:

Verified that the input variables passed to the verify function are correct and match the expected types.
Tried using both local storage image paths and online image URLs as input.
Ensured that the latest version of the DeepFace library (0.0.92) is being used.

**Expected Behavior**
The verify function should execute without errors and return the verification results.

**Actual Behavior**
The verify function raises an error: list indices must be integers or slices, not str.

**Request**
Please investigate and resolve this issue to ensure the verify function works correctly within the Android application using Chaquopy. Any insights or fixes would be greatly appreciated.

![s6](https://github.com/serengil/deepface/assets/169231592/774669ef-0686-4710-a5dd-dabffbb35064)
![s5](https://github.com/serengil/deepface/assets/169231592/b64471f6-325d-44e6-a19d-2f29324d7834)
![s2](https://github.com/serengil/deepface/assets/169231592/2149a65a-6e3e-49c4-a440-6a3a434bc6c0)
![s4](https://github.com/serengil/deepface/assets/169231592/6deb1d14-632d-4421-8ae6-030a785168c9)
![s3](https://github.com/serengil/deepface/assets/169231592/d255f0a9-07d0-4970-9cee-feec1c7729fd)
![s1](https://github.com/serengil/deepface/assets/169231592/fc0b71d7-2388-4c8d-a0b6-f915f04e4a41)

### Reproducible example

```Python
from deepface import DeepFace

# Sample images for verification
img1_path = "image1.jpg"  # Local storage path
img2_path = "image2.jpg"  

# Verify function call
try:
    result = DeepFace.verify(img1_path, img2_path)
    print(result)
except Exception as e:
    print(f"Error: {e}")
```

### Relevant Log Output

 error : list indices must be integers or slices, not str

### Expected Result

The verify function should execute without errors and return the verification results.

### What happened instead?

The verify function raises an error: list indices must be integers or slices, not str.

### Additional Info

If you require any further details or logs, please let me know. Thank you for your assistance!

**Comment by serengil** [comment]
If no issue in regular python, then it means no bug.

Deepface has no support for android. You may consider to open this issue in their repo.
