### ISSUE TITLE
[BUG]: <How to speed up face recognition time on cpu>

### ISSUE THREAD

**Issue by ybshaw** [serengil/deepface#1260]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.92

### Python version

3.8

### Operating System

windows10

### Dependencies

deepface==0.0.92

### Reproducible example

```Python
I have already deployed it on windows10 system, and it takes more than 4s to extract features when use `DeepFace.represent` , and 2s when ssd model is used. Is there any way to accelerate it within 500ms. Thank you
```

**Comment by serengil** [comment]
You may consider to buy a GPU.
