### ISSUE TITLE
[FEATURE]: Fairs for fast search faces

### ISSUE THREAD

**Issue by aliuskonte** [serengil/deepface#1270]
### Description

Faiss is a library for efficient similarity search and clustering of dense vectors. It contains algorithms that search in sets of vectors of any size, up to ones that possibly do not fit in RAM. Faiss allows you to quickly perform the operation of searching for the k nearest vectors for a given vector. 

It will help speed up the search through a large database of photos. 

### Additional Info

I use Faiss with DeepFace a Flake outside of the repo. And i can share it for other users. 
If you want I will raise a pull request.

**Comment by serengil** [comment]
A-nn tools should be implemented externally

https://sefiks.com/tag/nearest-neighbor/
