### ISSUE TITLE
extract_faces not working 

### ISSUE THREAD

**Issue by PriyangshuMazumder** [serengil/deepface#1277]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.92

### Python version

3.12.4

### Operating System

MAC OS 

### Dependencies

absl-py==2.1.0
annotated-types==0.7.0
anyio==4.4.0
appnope==0.1.4
asgiref==3.8.1
asttokens==2.4.1
astunparse==1.6.3
attrs==23.2.0
backoff==2.2.1
bcrypt==4.1.3
beautifulsoup4==4.12.3
bleach==6.1.0
blinker==1.8.2
bs4==0.0.2
build==1.2.1
cachetools==5.3.3
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
chroma-hnswlib==0.7.3
chromadb==0.5.3
click==8.1.7
coloredlogs==15.0.1
comm==0.2.2
contourpy==1.2.1
cycler==0.12.1
debugpy==1.8.2
decorator==5.1.1
-e git+https://github.com/serengil/deepface.git@b75e37c3f6f5a7c523e54a1d9571299aaddc290c#egg=deepface
Deprecated==1.2.14
dnspython==2.6.1
email_validator==2.2.0
executing==2.0.1
fastapi==0.111.0
fastapi-cli==0.0.4
filelock==3.15.4
fire==0.6.0
Flask==3.0.3
Flask-Cors==4.0.1
flatbuffers==24.3.25
fonttools==4.53.1
fsspec==2024.6.1
gast==0.6.0
gdown==5.2.0
google==3.0.0
google-auth==2.31.0
google-pasta==0.2.0
googleapis-common-protos==1.63.2
grpcio==1.64.1
gunicorn==22.0.0
h11==0.14.0
h5py==3.11.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
huggingface-hub==0.23.4
humanfriendly==10.0
idna==3.7
importlib_metadata==7.1.0
importlib_resources==6.4.0
install==1.3.5
ipykernel==6.29.5
ipython==8.26.0
itsdangerous==2.2.0
jax==0.4.30
jaxlib==0.4.30
jedi==0.19.1
Jinja2==3.1.4
jupyter_client==8.6.2
jupyter_core==5.7.2
kaggle==1.6.14
keras==3.4.1
kiwisolver==1.4.5
kubernetes==30.1.0
libclang==18.1.1
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.1
matplotlib-inline==0.1.7
mdurl==0.1.2
mediapipe==0.10.14
ml-dtypes==0.3.2
mmh3==4.1.0
monotonic==1.6
mpmath==1.3.0
mtcnn==0.1.1
namex==0.0.8
nest-asyncio==1.6.0
numpy==1.26.4
oauthlib==3.2.2
onnxruntime==1.18.1
opencv-contrib-python==4.10.0.84
opencv-python==4.10.0.84
opentelemetry-api==1.25.0
opentelemetry-exporter-otlp-proto-common==1.25.0
opentelemetry-exporter-otlp-proto-grpc==1.25.0
opentelemetry-instrumentation==0.46b0
opentelemetry-instrumentation-asgi==0.46b0
opentelemetry-instrumentation-fastapi==0.46b0
opentelemetry-proto==1.25.0
opentelemetry-sdk==1.25.0
opentelemetry-semantic-conventions==0.46b0
opentelemetry-util-http==0.46b0
opt-einsum==3.3.0
optree==0.11.0
orjson==3.10.6
overrides==7.7.0
packaging==24.1
pandas==2.2.2
parso==0.8.4
pexpect==4.9.0
pillow==10.4.0
platformdirs==4.2.2
posthog==3.5.0
prompt_toolkit==3.0.47
protobuf==4.25.3
psutil==6.0.0
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pydantic==2.8.2
pydantic_core==2.20.1
Pygments==2.18.0
pyparsing==3.1.2
PyPika==0.48.9
pyproject_hooks==1.1.0
PySocks==1.7.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
python-slugify==8.0.4
pytz==2024.1
PyYAML==6.0.1
pyzmq==26.0.3
requests==2.32.3
requests-oauthlib==2.0.0
retina-face==0.0.17
rich==13.7.1
rsa==4.9
scipy==1.14.0
setuptools==70.2.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
sounddevice==0.4.7
soupsieve==2.5
stack-data==0.6.3
starlette==0.37.2
sympy==1.12.1
tenacity==8.4.2
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.2
termcolor==2.4.0
text-unidecode==1.3
tf_keras==2.16.0
tokenizers==0.19.1
tornado==6.4.1
tqdm==4.66.4
traitlets==5.14.3
typer==0.12.3
typing_extensions==4.12.2
tzdata==2024.1
ujson==5.10.0
urllib3==2.2.2
uvicorn==0.30.1
uvloop==0.19.0
watchfiles==0.22.0
wcwidth==0.2.13
webencodings==0.5.1
websocket-client==1.8.0
websockets==12.0
Werkzeug==3.0.3
wheel==0.43.0
wrapt==1.16.0
zipp==3.19.2

### Reproducible example

```Python
import deepface as DeepFace
backends = [
  'opencv', 
  'ssd', 
  'dlib', 
  'mtcnn', 
  'fastmtcnn',
  'retinaface', 
  'mediapipe',
  'yolov8',
  'yunet',
  'centerface',
]

alignment_modes = [True, False]

# #face verification
# obj = DeepFace.verify(
#   img1_path = "img1.jpg", 
#   img2_path = "img2.jpg", 
#   detector_backend = backends[0],
#   align = alignment_modes[0],
# )

# #face recognition
# dfs = DeepFace.find(
#   img_path = "img.jpg", 
#   db_path = "my_db", 
#   detector_backend = backends[1],
#   align = alignment_modes[0],
# )

# #embeddings
# embedding_objs = DeepFace.represent(
#   img_path = "img.jpg", 
#   detector_backend = backends[2],
#   align = alignment_modes[0],
# )

# #facial analysis
# demographies = DeepFace.analyze(
#   img_path = "img4.jpg", 
#   detector_backend = backends[3],
#   align = alignment_modes[0],
# )

#face detection and alignment
face_objs = DeepFace.extract_faces(
  img_path = "/Users/priyangshumazumder/Desktop/DeepFaceExp/Capture-18.jpg", 
  detector_backend = backends[5],
  align = alignment_modes[0],
)
```

### Relevant Log Output

{
	"name": "AttributeError",
	"message": "module 'deepface' has no attribute 'extract_faces'",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 48
     15 alignment_modes = [True, False]
     17 # #face verification
     18 # obj = DeepFace.verify(
     19 #   img1_path = \"img1.jpg\", 
   (...)
     46 
     47 #face detection and alignment
---> 48 face_objs = DeepFace.extract_faces(
     49   img_path = \"/Users/priyangshumazumder/Desktop/DeepFaceExp/Capture-18.jpg\", 
     50   detector_backend = backends[5],
     51   align = alignment_modes[0],
     52 )

AttributeError: module 'deepface' has no attribute 'extract_faces'"
}

**Comment by serengil** [comment]
You imported library incorrectly!
