### ISSUE TITLE
[FEATURE]: add extract_faces to the web API / Limit to number of faces with represent

### ISSUE THREAD

**Issue by Circuit8** [serengil/deepface#1282]
### Description

If I have an image with 100 faces, but I'm only interested in 10 biggest faces in the foreground. If I'm using the API there is no way to only get the embeddings for the biggest 10 faces in a performant way. by calling represent, every single face will be processed which can take a very long time, then I would have to filter out the 10 biggest afterwards.

One option would be to allow a max_faces parameter for the represent API, so that only the max_faces largest faces are analyzed and returned. Alternatively, extract_faces could be exposed to the web API, so that we could do this filtering ourselves, and call represent for only the faces were interested in.

Let me know if I'm missing something here!

Thanks

**Comment by serengil** [comment]
represent method is not for it. you need to call verify method many times with the current design.

**Comment by Circuit8** [comment]
I'm not sure I understand. I want to extract the embeddings for many faces in an image, so that I can later on use `verify` with those embeddings. `represent` is the API that should be used for this correct? However `represent` will extract embeddings for every single face. I'm suggesting limiting to the `max_faces` largest faces to make this more performant and not extract embeddings for background faces. Alternatively exposing `extract_faces` will allow us to perform this filtering client side and then call `represent` on each individual extracted face that were interested in.

**Comment by Circuit8** [comment]
Yes well my thinking was filtering the largest faces would be much faster than calculating an embedding for every single face, as that is quite an expensive operation. 

If this isn't something you would consider, would you consider exposing `extract_faces` to the web API?

**Comment by serengil** [comment]
no no, totally makes sense

**Comment by Circuit8** [comment]
Awesome thanks!

**Comment by serengil** [comment]
@Circuit8 just pushed the changes. You can pull the latest source code and try. Let me know when you test please.

**Comment by Circuit8** [comment]
@serengil just tested it, all working perfectly. Thanks so much!

**Comment by serengil** [comment]
no problem. i misunderstood your requirement initially, sorry for that.

**Comment by Circuit8** [comment]
No worries, I wasn't being that clear :+1:

**Comment by Circuit8** [comment]
@serengil any chance of a new release on dockerhub with these changes?

**Comment by serengil** [comment]
would you please open a new issue for this? also, what do you expect in the response payload? base64 encoded extracted face is okay?

**Comment by Circuit8** [comment]
This is all fixed now in master nothing needs to be added, just wondering if a release could be made to dockerhub with the changes.

**Comment by serengil** [comment]
yes sure
