### ISSUE TITLE
[FEATURE]: <How to free up memory after using the verify method>

### ISSUE THREAD

**Issue by doudousukyi37** [serengil/deepface#1284]
### Description

i use verify function to compare two picture,this function is in a loop.However, even if my loop only needs to compare once, it still leads to memory overflow and causes the program to crash. How can I clean up the memory after executing this method? I'm not sure if my optimization method is reasonable. My source code is shown below:
        for face_image in face_images:
            similar_label = DeepFace.verify(
                img1_path=cropped_face_image,
                img2_path=face_image,
                model_name='GhostFaceNet',
                enforce_detection=False,
                threshold=tolerance
            )

### Additional Info

deepface == 0.0.92
python == 3.8

**Comment by serengil** [comment]
https://sefiks.com/2019/03/20/tips-and-tricks-for-gpu-and-multiprocessing-in-tensorflow/#google_vignette
