### ISSUE TITLE
[FEATURE]: possible improvement: 1. Avoid duplicated face detection and 2. Batch image process for Emotion analysis

### ISSUE THREAD

**Issue by captainst** [serengil/deepface#1288]
### Description

First, thank you for this handy library!

We found 2 issues that could potentially be improved:

1. In certain cases, we need both the face identification, and emotion. Given the current implementation, we need to first call `Deepface.represent(...)`, then `DeepFace.analyze(...)`. Both functions call the detector, which is a duplication, especially when a slow detector, like Retinaface, or yolov8 is employed. Since the `Deepface.represent()` already detects the face patches, it is natural to directly use these patches for analyze.
2. Inside _deepface/extenedmodels/Emotion.py_, the `predict(...) `is used to processes the face patches one by one. If there are many faces to be processed, this sequential operation may lead to performance degradation, especially when using GPU. It is possible to add a batch predict function to address it.

I could submit a PR if the above could be beneficial.

Many thanks again!
4.

**Comment by serengil** [comment]
1- You can call extract_faces firstly and pass its output to repesent and analyze function. In that way, detection will be done once. All functions are accepting pre-loaded numpy arrays. So, I disagree to do anything for this topic.

2- in facial recognition models, we handled batch processing like - https://github.com/serengil/deepface/blob/master/deepface/basemodels/VGGFace.py#L66 . Same approach can be adopted in emotion model. If you are volunteer to do this, PRs are more than welcome!
