### ISSUE TITLE
retraining model takes longer time on a different data set

### ISSUE THREAD

**Issue by snehasrav25** [serengil/deepface#129]
I am following the below link example to retrain the race model on a different data set, however the retaining of the model is taking so much time for 10,000 images where the model is run on GPU. I followed the same bach-wise split but for each epoch, it's taking around 2 hours of time. Can you direct me towards retraining my model faster. Surprisingly the example I followed retrain in just a minute for each epoch, but mine is taking so much time. There is so much GPU and GPU memory left, but when I retrain the model it is not utilizing to the fullest. Any thoughts would be really helpful.

https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/

**Comment by serengil** [comment]
I had a very strong hardware. Many cpu core ~ 80. The hardware is here the important thing.
