### ISSUE TITLE
'NoneType' object has no attribute 'copy' -- error in database path

### ISSUE THREAD

**Issue by bulentsiyah** [serengil/deepface#13]
Hi, I got an error when trying to work because there is a space in the database path.

```
from deepface import DeepFace
DeepFace.stream("C:/FromUbuntu/Azure DevOps for Git/Proje Detayları/dataset")
```

![image](https://user-images.githubusercontent.com/22625644/78136599-96773800-742c-11ea-9d22-646473cdedab.png)

worked when moving dataset to a space without spaces
```
from deepface import DeepFace
DeepFace.stream("C:/dataset")
```

thanks for the great work

**Comment by serengil** [comment]
Non-english character in the image path causes this trouble. This is actually the bug of OpenCV. I'm looking for a workaround.

**Comment by bulentsiyah** [comment]
hi, You are right, my use of a folder with Turkish characters caused an error.

`from deepface import DeepFace
DeepFace.stream("C:/FromUbuntu/Azure DevOps for Git/Proje Detaylari/dataset")`

**thanks for the great work**
