### ISSUE TITLE
Input normalization overview

### ISSUE THREAD

**Issue by btlorch** [serengil/deepface#1300]
Thank you for developing this comprehensive toolbox of face detection and recognition models.

I am looking for an overview which model was trained with what kind of input preprocessing, so that I can apply the same input preprocessing to the face images during inference.
I have seen that the user [can specify](https://github.com/serengil/deepface/blob/285c6b7e36fd486ec7cd37fa44d3db447f0c6852/deepface/modules/preprocessing.py#L19) different types of input preprocessing. Let's say I want to extract facial embeddings using Facenet512d, which input preprocessing should be used?

Some of the related issues suggest that "no models are using normalization techniques", e.g., #1178. Does that mean all models expect pixel values in the range `[0, 1]`?

**Comment by serengil** [comment]
normalization argument is experimental usage only. i mean [threshold](https://github.com/serengil/deepface/blob/master/deepface/modules/verification.py#L370) values are tuned for normalization = base. if you set normalization to something different, then you shouldn't trust verified key anymore.

if you still insist to use it, you can follow the links in the license section in read me. they will redirect you to the reference repositories. you can find the adopted methods in there.

**Comment by btlorch** [comment]
Thank you for your answer. Do I understand correctly that the FaceNet weights were ported from the [original implementation](https://github.com/davidsandberg/facenet)?

Looking at their [README](https://github.com/davidsandberg/facenet/blob/master/README.md) and [Wiki page](https://github.com/davidsandberg/facenet/wiki/Training-using-the-VGGFace2-dataset), FaceNet 512 expects what they call *fixed image standardization*. [Their input pipeline](https://github.com/davidsandberg/facenet/blob/096ed770f163957c1e56efa7feeb194773920f6e/src/facenet.py#L120-L122) suggests that images should be normalized to the range `[-1, +1]`. Please correct me if I have a misunderstanding.

**Comment by serengil** [comment]
Reference repo is correct.

For the normalization question, you should find that answer from that repository.

**Comment by btlorch** [comment]
Ok, `normalization="ArcFace"` matches the original input normalization. Thank you.
