### ISSUE TITLE
[BUG]: <list indices must be integers or slices, not str>

### ISSUE THREAD

**Issue by osama-shehab** [serengil/deepface#1313]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.55

### Python version

3.12.5

### Operating System

windows 10

### Dependencies

i am using chaquopy sdk to use deepface in android studio

numpy : 1.19.5
opencv : 4.5.1
deepface : 0.0.55

### Reproducible example

```Python
def detect_emotion(image_path):
    """Detect emotion from the given image using DeepFace."""
    print("Image Path: ", image_path)
    try:
        # Analyze emotions using DeepFace
        analysis = DeepFace.analyze(image_path, actions=['emotion'])

        # Print detailed information for debugging
        print("DeepFace Analysis Results: ", analysis)  # Debugging output

        # Ensure the analysis result is a list
        if isinstance(analysis, list) and len(analysis) > 0:
            # Check the type and content of the first result
            first_result = analysis[0]
            print("Type of first result:", type(first_result))
            print("Content of first result:", first_result)

            if isinstance(first_result, dict):
                # Extract emotions
                emotions = first_result.get('emotions', {})
                print("Type of emotions:", type(emotions))
                print("Content of emotions:", emotions)

                if isinstance(emotions, dict):
                    # Find the dominant emotion
                    dominant_emotion = max(emotions, key=emotions.get, default='unknown')
                    return dominant_emotion
                else:
                    print("Emotions data is not a dictionary.")
            else:
                print("First result is not a dictionary.")
        else:
            print("Analysis result is not in the expected format.")

        return None
    except Exception as e:
        print(f"Error in DeepFace emotion detection: {e}")
        return None
```

### Relevant Log Output

Image Path:  /data/user/0/com.example.detectionpython/cache/temp_image_resized.png
Error in DeepFace emotion detection: list indices must be integers or slices, not str

### Expected Result

return dom emotion

### What happened instead?

None value

**Comment by serengil** [comment]
are you using deepface v0.0.55? 

v0.0.94 is on live, you should use it!

**Comment by osama-shehab** [comment]
> are you using deepface v0.0.55?
> 
> v0.0.94 is on live, you should use it!

In chaquopy the openCV latest version is 4.5.1 not 4.10 which is not compatible with deepface v0.0.94

**Comment by serengil** [comment]
does not matter, try to upgrade deepface with no dependencies

pip install deepface --upgrade --no-deps

**Comment by osama-shehab** [comment]
Failed to install opencv-python>=4.5.5.64 from https://files.pythonhosted.org/packages/4a/e7/b70a2d9ab205110d715906fc8ec83fbb00404aeb3a37a0654fdb68eb0c8c/opencv-python-4.10.0.84.tar.gz#sha256=72d234e4582e9658ffea8e9cae5b63d488ad06994ef12d81dc303b17472f3526 (from deepface==0.0.93).

**Comment by osama-shehab** [comment]
deepface 0.0.93 has requirement opencv-python>=4.5.5.64, but you'll have opencv-python 4.5.1.48 which is incompatible.

it show me this note and it's still running i will see the output

**Comment by serengil** [comment]
yes, deepface requires opencv-python>=4.5.5.64.

having opencv 4.5.1.48 is the issue of chaquopy not deepface

**Comment by osama-shehab** [comment]
all deepface versions requires opencv-python>=4.5.5.64 ?

**Comment by serengil** [comment]
latest deepface version requires this version

previous versions are not important

**Comment by osama-shehab** [comment]
this is the output:

NumPy version: 1.19.5
OpenCV version: 4.5.1
Deepface version: 0.0.93
Image Path:  /data/user/0/com.example.detectionpython/cache/temp_image_resized.png
Error in DeepFace emotion detection: type numpy.ndarray doesn't define __round__ method

**Comment by serengil** [comment]
in except block, print the all exception log as

```python
import traceback
print(traceback.format_exc())
```

**Comment by osama-shehab** [comment]
Traceback (most recent call last): 
File "/data/data/com.example.detectionpython/files/chaquopy/AssetFinder/app/emotion.py", line 34, in detect_emotion
  analysis = DeepFace.analyze(image_path, actions=['emotion'])
File "/data/data/com.example.detectionpython/files/chaquopy/AssetFinder/requirements/deepface/DeepFace.py", line 253, in analyze
   return demography.analyze(
File "/data/data/com.example.detectionpython/files/chaquopy/AssetFinder/requirements/deepface/modules/demography.py", line 123, in analyze
   img_objs = detection.extract_faces(
 File "/data/data/com.example.detectionpython/files/chaquopy/AssetFinder/requirements/deepface/modules/detection.py", line 158, in extract_faces
    "confidence": round(current_region.confidence, 2),
TypeError: type numpy.ndarray doesn't define __round__ method

**Comment by serengil** [comment]
try to upgrade your numpy to

```shell
pip install numpy==1.23.1 --upgrade
```

**Comment by serengil** [comment]
still, created this issue to fix that trouble - https://github.com/serengil/deepface/issues/1314

**Comment by osama-shehab** [comment]
> try to upgrade your numpy to
> 
> ```shell
> pip install numpy==1.23.1 --upgrade
> ```

Failed to install numpy==1.23.3 from https://files.pythonhosted.org/packages/0a/88/f4f0c7a982efdf7bf22f283acf6009b29a9cc5835b684a49f8d3a4adb22f/numpy-1.23.3.tar.gz#sha256=51bf49c0cd1d52be0a240aa66f3458afc4b95d8993d2d04f0d91fa60c10af6cd.

the problem from chaquopy i will try to update numpy and i will give you answer

**Comment by serengil** [comment]
try to upgrade it to latest, doesn't have to be 1.23.1

**Comment by osama-shehab** [comment]
the latest version written in chaquopy is 1.26.2

**Comment by osama-shehab** [comment]
in terminal gives me error the latest version 1.24.4 

i'm confused so im trying to upgrade to 1.23.3
