### ISSUE TITLE
Google (GDrive) Blocking Weight downloads for DeepFace

### ISSUE THREAD

**Issue by Karmatica** [serengil/deepface#132]
Hi,
thought I should let you know.....

Google seem to have blocked access to:
facial_expression_weights.h5
age_model_weights.h5
gender_model_weights.h5
... and others.

The link is currently not accessible. Message and link below:
https://drive.google.com/uc?id=1nz-WDhghGQBC4biwShQ9kYjvQMpO6smj

_Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator._

**Comment by serengil** [comment]
Unfortunately, you have to wait. Or you can download file manually and copy to HOME/.deepface/weights folder.

**Comment by Karmatica** [comment]
> Unfortunately, you have to wait. Or you can download file manually and copy to HOME/.deepface/weights folder.

Thanks. I managed to find the _emotions_ weight online and successfully added it to .deepface/weights. But I've been unable to find the other weights and  GDrive links have been blocked for a while now. Would you be able to provide me with an alterative download link please for _age_ and _race_. Thank you. Keep up the good work.
