### ISSUE TITLE
[FEATURE]: Add an optional flag to the "find" function in recognition.py to return an ndarray.

### ISSUE THREAD

**Issue by kremnik** [serengil/deepface#1332]
### Description

Currently, the `find` function in `recognition.py` file returns the information about faces in a Pandas `dataframe`, which is actually very convenient. However, when using this function on a large photo database, the `dataframe` structure can significantly slow down the finding process, particularly for operations like filtering and sorting.
I suggest adding an optioanl flag to the function that allows it to process and return raw `ndarray` instead of creating a `dataframe`.

**Comment by serengil** [comment]
it would be a good feature ONLY IF its default behaviour isn't changed. We don't want to change the default interface of find function.

**Comment by kremnik** [comment]
I agree with you, the default behavior should not be changed.

**Comment by serengil** [comment]
appreciate @kremnik as always
