### ISSUE TITLE
[FEATURE]: add support for batch size and improve utilization of GPU to maximum

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [serengil/deepface#1335]
### Description

currently, the codebase doesn't utilize gpu to maximum and it process images one by one. Add a batch size option .

### Additional Info

.

**Comment by Arslan-Mehmood1** [comment]
Well thats not the solution.

**Comment by gl-aoussou** [comment]
@serengil 

Could you please explain what you mean by 

> Calling deepface functions in a for loop will perform batch processing.

?

At this time, DeepFace can only analyze one image at a time. This does not mean that it isn't using the GPU.

OK, mathematically it's a batch of one, but obviously that's not what a "batch" means in practice.
