### ISSUE TITLE
[FEATURE]: Comprehensive list of model URLs

### ISSUE THREAD

**Issue by hacker1024** [serengil/deepface#1336]
### Description

We'd like to ship a prepackaged `DEEPFACE_HOME` in order to avoid unexpectedly downloading large files at runtime. At the moment, this is hard to do, because model downloads occur all throughout the codebase.

It'd be great if the model names, URLs, and file paths were kept in an easily parseable data structure that could be used by both DeepFace at runtime and packaging scripts beforehand.

**Comment by serengil** [comment]
DEEPFACE_HOME can be updated with environment variables - https://github.com/serengil/deepface/blob/master/deepface/commons/folder_utils.py#L34

What do you need exactly? Would you please be more clearer? I couldn't understand the requirement.

**Comment by hacker1024** [comment]
I'd like to download all the model files needed by DeepFace in advance, but there is no easy way to get a list of all the required files and URLs.

**Comment by serengil** [comment]
Sure, we can store them all into a dictionary.

**Comment by serengil** [comment]
@hacker1024 now, you can download all model weights in one shot with the following code snippet.

```python
from deepface.commons import weight_utils
weight_utils.download_all_models_in_one_shot()
```
