### ISSUE TITLE
[FEATURE]: Bulk process of DeepFace.verify

### ISSUE THREAD

**Issue by kcfdaniel** [serengil/deepface#1340]
### [FEATURE]: Bulk process of DeepFace.verify #1340

Up till 
https://pypi.org/project/deepface/0.0.31/

It supported

```
dataset = [
	['dataset/img1.jpg', 'dataset/img2.jpg'],
	['dataset/img1.jpg', 'dataset/img3.jpg']
]
resp_obj = DeepFace.verify(dataset)
```
As of 0.0.93, it's no longer supported.
I have tens of thousands of images to process at once.  Should I downgrade to 0.0.31, or is there a better/faster way to do DeepFace.verify?

**Comment by serengil** [comment]
You should call verify in a for loop.

Running previous version will most probably underperform.

**Comment by kcfdaniel** [comment]
gotcha!
