### ISSUE TITLE
[BUG]: Error using this library with pyinstaller?

### ISSUE THREAD

**Issue by enrique-lozano** [serengil/deepface#1344]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.93

### Python version

3.11

### Operating System

Windows 11

### Dependencies

deepface==0.0.93
opencv_contrib_python==4.10.0.84
opencv_python==4.10.0.84
opencv_python_headless==4.10.0.84
Pillow==10.4.0
tf_keras==2.17.0

### Reproducible example

I'm trying to build an executable file from a python script that use this library with the pyinstaller command:

```
pyinstaller -F face_recognition.py --distpath "../executables/windows" -y --clean --add-data
```

The .exe file is generated correctly but when running the executable, It ways that the XML model can not be found:

```
File "deepface\models\face_detection\OpenCv.py", line 143, in __build_cascade

ValueError: ('Confirm that opencv is installed on your environment! Expected path ', 'C:\\Users\\my_user\\AppData\\Local\\Temp\\_MEI53882\\cv2\\data\\haarcascade_frontalface_default.xml', ' violated.')
```

I supposed that I need to add the model path to the add-data param, so I try with this command (I have a virtual env.):

```
pyinstaller -F face_recognition.py --distpath "../executables/windows" -y --clean --add-data "env\Lib\site-packages\cv2\data\haarcascade_frontalface_default.xml;."
```

In my virtual environment, the model inside the cv2 library is in that path. Of course, the problem it's still happening. Anyone knows what can I do to make the executable file work?

**Comment by serengil** [comment]
You should ask this question to pyinstaller's repo
