### ISSUE TITLE
Why model cannot load in call verify before?

### ISSUE THREAD

**Issue by ciaoyizhen** [serengil/deepface#1345]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.91

### Python version

python3.10.12

### Operating System

centos7

### Dependencies

ultralytics==8.2.30
deepface==0.0.91

### Reproducible example

```Python
from deepface import Deepface

img_1 = "xxx"
img_2 = "xxx"

result = deepface.verify(img_1, img_2, model_name="Facenet512", detector_backend="yolov8")
print(result)
```

### Relevant Log Output

loadding model
model output

### Expected Result

model output

### What happened instead?

I'd like to be able to load the model at the beginning instead of when it's called!

### Additional Info

Firstly, I think this is a very serious bug if the model can't be loaded at the beginning.

Because, in the production environment, after the service is started, because it does not load the model, he does not use the memory, and then after the service call, it starts to take up the memory, if at this time, there is not enough memory, then there will be an OOM error, but if you take up the memory at the beginning, then it will not be so easy to have an OOM, with k8s

Secondly, loading the model only after it has been called will obviously make the first call very time consuming, maybe ten seconds????

Although it has been tested that only the first time will take up the model loading time consuming, can it be implemented to load it earlier? Let's say I call bulit_model in advance, and then pass the model into verify by

**Comment by ciaoyizhen** [comment]
I try for loop ten times

the firsy time -> 17.44
2-9 -> maybe 1-2

**Comment by serengil** [comment]
Model building is singletonish. If you do it once, you will not spend time on it. You can directly call build model to perform verify faster. Here, build model could be done in initialization of service.

from deepface import Deepface

# load model in advance
_ = DeepFace.build_model("Facenet512")

img_1 = "xxx"
img_2 = "xxx"

result = deepface.verify(img_1, img_2, model_name="Facenet512", detector_backend="yolov8")
print(result)

**Comment by ciaoyizhen** [comment]
Very clever method.
Thank you. I hadn't thought of that.
