### ISSUE TITLE
[FEATURE]: Accessing landmarks "nose", "mouth_right", and "mouth_left" (retinaface)

### ISSUE THREAD

**Issue by straycat231** [serengil/deepface#1347]
### Description

It seems that in retinaface (https://github.com/serengil/retinaface), the landmarks "nose", "mouth_right", and "mouth_left" are accessible when'd detecting faces, but I could not see them in the results with deepface, even when using retinaface as backend. Perhaps it would be possible to make those accessible if this backend is used?

**Comment by serengil** [comment]
fair enough
