### ISSUE TITLE
[FEATURE]: DeepFace.find - filter by file extension

### ISSUE THREAD

**Issue by PaulSamuelsonSI** [serengil/deepface#1349]
### Description

I want to be able to filter DeepFace.find by file extension.

I have a use case with jpg, jpeg, and png files stored in the same folder with the same base filenames. The jpg is the full-resolution image, the jpeg is a small thumbnail and the PNG is transparent with the background removed. Because all the images contain the same person(s) when I use DeepFace.find() I do not want to search all 3 file types. I want to specify the extension(s) as a parameter, keeping all 3 extensions as the default for backward compatibility.

**Comment by serengil** [comment]
Thank you for your suggestion and the detailed explanation of your use case!

After reviewing your request, we believe that adding file extension filtering within DeepFace.find may not significantly enhance the overall functionality. DeepFace is primarily focused on facial recognition, and managing file extensions is better suited for your data organization or pre-processing workflow.

We recommend organizing your folder structure in a way that separates the full-resolution images from thumbnails and transparent images, which would allow you to more easily control which files are being used. Alternatively, you could modify the DeepFace source code to suit your specific use case.

We appreciate your understanding and contribution!
