### ISSUE TITLE
[FEATURE]: Return the anti_spoofing flag instead raise ValueError

### ISSUE THREAD

**Issue by Felpz905** [serengil/deepface#1353]
### Description

Hello, it's all good?

I'm using the method DeepFace.find with anti_spoofing, when image is considered a Spoof, the method return a ValueError and stop method exec.

Here is a code snippet where this happens in deepface\modules\recognition.py:
```
251 if anti_spoofing is True and source_obj.get("is_real", True) is False:
252         raise ValueError("Spoof detected in the given image.")
```

The suggestion is to return the “is_real” field within result_df, which would make it easier to deal with spoofing errors based on the method's return and would not depend on checking based on an exception.

deepface\modules\recognition.py:
```
271 result_df["antispoof_score"] = source_obj["antispoof_score"]
272 result_df["is_real"] = source_obj["is_real"]
```

That said, all the methods and documentation in this library are amazing, congratulations!
Thanks!!

**Comment by serengil** [comment]
Thank you for your suggestion.

However, we will not be making this change. The anti-spoofing control you are referencing only applies to the source image, not the images available in the database. The current implementation throws an exception when a spoof is detected in the source image to ensure immediate handling of the issue.

In your program, you can handle this by wrapping the DeepFace.find method in a try-except block to catch and process the ValueError. This allows you to manage the flow based on your needs without modifying the library's core behavior.

Let me know if you need further clarification!
