### ISSUE TITLE
[FEATURE]: Configurable MediaPipe Detection parameters

### ISSUE THREAD

**Issue by tyasnk** [serengil/deepface#1360]
### Description

I use the Mediapipe backend as detector. I look at the source https://github.com/serengil/deepface/blob/master/deepface/models/face_detection/MediaPipe.py#L35 it hardcoded the `min_detection_confidence` param and also there is no `model_selection` param there.

It would be good if we can config them by using environment variable like this
```
face_detection = mp_face_detection.FaceDetection(
    min_detection_confidence=os.getenv("MEDIAPIPE_MIN_DETECTION_CONFIDENCE", 0.7),
    model_selection=os.getenv("MEDIAPIPE_MODEL_SELECTION", 0)
)
```

**Comment by serengil** [comment]
They are not hard coded! In case of corresponding env vars are empty, default values are set. So, you can manage them with environment variables.

**Comment by serengil** [comment]
Fair enough

**Comment by serengil** [comment]
@tyasnk do you mind to create a PR for this? you already written the most of the code.
