### ISSUE TITLE
[BUG]: <The GhostFaceNet model cannot run in the verify function on ARM64 architecture.>

### ISSUE THREAD

**Issue by doudousukyi37** [serengil/deepface#1363]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

v0.0.92

### Python version

3.10.1

### Operating System

Ubuntu22.04

### Dependencies

In my code, I use the verify function to check if two images are similar. I packaged the program with PyInstaller and ran it on both amd64 and arm64, which are both Ubuntu 22.04 systems. However, the verify function works fine on amd64, but on arm64 it cannot compare the images and there are no error messages. How can I find out the reason for the error? Here is the code I used in the program.

### Reproducible example

```Python
similar_label = DeepFace.verify(
                    img1_path=image,
                    img2_path=match[0],
                    model_name='GhostFaceNet',
                    # detector_backend='retinaface',
                    enforce_detection=False,
                    threshold=1 - match[1]
                )
```

**Comment by serengil** [comment]
You should raise this issue in tensorflow's repo, it is all about it instead of deepface.
