### ISSUE TITLE
Different results on version changes

### ISSUE THREAD

**Issue by abduakhatov** [serengil/deepface#137]
Firstly, thank you for the library, amazing one. 

Coming to issue, today I pulled latest commits and my tests revealed some changes in results, after this [commit](https://github.com/serengil/deepface/commit/b663ac641bf9f861668b8c19d6ade517a2e42171).

Before above commit with model: Dlib, distance_metric: cosine, enforce_detection=False and detector=opencv I had follownig results: 
``` {'verified': False, 'distance': 0.07104641720871241, 'max_threshold_to_verify': 0.07, 'model': 'Dlib', 'similarity_metric': 'cosine'}```
After:
``` {'verified': True, 'distance': 0.05064566577204832, 'max_threshold_to_verify': 0.07, 'model': 'Dlib', 'similarity_metric': 'cosine'}```

As for the expected results: the first result one was correct.

**Comment by serengil** [comment]
default detector is mtccn now, this might cause the results. could you set detector_backend = 'opencv'

**Comment by abduakhatov** [comment]
In both cases above, I had opencv as detector,  and now i tried different detecots including mtccn. 
{'verified': True, 'distance': 0.042281921647302045, 'threshold': 0.07, 'metric': 'cosine', 'model': 'dlib'}

**Comment by abduakhatov** [comment]
Well, I opened this issue, because I thought this may somehow help you. Otherwise, I can close it.

**Comment by serengil** [comment]
As I mentioned, it seems detector backend effect. Nothing to worry :) thank you. I'm closing the issue.
