### ISSUE TITLE
Can image alignment be performed before performing face detection

### ISSUE THREAD

**Issue by TheHonestBob** [serengil/deepface#1371]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

v0.0.93

### Python version

3.9.19

### Operating System

ubuntu 22

### Dependencies

When my original image is rotated 90 degrees, if it is not aligned beforehand, it will seriously affect the effectiveness of the face detection model. Therefore, can we align the original image first and then rotate it

### Reproducible example

```Python
无
```

**Comment by serengil** [comment]
face detectors fail to find the eye coordinates for 90 degree aligned images. nothing to do unfortunately.

on the other hand, we are performing alignment first and detection second for images already.
