### ISSUE TITLE
[DOC]: <Add accuracy>

### ISSUE THREAD

**Issue by csipapicsa** [serengil/deepface#1375]
### Suggested Changes

Hi,

What is the emotion detection accuracy? This site says:

https://sefiks.com/2018/01/01/facial-expression-recognition-with-keras/

"Model produces 57% accuracy on test set. That can be acceptable because winner of kaggle challenge has got 34% accuracy."

So this is it?

**Comment by serengil** [comment]
Yeah, you found the answer by yourself!
