### ISSUE TITLE
[BUG]: Incompatibility with tensorflow 2.17.0

### ISSUE THREAD

**Issue by Anandesh-Sharma** [serengil/deepface#1376]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.93

### Python version

3.10

### Operating System

Ubuntu 22.04

### Dependencies

absl-py==2.1.0
addict==2.4.0
aiohappyeyeballs==2.4.3
aiohttp==3.10.10
aiohttp-devtools==1.1.2
aiohttp-middlewares==2.4.0
aioice==0.9.0
aiortc==1.9.0
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.6.2.post1
asttokens==2.4.1
astunparse==1.6.3
async-timeout==4.0.3
attrs==24.2.0
av==12.3.0
basicsr==1.4.2
beautifulsoup4==4.12.3
blinker==1.8.2
boto3==1.35.44
botocore==1.35.44
build==1.2.2.post1
CacheControl==0.14.0
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
cleo==2.1.0
click==8.1.7
contourpy==1.3.0
crashtest==0.4.1
cryptography==43.0.3
cycler==0.12.1
deepface==0.0.93
devtools==0.12.2
distlib==0.3.9
dlib==19.24.6
dnspython==2.7.0
dulwich==0.21.7
email_validator==2.2.0
exceptiongroup==1.2.2
executing==2.1.0
facexlib==0.3.0
fastapi==0.115.2
fastapi-cli==0.0.5
fastjsonschema==2.20.0
filelock==3.16.1
filterpy==1.4.5
fire==0.7.0
firebase-admin==6.5.0
Flask==3.0.3
Flask-Cors==5.0.0
flatbuffers==24.3.25
fonttools==4.54.1
frozenlist==1.4.1
fsspec==2024.9.0
future==1.0.0
gast==0.4.0
gdown==5.2.0
gfpgan==1.3.8
google-api-core==2.21.0
google-api-python-client==2.149.0
google-auth==2.35.0
google-auth-httplib2==0.2.0
google-auth-oauthlib==0.4.6
google-cloud-core==2.4.1
google-cloud-firestore==2.19.0
google-cloud-storage==2.18.2
google-crc32c==1.6.0
google-pasta==0.2.0
google-resumable-media==2.7.2
googleapis-common-protos==1.65.0
grpcio==1.67.0
grpcio-status==1.62.3
gunicorn==22.0.0
h11==0.14.0
h5py==3.12.1
httpcore==1.0.6
httplib2==0.22.0
httptools==0.6.4
httpx==0.27.2
idna==3.10
ifaddr==0.2.0
imageio==2.36.0
importlib_metadata==8.5.0
iniconfig==2.0.0
installer==0.7.0
itsdangerous==2.2.0
jaraco.classes==3.4.0
jeepney==0.8.0
Jinja2==3.1.4
jmespath==1.0.1
joblib==1.4.2
keras==3.6.0
Keras-Preprocessing==1.1.2
keyring==24.3.1
kiwisolver==1.4.7
lazy_loader==0.4
libclang==18.1.1
livekit-api==0.7.1
livekit-protocol==0.6.0
llvmlite==0.43.0
lmdb==1.5.1
loguru==0.7.2
lz4==4.3.3
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==3.0.2
matplotlib==3.9.2
mdurl==0.1.2
ml-dtypes==0.4.1
more-itertools==10.5.0
mpmath==1.3.0
msgpack==1.1.0
mtcnn==1.0.0
multidict==6.1.0
namex==0.0.8
networkx==3.4.1
numba==0.60.0
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.77
nvidia-nvtx-cu12==12.1.105
nvidia-tensorrt==99.0.0
oauthlib==3.2.2
opencv-python==4.10.0.84
opt_einsum==3.4.0
optree==0.13.0
packaging==24.1
pandas==2.2.3
pexpect==4.9.0
pillow==10.4.0
pkginfo==1.11.2
platformdirs==4.3.6
pluggy==1.5.0
poetry==1.8.4
poetry-core==1.9.1
poetry-plugin-export==1.8.0
propcache==0.2.0
proto-plus==1.24.0
protobuf==4.25.5
ptyprocess==0.7.0
pyasn1==0.6.1
pyasn1_modules==0.4.1
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
pyee==12.0.0
Pygments==2.18.0
PyJWT==2.9.0
pylibsrtp==0.10.0
pymongo==4.10.1
pyOpenSSL==24.2.1
pyparsing==3.2.0
pyproject_hooks==1.2.0
PySocks==1.7.1
pytest==8.3.3
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.12
pytz==2024.2
PyYAML==6.0.2
pyzbar==0.1.9
RapidFuzz==3.10.0
realesrgan==0.3.0
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
retina-face==0.0.17
rich==13.9.2
rsa==4.9
s3transfer==0.10.3
scikit-image==0.24.0
scipy==1.14.1
SecretStorage==3.3.3
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
starlette==0.40.0
sympy==1.13.3
tb-nightly==2.19.0a20241019
tensorboard==2.17.1
tensorboard-data-server==0.7.2
tensorboard-plugin-wit==1.8.1
tensorflow==2.17.0
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.37.1
tensorrt==10.5.0
tensorrt-cu12==10.5.0
tensorrt-cu12-bindings==10.5.0
tensorrt-cu12-libs==10.5.0
termcolor==2.5.0
tf_keras==2.17.0
tifffile==2024.9.20
tomli==2.0.2
tomlkit==0.13.2
torch==2.3.1
torchvision==0.18.1
tqdm==4.66.5
triton==2.3.1
trove-classifiers==2024.10.16
typer==0.12.5
types-protobuf==4.25.0.20240417
typing_extensions==4.12.2
tzdata==2024.2
uritemplate==4.1.1
urllib3==2.2.3
uvicorn==0.32.0
uvloop==0.21.0
virtualenv==20.27.0
watchfiles==0.24.0
websockets==13.1
Werkzeug==3.0.4
wrapt==1.16.0
yapf==0.40.2
yarl==1.15.5
zipp==3.20.2

### Reproducible example

```Python
from deepface import DeepFace


def detect_faces(image):
    detected_faces = DeepFace.extract_faces(
        image,
        color_face="bgr",
        enforce_detection=False,
        detector_backend="retinaface",
    )
    return detected_faces




Invoked in 
result = search_face(cf["cropped_image"]) # cf["cropped_image"] -> np.array
```

### Relevant Log Output

Oct 22 16:54:01 biometric fastapi[556207]: 2024-10-22 16:54:01.581 | ERROR    | src.webrtc.video:search_face_task:213 - Error in search face task: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:
Oct 22 16:54:01 biometric fastapi[556207]: ```
Oct 22 16:54:01 biometric fastapi[556207]: x = Input(...)
Oct 22 16:54:01 biometric fastapi[556207]: ...
Oct 22 16:54:01 biometric fastapi[556207]: tf_fn(x)  # Invalid.
Oct 22 16:54:01 biometric fastapi[556207]: ```
Oct 22 16:54:01 biometric fastapi[556207]: What you should do instead is wrap `tf_fn` in a layer:
Oct 22 16:54:01 biometric fastapi[556207]: ```
Oct 22 16:54:01 biometric fastapi[556207]: class MyLayer(Layer):
Oct 22 16:54:01 biometric fastapi[556207]:     def call(self, x):
Oct 22 16:54:01 biometric fastapi[556207]:         return tf_fn(x)
Oct 22 16:54:01 biometric fastapi[556207]: x = MyLayer()(x)
Oct 22 16:54:01 biometric fastapi[556207]: ```
Oct 22 16:54:01 biometric fastapi[556207]: Traceback (most recent call last):
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/src/webrtc/video.py", line 164, in search_face_task
Oct 22 16:54:01 biometric fastapi[556207]:     df_data = df_detect_faces(image=np.array(cf["cropped_image"]))
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/src/lib/face/deepface/__init__.py", line 5, in detect_faces
Oct 22 16:54:01 biometric fastapi[556207]:     detected_faces = DeepFace.extract_faces(
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/venv/lib/python3.10/site-packages/deepface/DeepFace.py", line 549, in extract_faces
Oct 22 16:54:01 biometric fastapi[556207]:     return detection.extract_faces(
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/venv/lib/python3.10/site-packages/deepface/modules/detection.py", line 95, in extract_faces
Oct 22 16:54:01 biometric fastapi[556207]:     face_objs = detect_faces(
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/venv/lib/python3.10/site-packages/deepface/modules/detection.py", line 206, in detect_faces
Oct 22 16:54:01 biometric fastapi[556207]:     face_detector: Detector = modeling.build_model(
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/venv/lib/python3.10/site-packages/deepface/modules/modeling.py", line 96, in build_model
Oct 22 16:54:01 biometric fastapi[556207]:     cached_models[task][model_name] = model()
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/venv/lib/python3.10/site-packages/deepface/models/face_detection/RetinaFace.py", line 9, in __init__
Oct 22 16:54:01 biometric fastapi[556207]:     self.model = rf.build_model()
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/venv/lib/python3.10/site-packages/retinaface/RetinaFace.py", line 54, in build_model
Oct 22 16:54:01 biometric fastapi[556207]:     retinaface_model.build_model(),
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/venv/lib/python3.10/site-packages/retinaface/model/retinaface_model.py", line 1027, in build_model
Oct 22 16:54:01 biometric fastapi[556207]:     x1_shape = tf.shape(ssh_c3_up)
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/venv/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
Oct 22 16:54:01 biometric fastapi[556207]:     raise e.with_traceback(filtered_tb) from None
Oct 22 16:54:01 biometric fastapi[556207]:   File "/home/hash/events.api/venv/lib/python3.10/site-packages/keras/src/backend/common/keras_tensor.py", line 138, in __tf_tensor__
Oct 22 16:54:01 biometric fastapi[556207]:     raise ValueError(
Oct 22 16:54:01 biometric fastapi[556207]: ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:
Oct 22 16:54:01 biometric fastapi[556207]: ```
Oct 22 16:54:01 biometric fastapi[556207]: x = Input(...)
Oct 22 16:54:01 biometric fastapi[556207]: ...
Oct 22 16:54:01 biometric fastapi[556207]: tf_fn(x)  # Invalid.
Oct 22 16:54:01 biometric fastapi[556207]: ```
Oct 22 16:54:01 biometric fastapi[556207]: What you should do instead is wrap `tf_fn` in a layer:
Oct 22 16:54:01 biometric fastapi[556207]: ```
Oct 22 16:54:01 biometric fastapi[556207]: class MyLayer(Layer):
Oct 22 16:54:01 biometric fastapi[556207]:     def call(self, x):
Oct 22 16:54:01 biometric fastapi[556207]:         return tf_fn(x)
Oct 22 16:54:01 biometric fastapi[556207]: x = MyLayer()(x)
Oct 22 16:54:01 biometric fastapi[556207]: ```

### Expected Result

I have tried running the retina face in my macbook m1 pro with TF version 2.17.0 and it works fine. But here on my ubuntu it doesnt. 

My ubuntu VM has GPU in it and uses CUDA ability. I have tried opencv and dlib, they work fine.

My thoughts:
1. May be its having issues with CUDA, because on mac it works fine. 
2. May be its just dependency issue or version of tf-keras.

Any help would be appreciated. 

Note: I have checked another issue, that suggests to use old package. But I cant change the version as my existing packages depend on tf 2.17.0

**Comment by serengil** [comment]
You should raise this issue in tensorflow's repo, it is all about it instead of deepface.
