### ISSUE TITLE
[FEATURE]: Adding OFIQ quality assessment for facial image

### ISSUE THREAD

**Issue by Tuulimylly-Jack** [serengil/deepface#1387]
### Description

Since the studies show that quality of the facial image impacts on recognition accuracy, it would be nice facial image QA tool integrated in DeepFace. BSI have developed an open-source refrence implementation (https://github.com/BSI-OFIQ/OFIQ-Project) of ISO/IEC 29794-5 which would fit well in DeepFace.

**Comment by serengil** [comment]
Isn't it a c / c++ library?
