### ISSUE TITLE
[BUG]: Manually docker built container fails 

### ISSUE THREAD

**Issue by Josefer25** [serengil/deepface#1388]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

latest commit

### Python version

docker

### Operating System

macOs

### Dependencies

--

### Reproducible example

```Python
So if you manually build the image and then run it, it seems to work but then on every request it says: TypeError: create_app() takes 0 positional arguments but 2 were given
```

### Relevant Log Output

TypeError: create_app() takes 0 positional arguments but 2 were given

**Comment by Josefer25** [comment]
Sorry for the messy format, is about docker and I didn't know how to do it. In apple silicon processors the prebuilt image does not work because avx, through conda it usually raises a SIGSEGV (which might be a bug aswell) and the only left option is to try to build manually the image, which fails aswell.

**Comment by serengil** [comment]
https://github.com/serengil/deepface/commit/e73bdb813801e91cc54c016ffc651daa138ea922
