### ISSUE TITLE
.JPG file issue in the find function

### ISSUE THREAD

**Issue by Fatima-Ali8765** [serengil/deepface#139]
I followed the pattern of large scale face recognition in my colab but for some reason in the find() function, it is showing the following error: 
('There is no image in ', '/content/my_db', ' folder!') even though I properly named my file.
'my_db' contains 2 folders: Class 70 and Class 74. Each class contains 7-8 images in the form 070A10.JPG in class 70, 074A15.JPG in class 74 and so on.
Only when i changed the name to .jpg by renaming, it worked.
Could the issue be resolved?

**Comment by serengil** [comment]
I fixed this in the last commit. Besides, it will appear in the version 0.0.44 soon. Thank you.
