### ISSUE TITLE
represent() uses base normalization by default which is almost always wrong

### ISSUE THREAD

**Issue by jbellis** [serengil/deepface#1391]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.94

### Python version

3.10

### Dependencies

n/a

### Reproducible example

```Python
embedding_objs = DeepFace.represent(
  img_path = "img.jpg"
)
```

### Expected Result

represent should default to appropriate normalization for the model in use

### What happened instead?

represent uses "base" normalization by default which is image with its components divided by 255

instead it should default to the normalization required by the model in use

**Comment by jbellis** [comment]
Just to make sure I understand correctly: it is your position that using VGGFace normalization with VGGFace model is the wrong default?

**Comment by serengil** [comment]
if you use vggface normalization, then you will get lower results.

**Comment by jbellis** [comment]
That is not what I observe.

**Comment by serengil** [comment]
then, you are free to use that normalization.

**Comment by jbrownkramer** [comment]
Thanks for this excellent repo!

I started opening my own issue to say exactly this, but then I found this one.  My experience with other models is that getting the normalization wrong dramatically impacts results - for the worse.  Are the models in this repo somehow prepared for "base" normalization?  If not, is it just an empirical fact that EVERY model works better with base normalization?  Do you have some insight into why this might be?

**Comment by serengil** [comment]
I can confirm that base normalization consistently outperforms other normalization techniques for every model in this repo. You can find detailed results in the benchmarks folder.

While base normalization is highly recommended, DeepFace provides the flexibility to use your own normalization method if you prefer. If you are determined to use a normalization technique other than base normalization, you are absolutely free to do so. However, as i mentioned, other normalization techniques are experimental purpose only and underperform.

Feel free to share your findings if you notice any significant differences!

**Comment by jbrownkramer** [comment]
I don't have the resources at my disposal right now to run full tables.  But I tried 

```
models = ["Facenet"]
detectors = ["opencv"]
metrics = ["euclidean_l2"]
alignment = [True]
```

with normalization="Facenet" and the accuracy was 86.4 as opposed to the reported 84.8.
