### ISSUE TITLE
Train Olayı

### ISSUE THREAD

**Issue by hhakangull** [serengil/deepface#14]
Şefik hocam kütüphanenizi anlık olarak izliyor takip ediyorum :) github ınızda gördüğüm kadarıyla realtime.py dosyasını farkettim 
inceledikten sonra farkettim ki her çalıştırmada image_path klasörünü her seferinde train ediyor.
Bunu her seferinde yapmak yerine o klasörü train ettikten sonra bir dosyaya yazıp daha sonra çalıştırma işini öyle yapsak daha iyi olmaz mı ? 

Hatta şöyle bir şey daha sorayım örnek olarak ocak ayındaki train dosyaları gibi bir ayrıma giderek şöyle bir şey yapmak mümkün mü 

people/ocak --> ocak ayında gelen insanların fotoğrafı ve içerisinde bu fotoğrafların analizini modele yükleyebileceğimiz bir .yaml dosyası

poeple/subat gibi bir şey yapmak mümkün mü ?

**Comment by serengil** [comment]
ilginiz için teşekkürler. ancak klasöre yeni resim eklenilip çıkarıldığı zaman değişiklikten haberi olmayacak framework'un bu durumda. dolayısıyla stream fonksiyonu çağırıldığında ilk çalışırken bu bilgilerin baştan alınmasını tercih ettim.

öneri ve geri bildirim için teşekkürler. issue'yu kapalı duruma getiriyorum.
