### ISSUE TITLE
Suggestion to improve face alignment performance in extract_faces()

### ISSUE THREAD

**Issue by huulockt** [serengil/deepface#1400]
### Description

First of all, I want to say thank you for creating and maintaining **DeepFace**. It’s a very useful and convenient framework.

While using the `extract_faces()` function, I noticed that when `alignment=True`, the _confidence_ of the detection results and overall performance are negatively impacted, especially when using lightweight models like **centerface** or **yunet**.

After checking the `detect_faces()` function in `deepface.modules.detection`, I found that a black border is added around the source image when `alignment=True`, before the `face_detector.detect_faces()` function is called. I believe this step is unnecessary and might be the reason for the reduced _confidence_ and performance.

If the intention is to prevent alignment from shifting detected faces outside the image boundary when they are close to the edges, I propose an alternative approach:
- Add a preprocessing step that applies the "border" only to the face region, not the entire image.
- As a suggestion, the "border" can replicate nearby pixels from the source image and only add a black region if there are not enough pixels available.

This solution will maintain the robustness of the face detector while significantly improving the speed of the `align_img_wrt_eyes` process, especially when the input image contains multiple faces.

I look forward to hearing your thoughts on this! :)

### Additional Info

My DeepFace version is 0.0.93 (installed via pip install)

**Comment by huulockt** [comment]
So, does this mean that the detection results can be affected when faces are close to the borders?

**Comment by serengil** [comment]
With current design, no.

With the design you recommended, yes.

**Comment by huulockt** [comment]
That's strange. In the current design, a border is added before calling detect_faces, whereas in my proposed design, `detect_faces` is called directly on the source image. Adding a border makes the image larger, and during model preprocessing, it must be scaled down, which inevitably causes a loss of information.
