### ISSUE TITLE
How to configure a custom model path?

### ISSUE THREAD

**Issue by Lixi20** [serengil/deepface#1408]
### Description

Because the code requires it, I downloaded the following models: age_model_weights.h5 arcface_weights.h5 facial_expression_model_weights.h5 gender_model_weights.h5 retinaface.h5, and the path to store the models is: /root/.deepface/weights, but in order to uniformly manage the model paths, I need to add custom model paths in the code, for example: I put the models in: /root/var/lib/, I need to specify the paths of these models in the code: mod_path="/root/var/lib/retinaface.h5", but I don't know what parameters can be added, can you help me?

**Comment by serengil** [comment]
You raised this as enhancement but you are basically using issue tracker to ask questions. You should use stackoverflow to ask questions as mentioned while creating issues.

**Comment by ArijitSinghEDA** [comment]
@serengil Please open a discussion section for this GitHub repo so as we can ask our doubts there, because the question still remains that if I have my pretrained model weights with me, how can I use the path instead of the model name?

**Comment by serengil** [comment]
You should use stackoverflow for these purposes

**Comment by Sunshine352** [comment]
> [@serengil](https://github.com/serengil) Please open a discussion section for this GitHub repo so as we can ask our doubts there, because the question still remains that if I have my pretrained model weights with me, how can I use the path instead of the model name?

By setting environment vars,  you can custom the model path. Code show as follows.
`
import os
os.environ["DEEPFACE_HOME"]=f"{your_model_dir}"
# your *.h5 model put in f"{your_model_dir}/.deepface/weights"
_ = DeepFace.build_model(model_name='ArcFace')
embedding_objs = DeepFace.represent(
    img_path=image_path,
    model_name='ArcFace',
    enforce_detection=False,
    detector_backend='skip',
    align=False,
    normalization='ArcFace'
)
`

**Comment by Sunshine352** [comment]
> ### Description
> Because the code requires it, I downloaded the following models: age_model_weights.h5 arcface_weights.h5 facial_expression_model_weights.h5 gender_model_weights.h5 retinaface.h5, and the path to store the models is: /root/.deepface/weights, but in order to uniformly manage the model paths, I need to add custom model paths in the code, for example: I put the models in: /root/var/lib/, I need to specify the paths of these models in the code: mod_path="/root/var/lib/retinaface.h5", but I don't know what parameters can be added, can you help me?
> 
> ### Additional Info
> _No response_

By setting environment vars, you can custom the model path. Code show as follows. Your .h5 model should put in f"{your_model_dir}/.deepface/weights/.h5"

`import os os.environ["DEEPFACE_HOME"]=f"{your_model_dir}" _ = DeepFace.build_model(model_name='ArcFace') embedding_objs = DeepFace.represent( img_path=image_path, model_name='ArcFace', enforce_detection=False, detector_backend='skip', align=False, normalization='ArcFace' )`
