### ISSUE TITLE
how to stop warning tensorflow

### ISSUE THREAD

**Issue by Noraluk** [serengil/deepface#145]
WARNING:tensorflow:6 out of the last 7 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fdffe0ac1f0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

**Comment by serengil** [comment]
Set this before calling deepface

import tensorflow as tf
import logging
tf.get_logger().setLevel(logging.ERROR)

I'll add this block in the framework in the next release

**Comment by serengil** [comment]
test/unit_test.py does it actually. you can see how to disable those kind of errors.
