### ISSUE TITLE
Api error with upgtrade to TF 2

### ISSUE THREAD

**Issue by t3ch9** [serengil/deepface#146]
Hello, I upgraded deepface and cloned the repo to the latest version. When I run api.py I get the following error:

Traceback (most recent call last):
  File "api.py", line 90, in <module>
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

**Comment by t3ch9** [comment]
Was able to resolve the error with:

tf.compat.v1.get_default_graph

**Comment by serengil** [comment]
wrong alert? is this solved?
