### ISSUE TITLE
Model indilemiyor

### ISSUE THREAD

**Issue by askinucuncu** [serengil/deepface#148]
Merhaba Şefik Bey,

Sistemi çalıştırdığımda modeli indirmeyi deniyor ancak başarısız oluyor. Link'e kendim baktığımda link aktif sorun yok. Kendim indirdiğim model dosyasını yol olarak nasıl verebilirim?

Unable to open file (unable to open file: name = '/root/.deepface/weights/vgg_face_weights.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by serengil** [comment]
Çok fazla indirilme talebi olduğunda verebiliyor bu hatayı google drive.

HOME_FOLDER/.deepface/weights altına saklayabilirsiniz.

HOME_FOLDER benim bilgisayarımda C:/Users/Sefik örneğin. Aşağıdaki kod bloğuyla da öğrenebilirsiniz.

```
from pathlib import Path
home = str(Path.home())
```
