### ISSUE TITLE
Yüz bulunamadı

### ISSUE THREAD

**Issue by askinucuncu** [serengil/deepface#151]
Merhaba Şefik Bey,

5 bin kişilik face database oluşturdum internetten indirdiğim resimler ile. Ancak birçok resimde yüz olmasına rağmen yüz tespit edilemedi diye hata alıyorum. Örneğin aşağıdaki resim. Zorla yüz algılamayı devre dışı bırakınca. da alakasız bir insanın yüzü olarak tanıyor. Bu konuda nerede yanlış yapıyorum. Bu arada elastic search üzerinde arama yapıyorum.

https://www.sacekiyoruz.biz/FileUpload/bs276640/File/bulent_cihantimur.jpg

**Comment by askinucuncu** [comment]
Resim arama kodum aşağıdaki gibi;

target_size = (160, 160)
    embedding_size = 128

    target_img = functions.preprocess_face(img1_path, target_size = target_size)
    target_embedding = modelD.predict(target_img)[0]

    query = {
        "size": 1,
        "query": {
        "script_score": {
            "query": {
                "match_all": {}
            },
            "script": {
                "source": "1 / (1 + l2norm(params.queryVector, 'title_vector'))",
                "params": {
                    "queryVector": list(target_embedding)
                }
            }
        }
    }}

    res = es.search(index="faces", body=query)
    item = res["hits"]["hits"]

**Comment by askinucuncu** [comment]
Resim DB si oluşturmak için de aşağıdaki kodu kullanıyorum;

if es.indices.exists(index="faces"):
        try:
            img = functions.preprocess_face(res_path, target_size = target_size)
            embedding = modelD.predict(img)[0]
            
            doc = {"title_vector": embedding, "title_name": res_ad, "title_path": res_path}
            es.index("faces", body=doc)
        except Exception as e:
            print(e)

**Comment by serengil** [comment]
modelD nedir? facenet mi dlib mi?

**Comment by askinucuncu** [comment]
Facenet

**Comment by serengil** [comment]
dlib ile de dener misiniz peki?

**Comment by serengil** [comment]
bir de resim db'si oluşturma adımında preprocess_face adımı hata alırsa hiç db'ye atmasın, enforce_detection = True kalsın yani. Böylelikle sadece yüzü algılayabildiği yüksek kaliteli resimlerle çalışacaktır.

**Comment by askinucuncu** [comment]
Merhaba, Aslında try bloğunda yazdığım için zaten veri tabanına eklenmiyor yüz bulunamayınca ancak yüz olduğu çok net belli olan resimlerde bile yüz bulunamadı diyebiliyordu ancak dlib sorunu çözdü. Yaklaşık 1200 yüz bulunamıyor seviyesinden 15 e kadar düştü. Bunlarda zaten çok zorlayıcı resimler. Çok teşekkürler yardımlarınız için.

**Comment by serengil** [comment]
dlib facenet'ten daha stabil görünüyor. bilgilendirme için teşekkürler.
