### ISSUE TITLE
verify function could be passed with numpy array ?

### ISSUE THREAD

**Issue by thisKK** [serengil/deepface#153]
I want to use DeepFace.verify() on a numpy array representing an image
`img1 = img1[:,:,::-1]; img2 = img2[:,:,::-1]

obj = DeepFace.verify(img1, img2
   , model_name = 'Dlib', distance_metric = 'euclidean')`

**Comment by serengil** [comment]
exact image path, numpy array or base64 encoded images could be pass to verify function.

**Comment by thisKK** [comment]
i got error like this
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-187-ef3b8c058f49> in <module>()
----> 1 obj = DeepFace.verify(img1, img2, model_name = "Dlib", distance_metric = "euclidean")

1 frames
/usr/local/lib/python3.6/dist-packages/deepface/commons/functions.py in initialize_input(img1_path, img2_path)
     39         else:
     40                 bulkProcess = False
---> 41                 if img2_path != None:
     42                         img_list = [[img1_path, img2_path]]
     43                 else:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by serengil** [comment]
Oke I understand the problem.

please upgrade deepface to 0.0.49 this is fixed in this release.

**Comment by serengil** [comment]
I also share the my testing code

```
import cv2

img1 = cv2.imread("deepface/tests/dataset/img1.jpg")
img2 = cv2.imread("deepface/tests/dataset/img2.jpg")

print(type(img1))
print(type(img2))

from deepface import DeepFace
obj = DeepFace.verify(img1, img2)
print(obj)
```

This returns the following message

(tensorflow) C:\Users\IS96273\Desktop>python dummy.py
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Using TensorFlow backend.
{'verified': True, 'model': 'VGG-Face', 'similarity_metric': 'cosine', 'distance': 0.2709779739379883, 'max_threshold_to_verify': 0.4}

I also add a control for numpy inputs in the unit tests. Thank you very much.

**Comment by thisKK** [comment]
Thank you very much for your help
