### ISSUE TITLE
[suggestion] Importing module 'gdown' at Boosting.py file

### ISSUE THREAD

**Issue by gui-lizarza** [serengil/deepface#155]
While experimenting with deepface in Google Colab, I ran into a problem when the function build_gbm() (at deepface > basemodels > Boosting.py) was called. The error message shown was `NameError: name 'gdown' is not defined`.

When manually adding `import gdown` at the beginning of the Boosting.py file, the function is called without further problems.

**Comment by serengil** [comment]
you're right. I fixed in in this next version and it will be released just in few minutes.

**Comment by serengil** [comment]
upgrade to 0.0.49 :) thank you.
