### ISSUE TITLE
can not use pip install deepface

### ISSUE THREAD

**Issue by thylm** [serengil/deepface#158]
I try install deepface by pip in windows. but it not work. it show "Requirement already satisfied:...." and repeat and repeat

**Comment by serengil** [comment]
if it says requirement already satisfied, then installation is complete. if you have trouble when you import deepface, then you might install it on a different python version or virtual environment.

try this command: "python -m pip install deepface" and run same python with your programs "python hello.py"

**Comment by thylm** [comment]
Yes. Thank you. I already installed it successfully. It failed because of my mistake. The environment has conflict.
