### ISSUE TITLE
enforce_detection

### ISSUE THREAD

**Issue by djeepp5** [serengil/deepface#161]
Hello,

How do I use the enforce_detection option in a script?
if I have to check all the pictures manually I'll be spending a very long amount of time.
I am using the Facial attribute analysis but with multiple images:

from deepface import DeepFace
objs = DeepFace.analyze(["img0.jpg", "img1.jpg"])
#print("emotion: ",obj["dominant_emotion"])
print(obj)
print(objs)

**Comment by serengil** [comment]
objs = DeepFace.analyze(["img0.jpg", "img1.jpg"], enforce_detection=False)

its default value is true. If you don’t set it, then it returns exception if it cannot detect any faces. Setting it to false skips exception when it cannot detect any faces.

**Comment by srijan14** [comment]
@serengil So what exactly does it do? triying to enforce finding any box and considering it to be a face and do the analysis?

**Comment by serengil** [comment]
enforce detection tries to find a face in the image. If it cannot find a face, then function returns exception. In this way, we can verify images with highly resolution. 

In some cases, you need to still apply face recognition without face detection. We set enforce_detection to False in this case. This decreases the accuracy but it won't return exception.

**Comment by srijan14** [comment]
Thanks for your commens @serengil . So is it a right understanding, that if I set the enforce_detection as False, then though MTCNN is not detecting any face in the picture, the library will consider the whole input image as a face and compute its embedding ?

Also you mentioned about verifying images with high resolution, I happen to observe the same behaviour. When i improve my image resolution, the face detection accuracy seems to go down. Though I am Not sure  why this is the case?

**Comment by serengil** [comment]
if I set the enforce_detection as False, then though MTCNN is not detecting any face in the picture, the library will consider the whole input image as a face and compute its embedding -> Yes

verifying images with high resolution, I happen to observe the same behaviour. When i improve my image resolution, the face detection accuracy seems to go down -> that might be appear in your case. The default behaivour is that the higher the resolution the better it is.

**Comment by souravsingh0990** [comment]
@serengil 

below is my code:
######  Decode the base64-encoded binary buffer received as Blob ### 
image_data = image_blob.split(",")[1]
image_data = base64.b64decode(image_data)
######   Convert the binary data to an image array
image_array = np.frombuffer(image_data, dtype=np.uint8)
img = cv2.imdecode(image_array, flags=cv2.IMREAD_UNCHANGED)
faces = face_cascade.detectMultiScale(img, scaleFactor=1.3, minNeighbors=5, flags=cv2.CASCADE_SCALE_IMAGE)
result = DeepFace.analyze(img_path = img , actions = ["emotion"], enforce_detection=False,detector_backend='ssd')

when i use DeepFace.analyze i am fetting error "/AppleInternal/Library/BuildRoots/c2cb9645-dafc-11ed-aa26-6ec1e3b3f7b3/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraph.mm:669: failed assertion `Placeholder shape rank mismatches"

but by commenting that out i don't get any error. 

### Any idea about the error ?
