### ISSUE TITLE
module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by hasretja** [serengil/deepface#165]
Hi Şefik ,

```
from deepface import DeepFace
from tensorflow.keras.layers import Embedding
obj = DeepFace.analyze(img_path = "Fotograf.png", actions = ['age', 'gender', 'race', 'emotion'])
#objs = DeepFace.analyze(["img1.jpg", "img2.jpg", "img3.jpg"]) #analyzing multiple faces same time
print(obj["age"]," years old ",obj["dominant_race"]," ",obj["dominant_emotion"]," ", obj["gender"])
```

I tried to run the code above, but I get the error below. I would be glad if you could help.

AttributeError                            Traceback (most recent call last)
<ipython-input-4-38f3cc07921a> in <module>
      1 from deepface import DeepFace
      2 from tensorflow.keras.layers import Embedding
----> 3 obj = DeepFace.analyze(img_path = "Fotograf.png", actions = ['age', 'gender', 'race', 'emotion'])
      4 #objs = DeepFace.analyze(["img1.jpg", "img2.jpg", "img3.jpg"]) #analyzing multiple faces same time
      5 print(obj["age"]," years old ",obj["dominant_race"]," ",obj["dominant_emotion"]," ", obj["gender"])

E:\Anaconda\lib\site-packages\deepface\DeepFace.py in analyze(img_path, actions, models, enforce_detection, detector_backend)
    307 
    308         img_paths, bulkProcess = functions.initialize_input(img_path)
--> 309         functions.initialize_detector(detector_backend = detector_backend)
    310 
    311         #---------------------------------

E:\Anaconda\lib\site-packages\deepface\commons\functions.py in initialize_detector(detector_backend)
    134 
    135         elif detector_backend == 'mtcnn':
--> 136                 face_detector = MTCNN()
    137 
    138 def initializeFolder():

E:\Anaconda\lib\site-packages\mtcnn\mtcnn.py in __init__(self, weights_file, min_face_size, steps_threshold, scale_factor)
     86         self._scale_factor = scale_factor
     87 
---> 88         self._pnet, self._rnet, self._onet = NetworkFactory().build_P_R_O_nets_from_file(weights_file)
     89 
     90 

E:\Anaconda\lib\site-packages\mtcnn\network\factory.py in build_P_R_O_nets_from_file(self, weights_file)
    121         weights = np.load(weights_file, allow_pickle=True).tolist()
    122 
--> 123         p_net = self.build_pnet()
    124         r_net = self.build_rnet()
    125         o_net = self.build_onet()

E:\Anaconda\lib\site-packages\mtcnn\network\factory.py in build_pnet(self, input_shape)
     36             input_shape = (None, None, 3)
     37 
---> 38         p_inp = Input(input_shape)
     39 
     40         p_layer = Conv2D(10, kernel_size=(3, 3), strides=(1, 1), padding="valid")(p_inp)

E:\Anaconda\lib\site-packages\keras\engine\input_layer.py in Input(shape, batch_shape, name, dtype, sparse, tensor)
    176                              name=name, dtype=dtype,
    177                              sparse=sparse,
--> 178                              input_tensor=tensor)
    179     # Return tensor including _keras_shape and _keras_history.
    180     # Note that in this case train_output and test_output are the same pointer.

E:\Anaconda\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

E:\Anaconda\lib\site-packages\keras\engine\input_layer.py in __init__(self, input_shape, batch_size, batch_input_shape, dtype, input_tensor, sparse, name)
     37         if not name:
     38             prefix = 'input'
---> 39             name = prefix + '_' + str(K.get_uid(prefix))
     40         super(InputLayer, self).__init__(dtype=dtype, name=name)
     41 

E:\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py in get_uid(prefix)
     72         A unique identifier for the graph.
     73     """
---> 74     global _GRAPH_UID_DICTS
     75     graph = tf.get_default_graph()
     76     if graph not in _GRAPH_UID_DICTS:

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

tensorflow version is Version: 2.1.0.

Thanks in advance

**Comment by serengil** [comment]
It seems that you cannot load mtcnn. It requires keras. Did you install it? Please run pip install keras —ignore-installed

You can skip that trouble if you change the detector

obj = DeepFace.analyze(img_path = "Fotograf.png", actions = ['age', 'gender', 'race', 'emotion'], detector_backend=‘opencv’)
