### ISSUE TITLE
pipenv installation error (Python 3.6)

### ISSUE THREAD

**Issue by havardl** [serengil/deepface#166]
Hi, when I try to insall deepface using pipenv I get the following error:

`pipenv install deepface`

```bash
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpk0eop9xpbuild/opencv-python/
```

My pipfile looks like this:
```python
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
deepface = "*"

[requires]
python_version = "3.6"
```

**Comment by serengil** [comment]
I don't know what pipenv actually. It seems that it cannot build opencv in the exception message.

**Comment by serengil** [comment]
you might open this issue in pipenv because deepface does not guarantee that it is compatible with pipenv.

**Comment by havardl** [comment]
I can confirm this is a pipenv issue, as installing it with pip solved the problem.
