### ISSUE TITLE
Poor performance on my dataset

### ISSUE THREAD

**Issue by mathieuUbble** [serengil/deepface#168]
Hi Sefik,
First of all, congratulations for your amazing work ! This is really brilliant, clear and well documented ! Bravo ! 🎉 

However, I do have some issues using your library. I have a data set with 3000 faces, and I am using the `find` method of your `DeepFace` class. I used it with all of the models "VGG-Face", "Facenet", "OpenFace", "DeepFace", but the results I got are very bad: I got a huge number of "False Positive" (faces which are predicted to belong to the same person but in reality do not belong to the same person).

My images resolution is in average 300 * 300 pixels, so this seems to be correct according to your tests.

Do you have any idea of what could be the reason of this poor performance ?
Do you think I should retrain your model on my our own data to get better results ?

Thank you in advance for your answer, and once again, thanks a lot for all this great job !

**Comment by serengil** [comment]
Hello, thank you for your feedback. DeepFace actually wraps some production ready models. I mean that I haven't train them from scratch. For example, FaceNet has 99.63% accuracy on LFW data set.

Could you share the code you are running?

**Comment by mathieuUbble** [comment]
Hi Sefik,
Thank for your quick answer.
I run the following code:

```
from deepface import DeepFace
from deepface.basemodels import Facenet
from glob import glob
import pandas as pd

model = Facenet.loadModel()

# Path to the folder containing all my face images
db_path = "/Users/mathieupichon/PycharmProjects/notebooks/face_repetition/all_faces/"

# A list with all the images path from the previous folder
img_path = glob("/Users/mathieupichon/PycharmProjects/notebooks/face_repetition/all_faces/" + "*.png" )

resp_ob_face_net = DeepFace.find(
    img_path=img_path,
    db_path=db_path,
    model_name="Facenet",
    model=model,
    distance_metric="cosine",
    enforce_detection=False,
)
```

In the folder `db_path`, there are 2982 face crops with an average size of 300 * 300. Among these 2982 faces, there are many pairs of face I would like to find.

Obviously, when I run the `find` method, the algo detects first the same image with a cosine similarity of 0. But then I got very bad result matching wrong faces.

If you have any idea of what could be the reason of this failure, I would be very grateful :)

Thanks again !

**Comment by serengil** [comment]
Setting enforce_detection to False will decrease the model accuracy dramatically. I think that is the problem you have.

**Comment by mathieuUbble** [comment]
That's really great news ! I did not understand that !
Thank you very much for your answer Sefik 🥇

**Comment by serengil** [comment]
Setting enforce detection to True enforce you to detect and align faces. Otherwise, it tries to recognize unclear images. That's why, its default value is True.

**Comment by mathieuUbble** [comment]
Yes, that does make completely sense :)
Thanks for the tip, I'll try it right now !

**Comment by mathieuUbble** [comment]
I rerun the experience wihtout setting enforce_detection to False (I had to remove 80 face crop among the 3000 of my dataset, because MTCNN did not detect a face for them). 
The results are greater but the accuracy is still very low.

Do you think the resolution of my face crop could explain these bad results ?
Do you think transfer learning could work to solve this issue ?

**Comment by serengil** [comment]
yes, resolution plays a key role.
