### ISSUE TITLE
Unable to calculate Confidence between 2 images in elastic search

### ISSUE THREAD

**Issue by rockstarvibu** [serengil/deepface#171]
when input image and database image are same then max score is outputting 1.00 but it should be 0.0 as both the images are same.

I'm using same code as you did in elastic search. using facenet model.

i tried 100 - max_score but still unable to calculate Confidence in (%).

thanks

**Comment by serengil** [comment]
try (1 - max score) * 100

**Comment by rockstarvibu** [comment]
I tried (1 - max score) * 100 but now as i increase size in query i.e size = 50. now the last image has highest confidence... why? but in fact 1st image is more similar so it must have high confidence... something is wrong

**Comment by rockstarvibu** [comment]
I tried to increase query size to 100 as I have 500 images.. now the 1st result has 92.37 % and last image at 100th position has  92.95% why?
