### ISSUE TITLE
Inquiry about performance about the race classifier 

### ISSUE THREAD

**Issue by nmangaokar** [serengil/deepface#172]
I am using this library in my work, and want to understand the performance of the race classifier as provided by the DeepFace.analyze() API. Could you tell me what the per-race performance breakdown of the underlying classifier is? Thanks in advance.

**Comment by serengil** [comment]
Please follow the links in the read me file of the repo. It will redirect you to a tutorial. You can find accuracy, precision and recall metrics of that model.
