### ISSUE TITLE
Get bounding box coordinates for face

### ISSUE THREAD

**Issue by kjfeng** [serengil/deepface#173]
Hello @serengil, it looks like a bounding box for the face is definitely created in the code, but there doesn't seem to be any way of printing out the coordinates. How can I go about doing that? I'm interested in doing this for the analysis function.

**Comment by serengil** [comment]
You cannot do it as is but I can add it in the next release.

**Comment by kjfeng** [comment]
Thanks! When do you estimate the next release to be?

**Comment by serengil** [comment]
I will not be able to do it soon, unfortunately.

**Comment by kjfeng** [comment]
Hmm ok, what do you mean by soon? Would you be able to put out the next release in the next month or so? Thanks for all your work on it already.

**Comment by serengil** [comment]
Sure, it will be done until in a month.

**Comment by vjsyong** [comment]
Hi kjfeng, I also wanted to get the bounding box for my current application. So I've directly modified the source to enable the extraction of bounding box information through the returned dictionary. If you need to use it urgently and don't mind messing around with the code a little, you can check out my pull request or clone my forked repository which has the feature present.

**Comment by serengil** [comment]
@vjsyong thank you for your contribution. I merged your pull request to the master branch. I found a little bug and fixed it.

@kjfeng you can clone the latest version of the code as shown below. I will release it in pypi in the next couples of days.

```
git clone https://github.com/serengil/deepface.git
cd deepface
pip install -e .
```
