### ISSUE TITLE
[Inquiry] Increase the resolution of detected face

### ISSUE THREAD

**Issue by zul96a** [serengil/deepface#174]
Hello sir! Thank you for developing this project. I have learnt a lot in face recognition and currently applying it, all thanks to you.

Currently I'm doing a project of comparing a person selfie photo with his/her ID card photo. In most cases, the face on ID photo
are smaller and less detailed then a person selfie, so I want to inquire if it is possible to increase the size of detected face during face detection stage.

Another thing that I noticed the difference of skin color from selfie and ID photo really affects the accuracy of my prediction.  Do you have suggestion on what I can do? Thanks

**Comment by serengil** [comment]
Hello,

Preprocess function has optional target size argument. You can increase the resolution of detected image by setting it. Its default value is (22, 224). I set it to (1024, 1024) in the following code snippet.

```
from deepface.commons import functions
detectors = ['opencv', 'ssd', 'dlib', 'mtcnn']
img = functions.preprocess_face(img = img_path
   , target_size = (1024, 1024)
   , detector_backend = detectors[0]
)[0] 
```
