### ISSUE TITLE
API error when pass matric=euclidean or euclideanl2

### ISSUE THREAD

**Issue by thisKK** [serengil/deepface#175]
no problem with matric=cosine can get the result without error 

but when i POST to http://127.0.0.1:5000/verify  with matric=euclidean  or  euclideanl2

`{
  "model_name": "ArcFace",
   "distance_metric":"euclidean",
  	"img": [
          { "img1" : "",
             "img2": ""
           }
  	]
 }
`

I got error like this in terminal

`>>> TypeError: Object of type 'float32' is not JSON serializable`

i this case  i fix in DeepFace.py  function verify()  from

```
			
if j == 'cosine':
   distance = dst.findCosineDistance(img1_representation, img2_representation)
elif j == 'euclidean':
   distance = dst.findEuclideanDistance(img1_representation, img2_representation)
elif j == 'euclidean_l2':
   distance = dst.findEuclideanDistance(dst.l2_normalize(img1_representation), dst.l2_normalize(img2_representation))

```

to

```
			
if j == 'cosine':
   distance = dst.findCosineDistance(img1_representation, img2_representation)
elif j == 'euclidean':
   distance = dst.findEuclideanDistance(img1_representation, img2_representation)
   distance = np.float64(distance)
elif j == 'euclidean_l2':
   distance = dst.findEuclideanDistance(dst.l2_normalize(img1_representation), dst.l2_normalize(img2_representation))
   distance = np.float64(distance)

```

that work for me POST to http://127.0.0.1:5000/verify return without error

**Comment by serengil** [comment]
Thank you for your contribution. I updated the source code: https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py

It is going to be published in the next release.

**Comment by thisKK** [comment]
My pleasure. Thank you too.  I learned a lot from this repository
