### ISSUE TITLE
How to use deepface inside tkinter

### ISSUE THREAD

**Issue by pythonhubpy** [serengil/deepface#176]
Hello, @serengil I tried to use the DeepFace.stream() inside Tkinter but it failed is there some way I could embed the box inside the Tkinter window.

And also how to make the stream() function detect the race of the person.

Thanks in advance.

**Comment by serengil** [comment]
I don't know anything about Tkinter unfortunately.

I could add the race prediction in streaming in the next release of course.

**Comment by pythonhubpy** [comment]
Is there any way I could get back values from the stream() function as a dictionary?

```
data  = DeepFace.stream('database')

print(data)
```
Now it returns ```NonetType```

I want something like this.

```
{
age: 20,
gender: male,
neutral: 0.3,
happy: , ....
}
```

**Comment by serengil** [comment]
Stream function runs a while loop. We might add the each frame result to the response but this makes slow your system. That is not logical. We might store the results in a custom file?

**Comment by pythonhubpy** [comment]
Yeah we can store just wanna see the values. Atleast at a certain interval of time about every one minute the value will be save along with the starting value.

**Comment by DakshG07** [comment]
Yes, this would be really useful. I need real-time emotion detection.

**Comment by serengil** [comment]
This is not gonna be handled soon and issue was open for a long time. That's why, I will close it.
