### ISSUE TITLE
How to label "unknown faces" with DeepFace.find(...)

### ISSUE THREAD

**Issue by FedericoLanzani** [serengil/deepface#177]
Hi!
I'm testing this library on face recognition with a database of two people (100 image for each), I used this method:
```
df = DeepFace.find(img_path=target, db_path="database", enforce_detection=False, model_name="VGG-Face",
                       model=model, distance_metric="cosine")
```
and it works well when I use people known to the database as target.

But, if I use a **face of a person that is not in the database**, how can I **label it as "unknown"**? 
I've tried to implement an if condition with a threshold: `if the distance is greater than x mark the face as unknown`. 
There is a better way to do this? 
How can I know that the **target face is not in the database**?

btw awesome library! 👍

**Comment by serengil** [comment]
if the returned data frame has size of 0, then no matches

```
if df.shape[0] > 0:
   print("matched found: ", df.head())
else:
   print("no matches")
```

**Comment by FedericoLanzani** [comment]
> if the returned data frame has size of 0, then no matches
> 
> ```
> if df.shape[0] > 0:
>    print("matched found: ", df.head())
> else:
>    print("no matches")
> ```

Yes.., I've figured that out later... thank you for your reply! 💯
