### ISSUE TITLE
Way to train new face detector?

### ISSUE THREAD

**Issue by ICanNomNoms** [serengil/deepface#178]
Hello @serengil I am trying to run this on an image set consisting of thermal images. In doing so the face detector can only detect a face 40% of the time. I was wondering if you could tell me how to retrain the facial detector using my dataset so I can increase the accuracy.

I know you have a tutorial for the face recognition model retraining, I am just wondering if you have one for the face_detector backend.

**Comment by serengil** [comment]
I have used out-of-the-box face detectors before.

You might read the SSD or MTCNN papers to find out how. Unfortunately, I don't have an experience on this subject.
