### ISSUE TITLE
Hardware resources for large scale 

### ISSUE THREAD

**Issue by TriptonPt** [serengil/deepface#187]
Hello!

Sorry this is not really an issue but would be interested in knowing if this would work on a large scale and what kind of hardware we would be looking at in order to make it feasible .

Let's assume a rate of 500 images every 3 seconds or so, can it be done and with what kind of server specs if this is the case ?

Thanks in advance, great project !

**Comment by serengil** [comment]
Please read the large scale face recognition section in the read me. It might satisfy your requirements.

**Comment by TriptonPt** [comment]
Hello !

Thanks for the fast reply :) 

I did read that section and watched the video about elasticsearch but couldn't find anything that mentioned the benchmarks / server requirements , which is why I posted this question . From what I understand it's definitely possible but was hoping you could give me an idea of what kind of hardware would be needed to support 500 images every 2 or 3 seconds, or lets say 10000 images per minute .

**Comment by serengil** [comment]
elasticsearch can handle it with a limited hardware. do not think the hardware limit.

**Comment by TriptonPt** [comment]
> elasticsearch can handle it with a limited hardware. do not think the hardware limit.

Thanks for clarifying that ! Does this also apply for gender, age and race estimation calculations? 

I do not plan to run face recognition but I am interesting in determining gender and age .

**Comment by TriptonPt** [comment]
Also I should have mentioned that I was planning to run this on a headless server without GPU , would it be feasible to process this many images with analyze ?

**Comment by serengil** [comment]
running on gpu is totally fine. It will speed you up.

Age and gender are easier tasks.

**Comment by TriptonPt** [comment]
> running on gpu is totally fine. It will speed you up.
> 
> Age and gender are easier tasks.

"Also I should have mentioned that I was planning to run this on a headless server without GPU" 

Without Gpu in this case , therefore my concern :) 

I am deciding whether to base a project on this repo so evaluating the feasability of working with certain resources is really important for me before deciding to proceed with testings, which always takes a lot of time on its own . 

I appreciate your patiente , I will try to be more specific to avoid losing your time . If I ran this on a dedicated server WITHOUT gpu , let's say an E3-1245 with 32gb RAM and I deployed elasticsearch would that be able to handle verification (age and gender) of about 10000 images per minute ?

Thanks again!

**Comment by serengil** [comment]
Elasticsearch can definetely handle it without GPU. If you watched the elasticsearch video, that would help you understand how it works.

**Comment by TriptonPt** [comment]
> Elasticsearch can definetely handle it without GPU. If you watched the elasticsearch video, that would help you understand how it works.

I did, I just wasn't aware if the verify age and gender functions also worked the same way face verification does 

Great , tyvm and keep up the great work :) 👍

**Comment by serengil** [comment]
thank you for your adoption. please do not forget to star the repo.
