### ISSUE TITLE
Avoiding startup / import times by listening a socket in a contiunous loop ?

### ISSUE THREAD

**Issue by TriptonPt** [serengil/deepface#189]
Hello !

I installed the project on a vps without cpu and realized that the startup time (import stage etc) takes a lot longer than the query itself , since I am getting around 20sec startup time and only 0.005sec  for the calculations in your elasticsearch tutorial, which was surprisingly good without a GPU .

Anyway, I was wondering if it would be possible to run a socket listener where I would send the images to analyze 1by1 or in batches and avoid this way to going through the startup stage everytime ? I plan to use the socket listener to continuously analyze new images that are sent upon request, like an API I suppose . 

Thanks

**Comment by serengil** [comment]
I am not an Elasticsearch expert. You should ask this question in elasticsearch repo.

**Comment by TriptonPt** [comment]
> I am not an Elasticsearch expert. You should ask this question in elasticsearch repo.

Well, the question isn't really about elasticsearch , more about tensorflow as this is what causes the delays when the script starts . 

Anyway I just wanted to know if it's possible to run the initial import only once and then send the images we want to get data for as a stream instead of an array ... 

Currently as far as I understand , if you use an array of targets it only does the import stage in the beginning right ? I read this was previously an issue that got corrected .
