### ISSUE TITLE
Slow performance on face analysis vs face comparison

### ISSUE THREAD

**Issue by TriptonPt** [serengil/deepface#190]
I was under the impression that face analysis model should take less time than face comparison, according to the benchmarks for each model .

My server specs are 4 CPU Cores and 8Gb RAM without GPU . 

However my tests show me that the model analysis for age / gender etc is quite slower when benchmarking against face comparison . 

Case 1 :

Ran a single image comparison against 5 results from database using elasticsearch and following the elasticsearch tutorial you provided . Total object analysis time was around  1.5seconds from elasticsearch query to end of analysis . 

Case 2 :

Used the provided example for face analysis based on gender / age / race for a single image . Elasticsearch is not needed here since we are not comparing against a database . 

Total time since object analysis start after model import is over 12 seconds , almost 10x more than face comparison .

Is this normal ?

**Comment by serengil** [comment]
it is totally normal. age and gender prediction models build vgg-face model first, then add age and gender layers.

**Comment by TriptonPt** [comment]
Can we pre built all models and load them into memory for subsequent object analysis ? I was just reading that the analyze function is importing models everytime we call it

**Comment by serengil** [comment]
Yes you can do it. Please follow the "Passing pre-built face recognition models" section in the read me file of the repo. That will speed you up dramatically.

**Comment by TriptonPt** [comment]
Tyvm !
