### ISSUE TITLE
'Illegal instruction' is the only output

### ISSUE THREAD

**Issue by plauthor** [serengil/deepface#191]
I have been trying to run the following code:

=========================

#!/usr/bin/python3
# -*- coding: utf-8 -*-

from deepface import DeepFace

DeepFace.stream("database")

result  = DeepFace.verify("mental.jpg", "voloda.jpg")
#results = DeepFace.verify([['img1.jpg', 'img2.jpg'], ['img1.jpg', 'img3.jpg']])
print("Is verified: ", result["verified"])

obj = DeepFace.analyze(img_path = "mental.jpg", actions = ['age', 'gender', 'race', 'emotion'])
#objs = DeepFace.analyze(["img1.jpg", "img2.jpg", "img3.jpg"]) #analyzing multiple faces same time

print(obj["age"]," years old ",obj["dominant_race"]," ",obj["dominant_emotion"]," ", obj["gender"])

==============================

However, the only output I ever get is 'Illegal instruction'.

The installation output was as follows. I upgraded numpy now so the current version is actually 1.20.1 not 1.16.2:

pandas 1.2.2 has requirement numpy>=1.16.5, but you'll have numpy 1.16.2 which is incompatible.
Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, filelock, gdown, absl-py, tensorflow-estimator, protobuf, grpcio, termcolor, google-pasta, gast, keras-preprocessing, cached-property, h5py, keras-applications, astor, wrapt, zipp, importlib-metadata, markdown, tensorboard, tensorflow, keras, mtcnn, pandas, deepface, PySocks
Successfully installed Flask-1.1.2 Jinja2-2.11.3 MarkupSafe-1.1.1 PySocks-1.7.1 Werkzeug-1.0.1 absl-py-0.11.0 astor-0.8.1 cached-property-1.5.2 deepface-0.0.49 filelock-3.0.12 gast-0.4.0 gdown-3.12.2 google-pasta-0.2.0 grpcio-1.35.0 h5py-3.1.0 importlib-metadata-3.5.0 itsdangerous-1.1.0 keras-2.4.3 keras-applications-1.0.8 keras-preprocessing-1.1.2 markdown-3.3.3 mtcnn-0.1.0 pandas-1.2.2 protobuf-3.15.1 tensorboard-1.14.0 tensorflow-1.14.0 tensorflow-estimator-1.14.0 termcolor-1.1.0 wrapt-1.12.1 zipp-3.4.0

Any idea what may be wrong? Thank you.

**Comment by plauthor** [comment]
I might add that this is what I get from the Python prompt:

Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepface import DeepFace
Illegal instruction


Thank you.

**Comment by serengil** [comment]
No idea. I can run it as is.

Could you import tensorflow directly? Please try to run the following code block.

```
import tensorflow
import keras
```

**Comment by KiLJ4EdeN** [comment]
> I have been trying to run the following code:
> 
> =========================
> 
> #!/usr/bin/python3
> # -_- coding: utf-8 -_-
> 
> from deepface import DeepFace
> 
> DeepFace.stream("database")
> 
> result = DeepFace.verify("mental.jpg", "voloda.jpg")
> #results = DeepFace.verify([['img1.jpg', 'img2.jpg'], ['img1.jpg', 'img3.jpg']])
> print("Is verified: ", result["verified"])
> 
> obj = DeepFace.analyze(img_path = "mental.jpg", actions = ['age', 'gender', 'race', 'emotion'])
> #objs = DeepFace.analyze(["img1.jpg", "img2.jpg", "img3.jpg"]) #analyzing multiple faces same time
> 
> print(obj["age"]," years old ",obj["dominant_race"]," ",obj["dominant_emotion"]," ", obj["gender"])
> 
> ==============================
> 
> However, the only output I ever get is 'Illegal instruction'.
> 
> The installation output was as follows. I upgraded numpy now so the current version is actually 1.20.1 not 1.16.2:
> 
> pandas 1.2.2 has requirement numpy>=1.16.5, but you'll have numpy 1.16.2 which is incompatible.
> Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, filelock, gdown, absl-py, tensorflow-estimator, protobuf, grpcio, termcolor, google-pasta, gast, keras-preprocessing, cached-property, h5py, keras-applications, astor, wrapt, zipp, importlib-metadata, markdown, tensorboard, tensorflow, keras, mtcnn, pandas, deepface, PySocks
> Successfully installed Flask-1.1.2 Jinja2-2.11.3 MarkupSafe-1.1.1 PySocks-1.7.1 Werkzeug-1.0.1 absl-py-0.11.0 astor-0.8.1 cached-property-1.5.2 deepface-0.0.49 filelock-3.0.12 gast-0.4.0 gdown-3.12.2 google-pasta-0.2.0 grpcio-1.35.0 h5py-3.1.0 importlib-metadata-3.5.0 itsdangerous-1.1.0 keras-2.4.3 keras-applications-1.0.8 keras-preprocessing-1.1.2 markdown-3.3.3 mtcnn-0.1.0 pandas-1.2.2 protobuf-3.15.1 tensorboard-1.14.0 tensorflow-1.14.0 tensorflow-estimator-1.14.0 termcolor-1.1.0 wrapt-1.12.1 zipp-3.4.0
> 
> Any idea what may be wrong? Thank you.

Hello, `illegal instruction (core dumped)` happens when you installed an incompatible whl. This means that the precompiled version of tensorflow that you use requires instructions that the CPU does not support (Happens with older CPU and Servers where VMWARE or KVM limit the usage of the CPU). Here for instance this can be AVX and AVX2 instructions, which you can find more on online.

My suggestion here is that you build tensorflow from source on your machine which will most likely fix this problem.
Or you can look for the keyword "non-avx tensorflow" wheels to download precompiled tensorflow versions that are compatible with older CPUs.

**Comment by serengil** [comment]
yesi it seems tensorflow installation related problem.

**Comment by plauthor** [comment]
Hi, thank you all for your comments. Attempts at importing both/either keras and/or tensorflow end up with 'Illegal instruction'. No precompiled version of tensorflow available on Pypi work on my Lenovo G 50-30. I will try and build it from source then. Thank you for your tips.
