### ISSUE TITLE
DeepFace.analyze 

### ISSUE THREAD

**Issue by askinucuncu** [serengil/deepface#192]
Merhaba, DeepFace.analyze fonksiyonu kapalı kadınlarda genel olarak erkek sonucu döndürüyor. Modeli bu yönde eğitmem mümkün müdür? Yardımcı olabilir misiniz?

**Comment by serengil** [comment]
Eğitim dökümanına buradan erişebilirsiniz: https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/

Buradaki adımları uygulayarak baştan yeni bir veri setiyle eğitebilirsiniz.

Ancak yüzü tespit ettikten sonra yaş ve cinsiyet modelleri çalıştırılıyor. Yani yüz dışında kalan bölge zaten tahmin başarısına etkide bulunmuyor.

**Comment by askinucuncu** [comment]
Teşekkür ederim
