### ISSUE TITLE
Small typo in a test script

### ISSUE THREAD

**Issue by JavierTG97** [serengil/deepface#195]
Hi @serengil, first of all thanks for this open-source repo, <br/>
I believe that the [face-recognition-how.py](https://github.com/serengil/deepface/blob/master/tests/face-recognition-how.py) file of the test examples contains a typo at [line 16](https://github.com/serengil/deepface/blob/master/tests/face-recognition-how.py#L16):

`input_shape = model.layers[0].input_shape[1:3]`

should be changed to:

`input_shape = model.layers[0].input_shape[0][1:3]`

Otherwise it gives an empty list instead of a tuple with the gray image size.

**Comment by glee92** [comment]
Can confirm the same issue from above:

Environment:
macos Catalina
Python 3.7.4

Libraries Versions:
deepface==0.0.49
dlib==19.21.1
grpcio==1.32.0
h5py==2.10.0
Keras==2.4.3
Keras-Preprocessing==1.1.2
matplotlib==3.3.4
mtcnn==0.1.0
numpy==1.20.1
opencv-contrib-python==4.5.1.48
opencv-python==4.5.1.48
pandas==1.2.3
protobuf==3.15.5
rsa==4.7.2
scikit-learn==0.24.1
scipy==1.6.1
six==1.15.0
tensorflow==2.4.1

**Comment by serengil** [comment]
It seems that is caused by your tf / keras environment. However, that file is not a part of the pipeline. If that change solved your issue, then nothing to do.
