### ISSUE TITLE
find_input_shape in functions.py - incorrect shape

### ISSUE THREAD

**Issue by glee92** [serengil/deepface#197]
Hi @serengil, thanks for this open-source repo.

I ran into an issue when running unit_tests.py for dlib.

The function find_input_shape returns a list for dlib model when it needs to be a tuple.

Error:
File "/Users/g/deepface/venv/lib/python3.7/site-packages/deepface/commons/functions.py", line 466, in preprocess_face
    img = cv2.resize(img, target_size)
SystemError: new style getargs format but argument is not a tuple

I traced it back to find_input_shape in functions.py
	
	input_shape = model.layers[0].input_shape
	print(input_shape)
	if type(input_shape) == list:
		input_shape = input_shape[0][1:3]
	else:
		input_shape = input_shape[1:3]
	
	# if type(input_shape) != tuple:
	# 	input_shape = tuple(input_shape)
	return input_shape`

input_shape = model.layers[0].input_shape = [[1, 150, 150, 3]]
input_shape = input_shape[0][1:3] = [150, 150] (This is still a list, needs to be (150,150))

It returns a list, when target_size has to be tuple.

**Comment by serengil** [comment]
I updated the [functions.py](https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py)  490th line. If it is list, then it is going to be converted to tuple. 

However, it seems that is because of your environment. When I test find_input_shape function it returns a tuple.
