### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by pasa13142** [serengil/deepface#2]
Hello again,

While applying DeepFace.analyze I got this error, I think something wrong with padding calculation

ValueError: Error when checking input: expected zero_padding2d_118_input to have shape (224, 224, 3) but got array with shape (48, 48, 1)

**Comment by serengil** [comment]
Do you pass actions in the analyze function? Please share it.

**Comment by serengil** [comment]
DeepFace.py and functions.py were updated in v0.0.2. It seems that you've run the legacy code. Could run "pip uninstall depface" and then "pip install deepface" commands respecrtively.

DeepFace.py
```
if action == 'emotion':
   img = functions.detectFace(img_path, (48, 48), True)
```

commons/functions.py
`def detectFace(image_path, target_size=(224, 224), grayscale = False):`

**Comment by serengil** [comment]
@pasa13142 I understand that problem and fix in v0.0.3. Please try and inform me again.

**Comment by pasa13142** [comment]
~/Desktop/deepface/deepface/basemodels/Race.py in loadModel()
     41 
     42                 #unzip race_model_single_batch.zip
---> 43                 with zipfile.ZipFile(output, 'r') as zip_ref:
     44                         zip_ref.extractall(home+'/.deepface/weights/')
     45 

~/anaconda3/lib/python3.7/zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel)
   1223         try:
   1224             if mode == 'r':
-> 1225                 self._RealGetContents()
   1226             elif mode in ('w', 'x'):
   1227                 # set the modified flag so central directory gets written

~/anaconda3/lib/python3.7/zipfile.py in _RealGetContents(self)
   1290             raise BadZipFile("File is not a zip file")
   1291         if not endrec:
-> 1292             raise BadZipFile("File is not a zip file")
   1293         if self.debug > 1:
   1294             print(endrec)

BadZipFile: File is not a zip file



It is a basic issue and handle easily by user but you would like to solve anyway

**Comment by serengil** [comment]
Oke, url variable in Race.py should be 

https://drive.google.com/uc?id=1nz-WDhghGQBC4biwShQ9kYjvQMpO6smj

I'll fix this immediately.

**Comment by serengil** [comment]
@pasa13142 It is fixed. Thank you so much for your feedback. I really appreciate.

**Comment by pasa13142** [comment]
I thank you so much for this amazing project, you are great

Have a nice day :)
