### ISSUE TITLE
Any thoughts as to make the models available for Google Coral USB accelerator?

### ISSUE THREAD

**Issue by Moehrenbaum** [serengil/deepface#203]
First off, you've done an amazing job! Thanks for sharing.

I own a Google Coral USB accelerator (TPU device) and would like to use this in combination with your models. I do know  those have to be quantized to fit for the device.

Have you considered doing this or would you be able to help if I try. I'm still a bit new to the topic. Thx

https://coral.ai/docs/edgetpu/models-intro/

TensorFlow Light Converter here
https://www.tensorflow.org/lite/convert/

**Comment by serengil** [comment]
I would like to help but I don't have a google coral usb accelerator unfortunately.
