### ISSUE TITLE
Access denied when downloading facenet_weights.h5 (in docker container)

### ISSUE THREAD

**Issue by aaramg** [serengil/deepface#204]
Hi.
I am trying to run a manually created docker image with the usage of deepface. 
I get:
```
facenet_weights.h5 will be downloaded...
Access denied with the following error:
        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator.
------------
filename = '/root/.deepface/weights/facenet_weights.h5', file descriptor = 4, errno = 21, error message = 'Is a directory', buf = 0x7fffa32849b0, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)
```
I have tried to do a manual download of the model with wget and put it in mentioned above directory.
`wget -P ~/.deepface/weights https://drive.google.com/uc?id=1971Xk5RwedbudGgTIrGAL4F7Aifu7id1`
```
root@8cdc694b4f5c:/app# ls -la /root/.deepface/weights/
total 12
drwxr-xr-x 3 root root 4096 Mar 20 08:20 .
drwxr-xr-x 3 root root 4096 Mar 20 08:20 ..
drwxr-xr-x 2 root root 4096 Mar 20 08:20 facenet_weights.h5
```
So it exists in the specified directory.
But the app throws the exception again.
I have found this link which maybe can useful:
https://stackoverflow.com/questions/60739653/gdown-is-giving-permission-error-for-particular-file-although-it-is-opening-up-f

Please help me to figure out if it is not an issue from your side and I am doing smth wrong.
Thanks in advance

**Comment by serengil** [comment]
This error throws because google drive daily limit reached. That's why, stackoverflow link will not help.

if weight exists in HOME/.deepface/weights then it will not try to download it. /root might not be your home folder? E.g. my home folder is /Users/sefik in my mac. So, weights are stored in here: /Users/sefik/.deepface/weights

**Comment by aaramg** [comment]
Here is the test of your mentioned "maybe root is not your home path"
```
root@8cdc694b4f5c:/app# ls -la ~/.deepface/weights/
total 12
drwxr-xr-x 3 root root 4096 Mar 20 08:20 .
drwxr-xr-x 3 root root 4096 Mar 20 08:20 ..
drwxr-xr-x 2 root root 4096 Mar 20 08:20 facenet_weights.h5
root@8cdc694b4f5c:/app# cd ~
root@8cdc694b4f5c:~# pwd
/root
root@8cdc694b4f5c:~# ls -la ./.deepface/weights/
total 12
drwxr-xr-x 3 root root 4096 Mar 20 08:20 .
drwxr-xr-x 3 root root 4096 Mar 20 08:20 ..
drwxr-xr-x 2 root root 4096 Mar 20 08:20 facenet_weights.h5
```

**Comment by aaramg** [comment]
Here is the Dockerfile:
```
FROM python:3.8-slim-buster
RUN mkdir /app
WORKDIR /app
COPY requirements.txt requirements.txt
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y
RUN apt-get install -y wget
RUN apt install libgl1-mesa-glx -y
RUN apt-get install 'ffmpeg'\
    'libsm6'\
    'libxext6'  -y
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
COPY . .
RUN wget -P ~/.deepface/weights/facenet_weights.h5 https://drive.google.com/uc?id=1971Xk5RwedbudGgTIrGAL4F7Aifu7id1
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
```

**Comment by serengil** [comment]
Could you run python and executes following lines?

from pathlib import Path
home = str(Path.home())
print(home)
if os.path.isfile(home+'/.deepface/weights/facenet_weights.h5') != True:
	print("facenet_weights.h5 will be downloaded...")
else:
	print("weight exists")

**Comment by serengil** [comment]
It seems that weight file does not exist obviously. You might copy the weights out of the docker?

**Comment by aaramg** [comment]
I will try to figure it out myself and reach you back. Also could you please tell me why I can download it with a browser manually but cannot download it from the app (via gdown)??

**Comment by aaramg** [comment]
@serengil I transferred locally already existing facenet_weights.h5 to docker container and it worked.
But before closing this ticket, could you please tell me if that file is updated from time to time in Google Drive or not. I mean once downloaded and it should be used forever or sometimes I should update it??
P.S: Thanks for your quick responses.

**Comment by serengil** [comment]
Google Drive has a daily limit and if it exceeded then it is not allowed to download it with out of browsers. That's why, you cannot download it with gdown but it is still reachable on browsers.

This file always exists in google drive with same link. You can use it forever.

Could you explain how to transfer locally existing files into the docker? This might help some people.

**Comment by aaramg** [comment]
Of course. Here is the docker file. Maybe some tuning/optimization can be done here. But this works:
```
FROM python:3.8-slim-buster
RUN mkdir /app
WORKDIR /app
COPY requirements.txt requirements.txt
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y
RUN apt install libgl1-mesa-glx -y
RUN apt-get install 'ffmpeg'\
    'libsm6'\
    'libxext6'  -y
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN mkdir -p /root/.deepface/weights
COPY facenet_weights.h5 /root/.deepface/weights/facenet_weights.h5
COPY . .
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
```
Before building the docker image "facenet_weights.h5" file should be downloaded for example with the browser and put in the project directory to let docker copy it during the building process.
P.S.>>"root" is the home path.
