### ISSUE TITLE
deepFace analyze on video

### ISSUE THREAD

**Issue by Nandu-Louro** [serengil/deepface#207]
Hi, great job with deepFace!

Is it possible to run analyze on a video and get as output the dominant emotion found in each frame?

**Comment by serengil** [comment]
you can run stream function. It will analyze facial attributes. But it won't store the dominant emotion anywhere. You should customize it based on your requirements.

**Comment by Nandu-Louro** [comment]
The emotion model for the analyze is based on a paper? I can't find a mention of this in your paper.
and which dataset was used to train?

**Comment by serengil** [comment]
read me of the repo will redirect you to the tutorial: https://sefiks.com/2018/01/01/facial-expression-recognition-with-keras/
