### ISSUE TITLE
detectFace() returns a blank image

### ISSUE THREAD

**Issue by JOST777** [serengil/deepface#210]
Hi, I am hoping you can help me with a problem I am having. When I run DeepFace.detectFace(), it returns a <class 'numpy.ndarray'>, shape: (224, 224, 3), where all the cells are set to 0. If I save the data to file, I get a 224x224 black image. I have tried all 4 detector backends: ['opencv', 'ssd', 'dlib', 'mtcnn']. 'dlib' causes an error ('#this is not a must library within deepface... 19.20.0'), but the other 3 run and all return the black square. I have the required model files in the weights folder. 

I have verified that my image loads with cv2, and I tried inputting the image both as a path and as an np.array, both with the same result. I have tried a few different images that I have successfully extracted faces from before using other libraries. I also tried inputting an image that does not contain any face, and I get the error: 'ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.' So it seems that the face detection is working, at least part of the way, but for some reason it just returns a blank array. Also, in case it is my libraries, I made a new virtualenv and the only library I installed was: `pip install deepface.`

Here is my code:

```
import cv2
from deepface import DeepFace

detected_face = DeepFace.detectFace( "in_img.jpg", detector_backend = 'opencv')
print( type(detected_face))
print( detected_face.shape)
print( detected_face)
    
cv2.imwrite( "test_out.jpg", detected_face)
```

**Comment by serengil** [comment]
Could you share your input photo?

**Comment by JOST777** [comment]
Here is one. Actually, I just noticed that for this image it returns some non-zero cells for 'ssd' and 'mtcnn' (but not 'opencv'). The output images are all still completely black though (at least to my naked eye). Here is a sample from the np.array returned from detectFace for this image and 'ssd':

```
[[[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  ...
  [0.30588236 0.30980393 0.32156864]
  [0.2627451  0.26666668 0.2784314 ]
  [0.30980393 0.3137255  0.3254902 ]]

 [[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  ...
  [0.3137255  0.31764707 0.33333334]
  [0.41960785 0.42352942 0.4392157 ]
  [0.35686275 0.35686275 0.36862746]]

 ...
```



![in_img](https://user-images.githubusercontent.com/74123028/112801397-b3395200-9025-11eb-9b18-66aee114cf95.jpg)

**Comment by serengil** [comment]
Alignment causes some black pixels in the detected face. You can see it below. 

```
from deepface import DeepFace
import matplotlib.pyplot as plt
import cv2

detected_face = DeepFace.detectFace( "in.jpg", detector_backend = 'opencv')

plt.imshow(detected_face)
plt.show()

detected_face = detected_face * 255
cv2.imwrite("out.jpg", detected_face) #opencv reads images as bgr instead of rgb. that's why, this will be blue oriented image.
cv2.imwrite("out2.jpg", detected_face[:, :, ::-1])
```

The problem here is detectFace function returns pixels in [0, 1]. Matplotlib expects inputs like that. However, if you are going to use opencv imwrite, then pixels should be in [0, 255]. You should denormalize it before calling imwrite.

![detected-face](https://user-images.githubusercontent.com/18491038/112802485-e954f100-907a-11eb-9c40-c9a429473e63.png)

**Comment by JOST777** [comment]
Thanks for your help Serengil. It works great.
