### ISSUE TITLE
Implementing Deepface in FastAPI

### ISSUE THREAD

**Issue by zul96a** [serengil/deepface#212]
Hello again!
I'm trying to integrate deepface into my FastAPI. Basically based on the docs in FastAPI 
[link](https://fastapi.tiangolo.com/tutorial/request-files/) , I have uploaded two images for face verification process.
I'm using PIL to read the image to read the uploaded images.

The uploaded file has the attribute of " SpooledTemporaryFile" which I try to pass to PIL and turn it into Jpeg.

Below are the snapshot of the codes and API UI.
![image](https://user-images.githubusercontent.com/77947380/113685398-ca003880-96f8-11eb-8ee2-3895b3cd3f8e.png)

And here is the preview of the API UI
![image](https://user-images.githubusercontent.com/77947380/113685499-e7cd9d80-96f8-11eb-8e96-0a2805101362.png)

Apparently, when i try to pass "image_name" to Deepface.verify function, I will get an error. Is there any way that I can convert the PIL.jpeg image to be readable by the verify function? Thanks

**Comment by serengil** [comment]
Hello, 

I do not have an experience on FastAPI firstly. Could you send image_name instead of numpy array or base64 encoded? Because verify function supports those inputs as well.

**Comment by serengil** [comment]
Here, I found a similar case: https://github.com/serengil/deepface/issues/65

To sum up, you should convert pil to numpy first.

```
open_cv_image = np.array(image) #image is pil here
open_cv_image = open_cv_image[:, :, ::-1].copy() # Convert RGB to BGR

open_cv_image2 = np.array(image2) #image is pil here
open_cv_image2 = open_cv_image2[:, :, ::-1].copy() # Convert RGB to BGR

DeepFace.verify(open_cv_image, open_cv_image2 )
```

**Comment by zul96a** [comment]
Thanks! My API works fine now! You have been very helpful sir

**Comment by okoliechykwuka** [comment]
@zul96a Please how were you able to solve the above issue, I am trying to replicate the same using fastapi.

I still get an `500 Internal Server Error
ERROR`

**Comment by zul96a** [comment]
@okoliechykwuka I have instead replaced PIL library and code just use opencv to read the spoof file.  If you see in my screenshot above at line 17, I modified it a little so it can compatible with opencv. First , I have to convert the buffer into nparray and then decoded it using cv2.imdecode fuction. Here is the sample of the code:

```
def read_imagefile(file):
    nparr = np.frombuffer(file, np.uint8)
    image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    return image
```
Then, you can pass the image to DeepFace.verify() function. Good luck!
