### ISSUE TITLE
Tensorboard-data-server version problem

### ISSUE THREAD

**Issue by ailkerarslan** [serengil/deepface#215]
Hello sir, 

Thank you for your excellent job. I had a problem while cloning your repo. It's about tensorboard-data-server version 0.6.0. I tried to install it via pip but the error below raised.

Collecting tensorboard-data-server<0.7.0,>=0.6.0 (from tensorboard<3,>=2.3.0->tensorflow>=1.9.0->deepface==0.0.51)
  Could not find a version that satisfies the requirement tensorboard-data-server<0.7.0,>=0.6.0 (from tensorboard<3,>=2.3.0->tensorflow>=1.9.0->deepface==0.0.51) (from versions: )
No matching distribution found for tensorboard-data-server<0.7.0,>=0.6.0 (from tensorboard<3,>=2.3.0->tensorflow>=1.9.0->deepface==0.0.51)

**Comment by serengil** [comment]
what was your python version? it seems a python version related issue. You might make your environment as same as mine.

```
(deepface) C:\Users\Sefik>python --version
Python 3.8.5
```

**Comment by ailkerarslan** [comment]
it was 3.5.5, now It's done, thank you sir
