### ISSUE TITLE
Alternative for Elasticsearch

### ISSUE THREAD

**Issue by filip-halt** [serengil/deepface#216]

**Comment by filip-halt** [comment]
A good alternative to wrapping an ANN library with Elasticsearch might be [Milvus](https://github.com/milvus-io/milvus). Milvus supports all the main ANN libraries like HNSW, Annoy, and Faiss while also being an easy to use database. 

Sorry about the close and reopen, computer spazzed out a bit.

**Comment by serengil** [comment]
You can use deepface with milvus. Why think this is an issue?
