### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike' 

### ISSUE THREAD

**Issue by ColinConwell** [serengil/deepface#217]
Thank you for the excellent package.

When initializing install deepface and then attempting to run the following:

```
from deepface import DeepFace
DeepFace.detectFace('some_photo.jpg')
```

I receive the following tensorflow error:

AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike' 

Downgrading tensorflow to 2.2.0, I am able to resolve this, but it seems then there might be an issue with requirements.txt.

Edit: (the original error seems to occur with tensorflow 2.4.1.)

**Comment by serengil** [comment]
Hi Colin,

My tests were run on tf 1.9 and 2.2. It seems that tensorflow based problem. I'm going to study on this. Thank you.
