### ISSUE TITLE
load parameters take too much time

### ISSUE THREAD

**Issue by sunshineinwater** [serengil/deepface#222]
It takes a large time when verifying an image on such step below:
` Loading DeepFace: 100%|██████████| 4/4 [00:16<00:00,  4.02s/it]`                  

Is there any way to preload these training parameters ?

**Comment by serengil** [comment]
Yes, you can build the model once and pass it to the verify function. This is mentioned in the "FAQ and Troubleshooting" section of the repo read-me.

```
model_name = "Facenet"
model = DeepFace.build_model(model_name)
DeepFace.verify("img1.jpg", "img2.jpg", model_name = model_name, model = model)
```

**Comment by sunshineinwater** [comment]
This is the fastest reply I've met. Thx a lot.
New issue:
How to deal with "Ensemble" method ?
`ValueError: Invalid model_name passed - Ensemble`

**Comment by serengil** [comment]
It can be done as shown below:

```python
#building ensemble method once
from deepface.basemodels import Boosting
model = Boosting.loadModel()

#pass pre-built one
DeepFace.verify("img1.jpg", "img2.jpg", model_name = "Ensemble", model = model)
```
