### ISSUE TITLE
For the stream function, are there any plans to add a real-time text output function?

### ISSUE THREAD

**Issue by sunshineinwater** [serengil/deepface#223]

**Comment by serengil** [comment]
Stream function exists in the interface already

**Comment by sunshineinwater** [comment]
too quick to typing the whole title....

**Comment by serengil** [comment]
what do you need exactly? I do not understand.

**Comment by sunshineinwater** [comment]
The code can obtain the recognition result of the video in real time, instead of displaying it on the video

**Comment by serengil** [comment]
no, it is out of scope.
