### ISSUE TITLE
Bug: cv2.imread(img) return None in Windows System 

### ISSUE THREAD

**Issue by sunshineinwater** [serengil/deepface#224]
**Environment:**
System:windows 10
Python:3.7.0
opencv-python:4.5.1.48

**Bug:** 
can't get JPG image array by method `img = cv2.imread(img)`

**Fix Method:**
replace the code in line 189 of file "deepface/common/functions.py" .

_**origin code**_
`img = cv2.imread(img)`
_**fixed code**_
`img = cv2.imread(np.fromfile(img,dtype=uint8),-1)`

**Comment by serengil** [comment]
Interesting because I can run that command in windows. Could you share your input image?

**Comment by sunshineinwater** [comment]
> Interesting because I can run that command in windows. Could you share your input image?

[https://www.google.com.hk/url?sa=i&url=https%3A%2F%2Fj.17qq.com%2Farticle%2Fghnnsmsky.html&psig=AOvVaw05qK0aE_HAKG1dhTlwSUr9&ust=1619944422182000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPjAkLGJqPACFQAAAAAdAAAAABAD](url)

**Comment by sunshineinwater** [comment]
actually, all images cannot read correctly in Windows environment , whereas it performs normally in my Mac

**Comment by ahmetdadak** [comment]
I also encountered the same issue. I am trying to pass the PIL.Image object to the DeepFace.analyze() and it says the object has no length.

**Comment by serengil** [comment]
@ahmetdadak you cannot pass pil image as input. You should convert it to numpy first.

`open_cv_image = np.array(image) #image is pil here`

**Comment by serengil** [comment]
@sunshineinwater , your approach is not working

>>> img = cv2.imread(np.fromfile("img1.jpg", dtype=np.uint8), -1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't convert object of type 'numpy.ndarray' to 'str' for 'filename'

**Comment by serengil** [comment]
As I mentioned, I've run all my unit tests on windows 10. The root cause must be different.

**Comment by sunshineinwater** [comment]
> @sunshineinwater , your approach is not working
> 
> > > > img = cv2.imread(np.fromfile("img1.jpg", dtype=np.uint8), -1)
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > TypeError: Can't convert object of type 'numpy.ndarray' to 'str' for 'filename'

Sorry for tying wrong code...
Here is the correct code:
`img = cv2.imdecode( np.fromfile(img, dtype=np.uint8), -1)`

**Comment by sunshineinwater** [comment]
**Here is my python environment:**
absl-py==0.12.0
astunparse==1.6.3
cachetools==4.2.2
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
deepface==0.0.51
filelock==3.0.12
Flask==1.1.2
flatbuffers==1.12
gast==0.3.3
gdown==3.12.2
google-auth==1.30.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
importlib-metadata==4.0.1
itsdangerous==1.1.0
Jinja2==2.11.3
joblib==1.0.1
Keras==2.4.3
Keras-Preprocessing==1.1.2
lightgbm==3.2.1
Markdown==3.3.4
MarkupSafe==1.1.1
mtcnn==0.1.0
numpy==1.19.5
oauthlib==3.1.0
opencv-python==4.5.1.48
opt-einsum==3.3.0
pandas==1.1.5
Pillow==8.2.0
protobuf==3.15.8
pyasn1==0.4.8
pyasn1-modules==0.2.8
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
retina-face==0.0.4
rsa==4.7.2
scikit-learn==0.24.2
scipy==1.6.3
six==1.15.0
tensorboard==2.5.0
tensorboard-data-server==0.6.0
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-estimator==2.4.0
tensorflow-gpu==2.4.1
termcolor==1.1.0
threadpoolctl==2.1.0
tqdm==4.60.0
typing-extensions==3.7.4.3
urllib3==1.26.4
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.4.1

**Comment by serengil** [comment]
Hello, I tested on my windows machine as well. It seems everything is oke.

Environment:
```shell
(deepface) C:\Users\Sefik\Desktop>python --version
Python 3.8.5
```

Testing code:
```python
import cv2
print("opencv version: ", cv2.__version__)
img = cv2.imread("deepface/tests/dataset/img1.jpg")
print("img shape: ",img.shape)
```

(deepface) C:\Users\Sefik\Desktop>python test.py
opencv version:  4.5.1
img shape: (1868, 1382, 3)
