### ISSUE TITLE
Analyze Only 1 Attribute

### ISSUE THREAD

**Issue by yagizcolak** [serengil/deepface#226]
Is it possible to analyze a single attribute? When I run Deepface.analyze(image) it returns 4 attributes, which include emotion, age, gender and race. Analyzing all of these takes a long time, and I only need one of them.

**Comment by serengil** [comment]
Hello, when you call the function as shown below:

```
from deepface import DeepFace
obj = DeepFace.analyze("img1.jpg", actions = ["age", "gender"])
print(obj)
```

The result is going to be 

{'region': {'x': 412, 'y': 161, 'w': 592, 'h': 853}, 'age': 33, 'gender': 'Woman'}

**Comment by yagizcolak** [comment]
As far as I can see it still calculates all 4 attributes, but only outputs the given ones.
I need only the ages for a large dataset, but it takes a very long time. Here's my code snippet, do you have any advice?

```
for i in range(1000):
      img = cv2.imread(path + "/" + filelist[i])
      obj = DeepFace.analyze(img)
      ageList.append(obj['age'])
```

**Comment by serengil** [comment]
You haven't passed actions argument. That's why, it finds 4 attributes. Besides, you can build age prediction model once to speed it up.

```
models = {}
models["age"] = DeepFace.build_model("Age")

for i in range(1000):
      img = cv2.imread(path + "/" + filelist[i])
      obj = DeepFace.analyze(img, actions = ["age"], models = models)
      ageList.append(obj['age'])
```
