### ISSUE TITLE
Move weights from Google drive

### ISSUE THREAD

**Issue by CITIZENDOT** [serengil/deepface#227]
Google drive is causing lot of problems, Since it is rate limited. Weight files can be moved to another GitHub repo or some public hosting service to avoid this.

**Comment by sunshineinwater** [comment]
According to my experience, you can download file faster by web browser ,such as Safari.

**Comment by CITIZENDOT** [comment]
I mean, Google drive has maximum limit of downloads per day through browser. Once that limit is reached, It's not allowing to download that file.

**Comment by CITIZENDOT** [comment]
I opened a PR in gdown (https://github.com/wkentaro/gdown/pull/97#issue-628560506), which avoids this to some extent.

**Comment by serengil** [comment]
Because of the size of weight files, I cannot store them in github. Some weights are about 500MB and there are tens of weights existing in the deepface. Google Drive is now the one free solution (I know). 

If this project has a budget, then I can move to dropbox but unfortunately I cannot pay anything.

**Comment by serengil** [comment]
We should follow this issue on the gdown. That's why, I am closing it. Nothing can be done for now.

**Comment by CITIZENDOT** [comment]
Got it. Thankyou for your work. I wish I could support this. Shall we discuss free alternatives of Google drive in this issue?

**Comment by serengil** [comment]
Sure, we can keep on to discuss this topic in this issue. Should I reopen it?

**Comment by CITIZENDOT** [comment]
Yeah. In-case someone is generous to offer something or some new plan comes, It would be helpful.
