### ISSUE TITLE
Emotion detection and classification with webcam

### ISSUE THREAD

**Issue by pirate-lofy** [serengil/deepface#23]
I don't see how I can use deepface to classify emotions on a frame comes from webcam, can someone please give me a hit

**Comment by serengil** [comment]
Store a file named hello.py on your desktop. Its content should be like the following code block.

```python
from deepface import DeepFace
DeepFace.stream("")
```

Then open your command prompt, go to your desktop

Call "python hello.py"

It is just that easy.

**Comment by pirate-lofy** [comment]
that's nice, thanks
I have another question if u don't mind, I want to make predictions of the emotions on real time without any pause...
is there a parameter I could pass to the function stream to prevent the detector from freezing for five seconds or should I edit the code inside common.analysis function?

**Comment by serengil** [comment]
It is not supported. You have to change the following file to do this task

https://github.com/serengil/deepface/blob/master/deepface/commons/realtime.py

You set the variables in the 117th line to 0

`
time_threshold = 5; frame_threshold = 5
`

I might add this as an optional argument in the stream function.

**Comment by leijue222** [comment]
It is not supported [real-time](https://youtu.be/Dm5ptTiIpkk) now? 
https://github.com/serengil/deepface/blob/fe80d944dd5d3deb42b837a6f7d979995729f00b/deepface/DeepFace.py#L774-L778
The code show `time_threshold` and `frame_threshold` must `>=1`

**Comment by serengil** [comment]
Set the both variables to 1. It becomes near real time.
