### ISSUE TITLE
Model format error occured when Ensemble learning.

### ISSUE THREAD

**Issue by XZJIsme** [serengil/deepface#231]
![image](https://user-images.githubusercontent.com/30148847/117691485-86648700-b1ee-11eb-838a-140b69da14ce.png)

**Comment by XZJIsme** [comment]
> it's a warning not error. could you print result variable?

But it said that it's fatal? And I couldn't print the result, because it didn't finish with 0 returned.
![image](https://user-images.githubusercontent.com/30148847/117755734-58635f00-b24f-11eb-9969-04d0ab1863eb.png)

And Here's the code, ```result = DeepFace.verify("3.jpg", "4.jpg", model_name="Ensemble", distance_metric='cosine')```.

**Comment by serengil** [comment]
It seems a lightgbm related issue. Could you open the following file? Its content is oke?

HOME_FOLDER\.deepface\weights\face-recognition-ensemble-model.txt

**Comment by XZJIsme** [comment]
> It seems a lightgbm related issue. Could you open the following file? Its content is oke?
> 
> HOME_FOLDER.deepface\weights\face-recognition-ensemble-model.txt

I re-downloaded it and the problem got resolved. At the beginning, I just copid the text of the file from GitHub and pasted it by notepad manually which may caused the error. Sorry.

**Comment by serengil** [comment]
Wonderful!

**Comment by XZJIsme** [comment]
> Wonderful!

And, thanks! DeepFace helps me a lot!

**Comment by serengil** [comment]
Appreciate
