### ISSUE TITLE
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

### ISSUE THREAD

**Issue by okoliechykwuka** [serengil/deepface#233]
Based on the above below issue [#65](https://github.com/serengil/deepface/issues/65)

 and [#212 ]
 
 when you pass in a Grayscale image, It often results to the above error.
 
 On the below function, I tried converting the Grayscale image to BGR so that I  can pass it to `Deepface.verify`

```
def read_imagefile(file) -> Image.Image:
    image = Image.open(BytesIO(file))
    open_cv_image = np.array(image)
    if len(open_cv_image.shape) > 2:
        open_cv_image = open_cv_image[:, :, ::-1] # Convert RGB to BGR

    if len(open_cv_image.shape) < 3:
         open_cv_image =   cv2.cvtColor(open_cv_image, cv2.COLOR_GRAY2BGR)
    return open_cv_image
```

But the error still occurs

**Comment by okoliechykwuka** [comment]
Not at all, I only have issues when we have grayscale images

**Comment by serengil** [comment]
Clear! do not use gray scale images please.
