### ISSUE TITLE
Is this a wrong align result of RetinaFace.extract_faces(align = True)?

### ISSUE THREAD

**Issue by XZJIsme** [serengil/deepface#234]
The input picture is 
![image](https://user-images.githubusercontent.com/30148847/117970054-c9dc0400-b35a-11eb-9467-9b38d532eeea.png)

The code is ```faces = RetinaFace.extract_faces(img_path = "test.jpg", align = True)```.

The aligned result is
![image](https://user-images.githubusercontent.com/30148847/117970535-58e91c00-b35b-11eb-8126-d302568a88cf.png)

**Comment by serengil** [comment]
interesting, why angelina is upside down in the base image :)

**Comment by XZJIsme** [comment]
> interesting, why angelina is upside down in the base image :)

I wanna test whether it could work correctly when the face is upside down, so I rotated it.

**Comment by serengil** [comment]
I am just kidding. That's a bug. I'm going to solve it soon.

**Comment by XZJIsme** [comment]
> I am just kidding. That's a bug. I'm going to solve it soon.

Got it. 😂

**Comment by anxueren8** [comment]
![Screenshot from 2021-05-27 17-50-18](https://user-images.githubusercontent.com/71525698/119901667-35ee6880-bf14-11eb-835f-117357356eb9.png)
![Screenshot from 2021-05-27 17-55-03](https://user-images.githubusercontent.com/71525698/119902176-da70aa80-bf14-11eb-95ef-9de62796c434.png)
It looks like 'opencv' and 'ssd' don't work either. And the output of 'retinface' is like a blue version Hulk.:joy:

```
backends = ['opencv', 'ssd', 'dlib', 'mtcnn', 'retinaface']
for backend in backends:
    #face detection and alignment
    detected_face = DeepFace.detectFace(pairs[0][0], detector_backend = backend)
    print(backend)
    plt.imshow(detected_face)
    plt.show()
```

**Comment by serengil** [comment]
the both opencv and ssd face detectors use the eye detector of opencv and it is not robust. that's why, the default detector backend is mtcnn. in other words, nothing can be done for opencv and ssd.

but, I'm going to fix retinaface in this weekend.

**Comment by serengil** [comment]
this is fixed in the source code of retinaface. Iit will be published in the next release. you can clone the source code until it is published.
