### ISSUE TITLE
parametrize extendedmodels loadmodel() API for url download

### ISSUE THREAD

**Issue by diegoskiveit** [serengil/deepface#236]
Can you please consider parametrizing the loadmodel() API in:
deepface/extendedmodels/Age.py
deepface/extendedmodels/Emotion.py
deepface/extendedmodels/Gender.py
deepface/extendedmodels/Race.py

So that the url for the package download can be overloaded like:
def loadModel(url = <default_url>):

This is along the same lines as the parameter that is already present in other loadModel() APIs like in DeepID.py / Facenet.py and so on.

**Comment by serengil** [comment]
Sure, it's going to be done in the next release.

**Comment by serengil** [comment]
This is handled in 0.0.52. It will be published soon.

**Comment by diegoskiveit** [comment]
Awesome, thanks !
