### ISSUE TITLE
gpu memory usage

### ISSUE THREAD

**Issue by flyingmrwang** [serengil/deepface#237]
I can run the model with gpu. However I noticed there are always large percentage of gpu memory occupied. 

To figure out whether it is due to large size of model. I try to load face analyze models one by one and monitor the gpu memory usage. The result is that after loading the first model, the memory is already pretty high. And for the following ones, it stops increasing. 

So is this a bug to load all the models as once internally? Since my gpu memory is quite large, and I never see a single model can consume such large memory. @serengil 

![image](https://user-images.githubusercontent.com/18489060/118586709-cec30c80-b7cd-11eb-99a8-0d0054e47347.png)

**Comment by serengil** [comment]
Tensorflow applies greddy approach. I mean that it allocates everything. If you have multiple gpus, then it would allocate their memory all. You can optionally set allow_growth argument to avoid greddy approach. It will allocate what it needs.

```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config)
keras.backend.set_session(session)
```

So, that's not a bug. It's tensorflow related approach.
