### ISSUE TITLE
Does DeepFace support to analyse the attributes of the images which contains many faces

### ISSUE THREAD

**Issue by Hwang64** [serengil/deepface#238]
Hi, when I use DeepFace to analyse the images, I find that the code returens  only one face attributes, but the image contains several faces, so I wonder if the DeepFace supports to analyse the attributes of the images which contains many faces?

**Comment by serengil** [comment]
it is designed to analyze just a face in an image

**Comment by hardiknahata** [comment]
@Hwang64 You can use Dlib face detected or some similar library to detect faces, and crop them out of the image in separate images. After that you can send those cropped face images to deepface for analysis.

**Comment by serengil** [comment]
as @hardiknahata mentioned, it can be handled as shown below.

```python
from deepface import DeepFace
from retinaface import RetinaFace
faces = RetinaFace.extract_faces("img1.jpg")

for face in faces:
     obj = DeepFace.analyze(face)
     print(obj)
```
