### ISSUE TITLE
how about detect once and analyze for each action

### ISSUE THREAD

**Issue by flyingmrwang** [serengil/deepface#239]
I find that the analyze code will parse actions and run whole pipeline of  face_detection+analyze for each of them.
This should cause duplicated inference for face detection. How about use shared bboxes of face detection?
@serengil

**Comment by serengil** [comment]
I don't understand the problem. Could you give me some details?

**Comment by flyingmrwang** [comment]
sorry to bother, I just did not see the "if img_224 is None:" before face detection. 
Please feel free to delete this issue.

**Comment by serengil** [comment]
it's oke :)
