### ISSUE TITLE
Analysis message suppression

### ISSUE THREAD

**Issue by tatami-matt** [serengil/deepface#24]
Currently there seems like there is no way to suppress the progress bar message which pops up during facial feature analysis. Could a parameter be added to the analyze function to suppress these messages from being printed?

**Comment by serengil** [comment]
Sure, I will add this feature in the following version.

**Comment by serengil** [comment]
This is going to handled in the new version. I close this because this is not an issue.

**Comment by kragrrr** [comment]
@serengil any idea about @MrPalais's issue. Suffering with the same at the moment.

**Comment by serengil** [comment]
one option is downgrade your tf

second option is adding verbose=0 argument to predict functions of keras as mentioned here: https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L770

even though i updated the code, i have not pushed it to pip.

**Comment by kragrrr** [comment]
result = DeepFace.analyze(img, actions = ['emotion'], prog_bar = False)
anyhow, i can do that in this line?

**Comment by OpenAyEye** [comment]
has this ever been addressed?
