### ISSUE TITLE
Feature request: embedding vector

### ISSUE THREAD

**Issue by stuz5000** [serengil/deepface#241]
Can the API produce the embedding vectors as output? It's useful for a wide range of applications.
Thanks in advance.

**Comment by serengil** [comment]
Sure, represent function exists in the deepface interface but I haven't added it to the api. It would be a nice feature. I'll add it in the next relase.

**Comment by stuz5000** [comment]
🎉 Many thanks!

**Comment by serengil** [comment]
This is handled in 0.0.52. It will be published soon.
