### ISSUE TITLE
Wrong result of detectFace, a pure black image returned.

### ISSUE THREAD

**Issue by XZJIsme** [serengil/deepface#245]
When I ran ```cv2.imwrite("base_image.jpg", act.DeepFace.detectFace(act.img_read("test.jpg"), detector_backend = "mtcnn"))```, got this: 
![image](https://user-images.githubusercontent.com/30148847/118977464-bf4beb00-b9a8-11eb-9c26-e3546ce06f86.png)
When I ran ```cv2.imwrite("base_image.jpg", act.DeepFace.detectFace(act.img_read("test.jpg"), detector_backend = 'mtcnn') * 255)```, got this:
![image](https://user-images.githubusercontent.com/30148847/118977576-e4d8f480-b9a8-11eb-9bc2-ebc29a003bb6.png)
The base image here.
![image](https://user-images.githubusercontent.com/30148847/118977060-5795a000-b9a8-11eb-875a-f8e9d8341c62.png)
In fact, I tried many images and it always returned pure black image.

**Comment by serengil** [comment]
Try this:

```
from deepface import functions
img = functions.preprocess_face("test.jpg", detector_backend = "mtcnn")[0]
cv2.imwrite("base_image.jpg", img[:, :, ::-1])
```

**Comment by XZJIsme** [comment]
I modify the source, then it could return correct RGB image.
![image](https://user-images.githubusercontent.com/30148847/118980087-b4df2080-b9ab-11eb-8961-fa3d24892815.png)

**Comment by serengil** [comment]
But this time you cannot plot it with matplotlib. It expexts in scale of [0, 1]

**Comment by serengil** [comment]
It should be: from deepface.commons import functions

**Comment by XZJIsme** [comment]
> It should be: from deepface.commons import functions

Sorry, my bad. 😅

**Comment by serengil** [comment]
so, your problem is solved, i am closing the issue if nothing else

**Comment by XZJIsme** [comment]
> so, your problem is solved, i am closing the issue if nothing else

But the aligned result is wrong.
![image](https://user-images.githubusercontent.com/30148847/118982242-cf19fe00-b9ad-11eb-80c0-230978f50846.png)

**Comment by serengil** [comment]
Mtcnn finds eye coordinates wrong.

Could you set detector_backend to retinaface?

**Comment by XZJIsme** [comment]
> Mtcnn finds eye coordinates wrong.
> 
> Could you set detector_backend to retinaface?

It said 
![image](https://user-images.githubusercontent.com/30148847/118997634-66398280-b9bb-11eb-9e20-6b67f4920133.png)

**Comment by XZJIsme** [comment]
> Mtcnn finds eye coordinates wrong.
> 
> Could you set detector_backend to retinaface?

Yes, RetinaFace.extract_faces() works well. Really thanks!
