### ISSUE TITLE
Precision/Accuracy

### ISSUE THREAD

**Issue by duongminhhieu16** [serengil/deepface#247]
Can you tell me if there is any function in the source code that gives the accuracy/precision of each model? Thank you.

**Comment by serengil** [comment]
it is mentioned in the read me of the repo.

**Comment by leijue222** [comment]
How about the emotion? I test emotion by `DeepFace.stream`, it always sad Instead of neutral

**Comment by serengil** [comment]
This is mentioned in the read me as well. Please follow the links.

Tutorial: https://sefiks.com/2018/01/01/facial-expression-recognition-with-keras/

Test loss: 2.27945706329
Test accuracy: 57.4254667071
 
Train loss: 0.223031098232
Train accuracy: 92.0512731201

**Comment by leijue222** [comment]
> This is mentioned in the read me as well. Please follow the links.
> 
> Tutorial: https://sefiks.com/2018/01/01/facial-expression-recognition-with-keras/
> 
> Test loss: 2.27945706329
> Test accuracy: 57.4254667071
> 
> Train loss: 0.223031098232
> Train accuracy: 92.0512731201

This repository is a great job.  Thank you.
