### ISSUE TITLE
CUDA GPU support and Docker deployment?

### ISSUE THREAD

**Issue by alvarobasi** [serengil/deepface#248]
Hi! 

Firs of all, thank you for the project! Is amazing and really easy to use! I want to deploy it on a container, what dependencies do I need to install to do so? And second question, is this library GPU compatible? As it installs tensorflow without the gpu tag by default when using pip...

Thanks in advance!

**Comment by serengil** [comment]
yes, it is gpu compatible. install its dependencies firstly, and mention tensorflow-gpu instead of regular tensorflow. then install deepface with no dependencies in the docker file.

pip install numpy>=1.14.0 pandas>=0.23.4 tqdm>=4.30.0 gdown>=3.10.1 Pillow>=5.2.0 opencv-python>=3.4.4 tensorflow-gpu>=1.9.0 keras>=2.2.0 Flask>=1.1.2 mtcnn>=0.1.0 retina-face>=0.0.1
pip install deepface --no-deps

**Comment by alvarobasi** [comment]
Hi! Thank you for the fast response! I followed your guidelines, but verify method still takes like 5 seconds tu run (preloading the model first) and checking with nvidia-smi I don't see any GPU usage... I have noticed that even if tensorflow-gpu is installed first and even if I use the --no-deps tag, it still installs tensorflow (without the gpu tag)

**Comment by serengil** [comment]
you are installing packages via pip?

**Comment by serengil** [comment]
this should install tensorflow-gpu instead of tensorflow

**Comment by alvarobasi** [comment]
I am getting this output when executing the build Dockerfile, just after the last module install from requirements.txt file:
Collecting retina-face>=0.0.1
  Downloading retina_face-0.0.4-py3-none-any.whl (14 kB)
Collecting wheel~=0.35
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting grpcio~=1.32.0
  Downloading grpcio-1.32.0-cp36-cp36m-manylinux2014_x86_64.whl (3.8 MB)
Collecting wrapt~=1.12.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Collecting astunparse~=1.6.3
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting protobuf>=3.9.2
  Downloading protobuf-3.17.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Collecting opt-einsum~=3.3.0
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting typing-extensions~=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting tensorflow-estimator<2.5.0,>=2.4.0
  Downloading tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
Collecting keras-preprocessing~=1.1.2
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting gast==0.3.3
  Downloading gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting google-pasta~=0.2
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting termcolor~=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting flatbuffers~=1.12.0
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting h5py~=2.10.0
  Downloading h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl (2.9 MB)
Collecting absl-py~=0.10
  Downloading absl_py-0.12.0-py3-none-any.whl (129 kB)
Collecting six~=1.15.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting tensorboard~=2.4
  Downloading tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.2
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting filelock
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting requests[socks]>=2.12.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pyyaml
  Downloading PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)
Collecting scipy>=0.14
  Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
Collecting click>=7.1.2
  Downloading click-8.0.1-py3-none-any.whl (97 kB)
Collecting itsdangerous>=2.0
  Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting Werkzeug>=2.0
  Downloading Werkzeug-2.0.1-py3-none-any.whl (288 kB)
Collecting Jinja2>=3.0
  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting tensorflow>=1.9.0
  Downloading tensorflow-2.5.0-cp36-cp36m-manylinux2010_x86_64.whl (454.3 MB)
Collecting importlib-metadata
  Downloading importlib_metadata-4.4.0-py3-none-any.whl (17 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp36-cp36m-manylinux2010_x86_64.whl (30 kB)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests[socks]>=2.12.0->gdown>=3.10.1->-r requirements.txt (line 4)) (2.6)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting PySocks!=1.5.7,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.30.1-py2.py3-none-any.whl (146 kB)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard~=2.4->tensorflow-gpu==2.4.1->-r requirements.txt (line 7)) (57.0.0)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.4-py3-none-any.whl (97 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting tensorflow>=1.9.0
  Downloading tensorflow-2.4.1-cp36-cp36m-manylinux2010_x86_64.whl (394.3 MB)
Collecting dataclasses
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.1-py3-none-any.whl (5.2 kB)


Not sure which module is requesting to install tensorflow. Maybe Keras?

**Comment by serengil** [comment]
maybe. try to install it with no dependencies.

**Comment by alvarobasi** [comment]
Ok, it seems like retina-face>=0.0.1 is pulling tensorflow>= 1.9.0. However, now that I only have installed tensorflow-gpu, it continues to take 8seconds per verify call...

**Comment by serengil** [comment]
Please send image pairs as input to the verify function

```python
resp = DeepFace.verify([
     [img1, img2], 
     [img1, img3], 
     [img2, img3]
]
, model=model)
```
here, img1, img2, img3 could be image path or numpy array
