### ISSUE TITLE
Deepface not detecting age correctly on Young People

### ISSUE THREAD

**Issue by RaghsMakes** [serengil/deepface#249]
I have tried multiple pictures with multiple people. Is this locked on deep face? or that's an image

**Comment by serengil** [comment]
You can find out age prediction tutorial here: https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/

To sum up, it has a plus minus 4 years mean absolute error. It also tends to make predictions with high mae for young people.

Besides, deepface expects one face in an image. If the image has multiple faces, then it will process the first one it found and ignore the others.
