### ISSUE TITLE
The model with unloaded weights is not taken.

### ISSUE THREAD

**Issue by waferson** [serengil/deepface#25]
I have manually downloaded the model with weights since it does not allow the automatic download due to user traffic, then said model is not recognized AND again try to download which leads to the vicious circle, Where can I specify the downloaded .h5 file so that I don't try to download it again and the rest will work?

**Comment by serengil** [comment]
.h5 files stored in your home folder /.deepface (e.g. mine is C:\Users\Sefik\.deepface\weights). If .h5 files exist in this directory, then it will not download again.

Notice that deepface is a hidden folder and starts with a dot character.

**Comment by waferson** [comment]
ok, i was able to solve it, thanks!
