### ISSUE TITLE
Issue with deepface

### ISSUE THREAD

**Issue by Fatima-Ali8765** [serengil/deepface#250]
Something strange happened. When I was using deepface version 0.0.51 on colab, I was getting my results and when I used the DeepFace.find function, I was getting the dataframe right like it was showing the rows and stuff.
But when I installed the deepface version 0.0.53 because I normally have to install it on colab before I use it, It has stopped showing the results because it considered that the images were of different people and there was no data in my dataframe when I ran the find function because it probably considered the images as not matching. Which was strange because I ran the same function on the same data but on version 0.0.51 and it showed me the result which was true and I got the dataframe right.
I was doing .find and .verify on VGG-Face model and I got a dataframe and true on 0.0.51 but 
an empty dataframe and False on 0.0.53.
If it's the issue of version that is going through some form of change then it would make sense or so. Otherwise I'm not really able to figure it out.

**Comment by serengil** [comment]
Super! I was afraid of my latest release causing some problems :)
