### ISSUE TITLE
Multiple faces analyze use DeepFace.analyze

### ISSUE THREAD

**Issue by sunny123123** [serengil/deepface#252]
Hi,
    I used deepface to acquire age and gender from a picture. But I found deepface only return one face result though multiple face exists.

example, this picture
![image](https://user-images.githubusercontent.com/10163641/120173637-c986a880-c236-11eb-9e70-596ecec99efd.png)
code snippet
```
obj = DeepFace.analyze(img_path = image_path, actions = ['age', 'gender'])
```
but result only one face
```
{'region': {'x': 329, 'y': 102, 'w': 118, 'h': 165},
 'age': 21,
 'gender': 'Man'}
```

So my question is how to analyze multiple faces with deepface?
Any suggestions help me, thanks

**Comment by serengil** [comment]
deepface is designed to be run for single faces. if more than one face exists in an image, then it will analyze the first one and discard others.

If you retrieve single images and pass them individually to deepface, it will analyze multiple faces.

```
#!pip install retina-face
from retinaface import RetinaFace
img = "img1.jpg" #this has multiple faces
faces = RetinaFace.extract_faces(img)

#!pip install deepface
from deepface import DeepFace
for face in faces:
     obj = DeepFace.analyze(face, actions = ['age', 'gender'])

```
