### ISSUE TITLE
DeepFace.Stream not working

### ISSUE THREAD

**Issue by talalz94** [serengil/deepface#259]
Hi,

Im getting the following error while trying to run the stream function:

![image](https://user-images.githubusercontent.com/29313245/122297286-c79a3600-cf14-11eb-94a7-8695bd5e6db0.png)

Kindly guide me through it.

Many Thanks in Adv :)

**Comment by serengil** [comment]
It seems that one one your images in Johhny folder causes that trouble. There are 3 items in that folder. Could you share them with me?

**Comment by serengil** [comment]
btw, which version of deepface you are running? This might be fixed in 0.0.55.

**Comment by serengil** [comment]
Oah yeas. It seems you are using a legacy version of deepface. Please update it to 0.0.55.
