### ISSUE TITLE
api.py hit error 

### ISSUE THREAD

**Issue by guangyi1609** [serengil/deepface#26]
get this error when call api from postman

in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable Block17_1_Branch_1_Conv2d_0a_1x1/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/Block17_1_Branch_1_Conv2d_0a_1x1/kernel)
	 [[{{node Block17_1_Branch_1_Conv2d_0a_1x1/convolution/ReadVariableOp}}]]

**Comment by serengil** [comment]
Which operation you are calling? Could you share the input request? Besides, could you share the environmental versions for keras and tensorflow?

**Comment by guangyi1609** [comment]
Hi i facing the error in both verify and analyze operations.

As for the input i using the postman file from ur reporistory.

**Comment by guangyi1609** [comment]
I downloaded it from pipy just now. So wasn't sure about it. Will check on it and update you.

**Comment by serengil** [comment]
My tests were done on tensorflow==1.9.0 and keras==2.2.0. Could you test the API for these versions.

**Comment by guangyi1609** [comment]
The my version was 2.3.1 and 1.14.0. alright sure.

**Comment by guangyi1609** [comment]
Thanks man. It worked well with 1.9 and 2.2

**Comment by serengil** [comment]
I will look for the root cause for tf 1.14.0 and keras 2.3.1 later. thank you.

**Comment by Hatef-Rostamkhani** [comment]
> My tests were done on tensorflow==1.9.0 and keras==2.2.0. Could you test the API for these versions.

We don't have TensorFlow versions 1.9.0
https://pypi.org/project/tensorflow/#history
Are you sure?
