### ISSUE TITLE
Different distance results for the same code on different machines

### ISSUE THREAD

**Issue by anxueren8** [serengil/deepface#262]
Hello, 

I run the following code on different machines (one just used CPU, one used GPU), but I got different results. For CPU, I got: 

  image1 | image2| cosine distance
001_002_0.5 | 001 | 0.471843
001_002_0.5 | 002 | 0.434614
001_003_0.5 | 001 | 0.565312
001_003_0.5 | 003 | 0.763006
001_004_0.5 | 001 | 0.666956

While for GPU one:

  image1 | image2| cosine distance
001_002_0.5 | 001 | 0.01673
001_002_0.5 | 002 | 0.01159
001_003_0.5 | 001 | 0.03172
001_003_0.5 | 003 | 0.03836
001_004_0.5 | 001 | 0.02838

In my experience, the results from CPU one are reasonable, while GPU one is not. Do you have any idea what's wrong with it? 

The deepface version I used is 0.0.51. The CPU on is i7-6800K, the GPU one is Xeon W-2175 with RTX 2080Ti. Plus, I try to use GPU on i7-6800K machine (1080Ti) with the code:
```
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"
```
But it didn't seem to work since GPU memory is not occupied.

The full code is as follows, where pairs_alpha05 is the path of my images, and path1 and path 2 is image 2 and image 1 shown above. Here is image 1 and 2.

![001_03_q30](https://user-images.githubusercontent.com/71525698/122615160-0c79b600-d056-11eb-9bad-d032a86d26ad.jpg)
![001_03_R_morphed_0 5_002_03_R](https://user-images.githubusercontent.com/71525698/122615168-100d3d00-d056-11eb-859e-1b5f5c596c1f.png)

```
model_name = "ArcFace"
model = DeepFace.build_model(model_name)

pairs_distance_lists = []

for j in range(len(pairs_name_alpha05)):
    
    print('{now}/{total}'.format(now = j, total = len(pairs_name_alpha05)))
    
    path1 = pairs_alpha05[j][0] # the path of frist image like 001_03_q30.jpg
    path2 = pairs_alpha05[j][1] # the path of second image like 001_03_R_morphed_0.5_002_03_R.png
    
    result = DeepFace.verify(path1, path2, model_name=model_name, model=model,\
                              distance_metric = "cosine", detector_backend = 'dlib')

    # extract distance from result
    a1 = pairs_name_alpha05[j][0]
    a2 = pairs_name_alpha05[j][1]
    a3 = result['distance']
    pairs_distance = [a1, a2, a3]
#     print(pairs_distance)
    pairs_distance_lists.append(pairs_distance)

    if (j+1)%1000 == 0:
        json_name = 'ArcFace_cosine_AMSL_distance_lists_sych_alpha05_' + str(j+1) + '.json'
        with open(json_name, 'w') as json_file3:
            json.dump(pairs_distance_lists, json_file3)
        print(json_name + ' saved!')
```

**Comment by serengil** [comment]
No idea :/ It might be a tensorflow related issue.

**Comment by anxueren8** [comment]
I think it could be the problem of tensorflow-gpu. After I disabled the gpu used in the code, the results in both computers are the same. For the environment requirement of deepface, it should not use  tensorflow-gpu, right?

**Comment by serengil** [comment]
it should not matter. it can be run on cpu or gpu.

**Comment by serengil** [comment]
I am closing this issue if it is oke, because it seems that it is independent from deepface.
