### ISSUE TITLE
Please Share Model Weights Google Drive Folder Link

### ISSUE THREAD

**Issue by ovichowdhury** [serengil/deepface#263]
Hi serengil, Most of the time during model weights download raising this error.

> Access denied with the following error:
> 
>         Too many users have viewed or downloaded this file recently. Please
>         try accessing the file again later. If the file you are trying to  
>         access is particularly large or is shared with many people, it may 
>         take up to 24 hours to be able to view or download the file. If you
>         still can't access a file after 24 hours, contact your domain      
>         administrator.
> 
> You may still be able to access the file from the browser

But It is very frustrating to download the weights one by one. So can you please share a folder link so that weights can be downloaded at once? It would also be very helpful for creating docker volumes for production usage of deepface.

**Comment by serengil** [comment]
unfortunately, that would exceed of my google drive limit.
