### ISSUE TITLE
Having Trouble Download age_model_weights.h5

### ISSUE THREAD

**Issue by JianSShi** [serengil/deepface#267]
I am having trouble to get the age_model_weights.h5, it always give me the error that it seems limit is exceeded.
I was wondering by any chance can someone give me a vaild link to download or send that file to me? Also I would appreciate that you can help me to get other files, gender_model_weights.h5 and race_model_single_batch.h5

**Comment by serengil** [comment]
Exception message mentions the url. You can still download that file from browser. Please read the faq and troubleshooting section in the read me.

**Comment by JianSShi** [comment]
> Exception message mentions the url. You can still download that file from browser. Please read the faq and troubleshooting section in the read me.

I tried the url manually, it still gives me same errro of download limition. 
![image](https://user-images.githubusercontent.com/30500313/123217371-1475a200-d4fd-11eb-9bca-341005dd769f.png)

**Comment by serengil** [comment]
which url you are trying to access?

**Comment by JianSShi** [comment]
> which url you are trying to access?
https://drive.google.com/uc?id=1YCox_4kJ-BYeXq27uUbasu--yz28zUMV, this one, I tried yesterday and today for several times, just not work for me.
