### ISSUE TITLE
zsh: illegal hardware instruction  error in Macbook Pro M1 Chip

### ISSUE THREAD

**Issue by Gavaskar821996** [serengil/deepface#268]
zsh: illegal hardware instruction  error in Macbook Pro M1 Chip. Pls help me to resolve

**Comment by serengil** [comment]
I am using macbook pro but mine has intel microprocessor. You should open an issue in tensorflow.

**Comment by Gavaskar821996** [comment]
ok thanks

**Comment by serengil** [comment]
It seems that you should install m1 compatible tf. Find out more on https://stackoverflow.com/questions/70324807/illegal-instruction-4-when-running-deepface/70440792?noredirect=1#comment125055180_70440792
