### ISSUE TITLE
[Question] : How did I get face coordinates for single and multi faces ? 

### ISSUE THREAD

**Issue by VinayChaudhari1996** [serengil/deepface#269]
Hello Guys , 

Im trying to match multiple face matching with custom encodings. 
So do I get face coordinates  (basically 4 values)  like face_recognition
package ?  

Please help.
Thanks

**Comment by serengil** [comment]
could you give some details?

**Comment by VinayChaudhari1996** [comment]
> could you give some details?

`image = face_recognition.load_image_file("picture.jpg")`


`face_locations = face_recognition.face_locations(image)`


### The output will be something like this!

```
I found 1 face(s) in this photograph.
A face is located at pixel location Top: 241, Left: 419, Bottom: 562, Right: 740
```

**Comment by serengil** [comment]
If you need just face detection, I recommend you to use retinaface directly. That's the dependency of this library.

https://github.com/serengil/retinaface

```python
from retinaface import RetinaFace
resp = RetinaFace.detect_faces("img1.jpg")
```

```json
{
    "face_1": {
        "score": 0.9993440508842468,
        "facial_area": [155, 81, 434, 443],
        "landmarks": {
          "right_eye": [257.82974, 209.64787],
          "left_eye": [374.93427, 251.78687],
          "nose": [303.4773, 299.91144],
          "mouth_right": [228.37329, 338.73193],
          "mouth_left": [320.21982, 374.58798]
        }
  }
}
```

You need facial_area key in the output.
