### ISSUE TITLE
error in api

### ISSUE THREAD

**Issue by Hatef-Rostamkhani** [serengil/deepface#27]
can you produce a list of the exact version of components you tested successfully and what is your version python?

**Comment by serengil** [comment]
You can find it in dependecies.txt or setup.py as well.

Python==3.5.5
numpy==1.14.0
pandas==0.23.4
gdown==3.10.1
tqdm==4.30.0
Pillow==5.2.0
opencv-python==3.4.4
tensorflow==1.9.0
keras==2.2.0
Flask==1.1.2

**Comment by Hatef-Rostamkhani** [comment]
thank you so much,
I didn't see python 3.5.5 exe installation on python website. it just has source
Do you have installation file?

**Comment by Hatef-Rostamkhani** [comment]
> You can find it in dependecies.txt or setup.py as well.
> 
> Python==3.5.5
> numpy==1.14.0
> pandas==0.23.4
> gdown==3.10.1
> tqdm==4.30.0
> Pillow==5.2.0
> opencv-python==3.4.4
> tensorflow==1.9.0
> keras==2.2.0
> Flask==1.1.2

thank you so much,
I didn't see python 3.5.5 exe installation on the python website. it just has a source
Do you have an installation file?
