### ISSUE TITLE
[Suggestion] Split or separate model downloads

### ISSUE THREAD

**Issue by elsheraey** [serengil/deepface#271]
It's really confusing that for example the VGGFace model still runs but with horrible results in case the model didn't download successfully due to Google Drive getting overwhelmed by the amount of download requests on those links.

My preferred suggestion is to at least upload the weight files to Github instead of Google Drive and it's always possible to split files that are > 100MB into smaller .zip files so it shouldn't pose an issue. I can do that and start a pull request if you want to.

If that's not possible, at least the structure of the base model files should be improved to be more consistent cause there is a pattern there and it would be much better if it explicitly separates model downloads by not having them under loadModel() cause again it's confusing for the VGGFace model that if the download fails then the model still gets built yielding incorrect results.

**Comment by elsheraey** [comment]
You can follow the same path used by face_recognition by having a [separate repo like this one](https://github.com/ageitgey/face_recognition_models).

**Comment by serengil** [comment]
I uploaded the pre-trained weights to github releases: https://github.com/serengil/deepface_models/releases/tag/v1.0

Besides, google drive referenced urls changed to github in the source code. 

deepface 0.0.63 is live! thank you for guiding me.
