### ISSUE TITLE
Question: License of Arcface

### ISSUE THREAD

**Issue by zul96a** [serengil/deepface#273]
Hello sir!

I would like to enquire about the licensing of Arcface. Is it available for commercial purpose? And I noticed that the Arcface a bit different in this package. Many thanks!

**Comment by elsheraey** [comment]
InsightFace / ArcFace was originally released under the MIT License. 

There is no limitation for both academic and commercial usage.

You can check the original repo. [here](https://github.com/deepinsight/insightface).

**Comment by zul96a** [comment]
> InsightFace / ArcFace was originally released under the MIT License.
> 
> There is no limitation for both academic and commercial usage.
> 
> You can check its official repo. [here](https://github.com/deepinsight/insightface).

Thanks for the reply! Actually to be precise with my question, I'm referring to the model of the Arcface itself. From what I understand, the source code for Arcface is released under MIT License, but I don't know if it is applied to the Arcface model developed by sir here, since the data and annotation might be covered under separate license. So I'm wondering if the model here created by sire is available for commercial purpose. Many thanks!

**Comment by serengil** [comment]
this is mentioned in the license section of deepface in the read-me file.

> Deepface is licensed under the MIT License - see LICENSE for more details. However, the library wraps some face recognition models: VGG-Face, Facenet, OpenFace, DeepFace, ArcFace and Dlib. Licence types will be inherited if you are going to use those models.

So, the both deepface library and arcface models are licensed under MIT. This license allows them to use in commercial purpose.

**Comment by zul96a** [comment]
> this is mentioned in the license section of deepface in the read-me file.
> 
> > Deepface is licensed under the MIT License - see LICENSE for more details. However, the library wraps some face recognition models: VGG-Face, Facenet, OpenFace, DeepFace, ArcFace and Dlib. Licence types will be inherited if you are going to use those models.
> 
> So, the both deepface library and arcface models are licensed under MIT. This license allows them to use in commercial purpose.

Thanks for reply and clarification!

**Comment by bobmoff** [comment]
I just checked the repo of insightface and noticed this:

"The training data containing the annotation (and the models trained with these data) are available for non-commercial research purposes only."

So, does this mean that using deepface for commercial use is off limit ? or have you trained new models on other data ?

is there any models in deepface that is available for commercial use ?

**Comment by zul96a** [comment]
> I just checked the repo of insightface and noticed this:
> 
> "The training data containing the annotation (and the models trained with these data) are available for non-commercial research purposes only."
> 
> So, does this mean that using deepface for commercial use is off limit ? or have you trained new models on other data ?
> 
> is there any models in deepface that is available for commercial use ?

Maybe it's best if you can get new set of training data and do transfer learning on the model. I'm currently doing that

**Comment by bobmoff** [comment]
Ok. Wouldnt I have to find a couple of million labelled photos to get similar performance?

**Comment by buckeye17** [comment]
I am also concerned about using the ArcFace model for commercial purposes.  Can @serengil clarify whether the ArcFace model weights in DeepFace were produced by the open source community's own training?

[This video](https://youtu.be/i_MOwvhbLdI?t=48) mentions that the models in DeepFace are "retrained" by the open source community, but it seems to predate ArcFace, since ArcFace isn't mentioned in the video.

**Comment by zul96a** [comment]
> Ok. Wouldnt I have to find a couple of million labelled photos to get similar performance?

Yeah, I think you have to use open dataset face and transfer learning/train the model
