### ISSUE TITLE
It is giving same result for any image sometimes

### ISSUE THREAD

**Issue by coderbablu** [serengil/deepface#274]
Hi Sefik,

The model is giving same result either True completely or False completely for any images. I have tried to check the images of elon musk and Obama for the default settings. I'm not sure whether to clear any logs or do I need to do anything before that but it looks so strange as those images are completely different. Let know do we need to clear anything or have to load anything before running the model. I have attached reference picture which is saying true for every result and by the way bab1 to bab7 are my pictures
![error3](https://user-images.githubusercontent.com/81971850/124263943-8bd8b080-db51-11eb-8ab4-8fd0811c1b3c.png)

**Comment by coderbablu** [comment]
One more point - Even switching to the model 'ArcFace' is giving the same result

**Comment by serengil** [comment]
It's very interesting. Could you send me your picture set? I want to try.

**Comment by coderbablu** [comment]
I compared elonmusk image which is attached against others

![obama](https://user-images.githubusercontent.com/81971850/124266883-2c7c9f80-db55-11eb-895f-49769e0b71d7.jpg)
![bill gates](https://user-images.githubusercontent.com/81971850/124266888-2dadcc80-db55-11eb-9d1c-721f7ca5e326.jpg)
![elon musk](https://user-images.githubusercontent.com/81971850/124266890-2e466300-db55-11eb-9253-45538d185ba9.jpg)
![jeff bezos](https://user-images.githubusercontent.com/81971850/124266897-30102680-db55-11eb-84d3-fd1cbf3cbf47.jpg)

**Comment by elsheraey** [comment]
I faced the same confusion and it was because the models didn't successfully download, I thought it would confuse lots of people and that's why I opened an [issue](https://github.com/serengil/deepface/issues/271) about it.

**Comment by serengil** [comment]
@elsheraey I'm going to move pre-trained weights from google drive to github releases in this weekend.

**Comment by elsheraey** [comment]
@serengil Yes, I noticed you creating a new repo. and gratefully put  a star on it.

**Comment by serengil** [comment]
@elsheraey you are so fast :) appreciate

**Comment by serengil** [comment]
I uploaded the pre-trained weights to github releases: https://github.com/serengil/deepface_models/releases/tag/v1.0

Besides, google drive referenced urls changed to github in the source code. 

deepface 0.0.63 is live! thank you for guiding me.
