### ISSUE TITLE
Attractiveness attribute?

### ISSUE THREAD

**Issue by davidwdw** [serengil/deepface#275]
Hi @serengil, thank you so much for this great package! I'm using your package in my academic research project, and I was wondering if you were considering adding in more attribute models such as facial attractiveness?

**Comment by serengil** [comment]
Hi David,

Actually I have studied on this topic

Beauty score: https://sefiks.com/2019/12/25/beauty-score-prediction-with-deep-learning/

Attractiveness: https://sefiks.com/2020/01/22/attractiveness-score-prediction-with-deep-learning/

I mean that models are ready and it is very easy to adapt in deepface. But I didn't know people what those features to use. I can add it in the next release if you need.

**Comment by Usama3059** [comment]
Hi @serengil  I want to know on which data you have trained Gender, Age model

**Comment by serengil** [comment]
@Usama3059 this is mentioned in this post: https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/

**Comment by davidwdw** [comment]
Hi @serengil thanks for taking this into consideration. I saw the links you provided. One suggestion would be to NOT train on SCUT because it's predominantly Asian, which might limit the generalizability of the model. Would recommend to train on the CelebA dataset (https://paperswithcode.com/dataset/celeba). 

I'm using your work in my research, and it's been very helpful. I cited your paper in my recent research (which is under second-round review now, and hopefully will come out soon). The attractiveness variable would be important because psychology research on faces usually control for the influence of attractiveness when looking at other facial perception influences.

**Comment by serengil** [comment]
Unfortunately, I cannot train a new model soon. But I can adapt those pre-trained models soon. I'm going to add the both beauty score and attractiveness modules into deepface in the next release.

Please inform me when your paper is published :)

**Comment by davidwdw** [comment]
Thanks! Yes, that would work too. 

Of course, I will! 

Thanks again for this wonderful library.

**Comment by Usama3059** [comment]
@serengil Thanks for your response,I have been using deepface it is really amazing. How can we do batch predictions as the input isthe image path, not the image arrays?

**Comment by serengil** [comment]
@Usama3059, the following code satisfies your requirement.

```
face_pairs= [
     ["img1.jpg", "img2.jpg"],
     ["img1.jpg", "img3.jpg"],
     ["img1.jpg", "img4.jpg"],
     ["img1.jpg", "img5.jpg"],
     ["img1.jpg", "img6.jpg"]
]

for face_pair in face_pairs:
     obj = DeepFace.verify(face_pair[0], face_pair[1])
     print(obj)
```

**Comment by Usama3059** [comment]
@serengil  I think it is still running the model for len(face_pairs)//2.  My requirement is running the deepface.analyze model once for len(face_pairs).

**Comment by serengil** [comment]
Did you mean this?

```
img_paths = ["img1.jpg", "img2.jpg", "img3.jpg", "img4.jpg", "img5.jpg"]
obj = DeepFace.analyze(img_paths)
```

**Comment by Usama3059** [comment]
@serengil  Yes Thanks Alot

**Comment by serengil** [comment]
I realized that I haven't save the pre-trained weights for beauty and attractiveness score prediction models. I have to re-train them :/ It may last longer than I expected.

I set the status of this issue to closed but I'm going to adapt these functionalities soon. Thank you for understanding.

**Comment by sehgal-neil** [comment]
Any update on including beauty?

**Comment by serengil** [comment]
@HlebKrah no, that requires re-training, pre-trained weights are gone.
