### ISSUE TITLE
tile cannot extend outside image!

### ISSUE THREAD

**Issue by coderbablu** [serengil/deepface#276]
Hi Serengil,

I took the [dataset](https://www.kaggle.com/jessicali9530/lfw-dataset) then I downloaded bill Clinton image from [Wikipedia](https://en.wikipedia.org/wiki/Bill_Clinton#/media/File:Bill_Clinton.jpg). I tried to find which images matches the bill Clinton image in the LFW dataset using DeepFace.find function. But initially after analyzing few images, it throws this error and then I tried to change the detector backend to 'mtcnn' and the same error is coming up again. But when I changed the detector backend to 'retinaface', looks like its running fine. 

Can you look at the error?

**Comment by serengil** [comment]
Could you share all error message. I cannot understand its root cause with the singe text. Sharing your full code would be fine as well.

Did you set enforce_detection argument to False?

**Comment by coderbablu** [comment]
```
#Import the packages
from deepface import DeepFace
import cv2
import matplotlib.pyplot as plt
import pandas as pd
import glob

#The image I uploaded to google drive and get the jpg image from dictionary
test_img = files.upload()
test_img = list(test_img.keys())[0]

#Using the find function to check the bill Clinton(test_img) image with the rest of the images in the path
df = DeepFace.find(test_img,'/content/lfw-deepfunneled/lfw-deepfunneled/',detector_backend='dlib')
```

I haven't put 'enforce_detection = False' by the way

**Comment by serengil** [comment]
Would you please try to set the enforce_detection to False?

**Comment by coderbablu** [comment]
Yes. With enforce_detection set to False, its working but what's the difference? There hasn't been any mention in the documentation about that so!

**Comment by serengil** [comment]
It seems that it cannot detect faces in lfw data set because of low resolution. Enforce_detection argument handles that issue. As you mentioned if face cannot be detected, its accuracy becomes low. You should use high resolution images and set this arrgument to True.

**Comment by coderbablu** [comment]
Hey Serengil, even with enforcement_detection set to False I'm getting the same error for the following line of code

`df_ensemble = DeepFace.find(test_img,'/content/lfw-deepfunneled/lfw-deepfunneled/',model_name='Ensemble',detector_backend='mtcnn',enforce_detection=False)`

![error4](https://user-images.githubusercontent.com/81971850/124555036-3ef82100-de54-11eb-86a4-1743a356af25.png)

**Comment by serengil** [comment]
it comes from pil module - out of deepface.

it might be because of "test_img = files.upload()"

btw, that's the all message you got?

**Comment by coderbablu** [comment]
That's all the message I got
