### ISSUE TITLE
Determining whether a face is present in a picture

### ISSUE THREAD

**Issue by liweilup** [serengil/deepface#277]
Hi, thank you very much for your contribution, you have provided a really great toolkit. I would like to use this toolkit to determine if a face is present in an image, but I can't find the API for it, please help me out. Thank you.

**Comment by serengil** [comment]
If I add detectFace function into the API, I think it satisfies your requirement. Right? 

I can add it in the next release.

**Comment by liweilup** [comment]
> 如果我在 API 中添加了 detectFace 函数，我认为它可以满足您的要求。正确的？
> 
> 我可以在下一个版本中添加它。

Yes, so that I can do the face presence detection first and then do some follow-up work. Thank you for your work.

**Comment by liweilup** [comment]
> If I add detectFace function into the API, I think it satisfies your requirement. Right?
> 
> I can add it in the next release.

Yes, so that I can do the face presence detection first and then do some follow-up work. Thank you very much for your work!

**Comment by laviua** [comment]
```DeepFace.detectFace(img, detector_backend=detector_backend)```
returns the numpy array, so you can just check that array empty or not

**Comment by serengil** [comment]
@laviua , @liweilup actually wants to use detectFace functionality in the API.

**Comment by liweilup** [comment]
> `DeepFace.detectFace(img, detector_backend=detector_backend)`
> returns the numpy array, so you can just check that array empty or not

Thank you very much for your help, the numpy array returned by `DeepFace.detectFace(img, detector_backend=detector_backend) `doesn't seem to be able to tell if the image contains a face or not. This is because the numpy array returned is not empty, regardless of the presence or absence of a face. Without the parameter `enforce_detection=False`, if an image is input that does not contain a face, this function gives a hint that there is no face and suggests that this parameter can be added to resolve it.

**Comment by serengil** [comment]
The following code returns exception if no face detected in the img.jpg.

`
DeepFace.detectFace("img.jpg", detector_backend=detector_backend)
`
