### ISSUE TITLE
Autocrop api

### ISSUE THREAD

**Issue by laviua** [serengil/deepface#278]
Hi,

Will be great to build face autocrop api.
Goal: to get centered and flat face 

Input: image or array of the images in base64
Output: array of the cropped images in base64

afaik need to crop face, then center, align/rotate, etc.

**Comment by serengil** [comment]
This is already covered in retinaface.

```
import matplotlib.pyplot as plt
faces = RetinaFace.extract_faces(img_path = "img.jpg", align = True)
for face in faces:
  plt.imshow(face)
  plt.show()
```

<img width="1263" alt="alignment-procedure" src="https://user-images.githubusercontent.com/18491038/124871867-4262e800-dfcd-11eb-86fb-08c7c6675544.png">
