### ISSUE TITLE
Missing image (image22) from the dataset

### ISSUE THREAD

**Issue by beltrand** [serengil/deepface#280]
Hi, I am currently working on a project with deepface, trying to replicate your work first, and the image 22 (img22.jpg) is missing from deepface/tests/dataset/. Could you upload it again please?

**Comment by beltrand** [comment]
I am using my own img22.jpg since I can google another picture, but it would be good to upload that missing image.

**Comment by serengil** [comment]
Sure

**Comment by serengil** [comment]
this is solved in the latest release (0.0.64)
