### ISSUE TITLE
Facenet VGGface 2 model

### ISSUE THREAD

**Issue by sadimoodi** [serengil/deepface#281]
First:  I would like to thank you for all of the effort you did to develop this valuable library.
Would it be possible to use the VGGface 2 model with the 512 dimensions? the Pre- trained model is already available here: https://github.com/davidsandberg/facenet file name:  "20180402-114759.pb"
i tried to replace your facenet_weights.h5 file with the new pretrained model but i ran into several errors (i changed file names in facenet.py) but seems like i am not able to read the file.
any idea how to load this pre-trained model with 512 dimensions ?
I assume i should also make other changes to account for the 512 imbedding's output as a result of running model.predict
Appreciate your help here

**Comment by serengil** [comment]
Sure!

Original Google paper uses 128 dimensional outputs that is why I adopt that model of David Sandberg.

We can of course add its 512 dimensional model as well. You can use with "Facenet512" model name in deepface functions. Regular Facenet will still use 128 dimensional one.

I can add it in the next release - end of this week I think.

**Comment by serengil** [comment]
deepface 0.0.64 release is on live! Try Facenet512 model to have the best model. Regular Facenet is still 128 dimensional.

`obj = DeepFace.verify("img1.jpg", "img2.jpg", model_name = "Facenet512")`
