### ISSUE TITLE
issue while calling  functions.detect_face

### ISSUE THREAD

**Issue by sadimoodi** [serengil/deepface#282]
in your realtime.py, i wanted to change face detection from using opencv to using ssd, so i did the following:

cap = cv2.VideoCapture(source) #webcam

while(True):
	ret, img = cap.read()

	if img is None:
		break

	#cv2.namedWindow('img', cv2.WINDOW_FREERATIO)
	#cv2.setWindowProperty('img', cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
	img = cv2.resize(img, (1080,720))

	raw_img = img.copy()
	resolution = img.shape

	resolution_x = img.shape[1]; resolution_y = img.shape[0]

	if freeze == False:
		#gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
		#faces = face_cascade.detectMultiScale(gray, 1.3, 5, minSize=(60,60))
		_ , faces = functions.detect_face(img,detector_backend='ssd',enforce_detection=False,grayscale=True)
		faces = [faces]
		print(faces)

		if faces[0] ==[0,0,img.shape[0],img.shape[1]] :
			face_included_frames = 0

	else:
		faces = []

	detected_faces = []
	face_index = 0
	for (x,y,w,h) in faces:
		if w > 60 and w < 250: #discard small detected faces
notice that i am calling:
_ , faces = functions.detect_face(img,detector_backend='ssd',enforce_detection=False,grayscale=True)
i wanted to use your wrapper to test multiple face detection libraries, however, when my face is at the edge of the camera, i am getting this error:

detected_face = OpenCvWrapper.align_face(detector["eye_detector"], detected_face)
File "C:\Users\ali.khankan\AppData\Roaming\Python\Python38\site-packages\deepface\detectors\OpenCvWrapper.py", line 62, in align_face
detected_face_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #eye detector expects gray scale image
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-k1ohfcms\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-k1ohfcms\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by sadimoodi** [comment]
it turns out that your functions.preprocess_face in realtime.py returns an empty image if the face is detected at the top edge of the frame, so to fix this i added this condition in realtime.py:

#face recognition
																		
						try:
							if custom_face is not None:
								custom_face = functions.preprocess_face(img = custom_face, normalization = normalization,model_name = model_name, target_size = (input_shape_y, input_shape_x), enforce_detection = False, detector_backend = 'ssd',align=False)
						except:
							print ('After exception : ', custom_face)

**Comment by serengil** [comment]
this is going to be followed in issue 283
