### ISSUE TITLE
Suggestion, allow selection of face detection model from DeepFace.stream

### ISSUE THREAD

**Issue by sadimoodi** [serengil/deepface#283]
Thanks again for all of your efforts, I would like to suggest the following improvement to your DeepFace.stream function:
add a detector_backend = 'opencv' parameter just like in DeepFace.find function.
you are using opencv as a default inside realtime.py file but as you know opencv is throwing lots of false positives, I had to change the code to use ssd which improved my results significantly.

**Comment by serengil** [comment]
Sure. I can add it in the next release.

**Comment by serengil** [comment]
I just pushed the source code for optional detector backend argument.

I'm going to publish it in pip in the next release. You can clone the source code to have this feature now.
