### ISSUE TITLE
BUG: wrong file name while loading facenet512 model

### ISSUE THREAD

**Issue by sadimoodi** [serengil/deepface#284]
When you download facenet 512 model, you download it as facenet_weights.h5 but when you load it, you load as :
facenet512_weights.h5 which is resulting in an error (file not found, had to manually rename the file and i also lost the old facenet file (with 128 embeddings)

**Comment by serengil** [comment]
You are right! I fix this soon.

**Comment by serengil** [comment]
Fixed in 0.0.65
