### ISSUE TITLE
DeepFace.analyze

### ISSUE THREAD

**Issue by onlinehuazai** [serengil/deepface#290]
AttributeError: 'str' object has no attribute 'decode'

**Comment by serengil** [comment]
I need your deepface version, and input image as well to understand the problem.

**Comment by serengil** [comment]
enough information is not provided in this bug.

**Comment by razzaghi** [comment]
> AttributeError: 'str' object has no attribute 'decode'

I had the same problem, try this: pip install h5py==2.10.0 --force-reinstall
My problem fixed
