### ISSUE TITLE
Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.

### ISSUE THREAD

**Issue by onlinehuazai** [serengil/deepface#291]
How to set parameter GPU when using deepface

**Comment by serengil** [comment]
For example, 

`DeepFace.verify("img1.jpg", "img2.jpg", enforce_detection = False)`

Similarly this argument exists in other functions.

**Comment by onlinehuazai** [comment]
> For example,
> 
> `DeepFace.verify("img1.jpg", "img2.jpg", enforce_detection = False)`
> 
> Similarly this argument exists in other functions.

thank you! In addition, How to set parameter "GPU" when using deepface?
