### ISSUE TITLE
Ram requirement

### ISSUE THREAD

**Issue by ivanocj** [serengil/deepface#295]
I'm trying to run the above program on a Ubuntu 20.04 , Dual core Epyc, 1GiB ram VPS (oracle cloud free tier) however I'm getting OOM errors all the way...
I have set a linux swap file of 2GiB.

```
#!/usr/bin/python3
import json
import sys

from deepface import DeepFace

img = str(sys.argv[1])
attributes = ['age', 'gender', 'race', 'emotion']
demography = DeepFace.analyze(img, attributes)
formatted_json = json.dumps(demography, indent=4)
print(formatted_json) 
```

**Question:** what are the minimum CPU and RAM requirements for Deepface?

**Comment by serengil** [comment]
You need 10GB memory for analysis models.

**Comment by ivanocj** [comment]
@serengil , good news.... I just made it work with 1GiB of Ram and 4GiB of swap. 😃


![image](https://user-images.githubusercontent.com/75158/127052480-16a6a6a7-efc4-415a-a544-8bb5fd7d2ea9.png)
