### ISSUE TITLE
Error using 'Facenet512' for DeepFace.represent

### ISSUE THREAD

**Issue by anxueren8** [serengil/deepface#296]
```
model_name = "Facenet512"
model = DeepFace.build_model(model_name)
embedding = DeepFace.represent(img_path, model_name = model_name, model=model, detector_backend = 'mtcnn')
```

Hello, Sefik. I tried the above code to embed a face image but got the error as follows, the deepface version is 0.0.65.

```
ValueError                                Traceback (most recent call last)
<ipython-input-4-e28faa823373> in <module>
      1 model_name = "Facenet512"
----> 2 model = DeepFace.build_model(model_name)
      3 
      4 embedding_lists = [] # [name, path, vector]
      5 N = len(imgs_path)

~/Jay/deepface_deepbull/deepface/DeepFace.py in build_model(model_name)
     58                 return model
     59         else:
---> 60                 raise ValueError('Invalid model_name passed - {}'.format(model_name))
     61 
     62 def verify(img1_path, img2_path = '', model_name = 'VGG-Face', distance_metric = 'cosine', model = None, enforce_detection = True, detector_backend = 'mtcnn', align = True):

ValueError: Invalid model_name passed - Facenet512
```

I appreciate it if you can offer me help. 

Thank you,
Jie

**Comment by serengil** [comment]
what was your deepface version?

**Comment by serengil** [comment]
update the deepface. it seems that you are using a legacy version of deepface.

verify function's default detector_backend is mtcnn but it should be opencv in latest version. this shows that you are using out-dated version.

**Comment by anxueren8** [comment]
Sorry, 0.65 is not the latest verison?

**Comment by serengil** [comment]
0.0.65 is the latest

**Comment by anxueren8** [comment]
I used ***represent function** not ***verify function***,  and mtcnn for detection

**Comment by anxueren8** [comment]
> 0.0.65 is the latest

I used 0.0.65, but I got this error. The reason I'd like to use mtcnn is that it has a better performance.

**Comment by serengil** [comment]
You copied that line. It show that you are not using deepface 0.0.65.

` 62 def verify(img1_path, img2_path = '', model_name = 'VGG-Face', distance_metric = 'cosine', model = None, enforce_detection = True, detector_backend = 'mtcnn', align = True):`

**Comment by serengil** [comment]
could you run pip freeze command?

**Comment by anxueren8** [comment]
> could you run pip freeze command?

![image](https://user-images.githubusercontent.com/71525698/127187149-1f8c21da-728b-4194-b42c-767a41cc1e24.png)

**Comment by serengil** [comment]
That's very interesting. Could open this file: ~/Jay/deepface_deepbull/deepface/DeepFace.py

I need the lines before 60th line. If you copy it to here, it makes sense to understand the problem.
