### ISSUE TITLE
RetinaFace does BGR2RGB conversion itself but image is converted to RGB in deepface already

### ISSUE THREAD

**Issue by BastiSch** [serengil/deepface#297]
Line 18 in [deepface/deepface/detectors/RetinaFaceWrapper.py](https://github.com/serengil/deepface/blob/master/deepface/detectors/RetinaFaceWrapper.py#L18) reads
` img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) #retinaface expects RGB but OpenCV read BGR `
so does convert the BGR image to an RGB image, but RetinaFace does BGR2RGB conversion again in [retinaface/commons/preprocess.py line 33](https://github.com/serengil/retinaface/blob/master/retinaface/commons/preprocess.py#L33), which is called from [retinaface/RetinaFace line 75](https://github.com/serengil/retinaface/blob/master/retinaface/RetinaFace.py#L75), which is called in [deepface/deepface/detectors/RetinaFaceWrapper.py line 34](https://github.com/serengil/deepface/blob/master/deepface/detectors/RetinaFaceWrapper.py#L34)

I have to admit, I was not able to check, whether the model or the precalculated weights assume BGR or RGB but at least the comments in the sourcecode are misleading.

**Comment by serengil** [comment]
you're right. comment in the retinaface confuses. because bgr2rgb is not handled in the source code of retinaface.
