### ISSUE TITLE
Getting wrong distance for numpy array compare to direct image path

### ISSUE THREAD

**Issue by nbhupendra** [serengil/deepface#299]
def load_image_into_numpy_array(data):
    return np.array(Image.open(BytesIO(data)))

image1 = load_image_into_numpy_array(await file1.read())
 image2 = load_image_into_numpy_array(await file2.read())

result = DeepFace.verify(
            image1,
            image2,
            distance_metric=metrics[2], model_name=models[1], detector_backend=backends[0],enforce_detection = False)

vs

result = DeepFace.verify(
    image_path1,
    image_path2,
    distance_metric=metrics[2], model_name=models[1], detector_backend=backends[3])

Please suggest

**Comment by serengil** [comment]
verify function reads an image with opencv and it seems that Image and OpenCV read images in a different way. You need to compare the following pair.

img1 = cv2.imread(img_path)
img2 = load_image_into_numpy_array(await file1.read())
