### ISSUE TITLE
ImportError: cannot import name 'DeepFace'

### ISSUE THREAD

**Issue by pasa13142** [serengil/deepface#3]
Hello

I tried install from pypi and git clone but I got this error, even I create new enviroment, any idea ?

**Comment by serengil** [comment]
calling "pip install deepface" completed successfully?

**Comment by pasa13142** [comment]
Yeah, I created new env, pip install deepface completly, same error, then create another new env, clone repo and setup and same error again, 
It is ubuntu 16.04 by the way

**Comment by serengil** [comment]
interesting, error message is directly because of the installation. is this a virtual environment? you might activate the virtual environment first.

**Comment by pasa13142** [comment]
ahahaha yeah I did, yeah it is conda env. Even I didnt, when I apply setup.py, it have to setup itself on current env

**Comment by serengil** [comment]
should i understand that problem is solved?

**Comment by serengil** [comment]
btw, you can run "!pip install deepface" in the first line of the python program. this handles to install the current environment.

**Comment by pasa13142** [comment]
No it isnt but I return my old computer which runs well, sorry I was an hurry didnt explain problem well, I will edit tonight

**Comment by serengil** [comment]
1- call "activate" command in command prompt. If your virtual environment has name then you should call "activate your_virtual_env_name". For example, my env name is tensorflow, that's why
 I always call "activate tensorflow" before running anything.

2- call "pip install deepface". In this way, deepface will be installed to your virtual environment.

3- create a test.py and it just imports deepface: "from deepface import DeepFace"

4- call "python test.py"

**Comment by serengil** [comment]
This issue will be followed in the following issue: https://github.com/serengil/deepface/issues/5

**Comment by pasa13142** [comment]
Sorry I am little bit late :')

from deepface import DeepFace , works for me, thanks

**Comment by NhatNam041206** [comment]
Hi,
I got the same error when I run:  from deepface import DeepFace
I got this error: 
ImportError: cannot import name 'Deepface' from 'deepface'
I use window 10
-Pip version: 19.2.3
-Python: 3.7
-Tensorflow: 2.3.1
-Deepface: 0.0.40

--Thank For Replying--

**Comment by pavithra-28-dev** [comment]
cannot import deepface

**Comment by Suhas99ssp** [comment]
cannot import name 'Deepface' from 'deepface' (C:\Users\LENOVO\anaconda3\Lib\site-packages\deepface\__init__.py)
i got this error while importing the deepface moldel .
