### ISSUE TITLE
run api on python 3.8.3

### ISSUE THREAD

**Issue by Hatef-Rostamkhani** [serengil/deepface#30]
I try to run API on python 3,8,3 but occur error.
Can you fix the API error on Python 3.8.3?

error
File "api2.py", in <module>
graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

**Comment by serengil** [comment]
Please set dependent library versions tensorflow 1.9.0 and keras 2.2.0.

Could you share your versions for tensorflow and keras also?
