### ISSUE TITLE
Not able to convert detected face output as image or base64 image bytes

### ISSUE THREAD

**Issue by shafichoudhary** [serengil/deepface#301]
Dear Sefik,

The original image and detectedFace output both are numpy array with different dimensions. Both appears in pyplot too but when you try to save/create base64 bytes, detectedFace output save a blank image instead of detected face image.

Please suggest me how to achieve it.

from deepface import DeepFace
import matplotlib.pyplot as plt
import cv2
import codecs
import pickle
import base64

original_img = cv2.imread("dataset/img5.jpg")
face_detected_img = DeepFace.detectFace(original_img) ###this is numpy array
####### this works fine
plt.imshow(original_img)
plt.show()

#####this works fine
plt.imshow(face_detected_img)
plt.show()

####save original img, save original image
cv2.imwrite("orginal_new.jpg",original_img)

####save detected face img, save blank image
cv2.imwrite("detected_face_img.jpg",face_detected_img)

#####this generates original image
retval, buffer = cv2.imencode('.jpg', original_img)
pic_str = base64.b64encode(buffer)
pic_str_original = pic_str.decode()
print(pic_str_original)

#####but this does not generated detected face image , it generates blank image same as cv2.imwrite
retval, buffer = cv2.imencode('.jpg', face_detected_img)
pic_str = base64.b64encode(buffer)
pic_str_detectedface = pic_str.decode()
print(pic_str_detectedface)

#####I tried using codec as suggested by you in the last email but it is having same issue.
img_base64_string = codecs.encode(pickle.dumps(face_detected_img , protocol=pickle.HIGHEST_PROTOCOL), "base64").decode('latin1')
print(img_base64_string)

**Comment by serengil** [comment]
I can encode - decode and restore as shown below:

```python
from deepface import DeepFace
import matplotlib.pyplot as plt
import base64
import numpy as np
import cv2

img_path = "deepface/tests/dataset/img11.jpg"

#-----------

detected_face = DeepFace.detectFace(img_path, detector_backend = "opencv",enforce_detection = True, align = True)
detected_face_shape = detected_face.shape

detected_face = np.ascontiguousarray(detected_face, dtype=np.float64)

#-----------

detected_face_encoded = base64.b64encode(detected_face)

print(detected_face_encoded[0:30])

detected_face_decoded = base64.decodebytes(detected_face_encoded)

detected_face_decoded_numpy = np.frombuffer(detected_face_decoded, dtype=np.float64)
detected_face_decoded_numpy = detected_face_decoded_numpy.reshape(detected_face_shape)

plt.imshow(detected_face_decoded_numpy)
plt.show()

#------------

cv2.imwrite("detected_face_decoded_numpy.jpg", (detected_face_decoded_numpy * 255)[:, :, ::-1])
```
