### ISSUE TITLE
Regarding DeepFace.detectFace

### ISSUE THREAD

**Issue by Jeba-create** [serengil/deepface#302]
Thanks for such a great work.

When i execute the code, I had come across two problems

1. The first one is, when i used this for face detection and if i set align=False, the following error is generated 

detected_face = DeepFace.detectFace(image, detector_backend = backends[4],enforce_detection = False, align = False)
TypeError: detectFace() got an unexpected keyword argument 'align'

2. The next one is I want to check if there exists face, i think facial region is an empty array in the absence of face. so, if i could display the region, i can skip that image and move to the next one. But here if there is no face in an image, the whole execution is halted. I have set "enforce_detection = False" and mention two output attributes, but it throws an error as mentioned below

detected_face,region = DeepFace.detectFace(image, detector_backend = backends[1],enforce_detection = False)
ValueError: too many values to unpack (expected 2)

But , when i look inside the code , there is an argument align and there are two output arguments as well

def detect_face(img, detector_backend = 'opencv', grayscale = False, enforce_detection = True, align = True):

	img_region = [0, 0, img.shape[0], img.shape[1]]

	#detector stored in a global variable in FaceDetector object.
	#this call should be completed very fast because it will return found in memory
	#it will not build face detector model in each call (consider for loops)
	face_detector = FaceDetector.build_model(detector_backend)

	detected_face, img_region = FaceDetector.detect_face(face_detector, detector_backend, img, align)

	if (isinstance(detected_face, np.ndarray)):
		return detected_face, img_region
	else:
		if detected_face == None:
			if enforce_detection != True:
			  return img, img_region
			else:
			  raise ValueError("Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.")

Please let me know if i had gone wrong. Thanks in advance

**Comment by serengil** [comment]
1- Because there is not alignment argument in the detectFace function. It was applying alignment by default. Now, I added this argument in the source code. You can clone the latest code to use it. I'm going to publish it in pip in the next couple of days.

2- detectFace returns just face, it won't return region. You should set the enforce_detection to True and check it with try - catch

```python
try:
    detected_face = DeepFace.detectFace(img_path, detector_backend = "retinaface",enforce_detection = True, align = False)
except:
    print("No face found")
```
