### ISSUE TITLE
[Bug] alignment_procedure() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by robonetphy** [serengil/deepface#303]
I am installing deepface on colab using following command:
              
      !pip install deepface

and when I try to run code:

      from deepface import DeepFace
      from deepface.basemodels import Facenet
      from deepface.commons import functions
      embedding = DeepFace.represent(img_path, model_name = 'Facenet', detector_backend = 'retinaface')
      
It's giving me following problem:
![image](https://user-images.githubusercontent.com/23169768/127780117-0304f279-d168-4824-9d5b-ee0b48170304.png)

But, it's working properly when I install 

    !pip install deepface==0.0.63

**Comment by serengil** [comment]
Oke, I understood the problem. This new argument added in retinaface because of a bug. Even though retinaface code was updated, it was not put to pip. Now, it is up-to-date in pip. Please update retinaface requirement to 0.0.5.
