### ISSUE TITLE
smallest distance issue in deepFace.find

### ISSUE THREAD

**Issue by fizamurtaza** [serengil/deepface#304]
I am using two images [Img78.jpg and Img80.jpg] to compare using DeepFace.verify and I am getting following result:
{'verified': True, 'distance': 0.34921315852571366, 'max_threshold_to_verify': 0.4, 'model': 'VGG-Face', 'similarity_metric': 'cosine'}

but when I use DeepFace.find for Img78.jpg it is giving me minimum distance with another image with distance= 0.3923993458579276 which is greater than the distance with Img80.jpg for which the distance was 0.3492. 

so my question is why DeepFace.find is not picking the image with the minimum distance?

**Comment by fizamurtaza** [comment]
![img80](https://user-images.githubusercontent.com/25634081/127819894-712bd299-67aa-49e7-af54-6f0ebe7f54a6.jpg)
![img78](https://user-images.githubusercontent.com/25634081/127819899-6c6154ee-db13-436e-8bb0-137f912ea1f9.jpg)

**Comment by fizamurtaza** [comment]
Even this issue is same with Img57 and Img58 given in the dataset folder
![img58](https://user-images.githubusercontent.com/25634081/127822385-ae18e667-8951-4b44-ae42-aa02db996b81.jpg)

**Comment by serengil** [comment]
seems a probably bug

**Comment by fizamurtaza** [comment]
how it can be corrected?

**Comment by serengil** [comment]
I'm going to study this tonight.

**Comment by fizamurtaza** [comment]
> I'm going to study this tonight.

Thank you @serengil

**Comment by serengil** [comment]
I tested it in my environment and it works!

Are you seeing a warning like "WARNING: Representations for images in  deepface/tests/dataset  folder were previously stored in  representations_facenet.pkl". Please delete that .pkl file and run find function again. That might be the reason of your trouble.
