### ISSUE TITLE
deployment to linux and handling of Pkl in distributed envirnonment 

### ISSUE THREAD

**Issue by shafichoudhary** [serengil/deepface#306]
Dear Serengil,

What are your recommendation for alternative ways of Pkl file, as there will be inconsistencies if we use pkl file in ditributed environment?

Secondly , can please brief or share any link for the deployment of this in higher linux environment?

Many Thanks,

**Comment by serengil** [comment]
if distributed environments have same pandas version, then pkl files should not cause any problem, should it?

unfortunately, I don't have any experience about linux.

**Comment by shafichoudhary** [comment]
> if distributed environments have same pandas version, then pkl files should not cause any problem, should it?
> 
> unfortunately, I don't have any experience about linux.
What I mean is :
Let say I am appending representation for new image in the existing pkl file. so In case new image appended in node 1 , will not have the same in node 2. so In case find function of node 2 ran ...... I will not be able to find the match . So either pickle file is stored at some remote location as common SFTP for both nodes or there can a DB which does this job so both node can be connected to the same DB.

**Comment by serengil** [comment]
that is hard to implement but we can add an argument to discard pkl files. You can set that argument to create pkl from scratch.

**Comment by serengil** [comment]
You might mount the folder among the distributed servers. In this way, they all read the same pkl file?

**Comment by serengil** [comment]
I am closing this issue because this is not going to handled in the framework side.
