### ISSUE TITLE
Deepface verify on LFW- not working on other models and detectors than 'ArcFace' with 'opencv'

### ISSUE THREAD

**Issue by Kamil-Rajewski** [serengil/deepface#309]
Hey,
I would like to compare the metrics for all of the models, detectors and distance metric available on DeepFace framework on LFW dataset. The problem is, that my code is working only on ArcFace and opencv with the default distance metric. The source code is based on this video: https://www.youtube.com/watch?v=9fT-9TFjeDQ.

Attached sample of errors for mtcnn and ssd detectors on Arcface. Also attacked colab link - you can edit it.

![mtcnn](https://user-images.githubusercontent.com/42155631/128337786-2a03cc50-0a55-49c2-bc7d-15fdb7d9c3f6.PNG)
![ssd](https://user-images.githubusercontent.com/42155631/128337789-f26461e5-7854-41fe-b688-cf1d4c15309f.PNG)

I will appreciate your help :)

link: https://colab.research.google.com/drive/1u4AA0HOSG1gezsc2LyG4dYWhCokxW4Dr?usp=sharing

**Comment by serengil** [comment]
what was your tf version?

**Comment by serengil** [comment]
It seems that you are using tf 2.5 in the colab. Could you downgrade to 2.2.0? That might be a tf version based trouble.

**Comment by Kamil-Rajewski** [comment]
> what was your tf version?
So I changed the version of tf to 2.20, and there is still the same problem. If you want, you can comment and also edit the code in colab.

**Comment by serengil** [comment]
Oke, it seems a probably bug. I'm going to study it tonight or tomorrow. I'll inform you here.

**Comment by serengil** [comment]
I just pushed an update to the code repo. You can pull the latest code to have the fixed code. I'm also going to publish it on pip in the next couple of days.
