### ISSUE TITLE
Flask API with gunicorn on multi-thread and multi-worker mode

### ISSUE THREAD

**Issue by NISH1001** [serengil/deepface#31]
I created a simple (bare minimum) API server in Flask. It runs smoothly with the default TF graph.
However, I don't seem to make it work when number of threads is greater than 1.
```bash
AttributeError: '_thread._local' object has no attribute 'value'
```
This error is seen with following gunicorn configuration:
```bash
gunicorn --bind 0.0.0.0:$PORT --threads=2 --workers=1  app.app:app
```

Now, when worker is bumped up, the server just freezes indefinitely without any response.
```bash
gunicorn --bind 0.0.0.0:$PORT --threads=1 --workers=2  app.app:app --timeout 120 --preload  --timeout 120
```
I know it's an issue with TF session and threads. But, has anyone got it to work?

Also, I have loaded the model within the same default graph.

**Comment by serengil** [comment]
what is your tensorflow and keras versions?

could you try this for tf 1.9.0 and keras 2.2.0?

**Comment by NISH1001** [comment]
I am using the latest versions: 2.1.0 and 2.3.1 
Okay. I will try downgrading TF. There might be issues with new TF 2.

**Comment by serengil** [comment]
It seems that the new TF has some issues. Please confirm that you and me have same versions.

tensorflow==1.9.0
keras==2.2.0

**Comment by NISH1001** [comment]
I think tensorflow==1.9.0 isn't available.
I tried:
keras==2.2.0
tensorflow==1.5.3

However, `keras_applications` will have few issues something like:
```bash
AttributeError: module 'keras_applications' has no attribute 'set_keras_submodules'
```
I will try to see what version is good to go to solve the threading issue and update here...

**Comment by serengil** [comment]
tf 1.9.0 seems to be existing here: https://pypi.org/project/tensorflow/1.9.0/

Did you call "pip install tensorflow==1.9.0"

**Comment by NISH1001** [comment]
Yup. 1.9.0 cannot be found.
The threading issue seems to be resolved with the following version:
```
tensorflow==1.15.3
keras==2.2.4
```
with `gunicorn --bind 0.0.0.0:$PORT --threads=2 --workers=1  app.app:app`

Now, bumping up the number of workers will freeze the server. Not sure if it's the problem with gunicorn itself.

**Comment by NISH1001** [comment]
Nevertheless, thanks for this project. It's easy to use. There seems to be a few places that need improvement. I might as well send a PR. :)

**Comment by serengil** [comment]
I should not change status of this issue?

**Comment by NISH1001** [comment]
I am not sure. The whole server, when running gunicorn in preloading mode (with `--preload` options), gets frozen. That might be issue with gunicorn and TF. I even tried using gevent.

Right now. the threading issue is solved. So, this issue can be closed. It was definitely a versinong issue with TF.

**Comment by serengil** [comment]
thank you very much.
