### ISSUE TITLE
Implementation of face detector returning many face pictures

### ISSUE THREAD

**Issue by xddun** [serengil/deepface#310]
hello，thank you for your contribution !
I have a few questions：
(1)There are many faces in one picture, _DeepFace.detectFace_ return one of them,  is there an interface to solve this requirement?
(2)How to keep the model fixed in GPU memory? The model and its parameters are in GPU memory can save some computing time.

**Comment by serengil** [comment]
Handling multiple faces is out-of-scope of the library but you can still apply face detection for many faces as shown below.

```python
from deepface.detectors import FaceDetector
import cv2 
img = cv2.imread("img.jpg")
detector_name = "opencv" #ssd, mtcnn, dlib, retinaface
detector = FaceDetector.build_model(detector_name)
resp = FaceDetector.detect_faces(detector, detector_name, img)
```

If you install tensorflow-gpu before installing deepface, then it is going to run on gpu and it will be faster

**Comment by shafichoudhary** [comment]
For using GPU , In case I want to use deepface package as python package
instead of library, then how I should configure tensor flow GPU?

**Comment by serengil** [comment]
Install the packages respectively.

```shell
pip install tensorflow-gpu
pip install deepface 
```
