### ISSUE TITLE
i am using Rtx 3090 24 GB RAM the DeepFace  utilize all the memmory of gpu how can i control its utilization

### ISSUE THREAD

**Issue by Uzair1947** [serengil/deepface#315]

**Comment by serengil** [comment]
Especially analyze method requires many complex models. unfortunately, nothing to do. I recommend you to use cpu.

**Comment by Uzair1947** [comment]
ok  thanks how can I shift the load to the CPU

**Comment by serengil** [comment]
import os
os.environ["CUDA_VISIBLE_DEVICES"]=""
#or
os.environ["CUDA_VISIBLE_DEVICES"]="-1"

**Comment by 12bitmisfit** [comment]
I could be wrong but I think by default allocates all available GPU memory.

This worked for me:
```
import tensorflow as tf
tf.config.set_visible_devices([], 'GPU')
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
```

**Comment by zuroh** [comment]
> I could be wrong but I think tensorflow by default allocates all available GPU memory.
> 
> This worked for me:
> 
> ```
> import tensorflow as tf
> tf.config.set_visible_devices([], 'GPU')
> gpus = tf.config.experimental.list_physical_devices('GPU')
> for gpu in gpus:
>     tf.config.experimental.set_memory_growth(gpu, True)
> ```

Thanks for this, I've seen other projects where tensorflow allocates all available memory as well, however when running your code deepface ended up not using gpu at all. I made just a small tweak to your code to get deepface to use gpu but not allocate all available memory:

`import tensorflow as tf


gpus = tf.config.experimental.list_physical_devices('GPU')
tf.config.set_visible_devices(gpus, 'GPU')
for gpu in gpus:
    print(gpu)
    tf.config.experimental.set_memory_growth(gpu, True)`

**Comment by zhaoshenhao** [comment]
I got same issue. I used a dumb solution: multiprocessing (not multithreading). I setup **N** workers and distribute the images via a Managed queue.
