### ISSUE TITLE
Ensemble-Face-Recognition

### ISSUE THREAD

**Issue by khiempg** [serengil/deepface#317]
Hi Sir,
I have a question about Ensemble-Face-Recognition.py
I think there is some problem in current source code of Ensemble-Face-Recognition.py:
     1. There are only 8 features, can not apply to current lib of deepface which use 11 features
        models = ['VGG-Face', 'Facenet', 'OpenFace', 'DeepFace']
        metrics = ['cosine', 'euclidean_l2']

     2. There is bug in this line:
       File "Ensemble-Face-Recognition.py", line 221, in <module>
       cm = confusion_matrix(y_test, prediction_classes)
       NameError: name 'prediction_classes' is not defined
I think this file Ensemble-Face-Recognition.py is out of date, could you update please.

Thank you in advance.

**Comment by serengil** [comment]
I plan to add new coming models to the ensembe model soon.

**Comment by khiempg** [comment]
That is great new, we are looking for new model of Ensembe. Can you tell us when you can release it ?
I have tested current Ensemble model, it worked well with images in dataset, but when I tested with other image (not in dataset, asian face ...), results was not good, so I hope you can release new version soon

**Comment by serengil** [comment]
I might not release it short term :/
