### ISSUE TITLE
mp4 support

### ISSUE THREAD

**Issue by Tortoise17** [serengil/deepface#320]
Does deepface support `mp4` as well or only` jpg `is possible?
if mp4, can I ask you how to take that import?

**Comment by serengil** [comment]
stream function has source input argument and its default value is 0. This means that it will access your 0 index web cam. You can set a mp4 file in this argument as well.

**Comment by Tortoise17** [comment]
That is a great feature, can you just give me example. I am just new with it and I am trying to export feature embeddings directly from mp4. using below piece. 
```

from deepface import DeepFace
import cv2
from google.colab.patches import cv2_imshow

#backends = ['opencv', 'ssd', 'dlib', 'mtcnn']
backends = ['mtcnn']
for backend in backends:
  #face detection and alignment
  detected_face = DeepFace.detectFace("1.jpg", detector_backend = backend)
  
  print(detected_face)
  print(detected_face.shape)

  im = cv2.cvtColor(detected_face * 255, cv2.COLOR_BGR2RGB)
  #cv2.imshow("image", im)
  cv2_imshow(im)
```

**Comment by serengil** [comment]
Unfortunately, you cannot extract embeddings from a video. Stream function applies real time analysis.

DeepFace.stream(source = "1.mp4")
