### ISSUE TITLE
How to analyze image with multiple face?

### ISSUE THREAD

**Issue by irvanseptiar** [serengil/deepface#321]
Hi serengil, thank you very much for the very helpful github page. I'm doing some exploration, I'm interested in doing analysis for a photo with multiple faces. How to do that using DeepFace?

Thank you so much

**Comment by serengil** [comment]
Hello, the following code snippet will help you

```python
from deepface import DeepFace
from retinaface import RetinaFace
import matplotlib.pyplot as plt

faces = RetinaFace.extract_faces("2.jpeg")

print("There are ", len(faces), " faces in the image")

for face in faces:
    plt.imshow(face)
    plt.axis('off')
    plt.show()
    
    obj = DeepFace.analyze(face, detector_backend = 'skip')
    print(obj)
    print("------------------------")
```

**Comment by irvanseptiar** [comment]
Thank you so much!

**Comment by AbigailWoolley** [comment]
Hello Serengil, just want to find out if there is a specific reason you used RetinaFace for the face extraction bit?

**Comment by woody0105** [comment]
Hello @serengil 

Thank you for sharing the code snippet. 
It processes detected faces one by one, which means processing time will increase linearly with the number of faces. Is multi threading supported with this model?
