### ISSUE TITLE
Open more feature PR's at once?

### ISSUE THREAD

**Issue by RoelofRuis** [serengil/deepface#329]
Dear Sefik,

In the past week I have built some more features which I would like to propose for merging:
- Add a detection mode that allows skipping a face
- Download the model files in a uniform way (and with optional checksum)
- Refactor the analysis models so they are pluggable (you can easily add a new one without having to edit the DeepFace.analysis function itself)

All features should not change the current behavior of the library (except in very minor ways where indicated)

These features are all built upon the currently open PR (https://github.com/serengil/deepface/pull/325) and all build upon each other in a certain order.

My question is: Shall I open all PR's already and indicate the order in which they should be reviewed or should I open them one by one as the previous one gets merged?

Cheers!

**Comment by serengil** [comment]
one by one is better buddy

thank you for your all support in advance
