### ISSUE TITLE
Match 1:N

### ISSUE THREAD

**Issue by dan-developer** [serengil/deepface#33]
I am developing an application where the user at the time of registration registers a photo of the face for later verification.
When the user identifies himself I want to match his face with all registered faces and identify "this user is the ID ...".
How to do this with the deep face?

**Comment by serengil** [comment]
1- store registration pictures in a folder (e.g. c:\users\dan\desktop\db).

Suppose that db folder has 3 identities: 1.jpg, 2.jpg, 3.jpg

2- when an user comes your system, take his/her current photo. Suppose that the current photo is tmp.jpg

3- build a for loop with the number of identities in your db folder. Call DeepFace for each photo in your db.

```
for i in range(0, 3):
   obj = DeepFace.verify("tmp.jpg", "%s.jpg" % (str(i)))
   if obj["verified"] == True:
      print("This is identity", i)
      break
```

I might add a find function to handle this operation in a simpler way.

**Comment by dan-developer** [comment]
Thanks for your quick reply. : D

Okay, I can loop it, so how much is it expensive for the CPU? Taking into account that the user does not want to wait too long.

Another question, taking advantage of the same context: is there a way to pre-train or pre-process (I don't know exactly the term) so that when making this loop I pass not the image, but a string?
For example, see this project https://github.com/ageitgey/face_recognition the images are nothing but an array of face information.

P.S .: I don't know exactly the terms because I'm trying to find a solution, I don't know if recognition is for authentication and identification, I'm lost.

**Comment by serengil** [comment]
Nope. all pre-process steps handled in the background of deepface.

The code block I previously shared builds a complex face recognition model in each iteration. This is costly. On the other hand, prediction is easy.

If you call deepface as illustrated below, then it will build a complex face recognition model once. This speeds your operations up dramatically.

```
obj = DeepFace.verify([
["tmp.jpg", "1.jpg"],
["tmp.jpg", "2.jpg"],
["tmp.jpg", "3.jpg"]
])
```

Then, obj variable is a list. You should check its verified and distance values.

**Comment by dan-developer** [comment]
Okay, I tried here.

I got the result:
```python
{'pair_1': {'distance': 0.1356278657913208,
            'max_threshold_to_verify': 0.4,
            'model': 'VGG-Face',
            'similarity_metric': 'cosine',
            'verified': True}}
``` 

Which of these keys do I use to tell if it's the same person or not?

**Comment by serengil** [comment]
verified. If it is true, then the both images are same person.

**Comment by dan-developer** [comment]
Thank you for your time and congratulations on the project. I will test everything you showed me.

**Comment by serengil** [comment]
you're welcome. do not hesitate to ask questions if you have any problem. 

PS: you can support this project by starring the repo :)

**Comment by dan-developer** [comment]
I star the project now :)

If your project fits mine, I'll pay you a lot of beers haha Hugs

**Comment by serengil** [comment]
As I mentioned, I can modify the framework based on the requirements. Inform me if you need anything.

**Comment by malahmadi1** [comment]
I have the same question above, I'm building an attendance system but it takes an intensive amount of time for matching each image with the images in my dataset. Is there a way where I can speed up the process? maybe by saving the images as numpy and pass it to verify? 

Thank you
