### ISSUE TITLE
DEEPFACE_HOME ?

### ISSUE THREAD

**Issue by apiszcz** [serengil/deepface#330]
I set the DEEPFACE_HOME environment variable set and have the .deepface/weights path with the h5 files, however deepface appears to want to connect to download the weights. Is there another parameter that needs to be set?
Thank you.

**Comment by serengil** [comment]
I am using the default path  ~/.deepface/weights as deepface home.

**Comment by apiszcz** [comment]
Thank you, my error, sorry.
