### ISSUE TITLE
Training FaceNet and mtcn on my own database to be used in real a time face recognition task, detecting and recognizing multiple faces in real time face recognition.

### ISSUE THREAD

**Issue by adhamgemi** [serengil/deepface#334]
Hi serengil, Awesome Work Really. It is so beautiful. I just have couple of questions. 1-I have a database folder with my own people and I want to train FaceNet and mtcn on them to be used later in a real time face recognition task so How can I train FaceNet and mtcn on that cuz the model get things mixed up and do so many mismatches between the people in that folder when I use it in real time task ?! 2-I know it is out of project'scope but is it possible to detect and recognize multiple faces in real time and if so how can i do that

**Comment by serengil** [comment]
stream function already does that!
