### ISSUE TITLE
new version supporting Configure models path via ENV variable

### ISSUE THREAD

**Issue by abdelwahebmoalla** [serengil/deepface#338]
Hey man,
Thank you for the awesome library.
I was wondering about the release date of this PR: https://github.com/serengil/deepface/pull/323

**Comment by serengil** [comment]
It seems that I forget to publish that release. I can publish it tonight, or tomorrow in the worst case.

**Comment by abdelwahebmoalla** [comment]
Hey,

Still waiting for the new version.

Thank you in advance

**Comment by cpatrickalves** [comment]
Hi there, 

Is the version with the model path from env available?
