### ISSUE TITLE
Stereo Video

### ISSUE THREAD

**Issue by santicomp2014** [serengil/deepface#339]
Hi, I'm new to this model, and I was wondering if there is some kind of stereo model that could be used for example with OAK-D or D435 cameras.

I used F455 as a face recognition platform, but since Intel is discontinuing this product in February 2022, I want to find another model to replace this hardware.

Do you think this model could be adapted with stereo data, or is there anything with this purpose? especially antispoofing since it could be easily faked with a cell phone if no depth information is available.

I found the F455 uses these models, most of them are new to me.
![Resnet](https://user-images.githubusercontent.com/9823189/133450577-bfc005fe-5b55-4d15-aece-477a49a52340.PNG)

Thanks

**Comment by serengil** [comment]
deepface comes with stream function and it is totally fine to use the library with stereo data.

**Comment by santicomp2014** [comment]
Thank you very much for the reply.
I will test it out.

Thanks again.
