### ISSUE TITLE
Using DeepFace.Verify for multiple images in a list

### ISSUE THREAD

**Issue by dlee0324** [serengil/deepface#340]
This question is a follow up to the closed post #257. I'm trying to use DeepFace.Verify for multiple images in a list. While the list that manually codes the image files works, the list that's generated through automatic pulling of the image file names does not:

`fn = 'img_1.jpg'` 
`otherimg = glob.glob("*.jpg")`
`otherimg.remove(fn)`
`dataset = [list(elem) for elem in list(zip(np.repeat(fn, len(otherimg)), otherimg))]`

The above code generates a **dataset** with the following elements:
`print(dataset)`
`[['img_1.jpg', 'img_0.jpg'], ['img_1.jpg', 'img_2.jpg'], ['img_1.jpg', 'img_3.jpg']]`

I created another list, **dataset1**, by manually typing the file names rather than using the automatic approach above:
`dataset1 = [
   ['img_1.jpg', 'img_0.jpg'], 
   ['img_1.jpg', 'img_2.jpg'], 
   ['img_1.jpg', 'img_3.jpg']  
]`

The `print(dataset1)` gives the same elements as **dataset**: 
`[['img_1.jpg', 'img_0.jpg'], ['img_1.jpg', 'img_2.jpg'], ['img_1.jpg', 'img_3.jpg']]`. 

And `print(dataset==dataset1)` gives me TRUE, which confirms that the two lists are identical. 

But when I run DeepFace.Verify using **dataset**, it gives me an error, while running it using **dataset1** runs successfully. The error I get when running it with **dataset** is shown below:

`result = DeepFace.verify(dataset, enforce_detection=False, model_name='OpenFace', distance_metric='euclidean_l2')`

> Verification:   0%|          | 0/3 [00:00<?, ?it/s]
> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-39-0cc57d109056> in <module>()
>       6 print(dataset1)
>       7 print(dataset==dataset1)
> ----> 8 result = DeepFace.verify(dataset, enforce_detection=False, model_name='OpenFace', distance_metric='euclidean_l2')
>       9 print(result)
> 
> 3 frames
> /usr/local/lib/python3.7/dist-packages/deepface/commons/functions.py in detect_face(img, detector_backend, grayscale, enforce_detection, align)
>      87 def detect_face(img, detector_backend = 'opencv', grayscale = False, enforce_detection = True, align = True):
>      88 
> ---> 89         img_region = [0, 0, img.shape[0], img.shape[1]]
>      90 
>      91         #----------------------------------------------
> 
> IndexError: tuple index out of range

Below shows the successful result when running it with **dataset1**:

`result1 = DeepFace.verify(dataset1, enforce_detection=False, model_name='OpenFace', distance_metric='euclidean_l2')`
`print(result1)`
`Verification: 100%|██████████| 3/3 [00:00<00:00,  6.93it/s]{'pair_1': {'verified': False, 'distance': 0.757963171275603, 'max_threshold_to_verify': 0.55, 'model': 'OpenFace', 'similarity_metric': 'euclidean_l2'}, 'pair_2': {'verified': True, 'distance': 0.5088304125698733, 'max_threshold_to_verify': 0.55, 'model': 'OpenFace', 'similarity_metric': 'euclidean_l2'}, 'pair_3': {'verified': False, 'distance': 1.2137577175804064, 'max_threshold_to_verify': 0.55, 'model': 'OpenFace', 'similarity_metric': 'euclidean_l2'}}`

Is there a way to use the automated list with the DeepFace.Verify?

**Comment by serengil** [comment]
I recommend you to use os.walk

```
pairs = []
for dirpath, dirnames, filenames in os.walk("deepface/tests/dataset/"):
    for filename in filenames:
        if '.jpg' in filename:
            file = dirpath+filename
            
            pair = [fn, file]
            pairs.append(pair)

results = DeepFace.verify(pairs)
```
