### ISSUE TITLE
speed up with gpu

### ISSUE THREAD

**Issue by 523997931** [serengil/deepface#347]
Hi, I try to use the find function to test the arcface precision in LFW dataset， but I find it's too slow, I don't know why ,at first i find I use CPU to compute, so I install tensorflow-gpu and deepface again, but I find it also slow, even slower.
I find when the process start ,the memory is occupied, but the utilization is always 0, it seems that it just use the memory without computing with gpu.
I use the list of input images as the parameter of function, and I use CUDA_VISIBLE_DEVICES=.... to start the python program.

**Comment by serengil** [comment]
cuda visible devices is enough to set your gpu. your gpu installation is oke? can you run different tensorflow models with your installed gpu?

**Comment by serengil** [comment]
closed due to inactivity.

**Comment by lujx1024** [comment]
sorry to bother you angin by reopening this issue, but I tried to install `tensorflow-gpu` before Iinstall `deepface`,but still downloaded the `tensorflow` cpu version as its dependence, and set `CUDA_VISIBLE_DEVICES `not worked either, so What should I do to fix this problem,I could really use some advise,please!

**Comment by GoutamKelam** [comment]
I know I am probably too late to answer your issue @lujx1024 
In order to stop deepface to install the tensorflow try using the following command
 `pip install deepface --no-deps`

**Comment by arsenal2006** [comment]
I know this is an old issue, but tensorflow-gpu doesn't exist anymore. Anyway, my deepface doesn't use my GPU, is there any way to make it? Thanks

**Comment by arijitamin** [comment]
Hi guys! Any updates to this thread?

**Comment by CrasCris** [comment]
@arijitamin :c
