### ISSUE TITLE
Deepface.verify with vector embedding?

### ISSUE THREAD

**Issue by Kick28** [serengil/deepface#348]
Hello! Thank you for your work and interesting library, but I have a question.

I already know that storing photo as vector embedding is implemented by using Deepface.represent. But is It possible to use vector embedding as one of the argument in Deepface.verify?
Thanks in advance for your reply.

**Comment by serengil** [comment]
Nope. But this feature might be interesting. I can add it in the next release.

**Comment by Kick28** [comment]
Good, thanks!

**Comment by serengil** [comment]
BTW, if you have the embeddings already, you can verify the pair as shown below

```python
from deepface.commons import distance as dst

distance = dst.findEuclideanDistance(img1_representation, img2_representation)
threshold = dst.findThreshold(model_name, 'euclidean')

if distance <= threshold:
	identified = True
else:
	identified = False
```

**Comment by Kick28** [comment]
That helped a lot, thanks!

**Comment by abhishekbiswas772** [comment]
This Method is good, but I am have encountered an issue with occasional mismatches. Specifically, the system sometimes incorrectly identifies a person as another.

def compare_single_encoding(embedding_string, item, each_emp_code):
		normalize_distance_embedding = dst.l2_normalize(embedding_string)
		normalize_distance_item = dst.l2_normalize(item)
		distance = dst.findEuclideanDistance(normalize_distance_embedding, normalize_distance_item)
		threshold = dst.findThreshold(Constants.DEEPFACE_FACE_RECOGNIZER_MODEL, Constants.METRIC_USED)
		is_found = distance <= threshold
		data = {"match_status": is_found}
		if is_found:
			data["employee_code"] = each_emp_code
		return data

**Comment by spoodzxs2345** [comment]
> BTW, if you have the embeddings already, you can verify the pair as shown below
> 
> ```python
> from deepface.commons import distance as dst
> 
> distance = dst.findEuclideanDistance(img1_representation, img2_representation)
> threshold = dst.findThreshold(model_name, 'euclidean')
> 
> if distance <= threshold:
> 	identified = True
> else:
> 	identified = False
> ```

`from deepface.commons import distance as dst` is not working

**Comment by koren12122** [comment]
"from deepface.commons import distance as dst" also not working for me

**Comment by serengil** [comment]
It is retired, use this instead: `from deepface.modules.verification import find_euclidean_distance`

**Comment by frodriguez-hu** [comment]
@serengil comparing embeddings with that is not returning the same distance as the `verify` method when I try it. Shouldn't do that?

**Comment by serengil** [comment]
@frodriguez-hu they should behave same, if you share your input image pair, i can check them

**Comment by frodriguez-hu** [comment]
@serengil 

I was doing this to generate the encodings that were different than the `verify`

```
embedding_objsFirst = DeepFace.represent(
  img_path = "feli1.jpeg",
  anti_spoofing = True,
)

embedding_objsSecond = DeepFace.represent(
  img_path = "tincho1.jpg",
  anti_spoofing = True,
)

embedding_first = embedding_objsFirst[0]['embedding']
embedding_second = embedding_objsSecond[0]['embedding']

distance = find_euclidean_distance(embedding_first, embedding_second)
```
![feli1](https://github.com/user-attachments/assets/765d40dd-8955-4a32-a54e-d1612ee8efe1)

![feli2](https://github.com/user-attachments/assets/0b7574d6-73ab-4edc-8f40-fac36553864a)

**Comment by serengil** [comment]
Because two faces are detected in this image. I highlighted the detected facial areas with yellow. If you use different detector than opencv, then this will be sorted.

<img width="417" alt="Screenshot 2024-09-20 at 20 23 20" src="https://github.com/user-attachments/assets/6f09ff14-fc4a-4840-9f8f-a66a38877ec8">

**Comment by frodriguez-hu** [comment]
@serengil And how can we address that? to detect just one or to detect just the right one?

**Comment by Lamarcke** [comment]
> @serengil And how can we address that? to detect just one or to detect just the right one?

You could try using the "retinaface" detector backend. Just pass it as argument for `detector_backend` in `DeepFace.represent`

Also, `DeepFace.verify` accepts vector embeddings as arguments for the images.

Just make sure both image's embeddings were generated with the same model (the `model_name` in `DeepFace.represent`).

See "Face Detection and Alignment" in the README for more info.
