### ISSUE TITLE
InceptionResNetV2 to InceptionResNetV1

### ISSUE THREAD

**Issue by nandocg** [serengil/deepface#349]
Hello! thank you for your works. 

I saw the InceptionResNetV2 function in basemodels/Facenet.py and I think the architecture is based on InceptionResNetV1 (from the "Reduction-A" block's architecture). I think this would make a confusion. Or am I wrong?

Sorry for my bad English

**Comment by serengil** [comment]
I cloned that model from here: https://github.com/davidsandberg/facenet/

To be honest, I do not know the difference between v1 and v2.
