### ISSUE TITLE
Curiosity about vgg_face_weights.h5

### ISSUE THREAD

**Issue by dan-developer** [serengil/deepface#35]
For each model I ran a specific file was downloaded, for example vgg_face_weights.h5, VGGFace2_DeepFace_weights_val-0.9034.h5.zip, facenet_weights.h5, etc ...
What are these files for?
Do I need to update them?

Sorry, I'm new to this area, I don't have any knowledge.
Thanks again.

**Comment by serengil** [comment]
these are the pre-trained weights of different face recognition models. When you installed them once, no need to update them.
