### ISSUE TITLE
Issues with ArcFace model with default values

### ISSUE THREAD

**Issue by sadimoodi** [serengil/deepface#359]
Hello,
I am facing strange accuracy issues with almost ALL models after I upgraded from deepface V0.65 to the current version 0.68, i am using the following code to turn on facial recognition on my built in camera:
video0 = 0
metrics = ["cosine", "euclidean", "euclidean_l2"]
DeepFace.stream("database", detector_backend = 'ssd',enable_face_analysis=False,
frame_threshold=2,time_threshold=1,distance_metric=metrics[2],model_name='ArcFace',source=video0)

I am using the demo images in your dataset folder along with my own image, after loading the frames from the webcam, my face is False positively identified as another face with (surprisingly) very low distance score on ALL distance metrics ("cosine", "euclidean", "euclidean_l2").
what am i doing wrong?
I have not changed the default thresholds of any model but its impossible that the distance of a wrong image is lower than the distance of similar images (my own face).

**Comment by sadimoodi** [comment]
@serengil pls advise how can I send you samples?  if you meant sample images then i can not publish these here, can i send to ur email instead? 
when comparing images you will notice that different models create surprisingly wrong predictions (low distance score)

**Comment by sadimoodi** [comment]
@serengil I am running the below code:
metrics = ["cosine", "euclidean", "euclidean_l2"]
result = DeepFace.verify('./database/person1/image2.jpg','./database/person2/Moodi_old.jpg',model_name='Facenet512',
distance_metric=metrics[1],detector_backend='mtcnn')

result:
{**'verified': True**, 'distance': 23.34801139896054, 'max_threshold_to_verify': 23.56, 'model': 'Facenet512', 'similarity_metric': 'euclidean'}

Please note that images 'person1' and 'person2' are completely different:
![Moodi_old](https://user-images.githubusercontent.com/32739021/140634207-3de64d49-451a-4bb7-9e13-5eabc0f558f3.jpg)
![image2](https://user-images.githubusercontent.com/32739021/140634213-45eb14bd-0890-42ec-a3be-4a71a2dfca7f.jpg)

**Comment by sadimoodi** [comment]
@serengil @sugyan @biranchi2018 @deepuvsdeepu can i get your opinion on this please?

**Comment by serengil** [comment]
please try retinafafe as a detector_backend and use regular facenet instead of facenet512

**Comment by sadimoodi** [comment]
@serengil RetinaFace is not able to detect any face, unlike all other detector backends.
In principal: no matter what combination of model / face_detector i use, i always end up with False Positives, although i have not changed a single line of code.
I wonder what could be wrong?

**Comment by serengil** [comment]
If retinaface can detect face, then the accuracy will increase. I think that is the problem.

**Comment by sadimoodi** [comment]
I am still facing this issue, retinaface can not detect faces when using live stream, can u take a look on [issue ](https://github.com/serengil/deepface/issues/368)
accuracy is still low on ALL models (facenet, facenet512, arcface)

**Comment by serengil** [comment]
to sum up, running a facial recongition with a camera offering that aspect causes underperforming. nothing to do unfortunately.
