### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by rockstarvibu** [serengil/deepface#36]
Hey i have nvidia 1070 GPU can you guide me to run this on gpu
i Tried 
`Deepface.allocateMemory() `
but it saying it will run on CPU. let me know the necessary tools as well as settings required to run this on GPU. 

Thanks

**Comment by serengil** [comment]
Could you try to add the following code block manually in the first line of your program.

```
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"
```

**Comment by bharatsood10** [comment]
i tried this... but still same "DeepFace will run on CPU" and i also installed CUDA Toolkit 10.2 but still not working....

**Comment by serengil** [comment]
You should not call allocateMemory() function if you set gpu devices manually. You didn't call this right?

**Comment by bharatsood10** [comment]
yess... i tried its not using GPU because i tried value 3,4,5,6 and its working perfectly fine.... no change...

**Comment by bharatsood10** [comment]
I'm not calling `allocateMemory()` and using 
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
```
at the first line of program but still its using CPU. I'm trying to see resources consumption from task manager. only cpu cycles increase GPU is at 0%.
and also using latest version of deepface 
```
pip show deepface
Name: deepface
Version: 0.0.24Note: you may need to restart the kernel to use updated packages.
Summary: Deep Face Analysis Framework for Face Recognition and Demography

Home-page: https://github.com/serengil/deepface
Author: Sefik Ilkin Serengil
Author-email: serengil@gmail.com
License: UNKNOWN
Location: c:\users\sood\anaconda3\lib\site-packages
Requires: tensorflow, keras, tqdm, pandas, numpy, Flask, gdown, opencv-python, Pillow
Required-by: 
```

**Comment by serengil** [comment]
could you run "nvidia-smi" command in the command prompt and share its screen?

**Comment by bharatsood10** [comment]
nvidia-smi
Traceback (most recent call last):

  File "<ipython-input-4-bc6386d60349>", line 1, in <module>
    nvidia-smi

NameError: name 'nvidia' is not defined

**Comment by serengil** [comment]
you should run this command in command prompt or terminal, not in python program.

**Comment by bharatsood10** [comment]
```
'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bharatsood10** [comment]
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89
```

**Comment by serengil** [comment]
sorry but I have no solutions for your case.

**Comment by bharatsood10** [comment]
okay... no problem... i will find solution... but tell me about nvidia-smi

**Comment by serengil** [comment]
nvidia-smi command show gpu utilization info. ids, available memory, utilization percentage vs.

**Comment by bharatsood10** [comment]
i have also installed nvidia geforce drivers as well as cuda driver...

**Comment by bharatsood10** [comment]
![Capture](https://user-images.githubusercontent.com/18743011/82880359-f0dbd300-9f5b-11ea-8f41-889adad79ccf.JPG)

**Comment by serengil** [comment]
you could allocate your gpus as shown below.

```
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"
```

could you monitor this command when you call deepface. there is no change?

BTW, memory size is small your gpu because deepface demands 10GB memory.

**Comment by bharatsood10** [comment]
```
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"
```
I Tried but stil its using CPU...

**Comment by serengil** [comment]
deepface requirest at lest 9GB memory but your gpus are less than this requirement.

**Comment by Taqikhan99** [comment]
So will it not work for 4gb memory gpus??
