### ISSUE TITLE
BUG in functions.py

### ISSUE THREAD

**Issue by sadimoodi** [serengil/deepface#360]
I am facing the below bug while on live stream (webcam):
  File "C:\Users\ali.khankan\AppData\Roaming\Python\Python38\site-packages\deepface\commons\functions.py", line 190, in preprocess_face
    factor_0 = target_size[0] / img.shape[0]
ZeroDivisionError: division by zero

**Comment by Winvoker** [comment]
I am trying to get the same error however i could not get any error. How can we reproduce the bug ? Does it happen when starting to livestream or , does it happen when face is detected etc. ?

**Comment by sadimoodi** [comment]
The errors pops up randomly during live streams when your head is at the edge of the frame, i am not able to reproduce it in every situation, better add exception handler to prevent division by 0 or maybe skip that frame

**Comment by serengil** [comment]
okay. i will fix this in the next release.

**Comment by serengil** [comment]
I updated the code. This is going to be published in the next release. Meanwhile, you can update the code as shown below.

```
	if img.shape[0] > 0 and img.shape[1] > 0:
		factor_0 = target_size[0] / img.shape[0]
		factor_1 = target_size[1] / img.shape[1]
		factor = min(factor_0, factor_1)
		
		dsize = (int(img.shape[1] * factor), int(img.shape[0] * factor))
		img = cv2.resize(img, dsize)
		
		# Then pad the other side to the target size by adding black pixels
		diff_0 = target_size[0] - img.shape[0]
		diff_1 = target_size[1] - img.shape[1]
		if grayscale == False:
			# Put the base image in the middle of the padded image
			img = np.pad(img, ((diff_0 // 2, diff_0 - diff_0 // 2), (diff_1 // 2, diff_1 - diff_1 // 2), (0, 0)), 'constant')
		else:
			img = np.pad(img, ((diff_0 // 2, diff_0 - diff_0 // 2), (diff_1 // 2, diff_1 - diff_1 // 2)), 'constant')
	
	#------------------------------------------
	
	#double check: if target image is not still the same size with target.
	if img.shape[0:2] != target_size:
		img = cv2.resize(img, target_size)
```
