### ISSUE TITLE
Wrong alignment direction issue when "align" set to True with detectface function

### ISSUE THREAD

**Issue by yvs997** [serengil/deepface#364]
Dear Serengil,
We're encounter an issue according to align parameters in detectface function.

Here how we call the detectface function:
```
def face_detect(image):
    face = DeepFace.detectFace(img_path=image, detector_backend='retinaface', align=True)
    return face
```
and call it by this codes:
```
def detection(path):
    print (deepface.DeepFace)
    image = Image.open(path)
    image.show()
    face = DeepFace.detectFace(img_path=np.array(image),detector_backend='retinaface',align=True)
    imface = Image.fromarray((face * 255).astype(np.uint8))
    imface.show()
```
we do small experiment with rotated potrait (90 degree both clockwise and counter clockwise). We expect when align set to true, the face will be aligned. When we test both clockwise and counter clockwise, the output just rotating to other side (180 degree)

**Comment by serengil** [comment]
would you please open this issue in the repo of retinaface? even though I am the owner of both repos, it will be easy to follow.

**Comment by serengil** [comment]
repo: https://github.com/serengil/retinaface

**Comment by yvs997** [comment]
Have sent the issue in [here:](https://github.com/serengil/retinaface/issues/12)
