### ISSUE TITLE
pip install error on windows w/ anaconda version of python

### ISSUE THREAD

**Issue by Jumabek** [serengil/deepface#365]
First of all, kudos for the amazing resource.

I am having the following error when `pip install deepface`

`ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'd:\\anaconda3\\lib\\site-packages\\scipy-1.6.2.dist-info\\METADATA'`

Would you please help me with that?

**Comment by serengil** [comment]
your anaconda environment seems not okay. this is not related to deepface.

**Comment by sri9s** [comment]
trying to setup docker image on windows, does it need visual studio? Could you please suggest base images for python and visual studio for the docker?
