### ISSUE TITLE
Deepface being killed in python:3.8-slim container

### ISSUE THREAD

**Issue by eshneken** [serengil/deepface#366]
I'm trying to run a face verification in a python:3.8-slim container.  I've run the script successfully on my mac.  When I try to run the same in a container the process gets killed without much detail.  Here is the latest piece of the verbose output

```
import 'deepface.commons.realtime' # <_frozen_importlib_external.SourceFileLoader object at 0x7ff66211f5e0>
Directory  /tmp /.deepface created
Directory  /tmp /.deepface/weights created
import 'deepface.DeepFace' # <_frozen_importlib_external.SourceFileLoader object at 0x7ff6bd77c8e0>
# destroy keras.engine.base_layer
# /python/keras/engine/__pycache__/base_layer_v1.cpython-38.pyc matches /python/keras/engine/base_layer_v1.py
# code object from '/python/keras/engine/__pycache__/base_layer_v1.cpython-38.pyc'
import 'keras.engine.base_layer_v1' # <_frozen_importlib_external.SourceFileLoader object at 0x7ff6b2ebc550>
# destroy keras.engine.base_layer_v1
# destroy keras.engine.training
# destroy keras.engine.training_v1
# destroy tensorflow.python.distribute.distribute_lib
# destroy tensorflow.python.framework.constant_op
# destroy keras.metrics
# destroy tensorflow.python.framework.ops
# destroy tensorflow.python.framework.tensor_spec
# destroy tensorflow.python.distribute.distribution_strategy_context
Killed
```

Is there some additional settings I need to make to run inside a docker container?

**Comment by serengil** [comment]
Try to install deepface with no dependencies in the docker file

pip install deepface --no-deps

before installing deepface install its dependencies with custom versions

numpy==1.14.0
pandas==0.23.4
gdown==3.10.1
tqdm==4.30.0
Pillow==5.2.0
opencv-python==4.2.0.34
opencv-contrib-python==4.3.0.36
tensorflow==1.9.0
keras==2.2.0

I think your tf version causes that and you might skip it with its pre-released versions.

**Comment by eshneken** [comment]
I tried with TF 1.9.0 but that version does not exist:

```
=> ERROR [build-stage 13/17] RUN pip3 install --target /python/  --no-cache --no-cache-dir tensorf  2.1s
------
 > [build-stage 13/17] RUN pip3 install --target /python/  --no-cache --no-cache-dir tensorflow==1.9.0:
#20 1.770 ERROR: Could not find a version that satisfies the requirement tensorflow==1.9.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
#20 1.770 ERROR: No matching distribution found for tensorflow==1.9.0
------
executor failed running [/bin/sh -c pip3 install --target /python/  --no-cache --no-cache-dir tensorflow==1.9.0]: exit code: 1
```
I did try various combinations of packages with --no-deps as well as other earlier versions of tensorflow (i.e. 2.2.0, 2.3.0) and all resulted in the same "Killed" message when running a verify().

Should I be use a different base image?  Is there another base image and/or a sample Dockerfile that has been shown to work?  Thank you!

**Comment by ErwinHaasnoot** [comment]
Docker assigns by default only 2 GB to your running container. You can change this in the Docker app on Mac

https://stackoverflow.com/a/39720010/1063621

**Comment by Shoichii** [comment]
I have the same error - killed when i try to install deepface in linux server. help please
![Screenshot_1](https://user-images.githubusercontent.com/62342750/214773660-771f16d7-9e93-4ae3-88c6-0ca06ca93fab.jpg)

**Comment by GitHub30** [comment]
> 私も同じエラーが発生しています。Linux サーバーに deepface をインストールしようとすると強制終了されます。助けてください ![スクリーンショット_1](https://user-images.githubusercontent.com/62342750/214773740-83bd69f9-3939-4b02-b250-4ef4014e2a9a.jpg)

`pip --no-cache-dir install deepface` add --no-cache-dir
