### ISSUE TITLE
Retinaface does not detect faces when called from DeepFace

### ISSUE THREAD

**Issue by sadimoodi** [serengil/deepface#368]
When using retinaface as backend_detector in DeepFace.stream, like this:

DeepFace.stream("database", detector_backend = 'retinaface',enable_face_analysis=False,
frame_threshold=2,time_threshold=2,distance_metric=metrics[1],model_name='Facenet',source=video0)

I get the following error: 
"Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False."

Please note that the image already contains a face, however, when calling RetinaFace directly like this:
from retinaface import RetinaFace
import matplotlib.pyplot as plt
faces = RetinaFace.extract_faces(img_path = "./database/Ali/Ali Mask.jpg", align = True)
for face in faces:
  plt.imshow(face)
  plt.show()

the face is detected on the SAME image.

**Comment by serengil** [comment]
I understand the reason of the trouble. This will be solved with the following logic. I changed the source code. It will add this in the next release soon. Meanwhile, you can change the code in your environment as shown below.

https://github.com/serengil/deepface/blob/master/deepface/commons/realtime.py

```
			try:
				#faces store list of detected_face and region pair
				faces = FaceDetector.detect_faces(face_detector, detector_backend, img, align = False)
			except: #to avoid exception if no face detected
				faces = []
```

**Comment by sadimoodi** [comment]
@serengil this didnt solve my problem, i still receive "Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False" when calling DeepFace.stream
i don't have this problem with :
faces = RetinaFace.extract_faces(img_path = "./database/Ali/Ali Mask.jpg", align = True)
