### ISSUE TITLE
'_thread._local' object has no attribute 'value' 

### ISSUE THREAD

**Issue by DevJoris** [serengil/deepface#37]
Hey there,

I just started with DeepFace and it seemed all to work. But something weirds happen when I put the exact same code (copied from the official page) in a function.

This is the code I try to run:

`            try:

                faceinfo = DeepFace.analyze("images/happy.jpeg")
                print('[INFO] Emotion:', faceinfo["dominant_emotion"])
                print('[INFO] Age:', faceinfo["age"])
                print('[INFO] Gender:', faceinfo["gender"])
                print('[INFO] Race:', faceinfo["dominant_race"])

            except Exception as e:
                print(str(e) + ' [FACE INFO]')`

The error i'm getting: '_thread._local' object has no attribute 'value'

Could anyone help me out with this?

**Comment by serengil** [comment]
could you print faceinfo directly?

**Comment by DevJoris** [comment]
I did some more testing, im gonna drop the full code because the code above seems to work now.
Im writing a telegram bot that fetches the face from a chat and gives info about it:

`
import cv2
import face_recognition
import os
import time
import telegram
from telegram.ext import Updater
from telegram.ext import CommandHandler
from telegram.ext import MessageHandler, Filters
from deepface import DeepFace


os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
secret = 'heregoesmytoken'
bot = telegram.Bot(token=secret)
startt = time.time()
#model = load_model("model_v6_23.hdf5")
print('[BOT] ' + str(bot.get_me()))

updater = Updater(token=secret, use_context=True)
dispatcher = updater.dispatcher


def start(update, context):
    context.bot.send_message(chat_id=update.effective_chat.id, text="Im functioning well!")


def unknown(update, context):
    context.bot.send_message(chat_id=update.effective_chat.id, text="Sorry, I didn't understand that command.")


def filedownloader(update, context):
    file = bot.getFile(update.message.photo[-1].file_id)
    file.download('./dwnimages/face.jpg')
    context.bot.send_message(chat_id=update.effective_chat.id, text="Processing picture...")


    try:
        face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
        img = cv2.imread("dwnimages/face.jpg")
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.1, 4)

        print('[INFO] FACES: ' + str(len(faces)))

        if len(faces) == 0:
            bot.send_message(chat_id=update.effective_chat.id, text='I could not find any faces :/')
        elif len(faces) == 1:

            # START DRAW
            try:
                for (x, y, w, h) in faces:
                    cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)

                cv2.imwrite('imgsend/face.png', img)
                bot.send_photo(chat_id=update.effective_chat.id, photo=open('imgsend/face.png', 'rb'))
                str1 = "I guess this picture contains 1 face!".format(len(faces))
                bot.send_message(chat_id=update.effective_chat.id, text=str1)
            except Exception as e:
                print(str(e) + ' [FACE DETECTION (1)]')
                bot.send_message(chat_id=update.effective_chat.id, text='Something went wrong :/ [ERROR 1]')

            # END DRAW
            # START EMOTION
            try:

                faceinfo = DeepFace.analyze("images/happy.jpeg")
                print('[INFO] Emotion:', faceinfo["dominant_emotion"])
                print('[INFO] Age:', faceinfo["age"])
                print('[INFO] Gender:', faceinfo["gender"])
                print('[INFO] Race:', faceinfo["dominant_race"])


            except Exception as e:
                print(str(e) + ' [FACE EMOTION]')
                bot.send_message(chat_id=update.effective_chat.id, text='Something went wrong :/ [ERROR 2]')

            #END EMOTION
            #START RECOGNITION

            try:
                picture_of_me = face_recognition.load_image_file("images/me.jpeg")
                my_face_encoding = face_recognition.face_encodings(picture_of_me)[0]
                encodings = face_recognition.face_encodings(img)
                unknown_encoding = encodings[0]
                results = face_recognition.compare_faces([my_face_encoding], unknown_encoding)

                if results[0] == True:
                    bot.send_message(chat_id=update.effective_chat.id, text='I also guess thats a picture of me!')
                else:
                    bot.send_message(chat_id=update.effective_chat.id, text="I don't think im in that picture!")

            except Exception as e:
                print(str(e) + ' [FACE EMOTION]')
                bot.send_message(chat_id=update.effective_chat.id, text='Something went wrong :/ [ERROR 3]')

            #END EMOTION

        elif len(faces) > 1:
            # START DRAW
            try:
                for (x, y, w, h) in faces:
                    cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)

                cv2.imwrite('imgsend/face.png', img)
                bot.send_photo(chat_id=update.effective_chat.id, photo=open('imgsend/face.png', 'rb'))
                str1 = "I guess this picture contains {0} faces!".format(len(faces))
                bot.send_message(chat_id=update.effective_chat.id, text=str1)
            except Exception as e:
                print(str(e) + ' [FACE DETECTION (2)]')
                bot.send_message(chat_id=update.effective_chat.id, text='Something went wrong :/ [ERROR 5]')

            # END DRAW

        else:
            bot.send_message(chat_id=update.effective_chat.id, text='It looks like something went down :/ [ERROR 6]')







    except Exception as e:
        print(e)
        bot.send_message(chat_id=update.effective_chat.id, text='It looks like something went down :/ [ERROR 7]')



def onready():
    start_handler = CommandHandler('online', start)
    dispatcher.add_handler(start_handler)
    unknown_handler = MessageHandler(Filters.command, unknown)
    phothandler = MessageHandler(Filters.photo, filedownloader)
    dispatcher.add_handler(unknown_handler)
    dispatcher.add_handler(phothandler)
    updater.start_polling()


onready()
end = time.time()
print('[INFO] It took ' + str(round(end - startt,2)) + ' seconds to load everything up')
`

**Comment by DevJoris** [comment]
I did some more testing, im gonna drop the full code because the code above seems to work now.
Im writing a telegram bot that fetches the face from a chat and gives info about it:

https://pastebin.com/AChUQq4w

**Comment by DevJoris** [comment]
Ill give u all of my code. Im writing a telegram bot that fetches faces from the chat and sends the user info about them

https://pastebin.com/r26h3M4V

Sorry for deleting multiple comments leaked token accendatily

**Comment by serengil** [comment]
You have faceinfo but you cannot access the values in faceinfo right? I cannot open the web site link you shared. 

Could you try to run the following code block and send me the printings.

```
from deepface import DeepFace

faceinfo = DeepFace.analyze("images/happy.jpeg")

print(resp_obj)

print("-------------------------")

for key, value in resp_obj.items():
	print(key,": ",value)
```

**Comment by serengil** [comment]
It seems that you cannot process json objects. Please import json library as well.

**Comment by DevJoris** [comment]
Adding "import json" did not solve the problem. Also the code u send me above did not work. 
resp_obj is undefined I assume u meant face info with it.

**Comment by serengil** [comment]
Right. Could you share the print screen when you run the following code block.

```
from deepface import DeepFace

faceinfo = DeepFace.analyze("images/happy.jpeg")

print(resp_obj)

print("-------------------------")

for key, value in faceinfo.items():
	print(key,": ",value)
```

**Comment by DevJoris** [comment]
<img width="526" alt="Screenshot 2020-05-30 at 15 31 23" src="https://user-images.githubusercontent.com/29674149/83329597-b4c1ae80-a28a-11ea-94d1-4b0d45dc10e4.png">
<img width="454" alt="Screenshot 2020-05-30 at 15 31 28" src="https://user-images.githubusercontent.com/29674149/83329604-ba1ef900-a28a-11ea-9bc0-52a4346e3a13.png">


It seems to stop at the line: faceinfo = DeepFace.analyze("image/happy.jpeg")

**Comment by DevJoris** [comment]
Hmm weird. I get the exact same error when I try to load a model with Keras inside a function.

from keras import load_model

model = load_model(emotions.hdf5) 

this will also trow the error

**Comment by serengil** [comment]
Could you change the exception block?

```
except Exception as e:
   print(str(s))
```

**Comment by serengil** [comment]
Replace resp_obj to faceinfo please.

**Comment by DevJoris** [comment]
I get the exact same error message. Removing try and exept gives something weird. It will just say: Actions to do:  ['emotion', 'age', 'gender', 'race']. And then stay on it. No error message nothing. Endless this

**Comment by serengil** [comment]
what was your tf and keras versions?

could you reinstall them for the following versions

pip install tensorflow==1.9.0
pip install keras==2.2.0

**Comment by DevJoris** [comment]
I have stopped using keras. I wanted to use your library now. Also pip install tensorflow==1.9.0 does not work. There is no tensor flow 1.9.0?

**Comment by DevJoris** [comment]
Collecting tensorflow==1.9
  Could not find a version that satisfies the requirement tensorflow==1.9 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
No matching distribution found for tensorflow==1.9

**Comment by serengil** [comment]
Interesting. Here, you can check the tf 1.9.0

https://pypi.org/project/tensorflow/1.9.0/

Please try 1.13.1

**Comment by DevJoris** [comment]
1.13.1 did work. Im now installing it

**Comment by DevJoris** [comment]
Using tensor flow 1.13.1 worked!

I do get some errors

1:

/Users/Joris/PycharmProjects/TestMode/venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])

2:

WARNING:tensorflow:From /Users/Joris/PycharmProjects/TestMode/venv/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:

But it did successfully get the emotions and everything! :D

**Comment by serengil** [comment]
these are warnings. you can discard and ignore.

happy to hear that.

**Comment by DevJoris** [comment]
Anyway how I can turn them off? I won't bother u anymore after this :D 
Anyways really really really thankful. Thanks for fast replies :D

**Comment by DevJoris** [comment]
Using os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' stops the second error but not the first
