### ISSUE TITLE
DeepFace

### ISSUE THREAD

**Issue by Gideon-O** [serengil/deepface#373]
I want to use DeepFace in Django. 

In my virtual environment, I run the command "pip install deepface" and it installs successfully. 
But when I do "from deepface import DeepFace" in my views.py my VS-Code highlights deepface and has an error "Import deepface could not be resolved"

Also, when I try running a the file in VS-Code, it raises error "no module named deepface"

Please advice

**Comment by serengil** [comment]
it seems that the environment you installed deepface and you run are different.
