### ISSUE TITLE
More Information about the pre-trained models

### ISSUE THREAD

**Issue by dragonchen10** [serengil/deepface#376]
Thanks for deveoping this great framework. I just wonder whether we could have more information about the pre-trained models? For example, what are the datasets and settings for training the pre-trained models? It looks that these information are not provied in either the github or the paper. In the code, we can find the model URL, e.g., 'https://github.com/serengil/deepface_models/releases/download/v1.0/arcface_weights.h5'. But knowing how those pre-trained models were trained will be very helpful and give us confidence to cite this work in the future works. Please feel free to let us know waht you think. Thanks a lot!

**Comment by serengil** [comment]
Reference repos cited in the read me. You can follow those links to have an information.

**Comment by dragonchen10** [comment]
Thanks a lot for the reply. From the cited references in Read me, it's still not clear what is the training dataset for the specific pretrained model. For example, for the FaceNet, the linked repo shows metrics on two different training sets:  CASIA-WebFace and VGGFace2. So how could we know which one is coresponding to the model: 'https://github.com/serengil/deepface_models/releases/download/v1.0/facenet_weights.h5'? Please feel free to let me know. Thanks a lot for your warm help!
