### ISSUE TITLE
Add Large Dataset face recognition in api also

### ISSUE THREAD

**Issue by rockstarvibu** [serengil/deepface#38]
Hey plz add large dataset face recognition in api also... if u are already working on it.. let me know..
Thanks

**Comment by serengil** [comment]
API use-case is not applicaple for large scale face recognition. We store the both images and its representations on the disk but in API we expect to send base64 images as inputs. Sending too many base64 images will cause memory problem.

**Comment by rockstarvibu** [comment]
i means to say searching from pickle file from find method through api

**Comment by serengil** [comment]
you want to send the pickle file to the request of find function?

**Comment by rockstarvibu** [comment]
yes through api

**Comment by serengil** [comment]
That will create a conflict against the simplicity of deepface framework.

**Comment by rockstarvibu** [comment]
User will send base64 image and find function will do searching from pickle file through find method

**Comment by serengil** [comment]
Cannot you do it with verify function as well?

**Comment by serengil** [comment]
Oke I will add this feature in the next version.

**Comment by rockstarvibu** [comment]
nope i have a large number of images and i will create pickle file uploaded to server so when new image comes as base64 image it will find from that pickle file and let me know

**Comment by rockstarvibu** [comment]
> Oke I will add this feature in the next version.

Thanks that will be a great feature
