### ISSUE TITLE
Emotion Detection Not Working

### ISSUE THREAD

**Issue by TheBandit105** [serengil/deepface#383]
I am currently trying to build an emotion recognition system to work using the DeepFace library. I was able to get the face being detected first by initially using this code:

`import cv2
from deepface import DeepFace

cam = cv2.VideoCapture(0)

faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

while True:

    ret, frame = cam.read()
    print(ret)

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(gray, 1.1, 4)

    for(x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    font = cv2.FONT_HERSHEY_SIMPLEX

    cv2.putText(frame, "FPS: {}".format(cam.get(cv2.CAP_PROP_FPS)), (10,30), font, 1, (0, 255, 255), 2, cv2.LINE_4) 
    cv2.putText(frame, 'Press q to quit', (200,450), font, 1, (0, 255, 255), 2, cv2.LINE_4)
    cv2.imshow("ERS Visual V1.0 - Emotion Recognition System", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cam.release()
cv2.destroyAllWindows()
quit()`

![image](https://user-images.githubusercontent.com/87244418/144239006-4f234533-3cd9-4f14-b945-8c08d521f1ae.png)

However, after adding the lines:

`emotRes = DeepFace.analyze(frame, actions = ['emotion'])
cv2.putText(frame, emotRes['emotion'], (50, 50), font, 1, (0, 0, 255), 2, cv2.LINE_4)`

as shown in:

`import cv2
from deepface import DeepFace

cam = cv2.VideoCapture(0)

faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

while True:

    ret, frame = cam.read()
    print(ret)

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(gray, 1.1, 4)

    for(x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    font = cv2.FONT_HERSHEY_SIMPLEX

    emotRes = DeepFace.analyze(frame, actions = ['emotion'])
    cv2.putText(frame, emotRes['emotion'], (50, 50), font, 1, (0, 0, 255), 2, cv2.LINE_4)

    cv2.putText(frame, "FPS: {}".format(cam.get(cv2.CAP_PROP_FPS)), (10,30), font, 1, (0, 255, 255), 2, cv2.LINE_4) 
    cv2.putText(frame, 'Press q to quit', (200,450), font, 1, (0, 255, 255), 2, cv2.LINE_4)
    cv2.imshow("ERS Visual V1.0 - Emotion Recognition System", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cam.release()
cv2.destroyAllWindows()
quit()`

the program essentially tries to start up, since I could see the camera attempting to turn on, but then just quits without any error for no reason, which I can't understand why it's doing it.

![image](https://user-images.githubusercontent.com/87244418/144239240-575e5d52-dd9b-4194-9c13-87d53154de21.png)

I would be grateful if someone is able to explain why this is happening and what I could do to fix the problem

**Comment by TheBandit105** [comment]
Check this link to see the problem there as well:
https://stackoverflow.com/questions/70112102/problem-in-getting-live-camera-emotion-recognition-system-to-work-using-deepface

**Comment by serengil** [comment]
It seems an opencv related issue. Unfortunately, I have no idea why this happens.

**Comment by serengil** [comment]
Why don't you try stream function of deepface? It handles real time analysis functionality.

**Comment by serengil** [comment]
Closing the issue because this is out-of-scope.

**Comment by KiLJ4EdeN** [comment]
> Check this link to see the problem there as well: https://stackoverflow.com/questions/70112102/problem-in-getting-live-camera-emotion-recognition-system-to-work-using-deepface


Aside the issue i don't think its a good idea to draw rectangles on the main frame before passing it to DeepFace.analyze,
this can mess up the face detection pipeline.

Secondly i suggest that you don't do face detection twice, one on your loop and another under DeepFace.analyze,
if you are looking to debug this you can crop the face using your own initial detector
do the preprocessing as done by the library, which if i am correct is a /255 and expand dims,
then predict using the baseline emotion model itself and see if the problem persists.
