### ISSUE TITLE
State of the art face analysis 

### ISSUE THREAD

**Issue by Siegi96** [serengil/deepface#384]
Hey, thanks for your great library.
Do you plan to integrate better performing models for gender prediction/age estimation? Because DeepFace, which is used for Face Analysis(Gender, Age,...), is quite old and behind state of the art.

**Comment by serengil** [comment]
No, I have no plan to add new age / gender models

**Comment by BoPeng** [comment]
@Siegi96 I have noticed the same issue with DeepFace. Have you been able to address this issue with any other library?
