### ISSUE TITLE
Train dataset using deepface and dump model using numpy

### ISSUE THREAD

**Issue by devdandi** [serengil/deepface#385]
how to train database of image ?

**Comment by serengil** [comment]
I don't understand what you need exactly. Please give more information.

**Comment by devdandi** [comment]
> I don't understand what you need exactly. Please give more information.

I iwant to train my image to my model own and then the trained dataset Will be dump using pickle, so the predict Will be model.predict(x)

**Comment by serengil** [comment]
this is out-of-scope of deepface.
