### ISSUE TITLE
This is a continuation of issue #383

### ISSUE THREAD

**Issue by TheBandit105** [serengil/deepface#387]
Hi again,

Sorry to be asking again, but I tried doing the same thing on my brother's computer and it worked there somehow. I just want to understand how it's working on my brother's PC, but not my own laptop. 

![image](https://user-images.githubusercontent.com/87244418/145028159-779db728-b8bd-4619-819b-faf748f0906f.png)

![image](https://user-images.githubusercontent.com/87244418/145028344-57f313b2-7a56-4987-8059-4f130e6bc73c.png)

**Comment by TheBandit105** [comment]
Here are the specifications of the devices I tried to execute the program:

My Laptop Specs: 

Device name     ShavinL
Processor          Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
Installed RAM   16.0 GB (15.9 GB usable)
Device ID          2CE317C9-4716-44A1-ABCA-DC73F5F046E5
Product ID         00325-81107-08090-AAOEM
System type      64-bit operating system, x64-based processor
Pen and touch   No pen or touch input is available for this display

Edition  Windows 10 Home
Version 21H1
Installed on       ‎22/‎03/‎2021
OS build            19043.1165
Experience        Windows Feature Experience Pack 120.2212.3530.0

My Brother’s PC Specs:

Device name    DESKTOP-4METK9U
Processor    Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.41 GHz
Installed RAM    16.0 GB
Device ID    0D6980AF-0CF5-4FEA-80A4-0763B18E2A1F
Product ID    00325-96014-57940-AAOEM
System type    64-bit operating system, x64-based processor
Pen and touch    Pen support

Edition    Windows 10 Home
Version    20H2
Installed on    ‎22/‎08/‎2021
OS build    19042.1348
Experience    Windows Feature Experience Pack 120.2212.3920.0

**Comment by serengil** [comment]
As I mentioned before, it seems an open-cv related issue and I don't have any idea.
