### ISSUE TITLE
DEEPFACE_HOME env var not applied to `retinaface` weights filepath

### ISSUE THREAD

**Issue by ErwinHaasnoot** [serengil/deepface#389]
Hi Sefik,

Thanks for this great tool! I've found it very useful to quickly bootstrap my projects :)

The pull request below 

https://github.com/serengil/deepface/pull/323

describes a very useful feature, that allows one to configure the location of the `.deepface` folder. However, it seems it is not yet consistently applied. Specifically in your retinaface project on Github:

https://github.com/serengil/retinaface/blob/c920f4e2b91e1ec04bdde013b3d29a4041ead59c/retinaface/model/retinaface_model.py#L18

I would make a pull request, but I'm not sure in which direction you'd want this problem solved. One option I see is making the `deepface` lib, as the orchestrator, download the weights, but then the `retinaface` lib would no longer be stand-alone. Another one I see is we include the `get_deepface_home` function in the `retinaface` lib, such that it also respects the path defined in the DEEPFACE_HOME env var, but it would mean some code replication.

Looking forward to hearing your thoughts!

Also, note that the current version of deepface on pypi (https://pypi.org/project/deepface/ ) is from August 20th and does not include the DEEPFACE_HOME configuration at all, but I see other people have already opened issues about it :)

**Comment by serengil** [comment]
I'm going to publish deepface in pip in the next couple of days

**Comment by serengil** [comment]
deepface and retinaface are diferent repos. You can add this feature in retinaface.
