### ISSUE TITLE
Face encoding generated for my pet

### ISSUE THREAD

**Issue by linux-devil** [serengil/deepface#39]
I am trying to find face encodings for an area. For an image it is able to find face encodings that too for a dog facing backwards. 

![2020-06-02T12:41:51_-1_Person_468_1182](https://user-images.githubusercontent.com/307810/83521979-a0391c80-a4fd-11ea-9315-5384de1d6273.jpg)

`
from deepface import DeepFace
#from deepface.basemodels import VGGFace, OpenFace, Facenet, FbDeepFace
from deepface.basemodels import Facenet
from deepface.commons import functions, realtime, distance as dst
model = Facenet.loadModel()
input_shape = (160,160)
model_name = 'Facenet'
distance_metric = 'cosine'
threshold = functions.findThreshold(model_name, distance_metric)
def get_face_encodings(file_name):
    try:
        img1 = functions.detectFace(file_name,input_shape)
        img1_representation = model.predict(img1)[0,:]
        print(img1_representation)
        return img1_representation
    except:
        return []
face_encoding = get_face_encodings(file)

`
Try it yourself  , it sometimes find face encodings for me when I am facing against the camera

**Comment by serengil** [comment]
detectFace function will return exception if it cannot detect a face. So, you cannot apply deepface for those kind of tasks.

**Comment by linux-devil** [comment]
so I am assuming I cannot use this to detect face

**Comment by serengil** [comment]
BTW, you can pass enforce_detection argument to detectFace function. Its default value is True. If you set this to False, then it would not enforce you to detect face.

**Comment by linux-devil** [comment]
but this doesnt solve above problem

**Comment by linux-devil** [comment]
Can we open this issue and rather fix it.
