### ISSUE TITLE
Training/finetune on Custom Dataset

### ISSUE THREAD

**Issue by ruhyadi** [serengil/deepface#393]
Hy Sefic, thanks for the best face library.
First of all, I'm beginner in face recognition field. I wonder how to train/finetune pretrained model (like facenet) on custom dataset?.
Did you provide the code or function?.

Thanks,

Didi

**Comment by serengil** [comment]
For example, age and gender prediction models are trained as mentioned in the following tutorial

https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/
