### ISSUE TITLE
Docker file base image for deepface on windoes

### ISSUE THREAD

**Issue by sri9s** [serengil/deepface#394]
Hi, I am struggling with errors for docker file built giving me errors.
Can you help me with docker file for running deepface on a windows machine?

**Comment by serengil** [comment]
I don't promise but I will study it whenever I find a time

**Comment by onuratakan** [comment]
@serengil I can do it, can you assign to me.

Best regards,

Onur Atakan ULUSOY

**Comment by serengil** [comment]
@onuratakan PRs are welcome!
