### ISSUE TITLE
euclidean_l2 may not be the best in face recognition 

### ISSUE THREAD

**Issue by wanghsinche** [serengil/deepface#395]
I found the readme suggests that euclidean_l2 is more stable. But I don't think so. 

The face recognition relies on the high dimensions features, which means the data points will be more different in the aspect of the position, rather than the distance. That is said almost all of them distributes on the surface of a high dimension sphere.

In my opinion , cosine may be a better choice for distance metric. But it still has the same problem.

There may be some better methods to distinguish the features in the face recognition.

**Comment by serengil** [comment]
If you follow the link in that sentence, you will find out why l2 form is more robust.
