### ISSUE TITLE
When i'm trying to verify two faces in pycharm it's not printing any output.

### ISSUE THREAD

**Issue by nithinreddyy** [serengil/deepface#397]
When i'm trying to verify two faces in pycharm it's not printing any output. Below i'm attaching the code and the image for your reference.

```
from deepface import DeepFace
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

img1_path = "Sunny.JPG"
img2_path = "Sunny (18).jpg"

model_name = "Facenet"

resp = DeepFace.verify(img1_path=img1_path, img2_path=img2_path, model_name=model_name)

print(resp)
```
<img width="707" alt="Capture" src="https://user-images.githubusercontent.com/56256685/148525065-f3da3334-9757-4297-817d-339da2b6b3f8.PNG">

Please let me know the solution if anyone knows. Thank you in advance.

**Comment by serengil** [comment]
I am not a pycharcm user :/

**Comment by serengil** [comment]
closed due to coming from an external tool instead of deepface itself
