### ISSUE TITLE
Change in default values of "max_threshold_to_verify" of facenet512 with eucledian l2 distance?

### ISSUE THREAD

**Issue by sri9s** [serengil/deepface#399]
If I remember right the default max threshold was 0.75, and now it is 1.04.
Has there been a change in the default value?

**Comment by serengil** [comment]
Facenet512 is newly added model. You might remember regular Facenet.

        'Facenet':  {'cosine': 0.40, 'euclidean': 10, 'euclidean_l2': 0.80},
        'Facenet512':  {'cosine': 0.30, 'euclidean': 23.56, 'euclidean_l2': 1.04},

**Comment by sri9s** [comment]
Which model and distance pair has the threshold 0.75?
