### ISSUE TITLE
Emotion detection problem

### ISSUE THREAD

**Issue by luispsantos** [serengil/deepface#4]
Great work on building this library by the way! I'm having an OpenCV exception when I try running emotion detection, while all the other networks work fine. I believe the problem stems from this line:

https://github.com/serengil/deepface/blob/62678e13ee163f47d250185cf4a8333bfb4b6dec/deepface/DeepFace.py#L155

By running detectFace with grayscale=True, we load the image already in grayscale with cv2.imread(), but then the function cv2.cvtColor expects a RGB image to convert to grayscale, hence an OpenCV error pops up. Thank you again for your time and for releasing this library to the world!

https://github.com/serengil/deepface/blob/62678e13ee163f47d250185cf4a8333bfb4b6dec/deepface/commons/functions.py#L147

**Comment by serengil** [comment]
Hello Luis, 

First of all, thank you for your feedback.

I understand the problem. It is my fault. Face alignment modification causes this error. I fixed this issue in 0.0.9 version. Please upgrade the framework.

`pip install --upgrade deepface`
