### ISSUE TITLE
Model unpacking

### ISSUE THREAD

**Issue by Deamoner** [serengil/deepface#40]
I am using the library in colab and when I try to load the age/emotion/gender models it seems to unzip the absolute root url but then it cannot find the models in the higher level path. 

Is there a different way to load these perhaps?

My code is quite simple:
`models = {}
  models["emotion"] = Emotion.loadModel()
  models["age"] = Age.loadModel()
  #models["gender"] = Gender.loadModel()
  #DeepFace.analyze("9.jpg", models=models)
  DeepFace.analyze("9.jpg")`

Console log: 

facial_expression_model_weights.h5 will be downloaded...
Downloading...
From: https://drive.google.com/uc?id=13iUHHP3SlNg53qSuQZDdHDSDNdBP9nwy
To: /root/.deepface/weights/facial_expression_model_weights.zip
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-23-18fb84c06258> in <module>()
      8 #print(img)
      9 
---> 10 process(im_pil)

2 frames
/usr/local/lib/python3.6/dist-packages/gdown/download.py in download(url, output, quiet, proxy, speed, use_cookies)
    174             dir=osp.dirname(output),
    175         )
--> 176         f = open(tmp_file, "wb")
    177     else:
    178         tmp_file = None

FileNotFoundError: [Errno 2] No such file or directory: '/root/.deepface/weights/facial_expression_model_weights.zipz42e9wnvtmp'

**Comment by serengil** [comment]
I know that people use deepface on colab

Your exception message is interesting: FileNotFoundError: [Errno 2] No such file or directory: '/root/.deepface/weights/facial_expression_model_weights.zipz42e9wnvtmp'

It appends a temp character to the file name

**Comment by serengil** [comment]
Could you just try to run the following code block

`DeepFace.analyze("9.jpg")`

**Comment by serengil** [comment]
no response
