### ISSUE TITLE
different max thresholds for vgg face & Euclidian l2 for different versions

### ISSUE THREAD

**Issue by sri9s** [serengil/deepface#400]
Earlier the version was 0.75 and now it is 0.86. Has the model changed?

**Comment by serengil** [comment]
model is same, threshold might be changed.

**Comment by sri9s** [comment]
so the model was retrained and has new weights and a different threshold?

**Comment by serengil** [comment]
No model is same as I mentioned. It has same weights.

Threshold might be changed.
