### ISSUE TITLE
Thresholds for FMR=0.1% 

### ISSUE THREAD

**Issue by sbnsl** [serengil/deepface#401]
Hi, Do you now about the threshold values corresponding to FMR=0.1% for FaceNet and ArcFace models using Euclidean L2 distance?

Thanks,

**Comment by serengil** [comment]
What FMR is?

**Comment by sbnsl** [comment]
I mean the threshold corresponding to false positive rate of 10^-3 on your validation set (e.g., LFW).

**Comment by serengil** [comment]
Actually, deepface wraps ready-to-use models. I mean that I haven't trained none of them for facial recognition. Those scores can be found in the reference studies or repos cited in the license section of the read me.
