### ISSUE TITLE
Hello, has anyone effectively used this module on a raspberry pi zero or raspi 3b+

### ISSUE THREAD

**Issue by fwuffyboi** [serengil/deepface#403]
Hi, i was wondering if anyone here has used this module on a raspi zero with a speed of about 1 frame every 2 - 5 seconds?

**Comment by serengil** [comment]
I did. What do you wonder?

**Comment by SlevinKlvra** [comment]
Hi. I am trying to run DeepFace in a Raspberry Pi 4. I am just doing a simple script giving to the program a simple png image and I am always same result:

Using TensorFlow backend.
Directory  /home/pi /.deepface created
Directory  /home/pi /.deepface/weights created
Traceback (most recent call last):
  File "emotion_detection.py", line 8, in <module>
    analyze = DeepFace.analyze(image,actions=['emotions'])
  File "/home/pi/.local/lib/python3.7/site-packages/deepface/DeepFace.py", line 450, in analyze
    resp_obj["region"][parameter] = int(region[i]) #int cast is for the exception - object of type 'float32' is not JSON serializable
IndexError: list index out of range

**Comment by fwuffyboi** [comment]
> I did. What do you wonder?

Was it fast? Are the dataset downloads the same size on all platforms? And was it as effective? Sorry for all the questions lol

**Comment by serengil** [comment]
@SlevinKlvra, i think there is a typo. it should be emotion (singular) instead of emotions (plural)

`analyze = DeepFace.analyze(image,actions=['emotion'])`

**Comment by serengil** [comment]
@fwuffyboi it depends on complex models and unfortunately it won't be really real-time. it would be some freezes.
