### ISSUE TITLE
ImportError: cannot import name 'DeepFace' 

### ISSUE THREAD

**Issue by Isameneses12** [serengil/deepface#404]
Hi, I've been trying to use deepface for real time recongnition but when I execute the .py file with:  
```
from deepface import DeepFace
DeepFace.stream('database') 
```

I get this error:
ImportError: cannot import name 'DeepFace' from partially initialized module 'deepface' (most likely due to a circular import) (C:\Users\MariaIsabelMeneses\Desktop\deepface.py)

**Comment by raoulalwani** [comment]
Don't name your file `deepface.py` because the name will conflict with the import statement. It's a silly brittle thing in Python, change the filename of your code and it should work.

**Comment by serengil** [comment]
@raoulalwani seems to find a solution :) thanks

**Comment by Isameneses12** [comment]
Thanks!!
