### ISSUE TITLE
how to get threshold from chefboost as in the notebook

### ISSUE THREAD

**Issue by sri9s** [serengil/deepface#405]
```
tmp_df = df[['distance', 'decision']].rename(columns = {"decision": "Decision"}).copy()
model = chef.fit(tmp_df, config)
```

```
sigma = 2
#2 sigma corresponds 95.45% confidence, and 3 sigma corresponds 99.73% confidence

#threshold = round(tp_mean + sigma * tp_std, 4)
threshold = 0.3147 #comes from c4.5 algorithm
print("threshold: ", threshold)
```

These are from the finetune notebook and the threshold is hardcoded.
How can I get the threshold from the c4.5 algorithm?

**Comment by serengil** [comment]
Once you call the fit command of the chefboost library, then it is going to create a file at current_folder/rules/rules.py. Here, you are going to see the threshold value.
