### ISSUE TITLE
necessary preprocessing steps to improve face verification performance

### ISSUE THREAD

**Issue by sri9s** [serengil/deepface#407]
As I use face verification to test on a new dataset I finetuned the threshold and got the best model and distance metric.

Can you also guide in any preprocessing steps that is to be taken to further improve the model performance?

**Comment by serengil** [comment]
detection and alignment are pre-processing stages. you can use many different face detectors within deepface: opencv, ssd, mtcnn, dlib, retinaface, mediapipe.

find the best detectors for your case. I mean that retinaface might be the most accurate but it is very slow. On the other hand, opencv is the fastest but its alignment score is very low.
