### ISSUE TITLE
Age difference when using DeepFace vs individual Age Model

### ISSUE THREAD

**Issue by sairaghava7** [serengil/deepface#408]
I see a significant difference in the predicted age between DeepFace.stream() and age-gender-prediction-real-time.py files. I see that the weights and VGG architecture are the same but not sure why there is a significant difference here. Can you please enlighten me? Thank you for this great work and I'm learning a lot from this

**Comment by serengil** [comment]
They are all same. I expect same results. Could you please give more details?

**Comment by serengil** [comment]
closed due to inactivity
