### ISSUE TITLE
Cropping the detected face with dlib

### ISSUE THREAD

**Issue by sotirismos** [serengil/deepface#409]
Hi Serengil! I've noticed that [DlibWrapper.py](https://github.com/serengil/deepface/blob/master/deepface/detectors/DlibWrapper.py) can be improved cause in some edge cases it fails. More specifically, there are edge cases where the bounding box is partially outside the image window (that explains the fact that some coordinates of the bounding box in dlib have negative values). In these cases, cropping the detected face based on the box coordinates either fails or returns odd results. 

So, instead of this command
- detected_face = img[top:bottom, left:right]

we should get the detected face with the following command

- detected_face = img[max(0, top): min(bottom, img_height), max(0, left): min(right, img_width)]

**Comment by serengil** [comment]
thank you for your contribution. I can do it but why don't you send a PR? In that way, you will be displayed in the contributors.

**Comment by sotirismos** [comment]
ok, i will send a PR, thank you!
