### ISSUE TITLE
i have in load_image     raise ValueError("Confirm that ",img," exists")

### ISSUE THREAD

**Issue by omar1997ogk** [serengil/deepface#410]
[code issue jupyter.docx](https://github.com/serengil/deepface/files/7892061/code.issue.jupyter.docx)
[error.pdf](https://github.com/serengil/deepface/files/7891940/error.pdf)
code 
from deepface import DeepFace
import matplotlib.pyplot as plt
img1_path = r"C:\Users\Omar\PycharmProjects\pythonProject5\img1.jpg"
img2_path = r"C:\Users\Omar\PycharmProjects\pythonProject5\img2.jpg"
img1 = DeepFace.detectFace(img1_path)
img2 = DeepFace.detectFace(img2_path)
plt.imshow(img1)
model_name = 'facenet'
resp = DeepFace.verify(img1_path = img1_path, img2_path = img2_path, model_name = model_name)
resp

**Comment by serengil** [comment]
exception message is clear
