### ISSUE TITLE
The conflict is cause

### ISSUE THREAD

**Issue by gaplan** [serengil/deepface#413]
system : Mac Mini M1 

using : python3 -m pip install deepface

and error message is : 

use these package versions have conflicting dependencies.

The conflict is caused by:
    deepface 0.0.72 depends on tensorflow>=1.9.0
    deepface 0.0.71 depends on tensorflow>=1.9.0
    deepface 0.0.70 depends on tensorflow>=1.9.0
    deepface 0.0.69 depends on tensorflow>=1.9.0
    deepface 0.0.68 depends on tensorflow>=1.9.0
    deepface 0.0.67 depends on tensorflow>=1.9.0
    deepface 0.0.66 depends on tensorflow>=1.9.0
    deepface 0.0.65 depends on tensorflow>=1.9.0
    deepface 0.0.64 depends on tensorflow>=1.9.0
    deepface 0.0.63 depends on tensorflow>=1.9.0
    deepface 0.0.62 depends on tensorflow>=1.9.0
    deepface 0.0.61 depends on tensorflow>=1.9.0
    deepface 0.0.60 depends on tensorflow>=1.9.0
    deepface 0.0.59 depends on tensorflow>=1.9.0
    deepface 0.0.58 depends on tensorflow>=1.9.0
    deepface 0.0.57 depends on tensorflow>=1.9.0
    deepface 0.0.56 depends on tensorflow>=1.9.0
    deepface 0.0.55 depends on tensorflow>=1.9.0
    deepface 0.0.54 depends on tensorflow>=1.9.0
    deepface 0.0.53 depends on tensorflow>=1.9.0
    deepface 0.0.52 depends on tensorflow>=1.9.0
    deepface 0.0.51 depends on tensorflow>=1.9.0
    deepface 0.0.50 depends on tensorflow>=1.9.0
    deepface 0.0.49 depends on tensorflow>=1.9.0
    deepface 0.0.48 depends on tensorflow>=1.9.0
    deepface 0.0.47 depends on tensorflow>=1.9.0
    deepface 0.0.46 depends on tensorflow>=1.9.0
    deepface 0.0.45 depends on tensorflow>=1.9.0
    deepface 0.0.44 depends on tensorflow>=1.9.0
    deepface 0.0.43 depends on tensorflow>=1.9.0
    deepface 0.0.41 depends on tensorflow>=1.9.0
    deepface 0.0.40 depends on tensorflow>=1.9.0
    deepface 0.0.39 depends on tensorflow>=1.9.0
    deepface 0.0.38 depends on tensorflow>=1.9.0
    deepface 0.0.37 depends on tensorflow>=1.9.0
    deepface 0.0.36 depends on tensorflow>=1.9.0
    deepface 0.0.35 depends on tensorflow>=1.9.0
    deepface 0.0.34 depends on tensorflow>=1.9.0
    deepface 0.0.33 depends on tensorflow>=1.9.0
    deepface 0.0.32 depends on tensorflow>=1.9.0
    deepface 0.0.31 depends on tensorflow>=1.9.0
    deepface 0.0.30 depends on tensorflow>=1.9.0
    deepface 0.0.26 depends on tensorflow>=1.9.0
    deepface 0.0.25 depends on tensorflow>=1.9.0
    deepface 0.0.24 depends on tensorflow>=1.9.0
    deepface 0.0.23 depends on tensorflow>=1.9.0
    deepface 0.0.22 depends on tensorflow>=1.9.0
    deepface 0.0.21 depends on tensorflow>=1.9.0
    deepface 0.0.20 depends on tensorflow>=1.9.0
    deepface 0.0.19 depends on tensorflow>=1.9.0
    deepface 0.0.18 depends on tensorflow>=1.9.0
    deepface 0.0.16 depends on tensorflow>=1.9.0
    deepface 0.0.15 depends on tensorflow>=1.9.0
    deepface 0.0.14 depends on tensorflow>=1.9.0
    deepface 0.0.13 depends on tensorflow>=1.9.0
    deepface 0.0.12 depends on tensorflow>=1.9.0
    deepface 0.0.11 depends on tensorflow>=1.9.0
    deepface 0.0.10 depends on tensorflow>=1.9.0
    deepface 0.0.9 depends on tensorflow>=1.9.0
    deepface 0.0.7 depends on tensorflow>=1.9.0
    deepface 0.0.6 depends on tensorflow>=1.9.0
    deepface 0.0.5 depends on tensorflow>=1.9.0
    deepface 0.0.4 depends on tensorflow>=1.9.0
    deepface 0.0.3 depends on tensorflow>=1.9.0
    deepface 0.0.2 depends on tensorflow>=1.9.0
    deepface 0.0.1 depends on tensorflow>=1.9.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by mikila85** [comment]
+1

**Comment by mikila85** [comment]
@gaplan are you on windows too?

**Comment by gaplan** [comment]
@mikila85 no i'm using mac mini M1  - Bigsur.

**Comment by gaplan** [comment]
Python 3.8.9 does not support tensorflow 1.9.0 :(

**Comment by serengil** [comment]
I am using python 3.8.12 and tf 2.2.0 in my mac (intel processor)

try to install tensorflow 2.2.0 before installing deepface

pip install tensorflow==2.2.0
pip install deepface

**Comment by serengil** [comment]
Please look this issue as well: https://github.com/serengil/deepface/issues/391

**Comment by serengil** [comment]
closed due to duplication
