### ISSUE TITLE
Enhancement in the alignment procedure of Dlib

### ISSUE THREAD

**Issue by sotirismos** [serengil/deepface#414]
Hi Serengil! In the past few days i'm studying comprehensively the DlibWrapper. After the change we made in the DlibWrapper, setting
- detected_face = img[top:bottom, left:right] 

to
 
- detected_face = img[max(0, top): min(bottom, img_height), max(0, left): min(right, img_width)]
we were able to crop the detected faces in the edge cases where the bounding box is partially outside the image window. 
Let's give a brief example. Suppose we have the following image of Hulusi Akar:

![6](https://user-images.githubusercontent.com/26204902/150532466-5f3040f7-8be1-4c97-ae53-a2ed8e11b302.png)

For the face that is on the left side the coordinate d.top() is negative (the bounding box is partially outside the image window). So before our change we wouldn't have the ability to crop it. But, after our change we are able to detect it and the following image is returned:

![a](https://user-images.githubusercontent.com/26204902/150537584-c3e95b66-645e-47b9-aed4-42c355c1830a.jpeg)

The "problem" occurs when we set **align = True**. Then, the following image is returned (a part of the image is total black)
 
![afte_alignment](https://user-images.githubusercontent.com/26204902/150533330-bcab410a-279a-4484-bc99-7c942e00ac58.png)

meaning that the embeddings may not be that accurate.
Note, this edge case occurs when we set **align = True** using the dlibWrapper.
(I'm not sending a PR cause i didn't find the solution yet)

**Comment by serengil** [comment]
Black pixels refer to (0, 0, 0) in RGB code. So, there is no information in black area. This means aligned version is totally okay to find embeddings. This is not a bug.
