### ISSUE TITLE
Unify all the inference by replacing the custom code with the unified one dealing with ONNX only

### ISSUE THREAD

**Issue by KOLANICH** [serengil/deepface#418]
Currently there is a zoo of wrappers for models, each with custom code.

It is proposed to do the following:

1. Rewrite the code importing models into code converting them into ONNX. For some formats there are existing convertors, so that code can be thrown away and replaced with the third-party one. It should be possible to execute the converting scripts standalonely.
2. Write unified backend working with any ONNX file as a model ahd maybe some metadata specifying input and output transformations.
3. Pre-convert all the models into ONNX.
4. Write an abstraction layer around different frameworks to make them do inference we need on the models in ONNX format.
5. Cooperate with the upstream projects to make them ship the models in ONNX format by default.
6. ...
7. PROFIT

**Comment by serengil** [comment]
thank you for your recommendation.

**Comment by haseebkhawaja** [comment]
@KOLANICH @serengil .
hi 
is this logic has been implemented or not?

**Comment by serengil** [comment]
No, it has not and it will not.
