### ISSUE TITLE
[Question] Is there way to detech all faces and then use analyze() on each?

### ISSUE THREAD

**Issue by santoshbs** [serengil/deepface#419]
When I feed an image with multiple people in it to the DeepFace.analyze(), the function seems to return age, gender, etc. information for only one of the faces. Is there a way to first extract all faces and then analyze() age, gender, etc. for each face?

**Comment by serengil** [comment]
Yes, you can!

```python
from retinaface import RetinaFace
from deepface import DeepFace

faces = RetinaFace.extract_faces("img.jpg")
for face in faces:
    obj = DeepFace.analyze(img)
    print(obj["age"])
```
