### ISSUE TITLE
Cannot run deepface

### ISSUE THREAD

**Issue by mahaputrailhamawal** [serengil/deepface#421]
Hello Mr. Serengil. Can you help me?.  I have installed deepface library on my laptop. When I want to try deepface I get an error like in the picture. Were there any steps that were skipped when I installed deepface? .
![error](https://user-images.githubusercontent.com/51139989/151663579-93a69a67-9cde-4efb-b416-62b2b9ad642e.PNG)

**Comment by serengil** [comment]
install gdown dependency

pip install gdown

**Comment by mahaputrailhamawal** [comment]
Hello Mr. Serengil. Thank you for your answer. I've installed gdown on my laptop. When I run it still appears "No module named gdown". I've tried uninstalling deepface and gdown. After that I installed it too. But the result I get is still the same. Do you have any suggestions for me to solve this problem?

**Comment by serengil** [comment]
you might install those packages into a virtual environment but test it on different one
