### ISSUE TITLE
Bad Accuracy in some cases

### ISSUE THREAD

**Issue by kishanios123** [serengil/deepface#422]
I have observed very bad accuracy mainly in child images...

![ben-white-qDY9ahp0Mto-unsplash](https://user-images.githubusercontent.com/60137209/152100530-05904eeb-6ca5-4c2a-ac5e-9cfea5b4bdc5.jpg)

Showing age 22 years, and gender Woman ...

**Comment by serengil** [comment]
You cannot expect 100% accuracy in a machine learning model.

According to the [tutorial](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/), it has plus and minus 4 years error and gender prediction model has 97% accuracy.

**Comment by kishanios123** [comment]
> You cannot expect 100% accuracy in a machine learning model.
> 
> According to the [tutorial](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/), it has plus and minus 4 years error and gender prediction model has 97% accuracy.

Hello Serengil,

I appreciate your work.

But this difference is not +/- 4 years, there is more error I think.

If you keep this issue open then someone can do work on this point in the future.

**Comment by serengil** [comment]
That is mean absolute error. Of course, some cases have higher errors and some others have lower.

**Comment by kishanios123** [comment]
> That is mean absolute error. Of course, some cases have higher errors and some others have lower.

I have checked every available class... you can add tag for improvement for child cases...

**Comment by skyler14** [comment]
Can we receive some clarifications on how to enable improved estimating for child/elderly. I noticed some pretty bad results on those two groups
