### ISSUE TITLE
About adding find function in api

### ISSUE THREAD

**Issue by arrogant-create** [serengil/deepface#425]
hello, If I want to add a find function to the api to compare the same person in the library, how do I add a function to the api and how to output the json format?

**Comment by serengil** [comment]
I have not added find function in the api on purpose. Because it requires to store pickle files and that might not be convenient for servers.

**Comment by luzik** [comment]
As You are adding more functions to manage pickle file https://github.com/serengil/deepface/issues/516 ,maybe this is good time to rethink also this issue as a whole bigger picture?
