### ISSUE TITLE
error Facial attribute analysis - multiple items

### ISSUE THREAD

**Issue by 110ermya** [serengil/deepface#427]
![image](https://user-images.githubusercontent.com/49756184/155108838-affce7ba-06a4-4441-8b48-32ad00bcee7a.png)

Facial analysis - several cases
I get an error
TypeError: 'tuple' object does not support item assignment
127.0.0.1 - - [22/Feb/2022 13:21:05] "POST /analyze HTTP/1.1" 500 -

**Comment by serengil** [comment]
please share your input image as is.

**Comment by serengil** [comment]
closed due to inactivity
