### ISSUE TITLE
How to train custom model or exiting model on different datasets

### ISSUE THREAD

**Issue by vishalkumar14** [serengil/deepface#43]
the age and gender prediction model performing as good as i want. so i want to train exiting model with larger and FairFace Datasets, so it does not include biases towards Asian and Indian races. currently model is predicting most of the indian as middle eastern and girl black and white picture as male (e.g https://instagram.fdel8-1.fna.fbcdn.net/v/t51.2885-15/sh0.08/e35/s640x640/54511194_316042602429112_4909322531097362425_n.jpg?_nc_ht=instagram.fdel8-1.fna.fbcdn.net&_nc_cat=104&_nc_ohc=mmm3Ugh_-hgAX80XTsi&oh=e1fbaa372f216514d81d3bb86a19da86&oe=5F02F4EE)?

can you help or guide me how to train existing model on dataset

Thank You

**Comment by serengil** [comment]
please follow this tutorial firstly: https://sefiks.com/2019/11/11/race-and-ethnicity-prediction-in-keras/

Secondly, all you need is to update the pre-trained weights in your home folder/.deepace/weights

**Comment by vishalkumar14** [comment]
can you guide me how to update weights of model?

**Comment by serengil** [comment]
Firstly find your home folder

```
from pathlib import Path
home = str(Path.home())
print(home)
```

Weights are stored in home+'/.deepface/weights/' folder.

For example, weight of the age model is home+'/.deepface/weights/age_model_weights.h5'. If you update this h5 file, then you will run the model for new weights.

**Comment by vishalkumar14** [comment]
**faces = face_detector.detectMultiScale(img, 1.3, 5)**

deepface.analysis() is not detecting face in images although face is present, i also test below link image on other face detection model they are detecting face but **face_detector** not?

i unable to understand why model is unable to detect face in this image

https://instagram.fdel8-1.fna.fbcdn.net/v/t51.2885-15/sh0.08/e35/s640x640/54511194_316042602429112_4909322531097362425_n.jpg?_nc_ht=instagram.fdel8-1.fna.fbcdn.net&_nc_cat=104&_nc_ohc=mmm3Ugh_-hgAX80XTsi&oh=e1fbaa372f216514d81d3bb86a19da86&oe=5F02F4EE

**Comment by vishalkumar14** [comment]
i think , i have found the problem, for brighter images haar cascade does not able to detect faces.

**Comment by serengil** [comment]
This might be an issue of opencv. BTW, you can pass enforce_detection argument as False to both verify and analze function. Then, you will not have that exception even if the face could not be detected.

**Comment by vishalkumar14** [comment]
correct me if i am wrong, but this line **if (exact_image == True) or (enforce_detection != True)** 
should be like this **if (enforce_detection != True)** because  if i am passing a exact image and the image does not have a face and enforce_detection is set to True.. function detectFace still returning a value , which is wrong i guess because

**Comment by vishalkumar14** [comment]
or more like this **if (exact_image == True) and (enforce_detection != True)**
