### ISSUE TITLE
questions about Deepface architecture in the paper

### ISSUE THREAD

**Issue by abcsimple** [serengil/deepface#430]
Not sure it’s a right place or not to ask questions about the paper. Hope someone can help me.

The paper defined 32 * 11 * 11 * 3@152 * 152 in Layer C1 (Fig.2.) , means given 32 * 11 * 11 * 3 filers for 152 * 152. However Layer C1 in Fig 2 is 32 * 11 * 11 * 3@142 * 142, I can understand it as the result of convolution 32 * 11 * 11 * 3 is 142 * 142. I’m confused about that.

Another question: still in the Fig.2, how can I get L5 by only implementing ONE convolution layer on L4? It’s hard to figure it out

**Comment by serengil** [comment]
I used deepface model as is. Do not have a deeply information.

**Comment by abcsimple** [comment]
so this is not the official repo of the paper?
