### ISSUE TITLE
Merging Facial Feature Vectors

### ISSUE THREAD

**Issue by SandaruT** [serengil/deepface#432]
Is there a way to merge a couple of vectors of a certain unique face into one vector or is there a way compare many vectors at the same time?

I have a couple of vectors of the same face with different angles generated by the Deepface.represent() function. However as the comparisons can only be done one at a time, I was looking for an approach where I can merge the group of vectors into one vector so that I could just do the comparison process at once. 

Another approach I was looking for was to generate a single vector from the couple of images instead of generating a couple of vectors and merging them. Do you think this is possible?

Optional approach I was thinking was to have a vector generated from a short video of about 5 seconds of a person scanning their face. Is this feasible?

**Comment by serengil** [comment]
Suppose that you have n different 128 dimensional vector

Create a 128 dimensional vector by finding the average of each dimension. That would be your summary vector. You can use this in your experiments.

**Comment by SandaruT** [comment]
Any tips or Code Snippets that would help facilitate the above process?

**Comment by RGuven** [comment]
Maybe you could be any solution but I am writing for those who will study later. 
You can open and parse the pickle file which is generated from deepface.find() or other deepface functions. Then you will see list in list informations and you can calculate easily an average 128d vector using pandas or numpy, up to you.
