### ISSUE TITLE
Resizing Images when being compared with DeepFace using FaceNet

### ISSUE THREAD

**Issue by SandaruT** [serengil/deepface#434]
I am working on a project that requires scanning faces from an image and cross-checking it with another image. However, the accuracy of deepface tends to be poor when I extract the vectors and compare and I'm thinking the issue with this is the images not being in the proper size. How do I resize the images to (160,160) which is the size required by Google Facenet before the vector embeddings are generated? I use Retina Face to extract the faces and then generate the vectors using DeepFace.represent() function. 

Any idea how I could resize it beforehand?

**Comment by serengil** [comment]
img = cv2.resize(img,(160, 160))
