### ISSUE TITLE
Cosine Distance bigger than 1

### ISSUE THREAD

**Issue by TinoCalamia** [serengil/deepface#437]
Hey,

first of all thank you very much for this amazing framework!

I was recently playing around with a facial dataset and using DeepFace. For some models I used the cosine distance and got values bigger than 1. As far as I know the value should be between 0 - 1. Is there anything I am missing? And is this expected?

I am using the most recent version of DeepFace.

Thank you!

**Comment by serengil** [comment]
rounding might cause this. can you share your input image and configuration?

**Comment by TinoCalamia** [comment]
Not sure if this is a rounding issue as I sometimes get values of e.g. 1.3. I am using a variety of images from the LFW database, so this is not happening on a particular image. Using the Tensorflow2.6 image from google cloud platform :)

**Comment by serengil** [comment]
can you share the exact image in LFW?

**Comment by TinoCalamia** [comment]
It happens when I compare the following images:
- African/m.03c4nns/57-FaceId-0_align.jpg
- African/m.02rtz9c/40-FaceId-0_align.jpg

I used FaceNet512 and the cosine distance

**Comment by serengil** [comment]
@TinoCalamia would you please attach the items into this issue? i cannot access the data set.

**Comment by serengil** [comment]
I found a pair in deepface unit tests having a cosine distance greater than 1. 

Besides, I tested same pair with scipy cosine distance formula. The both deepface and scipy return a distance value greater than 1.

```python
from deepface import DeepFace
from deepface.commons import distance as dst
from scipy import spatial

img1_path = "deepface/tests/dataset/img6.jpg"
img2_path = "deepface/tests/dataset/img8.jpg"

#obj = DeepFace.verify(img1_path, img2_path, model_name = "Facenet512", distance_metric="cosine")
#print(obj)

img1 = DeepFace.represent(img1_path, model_name = "Facenet512")
img2 = DeepFace.represent(img2_path, model_name = "Facenet512")

distance_v1 = dst.findCosineDistance(img1, img2)
print(distance_v1)

distance_v2 = spatial.distance.cosine(img1, img2)
print(distance_v2)
```

According to [this](https://stackoverflow.com/questions/68142841/cosine-distance-more-than-1) stackoverflow post, if dot product of these vectors is negative, it's perfectly OK for cosine to return a value greater than 1.

So, this is not a bug.
