### ISSUE TITLE
Could you provide guidance for Database images?

### ISSUE THREAD

**Issue by chrisroge** [serengil/deepface#438]
I would like to say I deeply appreciate the work you have done on this solution.  It is really excellent.

Would you be able to provide guidance on the quantity and quality of images which would be optimal for the database?

I am using:
Facenet512
Euclidian_l2
retinaface

I have a small number of images in my database folder (10) and I cropped the images down to only show the face

The images I am feeding in are 2560 x 1920 (color) because I want to provide the best possible resolution for what will be quite small faces

**Comment by serengil** [comment]
you can store thousands of identities on your db

**Comment by serengil** [comment]
you do not have to crop. deepface handles cropping.
