### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by INF800** [serengil/deepface#439]
Can we train using our own data

**Comment by chrisroge** [comment]
Actually I now doubt what I said... I see what you mean about the model itself...

"Already built model is passed"

this is shown when I run Deepface.find even for the first time against a new DB so I guess the file stored is just tag data?

**Comment by INF800** [comment]
The images that we store in db are for calculating similarities. Training models is different.

**Comment by serengil** [comment]
nope training is out of the scope. in deepface you are using pre-trained models.
