### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by AmoghM** [serengil/deepface#44]
I am unable to install deepface via pip:
> `pip install deepface` resulted as-

`ERROR: Could not find a version that satisfies the requirement deepface (from versions: none)
ERROR: No matching distribution found for deepface`

**Comment by serengil** [comment]
This is very interesting. You can install it by hand. Clone the source code from github. Change your directory to deepface and run "pip install -e ." where setup.py exists.

```
git clone https://github.com/serengil/deepface.git
cd deepface
pip install -e .
```
