### ISSUE TITLE
RTSP stream support in DeepFace.stream()?

### ISSUE THREAD

**Issue by jshep321** [serengil/deepface#444]
Hi,
I have stream working with an http mjpeg stream:  DeepFace.stream(source = "http://10.0.0.101:8081")

However an H264 rtsp stream only grabs the first frame (I think) and then crashes after about 30s.    DeepFace.stream(source = "rtsp://10.0.0.102:8554/stream")

Are there simple settings for cv2.VideoCapture to handle this or is this a limitation of deepface?

Thanks!

**Comment by serengil** [comment]
You might ask this question in the opencv repo because deepface is using opencv directly. I think this is not directly related to deepface.
