### ISSUE TITLE
Very low accuracy

### ISSUE THREAD

**Issue by rinath** [serengil/deepface#445]
I tried to compare the performance of this code 1:
`from deepface import DeepFace
DeepFace.stream(db_path='./', model_name='Facenet', detector_backend='mtcnn',
	time_threshold=1, frame_threshold=1)`
run on windows 10, tensorflow 2.8 with no GPU support
with a similar framework with dlib and particularly with this example code 2 https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam.py (added my own pictures) on ubuntu 20.04
For each framework I added only 4 images (4 different people). MTCNN detects faces pretty good, but face recognition with code 1 works really really bad (similar performance or worse than opencv haar method), it can recognize myself only at particular lightning and position, while dlib (https://github.com/ageitgey/face_recognition) recognizes every frame really good with different lightning and position.
What could be the issue here? As I understand the face recognition performance with Facenet and dlib should be very similar.

**Comment by serengil** [comment]
You can try dlib within deepface.

`DeepFace.stream(db_path='./', model_name='Dlib', detector_backend='dlib', time_threshold=1, frame_threshold=1)`

Besides, those face recognition models are ready to use. I have not train them. Scores are shared in the original studies. Facenet researchers claim that they have 99% accuracy. If you cannot reach that score, nothing to do.
