### ISSUE TITLE
'prediction_classes' is not defined

### ISSUE THREAD

**Issue by Winchester37** [serengil/deepface#446]
öncelikle böyle bir repo hazırladığınız çok teşekkür ederim bitirme tezim için birkaç çalışma yapıyorum Şefik bey örnek kodlarınızda yer alan Ensemble-Face-Recognition.py dosyasını ve sizin datasetiniz üzerinde test amaçlı çalıştırdım ancak prediction_classes tanımlı değil hatası alıyorum bu alanda yeni olduğum için tam anlayamadım yardımcı olursanız sevinirim

**Comment by serengil** [comment]
prediction_classes'ı predictions şeklinde değiştirerek tekrar dener misiniz?

**Comment by Winchester37** [comment]
Cevabınız için teşekkür ederim şefik bey ancak şimdide farklı bir hata söz konusu örnek kodunuz dediğiniz yer haricinde hiç bir değişiklik yapmadım datasete örnek olarak sunduğunuz

![image](https://user-images.githubusercontent.com/15074140/159735788-2eda9818-a270-41a9-98e0-abdfaaf93c4a.png)

**Comment by serengil** [comment]
Aşağıdaki şekilde dener misiniz bir de?

ax1 = fig.add_subplot(5, 2, figure_idx)

**Comment by Winchester37** [comment]
aynı hatayı verdi şefik bey
![image](https://user-images.githubusercontent.com/15074140/159949463-8196d0df-b103-4968-9570-b6537f599322.png)

**Comment by Winchester37** [comment]
rakkamı 6 çıkarttım şimdi farklı bir hata meydana geldi 
![image](https://user-images.githubusercontent.com/15074140/159956786-0e623a25-ac41-40c7-9dff-ac1a2820e12f.png)

**Comment by serengil** [comment]
Ben bir hatamı fark ettim. prediction_classes hesabını aşağıdaki şekilde yapar mısın?

```
predictions = gbm.predict(x_test)

prediction_classes = []
for prediction in predictions:
    prediction_class = np.argmax(prediction)
    prediction_classes.append(prediction_class)

cm = confusion_matrix(y_test, prediction_classes)
```

**Comment by Winchester37** [comment]
Üssteki hatanın aynısını verdi şefik bey ancak bu hataya ramen pivot falan çıkartıyor ancak f1 skoru falan vermiyor

**Comment by serengil** [comment]
gbm.predict adımında hepsini 0 tahmin ediyor olmalı ama neden bilemedim

**Comment by Winchester37** [comment]
Çıktığı CSV de falan herşey çok güzel tahminliyor. Dataset değiştirdim yine aynı yerde aynı hatayı verdi yardım çabaniz için çok teşekkürler şefik bey

**Comment by serengil** [comment]
sklearn'in yeni versiyonundan kaynakli bir sey sanirim. y_test numpy tipindeyken prediction_class list tipinde. Aşağıdaki gibi y_testi listeye çevirirseniz problem ortadan kalkmalı.

```
predictions = gbm.predict(x_test)

prediction_classes = []
for prediction in predictions:
    prediction_class = np.argmax(prediction)
    prediction_classes.append(prediction_class)

y_test = list(y_test)

cm = confusion_matrix(y_test, prediction_classes)
print(cm)
```

**Comment by serengil** [comment]
ayrıca kodu repo'da da degistirdim. guncel halini cekip kullanirsaniz daha faydali olur.
