### ISSUE TITLE
Question regarding facenet

### ISSUE THREAD

**Issue by blueprintparadise** [serengil/deepface#448]
Why did you manually add the inceptionnetv2 instead of importing it from the tensorflow API?

**Comment by serengil** [comment]
I followed what reference study did. There might be some little differences.

**Comment by blueprintparadise** [comment]
Can you share what reference study you followed?

**Comment by serengil** [comment]
follow the links in the read me - license section.

**Comment by blueprintparadise** [comment]
The link for facenet in license section does not work

**Comment by rinath** [comment]
this guy likes to close issues without answering. 3 issues open, 413 closed lol and most of the closed issues without direct answers. why do you even reply if you do not want to answer

**Comment by serengil** [comment]
@blueprintparadise as i mentioned you should follow the link in the license section of read-me. It will redirect you to [here](https://github.com/davidsandberg/facenet/blob/master/LICENSE.md). I re-checked it and the link works! 

@rinath I cannot see any issue here. the real issues are in the status of open for a long time.
