### ISSUE TITLE
Have you ever re-implemented 3D face alignment in facenet of Facebook?

### ISSUE THREAD

**Issue by MengHao666** [serengil/deepface#449]
Actually ,in paper `DeepFace: Closing the Gap to Human-Level Performance in Face Verification`, they use 3D face alignment to boost accuracy. In this way , the alignment method [here](https://github.com/serengil/deepface/blob/b13cca851f6415372e7baf988ba6d2098af1297e/deepface/detectors/FaceDetector.py#L68) looks quiet simple compared with the 3D face alignment method. Have you ever re-implemented their method?

**Comment by serengil** [comment]
Deepface model ıs cloned from this project: https://github.com/swghosh/DeepFace . This is mentioned in the read-me of the repo already. Similar to reference project, this package just uses 2d alignment.
