### ISSUE TITLE
How to adjust thresholds for find and verify

### ISSUE THREAD

**Issue by Henrix-Andre** [serengil/deepface#451]
I've ran the script to generate the 'rules' and new value of the threshold as the tutorial on fine tuning explained but still running any other verification or find command still marks the distance threshold as 0.4.

I'd like to know if there is any way to change it directly rather than having to add a check to compare the distance calculated with a custom threshold.

**Comment by serengil** [comment]
Thresholds are defined here hard-coded: https://github.com/serengil/deepface/blob/b13cca851f6415372e7baf988ba6d2098af1297e/deepface/commons/distance.py#L24

You can use the distance key in the response of verify function and check it is less than the threshold value you want to set.
