### ISSUE TITLE
How train new model

### ISSUE THREAD

**Issue by lavrenkov-sketch** [serengil/deepface#452]
Hello.
how you trained the Facenet512 [model,](https://github.com/serengil/deepface/blob/master/deepface/basemodels/Facenet512.py) I would like to make another one with even more dimensions and use it in this project

**Comment by serengil** [comment]
I found it as pre-trained. Please follow the license section in the read me of the repo, you can find its original work if you follow the links.

When you train a new model, you should do the following steps in deepface.

1- Add the structure and weight loading steps here in a dedicated file: https://github.com/serengil/deepface/tree/master/deepface/basemodels

2- Reference your new model in the DeepFace.py: https://github.com/serengil/deepface/blob/b13cca851f6415372e7baf988ba6d2098af1297e/deepface/DeepFace.py#L40
