### ISSUE TITLE
how to get top 2 similar detected faces?

### ISSUE THREAD

**Issue by akashAD98** [serengil/deepface#455]
I have few qustion
1).when i run Deepface.stream on video ,im getting single detected output,  

![image](https://user-images.githubusercontent.com/62583018/163319102-2030f820-e2ee-4ac6-bd3d-834606f349f6.png)

so i want to know how can we get the top two or more similar images, where is the code to get top similarities detected images?

2).on top of images, we are getting multiple detection results. so what's the logic behind it ? distance = 0 means image accuracy is 100% & 1 is for False? im correct?
![image](https://user-images.githubusercontent.com/62583018/163319250-1a34dd03-7f52-4f0f-9814-0feef6d92cde.png)

3)In some cases distance is very less but prediction is false,you can see distance with less probablity is false & in some cases having more distance is also true. How can we solve this isse?
![image](https://user-images.githubusercontent.com/62583018/163319562-d8fa245f-cc23-4757-a6ef-114b533320fa.png)
 

4.) Taking more images in database will model confuse?? i have 50 actors & each actor has 500 images? whats your suggetion,should i take less images or more? will model confuse if there is more images?

**Comment by serengil** [comment]
1- you cannot do it with stream function. but find function does this.
2- the less distance, the more similar faces
3- you cannot solve this. no models come with 100% accuracy in machine learning
4- one image per person is enough (one shot learning), but you are still able to use many images per person. it will not confuse the model.

**Comment by akashAD98** [comment]
@serengil thanks for your valuable info
