### ISSUE TITLE
os error jupyter deepface

### ISSUE THREAD

**Issue by olfa-askri-esen** [serengil/deepface#459]
![issue](https://user-images.githubusercontent.com/98912003/163901448-8257b7d2-6bc2-45a2-ae4d-3d990e6e59e2.PNG)
hello i  installed the deepface but when i excute analyze commande this error appear how could i fix it please .Thank you

**Comment by serengil** [comment]
could you share the all error message?

**Comment by serengil** [comment]
closed due to inactivity
