### ISSUE TITLE
disk space issue

### ISSUE THREAD

**Issue by arkkanoid** [serengil/deepface#46]
I've installed deepface successfully and now I'm running this command in a loop:

`res = DeepFace.analyze("img.jpg", actions = ['age', 'gender', 'race', 'emotion'])`

When I run the script it takes a lot of disk space (+60GB) , getting a "no space left on device" error. Then the process ends it free up the disk space used. 
I'm not sure in which directory it writes all this data and how to avoid it.
Can you help me?

Thank you

**Comment by serengil** [comment]
You do not have to build a for loop. Could you try the following approach?

```
res = DeepFace.analyze(["img1.jpg", "img2.jpg", "img3.jpg"], actions = ['age', 'gender', 'race', 'emotion'])
print(res)
```

**Comment by arkkanoid** [comment]
Hi @serengil , 
Yes it works, however I'm analyzing a large dataset (thousands of images) so I need a for loop.
I don't understand why it takes a large amount of disk space, and if there's a way to free up it once analyze function ends.

Thank you in advance

**Comment by serengil** [comment]
Every call of analyze function builds those facial attribute analysis model. That's the problem you had.

You can build a for loop and store all images in a python list, and then pass this list to analze function as well. In this way, those models build once.

```
#prepare test set
test_set = []
for i in range(0, 10000):
   test_set.append("img_%s.jpg" % (i))

#call analyze function once
res = DeepFace.analyze(test_set, actions = ['age', 'gender', 'race', 'emotion'])

for i in range(0, len(res)):
   print(res[i])
```
