### ISSUE TITLE
deepface.Deepface.analyze() for opencv frame.

### ISSUE THREAD

**Issue by aaa9753** [serengil/deepface#460]
I'm trying to code a program that detects my visible emotion from live webcam footage. I'm using opencv to get images from my webcam. At the moment I'm getting the frame from the webcam then saving it to a .png file, then I'm calling Deepface.analyze() on the .png image. That method makes the program not perform as well as it could. It there an option to call the analyze function on an opencv image? 
Here's my code:
`
import cv2
import numpy
from deepface import DeepFace

class App:
	def __init__(self):
		self.GREEN = (0, 255, 0) #in BGR
		self.face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")
		self.previous_face = [[0,0,0,0]]

		print("Setting things up...")
		self.camera = cv2.VideoCapture(0, cv2.CAP_DSHOW)
		print("Now running...")

	def get_image_from_webcam(self):
		sucess, frame = self.camera.read()

		if not sucess:
			return "Error -- could not capture output from your webcam."

		grayscale_image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

		return frame, grayscale_image

	def detect_face(self, grayscale_image):
		scale_factor = 1.15
		min_neighbors = 5
		flags = cv2.CASCADE_SCALE_IMAGE
		face = self.face_cascade.detectMultiScale(grayscale_image, scale_factor, min_neighbors)
	
		return face

	def render_text(self, frame, text, bottom_left_xy):
		cv2.putText(frame, text, bottom_left_xy, cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 1, 2)

	def mark_detected_face(self, frame, detected_face):
		for (x, y, width, height) in detected_face:
			cv2.rectangle(frame, (x, y), (x + width, y + height), self.GREEN, 4)

	def save_webcam_image(self, frame):
		cv2.imwrite("image.png", frame)

	def get_dominant_emotion(self):
		dominant_emotion = DeepFace.analyze('image.png', actions=['emotion'], enforce_detection=False)
		return dominant_emotion

	def run(self):
		while True:
			frame, grayscale_image = self.get_image_from_webcam()

			self.save_webcam_image(frame)

			#so there's np flickering --> if no face detected, previous detected face will replace it else previos detected face = detected face
			detected_face = self.detect_face(grayscale_image)
			if (len(detected_face)) != 0:
				self.previous_face = detected_face
			else:
				detected_face = self.previous_face

			self.mark_detected_face(frame, detected_face)

			dominant_emotion = self.get_dominant_emotion()
			
			self.render_text(frame, dominant_emotion['dominant_emotion'], (detected_face[0][0], detected_face[0][1]))

			cv2.imshow("How are you feeling?", frame)

			key = cv2.waitKey(1)

			#if window is closed
			if cv2.getWindowProperty("How are you feeling?", cv2.WND_PROP_VISIBLE) < 1:
				break

		self.camera.release()
		cv2.destroyAllWindows()

if __name__ == '__main__':
	app = App()
	app.run()
`

**Comment by serengil** [comment]
DeepFace.stream does this

**Comment by aaa9753** [comment]
What's the function parameters?
