### ISSUE TITLE
Missing Function "detectFace"

### ISSUE THREAD

**Issue by Risingabhi** [serengil/deepface#462]
Am I not sure, but this code uses function detectFace, i cant find the same func in functions.py

`#using DEEPFACE WRAPPER 

from deepface.commons import functions
backends = ['opencv', 'ssd', 'dlib', 'mtcnn', 'retinaface']
img1 = functions.detectFace("img1.jpg", target_size=input_shape, detector_backend = backends[3])
img2 = functions.detectFace("img2.jpg", target_size=input_shape, detector_backend = backends[3])`

As per the file functions.py in line 96:

`def detect_face(img, detector_backend = 'opencv', grayscale = False, enforce_detection = True, align = True):

	img_region = [0, 0, img.shape[0], img.shape[1]]

	#----------------------------------------------
	#people would like to skip detection and alignment if they already have pre-processed images
	if detector_backend == 'skip':
		return img, img_region

	#----------------------------------------------

	#detector stored in a global variable in FaceDetector object.
	#this call should be completed very fast because it will return found in memory
	#it will not build face detector model in each call (consider for loops)
	face_detector = FaceDetector.build_model(detector_backend)

	try:
		detected_face, img_region = FaceDetector.detect_face(face_detector, detector_backend, img, align)
	except: #if detected face shape is (0, 0) and alignment cannot be performed, this block will be run
		detected_face = None

	if (isinstance(detected_face, np.ndarray)):
		return detected_face, img_region
	else:
		if detected_face == None:
			if enforce_detection != True:
				return img, img_region
			else:
				raise ValueError("Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.")`

**Comment by serengil** [comment]
it is replaced with preprocess_face function
