### ISSUE TITLE
Confusing behavior with np.array represented images

### ISSUE THREAD

**Issue by andrii0yerko** [serengil/deepface#463]
Hi! Thank you for this great framework

The only thing I found confusing is the option of usage of numpy arrays as input.

DeepFace.represent docstring says
> img_path: exact image path, numpy array or based64 encoded images could be passed.

But actually, if img_path is a path - the image will be loaded [here](https://github.com/serengil/deepface/blob/e4c3883f5902a4619725f4c2df4646d107f1e25a/deepface/commons/functions.py#L92) using cv2, which means that it will be a BGR array. But if img_path is a numpy array - no additional transformation is performed, which means that np.array should be already a BGR image to receive the same result as with the file path.

This little thing was very unobvious to me and not specified in the docstring, but can be really crucial, because embedding of the RGB and BGR inputs differs up to 0.5 cosine distance in some cases.

So, I'd like to ask you to add more documentation or examples specifically for this feature, because I believe represent is not the only function that can return misleading results for RGB input. Thanks

**Comment by serengil** [comment]
right, if you are using numpy array then you should use BGR format. I will add this in the next release.

**Comment by MarriamSiddiqui** [comment]
Is this feature added yet? I have obtained image in np array format using the following the code line:
image = cv2.cvtColor(np.reshape(image_data, (height, width, channels)), cv2.COLOR_BGR2RGB)
since the model takes the path, How can i use the deepface model with this format? is there some built in function or work around?
