### ISSUE TITLE
OS error occurs when running DeepFace.stream()

### ISSUE THREAD

**Issue by thushaltk** [serengil/deepface#465]
Hello, I am completely new to deepface and I recently faced an error stated in this image when running DeepFace.stream(). I tried to reinstall deepface, keras and h5py packages but the problem still occurs. Any solutions for this?

This is what i ran,
[
![image](https://user-images.githubusercontent.com/62991941/165404798-59d5509e-4d4d-432e-9ad2-48474929d9ab.png)
](url)

This is the error,
![Screenshot 2022-04-27 040920](https://user-images.githubusercontent.com/62991941/165404920-fe5a8c24-31e8-4e93-97a0-31e83ec2ccb6.jpg)

**Comment by serengil** [comment]
this is the all error message?

**Comment by serengil** [comment]
this is obvious dependency problem - not directly related to deepface
