### ISSUE TITLE
Emotion model ignores DEEPFACE_HOME environment variable in container environment

### ISSUE THREAD

**Issue by Blacksuan19** [serengil/deepface#467]
Hello, 
I'm trying to run deepface for mainly emotion detection in a lambda function through a docker image, my docker file explicitly sets the DEEPFACE_HOME env variable, however Emotion model still tries to download to the home folder with this error
```python
[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 27, in lambda_handler
    dom_em, em_df = get_emotions(frames)
  File "/var/task/utils.py", line 41, in get_emotions
    result = DeepFace.analyze(
  File "/var/task/deepface/DeepFace.py", line 349, in analyze
    models['emotion'] = build_model('Emotion')
  File "/var/task/deepface/DeepFace.py", line 61, in build_model
    model = model()
  File "/var/task/deepface/extendedmodels/Emotion.py", line 60, in loadModel
    gdown.download(url, output, quiet=False)
  File "/var/task/gdown/download.py", line 120, in download
    os.makedirs(cache_dir)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
```

checking the file `/var/task/deepface/extendedmodels/Emotion.py` I can see that it does take get the home directory using `functions.get_deepface_home()`

```python
home = functions.get_deepface_home()

if os.path.isfile(home+'/.deepface/weights/facial_expression_model_weights.h5') != True:
print("facial_expression_model_weights.h5 will be downloaded...")

output = home+'/.deepface/weights/facial_expression_model_weights.h5'
gdown.download(url, output, quiet=False)
```

I tried to manually set the environment variable from python before importing DeepFace and faced the same error
```python

# set deepface home
os.environ.setdefault("DEEPFACE_HOME", "/tmp")
from deepface import DeepFace
```
checking the lambda function logs, there is some output from DeepFace, it seems to create `.deepface` folder at the right place but still fails to use it properly
```
Directory  /tmp /.deepface created
Directory  /tmp /.deepface/weights created
facial_expression_model_weights.h5 will be downloaded...
```
Any idea why it's ignoring the environment variable despite acknowledging it?

**Comment by Blacksuan19** [comment]
if you create the directories in `/tmp` and download the model with wget and finally set `DEEPFACE_HOME=/tmp`, everything works as expected, I'm not sure how this can be integrated into the library but a better solution would be to give the user the ability to specify that directory when they use a module like analyze or stream instead of automatically downloading it when the library is imported, here's the code for the workaround

```python
import os
from pathlib import Path

def download_emotion_model():
    model_url = "https://github.com/serengil/deepface_models/releases/download/v1.0/facial_expression_model_weights.h5"
    os.system(
        f"wget {model_url} -O /tmp/.deepface/weights/facial_expression_model_weights.h5"
    )

# now in the  function DeepFace is used
def analyze_frames(frames: List) -> None:

    # set deepface home
    os.environ.setdefault("DEEPFACE_HOME", "/tmp")
    # download emotion model manually
    Path("/tmp/.deepface/weights").mkdir(parents=True, exist_ok=True)
    download_emotion_model()
    from deepface import DeepFace

    # analyze frame
    result = DeepFace.analyze(img_path=np.array(frames[0]), actions=("emotion",))
...
```

**Comment by serengil** [comment]
can you set the env var as

os.environ["DEEPFACE_HOME"] = "/tmp"

**Comment by Blacksuan19** [comment]
> can you set the env var as
> 
> ```
> os.environ["DEEPFACE_HOME"] = "/tmp"
> ```
> 
> btw, your workraround seems well!

Still generates the same error.

**Comment by serengil** [comment]
i closed this issue because @Blacksuan19 already proposed a workaround.
