### ISSUE TITLE
ArcFace model in DeepFace for commercial use?

### ISSUE THREAD

**Issue by buckeye17** [serengil/deepface#469]
I am concerned about using the ArcFace model for commercial purposes.  Can @serengil clarify whether the ArcFace model weights in DeepFace were produced by the open source community's own training?

[This video](https://youtu.be/i_MOwvhbLdI?t=48) mentions that the models in DeepFace are "retrained" by the open source community, but it seems to predate ArcFace, since ArcFace isn't mentioned in the video.

_Originally posted by @buckeye17 in https://github.com/serengil/deepface/issues/273#issuecomment-1113906155_

**Comment by serengil** [comment]
Reference models cited in the license section of the read me.

This is the reference study of arcface: https://github.com/leondgarse/Keras_insightface/blob/master/LICENSE

Also license type of the original arcface model is mentioned here: https://github.com/deepinsight/insightface/blob/master/LICENSE

They are both mit license. So, it seems you are free to use it for any purpose.

**Comment by buckeye17** [comment]
Thanks @serengil.  Knowing that the ArcFace model weights come from [Keras-InsightFace](https://github.com/leondgarse/Keras_insightface) clears up my confusion!

**Comment by ziyuang** [comment]
Which model is it in Keras-InsightFace? I cannot find ArcFace in the model list: https://github.com/leondgarse/Keras_insightface/releases/tag/v1.0.0
