### ISSUE TITLE
small bug in face-recognition-how.py

### ISSUE THREAD

**Issue by xiexvying** [serengil/deepface#470]
when I run face-recognition-how.py ,it gives me an error as follows:

> Traceback (most recent call last):
  File "D:/code/deepface-master/tests/face-recognition-how.py", line 26, in <module>
    img1 = functions.preprocess_face("dataset/img1.jpg", input_shape)
  File "D:\code\deepface-master\deepface\commons\functions.py", line 200, in preprocess_face
    factor_0 = target_size[0] / img.shape[0]
IndexError: list index out of range

so I try to print target_size[0], the same error as above.It looks like some wrong with parameter target_size. 
then I find some codes in this file:

`input_shape = model.layers[0].input_shape[1:3]
print("model input shape: ", model.layers[0].input_shape[1:])
print("model output shape: ", model.layers[-1].input_shape[-1])`

Print result as follows:
model input shape:  []
model output shape:  2622

It's a little bug because model.layers[0].input_shape) is [(None, 224, 224, 3)], so we should just change input_shape like this:

input_shape = model.layers[0].input_shape[0][1:3]

**Comment by serengil** [comment]
that is because of tensorflow version. i fixed this in the main code of deepface but it seems that i have to do it here, too. thank you.
