### ISSUE TITLE
Adding unit test workflow

### ISSUE THREAD

**Issue by onuratakan** [serengil/deepface#472]
I am expert for open source project management, and we must add a workflow for testing and using in the process of development. Can you assign me for this workflow @serengil .

Best regards,

Onur Atakan ULUSOY

**Comment by serengil** [comment]
this should be run before any PR: https://github.com/serengil/deepface/blob/master/tests/unit_tests.py

workflow is not a must IMO

**Comment by onuratakan** [comment]
For my window the testing is most important part of an development process and github provide this with action via integration with pr.

**Comment by onuratakan** [comment]
But its my mistake. I should look at to the contribution guilde.
