### ISSUE TITLE
About copyright in licence

### ISSUE THREAD

**Issue by onuratakan** [serengil/deepface#479]
Hello @serengili, you know i said "this project is awesome" its true but there is a something that i must ask.

The project license is on just you. You can change, you can sell, you can transfer and other thinks you want. You are project creator and i think me and other contributor thanks to you for your work and idea.

But again i think me and other contributor wants to stay safe in developming this project. The contributors does not want any selling removing or changing project or the possibility of this.

So i want to add me and other contributors to licence and making the project immortal. By accepting this friendly offer, you open the project more to volunteer developers like me and make a generous offer of making your work available to everyone.

Best regards,

Onur Atakan ULUSOY | Contributor of DeepFace

**Comment by serengil** [comment]
i do not take kindly to something

**Comment by onuratakan** [comment]
> i do not take kindly to this

I respect your decision, but I think this topic deserves more explanation.

**Comment by onuratakan** [comment]
Also you can use "DeepFace developers" after your copyright. To be honest i wan to you give your right work to the world it s difficult but also its a importand milestone.
