### ISSUE TITLE
Running api.py yeilds: module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by Basant206** [serengil/deepface#48]
Anyone experience the same problem/know how to fix it? I believe I might need to downgrade tensorflow/keras but I have also had trouble doing this.

**Comment by serengil** [comment]
the newer tensorflow versions come with this issue. please install the packages with the following commands.

```
pip install tensorflow==1.9.0
pip install keras==2.2.0
pip install deepface --no-deps
```

In this way, you can install working versions of dependent libraries.

**Comment by vvkuryshev** [comment]
I have the same problem. Trying to run pip install tensorflow == 1.9.0 results in an error:
C:\WINDOWS\system32>pip install tensorflow==1.9.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.9.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1)
ERROR: No matching distribution found for tensorflow==1.9.0

Windows10
Python 3.8.
