### ISSUE TITLE
detect_faces() bug

### ISSUE THREAD

**Issue by buckeye17** [serengil/deepface#480]
As far as I can tell, there is a bug in the `FaceDetector.detect_faces()` method.  I use the following code to pass an image via it's path:
> face_img_path = "/path/to/image.jpg"
> backends = ["opencv", "ssd", "dlib", "mtcnn", "retinaface"]
> face_detector = build_model(backends[4])
> result = detect_faces(face_detector, backends[4], face_img_path)

This causes the detector wrapper to throw an error.  When I dig into the error, it looks like the wrapper wants the image as a numpy array rather than as a file path.  Here's the error message (the `img` variable mentioned below is actually a string in this case):
> Traceback (most recent call last):
>   File ".../Documents/rare_fusion/face/play.py", line 31, in <module>
>     result = detect_faces(face_detector, backends[4], ".../Documents/rare_fusion/face/Tom-Cruise-1.jpg")
>   File "...\Anaconda3\envs\face\lib\site-packages\deepface\detectors\FaceDetector.py", line 61, in detect_faces
>     obj = detect_face(face_detector, img, align)
>   File "...\Anaconda3\envs\face\lib\site-packages\deepface\detectors\RetinaFaceWrapper.py", line 49, in detect_face
>     detected_face = img[int(facial_area[1]): int(facial_area[3]), int(facial_area[0]): int(facial_area[2])]
> TypeError: string indices must be integers

So I use the following code to provide the `detect_faces()` method with a numpy array:
> face_img_path = "/path/to/image.jpg"
> backends = ["opencv", "ssd", "dlib", "mtcnn", "retinaface"]
> face_detector = build_model(backends[4])
> face_img = preprocess_face(face_img_path, detector_backend=backends[4])
> result = detect_faces(face_detector, backends[4], face_img)

Now I get an error from RetinaFace's detector.  When I dig into this error, it appears the detector is expecting the image path rather than a numpy array.  Here's the error message (the `img_path` variable mentioned below is actually the numpy array):
> Traceback (most recent call last):
>   File ".../Documents/rare_fusion/face/play.py", line 31, in <module>
>     result = detect_faces(face_detector, backends[4], face_img)
>   File "...\Anaconda3\envs\face\lib\site-packages\deepface\detectors\FaceDetector.py", line 61, in detect_faces
>     obj = detect_face(face_detector, img, align)
>   File "...\Anaconda3\envs\face\lib\site-packages\deepface\detectors\RetinaFaceWrapper.py", line 35, in detect_face
>     obj = RetinaFace.detect_faces(img, model = face_detector, threshold = 0.9)
>   File "...\Anaconda3\envs\face\lib\site-packages\retinaface\RetinaFace.py", line 64, in detect_faces
>     img = get_image(img_path)
>   File "...\Anaconda3\envs\face\lib\site-packages\retinaface\RetinaFace.py", line 55, in get_image
>     raise ValueError("Input image needs to have 3 channels at must not be empty.")
> ValueError: Input image needs to have 3 channels at must not be empty.

So it seems the `FaceDetector.detect_faces()` method is broken, because there doesn't appear to be a valid way to pass an image into it.  I haven't tried this for other backends besides `retinaface`.

**Comment by serengil** [comment]
this is not bug. you should read your image with cv2.imread before feeding this function. you can check how it is called in the deepface.py

**Comment by buckeye17** [comment]
Thanks @serengil.  I assumed that `preprocess_face()` was doing all of the image reading, normalization, resizing, etc.  I didn't expect it to use `detect_face()` based on the name.  That's what led me astray.
