### ISSUE TITLE
Threshold

### ISSUE THREAD

**Issue by AhmedLiwane** [serengil/deepface#484]
I want to increase the threshold, is it possible?

**Comment by serengil** [comment]
yes. you should use the distance key in the response instead of verified key.

the library actually checks distance is less than the threshold in the response. you can check this condition is satisfied manually after calling verify function.

**Comment by OttomanZ** [comment]
@serengil How does the distance key affect the threshold as in,

If the distance key is smaller does it mean that it's more likely to be that person?

**Comment by OttomanZ** [comment]
No Worries got it! Dealing with quite similar related faces so,
![image](https://user-images.githubusercontent.com/79105382/186451473-a8fdcfa0-e6f7-4b05-9b95-f39440eba5d2.png)
