### ISSUE TITLE
Switch to pure entry_points console_scripts

### ISSUE THREAD

**Issue by BastianZim** [serengil/deepface#486]
Hi, I'm currently in the process of adding this tool to conda-forge and I was wondering if it would be possible to not use the `scripts` tag but to switch to pure  entry_points console_scripts or something else? That would make packaging much easier for us as we can then package it platform-independent. 
Thanks!

Ref: https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#scripts

**Comment by serengil** [comment]
i updated setu.py and removed scripts key

**Comment by BastianZim** [comment]
Thank you!

**Comment by serengil** [comment]
please inform me if you add this package to conda

**Comment by BastianZim** [comment]
The PR is live already. :) 
Would you like to be added as a maintainer?

**Comment by serengil** [comment]
Found it here: https://github.com/conda-forge/staged-recipes/pull/19005

I would be happy if you add me as a maintainer

**Comment by serengil** [comment]
how can i publish a new release in conda? i did it before for pypi but no experience on conda.

**Comment by BastianZim** [comment]
Our bots will pick up a release and open a PR a couple of hours later. There, the version and SHA will already be updated, only the dependencies, license, etc. will need to be updated manually. 
But I'm also maintaining it and will do so you don't really need to do anything besides maybe responding to potential issues.

**Comment by BastianZim** [comment]
Yes, that’s correct.

**Comment by serengil** [comment]
@BastianZim hello, deepface started to fail in conda builds.

For instance, [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=855107&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7) it is getting this error

```shell
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/feedstock_root/build_artifacts/deepface_1704766023421/work/setup.py", line 6, in <module>
      with open("requirements.txt", "r", encoding="utf-8") as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

It is saying that it cannot find requirements.txt. It is not available in wheel package but it has never been.

Do you have any idea why this happens? Putting requirements.txt into wheel package will sort this?

**Comment by BastianZim** [comment]
> Putting requirements.txt into wheel package will sort this? 

I have added a more detailed explanation in the other feedstock but yet, just including the files mentioned in the setup.py (readme and reqs) is sufficient to fix this.
