### ISSUE TITLE
Automatic publish action

### ISSUE THREAD

**Issue by onuratakan** [serengil/deepface#488]
Hello, i can write a action for automatic publishing the pypi release, its will triggered with release publishing from github.

Ex. https://github.com/Decentra-Network/Decentra-Network/blob/master/.github/workflows/deploys.yml

Best regards,

Onur Atakan ULUSOY

**Comment by serengil** [comment]
hi @onuratakan , thank you but auto-deploy is off intentfully. i prefer to wait a couple of changes for a release.

still, appreciate for your contribution and support.
