### ISSUE TITLE
Run deepface on GPU

### ISSUE THREAD

**Issue by nadia-maarfavi** [serengil/deepface#489]
Hello

I wonder how we can run the DeepFace library on GPU. I tried your suggestion on other posts, but none of them worked.
I installed TensorFlow-gpu before the DeepFace and set CUDA_VISIBLE_DEVICES on my code. But none of the tricks works.  I also tried to install DeepFace with no dependencies but no luck.
When running on Google Colab, the library uses the GPU, but when I tried in my system, it did not. 
Can you please advise how to resolve it?

import time
from deepface import DeepFace
from retinaface import RetinaFace
import os
#os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
#os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"

start = time.time()
faces = RetinaFace.extract_faces("friends2.jpg")
print("There are ", len(faces), " faces in the image")

for face in faces:
    obj = DeepFace.analyze(face, detector_backend='skip')

end = time.time()
print("Finished at:  ", end - start)

It took 12 second on my machine, but 3 sec on Google Colab. 

Python: 3.6.9
tensorflow-gpu:  2.6.2
Ubuntu: 18.04.6 LTS

Thanks
Nadia

**Comment by serengil** [comment]
you should open an issue on tensorflow repo because this is directly related to it. it seems your gpu configuration is not okay.
