### ISSUE TITLE
Library Failed to install . CheaquePy ver 12.0.0   

### ISSUE THREAD

**Issue by Zaeem6100** [serengil/deepface#492]
Failed to install opencv-python>=4.5.5.64 from https://files.pythonhosted.org/packages/3c/61/ee4496192ed27f657532fdf0d814b05b9787e7fc5122ed3ca57282bae69c/opencv-python-4.5.5.64.tar.gz (from deepface).

Python =  > 3.10

**Comment by serengil** [comment]
install deepface with no dependencies: pip install deepface --no-deps

install opencv's latest version: pip install opencv-python

ps: sface will not work if you do not install the opencv version 4.5.5.64
