### ISSUE TITLE
Compile Models to AWS Inferterian

### ISSUE THREAD

**Issue by shirasael** [serengil/deepface#499]
Hi,

I am trying to compile the models used in DeepFace to work with AWS's Inferteria cheaps, using AWS tensorflow-neuron.
Have you ever tries to do something like this? Out of the box, simply saving the models and calling `tensorflow_neuron.compile()` didn't seem to work. I can go into details here with the exact exceptions I get, but more broadly I wanted to know if you ever tried doing something like this before and what would be the best way to go about this.

Thank you!

**Comment by serengil** [comment]
No experience - sorry

**Comment by serengil** [comment]
may i close this issue? because it is not directly related to deepface. errors come from tensorflow dependencies.

**Comment by yannickschuchmann** [comment]
@shirasael did you have any success eventually? I'm about to try the same and wonder if you made it working?

**Comment by niyazed** [comment]
I am also trying to use AWS Inferentia with deepface. Any update on this issue?
