### ISSUE TITLE
ResourceExhaustedError: OOM when allocating tensor

### ISSUE THREAD

**Issue by vocuzi** [serengil/deepface#50]
Repeated calls to analyze function keeps occupying memory. Even after the analysis is complete.

To reproduce try running on the following config : 
OS : Ubuntu 16
Python : 3.6,3.8
No GPU Available

**Comment by serengil** [comment]
Do not use analyze and verify functions in a for loop. You can pass a list to these functions.

```
test_set = []
for i in range(0, 100):
   test_set.append("img_%s.jpg" % (i))

DeepFace.analyze(test_set)
```

**Comment by vocuzi** [comment]
That's cool, but what if I want to use analyze function as a service ?

**Comment by serengil** [comment]
still you can pass a list to analyze function.
