### ISSUE TITLE
Detect Scalability issues

### ISSUE THREAD

**Issue by guysiTomax** [serengil/deepface#500]
Hi,
not sure its the right place to ask ,  
we are using DeepFace verify to validate participants identity ,
however when we execute 5 requests in parallel it crashes.
we tried cropping the image first using detectFace + normalization to 255 in order to reduce image size but it does not seems to help
do you have any statistics about  scalability ? 
Thanks,
Guy

**Comment by serengil** [comment]
deepface uses very complex models in the background. one thread allocates all memory almost. so, it is very normal having memory issues if you run it in parallel.
