### ISSUE TITLE
Precision problem

### ISSUE THREAD

**Issue by yyq-GitHub** [serengil/deepface#501]
Hi, thanks for your work. I have two questions to ask.
1. After L2 norm normalization, the Euclidean distance of a set of vectors is linearly related to their cosine similarity. In fact, the distance in the frame conforms to cosine=(euclidean_l2*euclidean_l2)/2. However, their thresholds are not in this equivalence relation. For example OpenFace': {'cosine': 0.10, 'euclidean': 0.55, 'euclidean_l2': 0.55}, where the threshold of cosine is a bit low and should be 0.15. For example, Akhmed_Zakayev_0001.jpg and Akhmed_Zakayev_0003.jpg are true under euclidean_l2, however It is false under cosine.
2. When I tested the lfw dataset with different models, I found that the accuracy was not so high. On the contrary, the accuracy rate is even a bit low.

**Comment by yyq-GitHub** [comment]
Thanks for your reply, I noticed something unique in OpenFace.py. In addition, I can't reproduce the face-recognition-pivot.csv results in the code base, and there is always a big deviation. But I don't get any errors, what's the reason? thanks

**Comment by serengil** [comment]
i changed the face detectors a lot since i commit that face-recognition-pivot.csv. if i want to re-run it, i will not be able to re-produce it.
