### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'copy'"

### ISSUE THREAD

**Issue by maxyvisser** [serengil/deepface#502]
I get this error whenever I try to use DeepFace.find on a folder full of pictures. 

Relevant folder structure:
F:\Pictures\jpg\ (images with the names "db (1).jpg" through "db (13713).jpg")
D:\Work\known\ (find.jpg)

Here's my code:
"""
from deepface import DeepFace
import os

#The path containing the face(s) I want too search
known_path = "D:\Work\known"

#Making a list containing the path to all pictures in a certain folder to search through
pictures = []

for (root, dirs, known) in os.walk(known_path): pass

for i in known:
    pictures.append("D://Work//known//" + i)

#The actual searching
df = DeepFace.find(img_path = pictures, db_path = "F:\Pictures\jpg", enforce_detection=(False), model_name = "Facenet512", detector_backend = "ssd")
"""

Here's the full error:
"""
Traceback (most recent call last):
  File "C:\Users\----\Desktop\Programming\DeepFace.py", line 14, in <module>
    df = DeepFace.find(img_path = pictures, db_path = "F:\Pictures\jpg", enforce_detection=(False), model_name = "Facenet512", detector_backend = "ssd")
  File "C:\Users\----\anaconda3\envs\face_recognition\lib\site-packages\deepface\DeepFace.py", line 581, in find
    representation = represent(img_path = employee
  File "C:\Users\----\anaconda3\envs\face_recognition\lib\site-packages\deepface\DeepFace.py", line 754, in represent
    img = functions.preprocess_face(img = img_path
  File "C:\Users\----\anaconda3\envs\face_recognition\lib\site-packages\deepface\commons\functions.py", line 176, in preprocess_face
    base_img = img.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
"""

Python version 3.10.5, using an Anaconda environment. The only packages installed are DeepFace (and all dependencies) and face_recognition (and all dependencies).

My issue gives the same error as issue #13 and issue #206. However, I don't think either solution is relevant to me, as there are no non-English characters in my path (like issue #13) and the solution to issue #206 should already be implemented(?). Also, both other issue's occurred when using DeepFace.stream, which I am not doing

Also, thanks for creating this program and making it available for free to everyone. I've had some other (successful) tests with this program, and it worked perfectly every time, with good performance and clear syntax.

**Comment by serengil** [comment]
use slash instead of backslash

**Comment by maxyvisser** [comment]
Could you reopen the issue @serengil? I don't think it has been solved yet. Thanks in advance.

**Comment by maxyvisser** [comment]
@serengil Sorry for wasting your time, turns out I had some corrupted jpg's in my folder. I don't know how they got there, but removing them seems to solve the problem. An ambitious solution would be to check if all images are readable, and if not, let the user know which files are corrupt. A simpler solution would be to add a "try...except" block around line 176 in /commons/functions.py, letting the user know that this error might be caused by a corrupt file. Thank you for your time, and for making an amazing application.
