### ISSUE TITLE
Reproduce LFW scores

### ISSUE THREAD

**Issue by Abdelfatah1998** [serengil/deepface#506]
Could you please explain the procedure and provide codes to reproduce LFW scores with the models?

**Comment by serengil** [comment]
1- model accuracy scores in the read me referenced from the original research papers. i have not got those scores.

2- here, i wrote a tutorial about how to evaluate a model on lfw: https://sefiks.com/2020/08/27/labeled-faces-in-the-wild-for-face-recognition/
