### ISSUE TITLE
Questions: How do I use deepface to detect all faces on a image? How do I get embedings for  a particular face in image? How to use API in multi threaded way?

### ISSUE THREAD

**Issue by martinenkoEduard** [serengil/deepface#508]
First of all! You wrote a really cool lib! The github page is just awesome, real pleasure to eyes) 
But I have several questions regarding how to use it:

How do I use deepface to detect all faces on a image? And get bounding boxes?
How do I get embedings for  a particular face in image? If I execute
DeepFace.represent(img_path = "test.jpg", model_name = 'Facenet')  
I get embedings for only one face... How do I choose what one?

Does your API works in gunicron or something like that? (when there are several simultaneous requests?)

**Comment by martinenkoEduard** [comment]
And additionaq question - how do you convert distanse between images to percentage?
I want to use milvus to create a face recognition app, but can't figure out how to convert distance to human redable percentage..

**Comment by serengil** [comment]
1- extract faces in a given image via [retinaface](https://github.com/serengil/retinaface).

```python
from retinaface import RetinaFace
faces = RetinaFace.extract_faces(img_path = "img.jpg", align = True)
```

if you want to get the coordinates you need to call detect_faces function of retinaface.

2- we already stored each face in the faces list. find embedings for each face in the faces list then.

```python
from deepface import DeepFace
for face in faces:
     embedding = DeepFace.represent(face, model_name = 'Facenet')
```

**Comment by serengil** [comment]
3- of course this is a flask app and you can run it via gunicorn

4- you cannot convert the distance to percentage

**Comment by martinenkoEduard** [comment]
Is it possible to extract  RetinaFace.extract_faces using different models?
RetinaFace is really cool but slow.

**Comment by martinenkoEduard** [comment]
Is it possible to use different backend 
backends = ['opencv', 'ssd', 'dlib', 'mtcnn', 'retinaface', 'mediapipe']

in retina face?

**Comment by martinenkoEduard** [comment]
Because retinaface is good but really slow.
