### ISSUE TITLE
DeepFace.stream Data?

### ISSUE THREAD

**Issue by Luke-Crichton** [serengil/deepface#513]
Kia ora,
I am using DeepFace.stream to get real-time emotional recognition, however, I was wondering if there was a way to get the dominant emotion from the stream and run functions based upon the dominant emotion. I would also like to increase the time between snapshots if possible.
Love your work
Thank you.

**Comment by serengil** [comment]
1- stream function is just for demo purpose. you cannot store its values by default. but you can customize the function based on your requirements.

2- Stream function has those optional input args: time_threshold = 5, frame_threshold = 5 . So, you can decrease or increase these values.
