### ISSUE TITLE
Face Anti-Spoofing

### ISSUE THREAD

**Issue by sumurtk2** [serengil/deepface#518]
Hello Sefik, thanks for all the hard work and time that you obviously invested on the project.

Is there any way for DeepFace to verify that the face being detected is a real face? (not a printed face or a face in a screen)
This way it could be used in access control and not be fooled by just a printed photo.
If not, what method or library would you recommend?
Thank you.

**Comment by serengil** [comment]
this is out of the scope

unfortunately, i do not have an experience on that subject.

**Comment by sumurtk2** [comment]
Thanks Sefik, Ill try to find or create a model to detect a printed faced, the problem is I don't know what attribute would differentiate an image of a face and an image of a printed face. Depth sensor comes to mid but that would require extra hardware.
