### ISSUE TITLE
Mediapipe imported but no output

### ISSUE THREAD

**Issue by MKJ52** [serengil/deepface#519]
Hi Mr. Sefik,

I am trying to create embeddings of a dataset using mediapipe and facenet. 
The model and detector are built successfully but there is not progress in the embeddings task (see image below):

<img width="569" alt="Screen Shot 2022-07-22 at 18 02 40" src="https://user-images.githubusercontent.com/46068423/180455738-da2ba1bf-2e4a-4ddb-a6d6-fd9c80935b44.png">

After waiting for a long time, the program remains at 0 progress and doesn't throw any errors to resolve. 

What is the issue here?

**Comment by serengil** [comment]
It has a issue in mediapipe. You can follow it here: https://github.com/google/mediapipe/issues/1461

I recommend you to use a different detector

**Comment by MKJ52** [comment]
> It has a issue in mediapipe. You can follow it here: [google/mediapipe#1461](https://github.com/google/mediapipe/issues/1461)
> 
> I recommend you to use a different detector

What other detector do you recommend to viably replace the accuracy and speed of mediapipe?

**Comment by serengil** [comment]
retinaface is the best but slow

mtcnn is robust and fast

**Comment by MKJ52** [comment]
> retinaface is the best but slow
> 
> mtcnn is robust and fast

MTCNN works, but i have the Apple M1 chip and since mtcnn is running on the CPU i get 3-4 frames. Can fast-mtcnn be integrated to suitably replace mtcnn?
