### ISSUE TITLE
Why discard smaller detected faces in stream?

### ISSUE THREAD

**Issue by zoli** [serengil/deepface#520]
Before anything thanks for the library that gathers most of prevalent models and its easy to work with.

I was confused that why deepface doesn't detect faces in my sample video. I figured out its because of [this line](https://github.com/serengil/deepface/blob/master/deepface/commons/realtime.py#L155=) which is discarding faces with width lower than 130.

Commenting out that line fixed my problem. Why is that limit there? Isn't it better to be as optional parameter or documenting it somewhere as it is a bit confusing.

**Comment by serengil** [comment]
The purpose of this line is obvious. We are discarding small faces. Of cource, you can customize the code based on your requirements.
