### ISSUE TITLE
Getting "an illegal memory access was encountered" when using GPU for Facial Recognition demo

### ISSUE THREAD

**Issue by teenaxta** [serengil/deepface#521]
I am trying to run the facial recognition demo but I am getting the following errors:

> 2022-07-25 05:50:01.611523: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

> 2022-07-25` 05:50:01.611647: F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1

when I run on cpu, everything works fine but i keep on getting this error when running on GPU. for reference I am using the tensorflow 2.9.1 with Cuda 11.2 and cudnn 8.1

**Comment by serengil** [comment]
you have a problem with your gpu. disable it.

```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = ""
```
