### ISSUE TITLE
AttributeError: module 'numpy.core.multiarray' has no attribute 'from_dlpack'

### ISSUE THREAD

**Issue by iamMaverick** [serengil/deepface#522]
@serengil Having issues while importing deep face. 

The error trace is as below :
**********************************
AttributeError                            Traceback (most recent call last)

---> 1 from deepface import (
DeepFace,
detectors as deepface_detectors
)

File c:\Users\Itcomplex\anaconda3\envs\vision\lib\site-packages\deepface\DeepFace.py:10, in <module>
**_---> 10 import numpy as np_**

File c:\Users\Itcomplex\anaconda3\envs\vision\lib\site-packages\numpy\__init__.py:140, in <module>

**_--> 140 from . import core_**

File c:\Users\Itcomplex\anaconda3\envs\vision\lib\site-packages\numpy\core\__init__.py:99, in <module>

**_---> 99 from . import _add_newdocs_**

File c:\Users\Itcomplex\anaconda3\envs\vision\lib\site-packages\numpy\core\_add_newdocs.py:1598, in <module>

**_-> 1598 add_newdoc('numpy.core.multiarray', 'from_dlpack',_**

...
**_--> 521     new = getattr(__import__(place, globals(), {}, [obj]), obj)_**
    522     if isinstance(doc, str):
    523         _add_docstring(new, doc.strip(), warn_on_python)

**_AttributeError: module 'numpy.core.multiarray' has no attribute 'from_dlpack'_**
********************************** #

**Comment by serengil** [comment]
your numpy dependency seems not to be installed correctly

if you run this command ->  import numpy as np, then you will have an exception
