### ISSUE TITLE
verify multiple faces in a list

### ISSUE THREAD

**Issue by wisdompython** [serengil/deepface#529]
This is a very cool library 

I would like to find out if i can run  a DeepFace.verify after extracting the faces in an image with retinaface

Say something like this :

faces = RetinaFace.extract_image(image, enforce_detection=False)
for face in faces:
      Deepface.verify(source_image, face)

I look forward to your response thank you

**Comment by serengil** [comment]
verify function expects an image pair. but extract_faces return many faces.

you cannot do it as you want

**Comment by wisdompython** [comment]
thanks for the prompt reply
