### ISSUE TITLE
How does this module handle group photos? 

### ISSUE THREAD

**Issue by Basant206** [serengil/deepface#53]
Comparing an image with one person with one with many people yields a result, but I am not sure how it is calculating that result. Does it just match the closes face? 

A couple other quick questions--Can the max_threshold_to_verify easily be modified? Finally, is there a way to have the "verified" value be set to false if the module cannot find a face in one of the images instead of erroring, and have this be done over a large dataset of images?

Thank you so much!

**Comment by serengil** [comment]
Find function returns a data frame and this data frame is sorted closest to longest. That's why, 1st line of the data frame is the closest one.

max_threshold_to_verify variable comes from deepface.commons.functions.findThreshold(model_name, distance_metric). 

Find function return None if nothing found. Verify function expects two images and says these are same or different. What do you need exactly?

**Comment by Basant206** [comment]
Thank you for the response! I apologize if these are obvious questions, but let me better explain what I am trying to do. 

1) I would like to compare an image of an one person to an image of multiple people to see if the first person is also in the group photo. When you say "the dataframe is sorted closest to longest" what do you mean by closest? If there are multiple people in each image, does Deepface.verify() already compare the two "most similar" faces in both images? 

2) I would like to change the handling of images where a face cannot be found (for example, if one image is of a person and the other is of a tree). In this case, is it enough to set the "enforce_detection" parameter to be false? What exactly does this do? 

Thanks again for your help!

**Comment by serengil** [comment]
1- deepface compares faces one to one. I mean that there are images in a folder img1.jpg to img10.jpg. Each image should include one face. If an image includes more than one face, deepface will not throw an exception but it will focus on the first face it see. 

2- if opencv could not detect a face in a fed image, then it throws an exception. If you set enforce_detection=False, then image will be fed to the face recognition / analysis model even face could not be detected.
