### ISSUE TITLE
Stuck with DeepFace.find()

### ISSUE THREAD

**Issue by LAFLAMIE1024** [serengil/deepface#531]
Hello !

I hit an error when I was using your api `DeepFace.find()` on **Colab**

I was told that 

>ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.

after executing : 
``` python
from deepface import DeepFace
model = DeepFace.build_model('VGG-Face')
df = DeepFace.find(img_path = "/content/ff_extracted/000/000_0.png", db_path ="/content/ff_extracted",detector_backend='opencv',model=model)
df
```
I do not want to set the param `enforce_detection` to `False` as it will spend up to 10 mins to run the code above.

I think I was doing it right by following your tutorial in README, but I still got this error, and I do not know why I could not run correctly even if I print out the detected face by myself

``` python
from deepface.commons.functions import detect_face
import cv2
img = cv2.imread('/content/ff_extracted/000/000_0.png')
img, region = detect_face(img = img, detector_backend = 'opencv', grayscale = 'True', enforce_detection = 'True', align = 'True')
```

![image](https://user-images.githubusercontent.com/73602420/183557977-b1131547-a650-4a39-88ce-1718e179f9dc.png)

please tell what steps I missed or something that I did wrong, many thanks in advanced !

Before getting this error, I succeeded in using `DeepFace.find()` in a specific folder of one person like this:

![image](https://user-images.githubusercontent.com/73602420/183557222-d99c2c58-5251-4075-a43c-d7f7ba536014.png)

is there any limitation on the size of dataset?
(ps. there are 10k pictures in my own dataset)
And here is how my dataset looks like :

![image](https://user-images.githubusercontent.com/73602420/183554753-f79d152b-eff3-43df-992f-5361ee65a911.png)

if you have any interest in downloading this dataset, here is the [link](https://drive.google.com/file/d/1-4Vvpw3uX0LSLZCy-xyUkvlvLBPtnzj6/view?usp=sharing) from google drive.

**Comment by duongminhhieu16** [comment]
@LAFLAMIE1024 That error occurs when the face detector (opencv in your case) cannot detect any face in the image because the face in the image is too large/small (in this case it is too large). `enforce_detection = False` will return the original image if no face is detected.

**Comment by LAFLAMIE1024** [comment]
> 

Thank you so much !  I would try to resize the images in the dataset and try again.

**Comment by LAFLAMIE1024** [comment]
> @LAFLAMIE1024 That error occurs when the face detector (opencv in your case) cannot detect any face in the image because the face in the image is too large/small (in this case it is too large). `enforce_detection = False` will return the original image if no face is detected.


Thank you so much ! I would try to resize the images in the dataset and try again.

**Comment by serengil** [comment]
as mentioned in the error message, the library cannot find a face in that photo. you have to set enforce_detection to False if you do not want to get any error related to undetected faces.

this error comes from a photo in the db_path folder. no limitations for that folder.

**Comment by LAFLAMIE1024** [comment]
> as mentioned in the error message, the library cannot find a face in that photo. you have to set enforce_detection to False if you do not want to get any error related to undetected faces.
> 
> this error comes from a photo in the db_path folder. no limitations for that folder.

Thank you for replying ! I would check whether there is any photo do not have face, too.
