### ISSUE TITLE
load_image is not same from url or from file

### ISSUE THREAD

**Issue by mistake0316** [serengil/deepface#532]
```python
# in colab
from deepface.commons import functions
import numpy as np
url = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/MontreGousset001.jpg/440px-MontreGousset001.jpg"
file = "440px-MontreGousset001.jpg"
!wget {url} -O {file} -q

img_from_url = functions.load_image(url)
img_from_file = functions.load_image(file)

print(np.abs(img_from_url-img_from_file).mean())
# 98.4184350027692
```

https://github.com/serengil/deepface/blob/ba9f56755abdc9d1d80777d7680c4267d5d5e0e9/deepface/commons/functions.py#L85-L92
The reason is because you convert the image to RBG with url
And for file, you use cv2.imread, the default setting is rgb

Please align those two methods

**Comment by Vincent-Stragier** [comment]
@mistake0316, 

The following solve this issue: https://stackoverflow.com/a/39270509/10949679

```python
elif url_img is True:
        img = np.array(Image.open(requests.get(img, stream=True, timeout=60).raw).convert("RGB"))[:,:,::-1]
```

If needed I can create a PR.

Best,
Vincent

**Comment by serengil** [comment]
@Vincent-Stragier PRs are welcome
