### ISSUE TITLE
Confirm that opencv is installed on your environment! 

### ISSUE THREAD

**Issue by alib022** [serengil/deepface#533]
Hi,

I have opencv installed and using it to load images, however, I am still getting this error. 

`File ~/miniconda3/envs/deepface/lib/python3.10/site-packages/deepface/detectors/OpenCvWrapper.py:23, in build_cascade(model_name)
     20 face_detector_path = opencv_path+"haarcascade_frontalface_default.xml"
     22 if os.path.isfile(face_detector_path) != True:
---> 23 	raise ValueError("Confirm that opencv is installed on your environment! Expected path ",face_detector_path," violated.")
     26 face_detector = cv2.CascadeClassifier(face_detector_path)
     27 return face_detector
('Confirm that opencv is installed on your environment! Expected path ', '.....miniconda3/envs/deepface/lib/python3.10/site-packages/data/haarcascade_frontalface_default.xml', ' violated.')`

**Comment by serengil** [comment]
exception message is clear. it cannot find opencv in the expected place. virtual environment might cause this. try this after opencv available in path `miniconda3/envs/deepface/lib/python3.10/site-packages/data/`.
