### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by kadiraltug** [serengil/deepface#535]
Hello sir. I am aslo from Turkey. I want to use your deepface repo but I got an error about connection.
ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı', None, 10054, None))
Here is the error. What is the problem? 
Have a nice day.

**Comment by serengil** [comment]
you have a network issue on your side. nothing is related to deepface side.
