### ISSUE TITLE
RAM leak with multiple calls

### ISSUE THREAD

**Issue by nicobonne** [serengil/deepface#537]
Hello @serengil, many thanks for this awesome library! 
I noticed a non neglectible memory leak when calling `DeepFace.analyze()` multiple times. I've seen #78 and your suggestion to not use the function in a `for` loop and to use the `tf.keras.backend.clear_session()` to clear the tf graph. 

Unfortunately, even calling `tf.keras.backend.clear_session()` at every iteration does not stop the memory leak. I really need to use a for loop, as I'm processing a large dataset of videos, so I need to extract the frames and pass them to the function (can't use filenames instead of actual frames). 

The pseudo-code is the following:
```python
models = {}
models['race'] = DeepFace.build_model('Race')

dataset_results = list()
for v in videos:
    frame_list = extract_fixed_number_of_frames(v) 
    deepface_result =  DeepFace.analyze(frame_list, actions=['race'], models=models)
    dataset_results.append(deepface_result)
```
The dataset is too large to load it entirely and call `DeepFace.analyze([frame_list_1, ..., frame_list_v])`.

Do I have other options other than splitting the dataset into chunks that can fit my RAM considering the memory leak?

Do you have any idea on what part of the code is leaking memory? The models are pre-built and the face detector (opencv) is allocated once and retrieved as a global variable, so those should be ok.

**Comment by serengil** [comment]
calling deepface functions was problematic in old versions but this is sorted. you can call it in for loops now.

**Comment by nicobonne** [comment]
I have version 0.0.75 installed by pip a few days ago. Isn't this the latest version?

**Comment by serengil** [comment]
it is the latest. you are having this issue even if you call it in the for loop?

**Comment by nicobonne** [comment]
Yes, the for loop looks like the one in the pseudo code above

**Comment by serengil** [comment]
no, you are feeding input images as array still. send just an image to analyze function.

```python
models = {}
models['race'] = DeepFace.build_model('Race')

dataset_results = list()
for v in videos:
    frame_list = extract_fixed_number_of_frames(v)
    for frame in frame_list:
       deepface_result =  DeepFace.analyze(frame, actions=['race'], models=models)
       dataset_results.append(deepface_result)
```

**Comment by serengil** [comment]
long story short, this is not directly related to the library. you have memory issues on your env. closing this issue.
