### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by kg6kvq** [serengil/deepface#538]
pip install deepface is resulting in the following error

"ImportError: cannot import name 'DeepFace' from partially initialized module 'deepface' (most likely due to a circular import)"

have deleted and recreated the environment multiple times and continue to get this message.  Running the same install command 2 months ago on a different system did not produce this error

**Comment by kg6kvq** [comment]
Looking in the package code Deepface.py calls deepface.basemodels the VGGFace (first model) calls deepface.commons functions.  The functions.py file calls deepface.detectors facedetector  then facedetector.py calls opencvwrapper.py which then loops back to import deepface.detectors facedetector ...

**Comment by serengil** [comment]
what is the name of the file you are importing deepface? if it is deepface.py and you import deepface in this file, you will have this issue.

**Comment by kg6kvq** [comment]
The filename is df.py ... as an update that was with Anaconda on Windows 10, installed it under WSL and it works

**Comment by serengil** [comment]
perfect. it is obvious that you have an environment issue then.

**Comment by kg6kvq** [comment]
Yes, I would chase it down ... but the actual run environment will be linux so not a big deal
