### ISSUE TITLE
How do I detect multiple faces? Can I use 'opencv', 'ssd', 'dlib', 'mtcnn', 'retinaface', 'mediapipe'  to get bounding boxes of each face on a group photo?

### ISSUE THREAD

**Issue by martinenkoEduard** [serengil/deepface#541]
How do I detect multiple faces? Can I use 'opencv', 'ssd', 'dlib', 'mtcnn', 'retinaface', 'mediapipe'  to get bounding boxes of each face on a group photo?

**Comment by martinenkoEduard** [comment]
Because retinaface is good but really slow.

**Comment by martinenkoEduard** [comment]
Does DeepFace.represent work with images with several faces (group photos)?

**Comment by martinenkoEduard** [comment]
What is the best way to get al embeddings (and positions) of all faces on a photo?

**Comment by serengil** [comment]
deepface verify and analyze functions are designed for working for just image. if it includes more than one face, deepface discards the other faces.

still, you can extract faces with this function: https://github.com/serengil/deepface/blob/master/deepface/detectors/FaceDetector.py#L47

**Comment by martinenkoEduard** [comment]
Am I right that it will return array of 226*226 face objects which then I need to feed into  DeepFace.represent
But how do I prevent double work. because  DeepFace.represent will try to detect face on this image.


Additional question: can detect_faces return bounding boxes? I

**Comment by serengil** [comment]
1- you cannot avoid this double work
2- yes this function return bounding box information: https://github.com/serengil/deepface/blob/master/deepface/detectors/FaceDetector.py#L40

**Comment by martinenkoEduard** [comment]
Won't setting enforce_detection = False help avoid double work?

**Comment by serengil** [comment]
if the library cannot find a face in the image, it returns an exception. that argument avoids you to get that exception even if no faces available in the image. so, it will not avoid the double work.

**Comment by omarsayed7** [comment]
Here is a sample to get the bounding box of a face in an image:
`obj_list = FaceDetector.detect_faces(
            detector, "ssd", image[person[1] : person[3], person[0] : person[2]]
        )
        try:
            obj = obj_list[0][1]
        except:
            return image
        face_top_x = obj[0]
        face_top_y = obj[1]
        face_bottom_x = obj[0] + obj[2]
        face_bottom_y = obj[1] + obj[3]`
