### ISSUE TITLE
What is the target_size = (224, 224)  for each of the models?

### ISSUE THREAD

**Issue by martinenkoEduard** [serengil/deepface#542]
What value of target_size should I use for each of the models?  

 "VGG-Face", 
  "Facenet", 
  "Facenet512", 
  "OpenFace", 
  "DeepFace", 
  "DeepID", 
  "ArcFace", 
  "Dlib", 
  "SFace",
]

**Comment by serengil** [comment]
you can find this information here: https://github.com/serengil/deepface/tree/master/deepface/basemodels

find the value for input_shape or shape for the model files. e.g. 160x160x3 for facenet and 224x224x3 for vgg.
