### ISSUE TITLE
Not working on GPU of the Jetson NX

### ISSUE THREAD

**Issue by MHasanlou1** [serengil/deepface#544]
I've installed TensorFlow 2.6.2 ,nv 21.12 in jetson Xavier nx with jetpack 4.6. The problem is when I'm using the deep face package, it's too slow, and the GPU is not involved!  
Please tell me what I should do to use the deep-face with GPU in jetson. Thanks..
![20](https://user-images.githubusercontent.com/20393059/185792718-d28ac2fe-0633-4380-8e93-00e5d83544b6.png)
.

**Comment by serengil** [comment]
you should install tensorflow-gpu before installing deepface to be able to use gpu functionalities.

besides, you should ask this question to jetson discussion forum because deepface is using just tensorflow.
