### ISSUE TITLE
What is the best way to change model file?

### ISSUE THREAD

**Issue by martinenkoEduard** [serengil/deepface#545]
What is the best way yo use my own model?

**Comment by martinenkoEduard** [comment]
Especially for ArcFace.

**Comment by serengil** [comment]
what do you mean? arcface is a pre-trained model in deepface.

**Comment by serengil** [comment]
if the structure of the model changed, then you have to update deepface/basemodels/ArcFace.py folder

weight file is mentioned in this file also.
