### ISSUE TITLE
Expanding findThreshold function with custom threshold

### ISSUE THREAD

**Issue by Terminazor** [serengil/deepface#547]
I want to propose a small change regarding the threshold(s) provided by deepface. 
An example: I'm currently using SFace with cosine function and the standard threshold according to the `findThreshold` function inside of `distance.py` is 0.5932763306134152. But what if a usecase needs a more strict (i.e. lower) or more loose (i.e. higher) threshold? My suggestion would be to expand the `findThreshold` function:
```
def findThreshold(model_name, distance_metric, custom_threshold):    
    if custom_threshold:
        return custom_threshold
    else: [REST OF CODE]
```
`DeepFace.find` and `DeepFace.verify` should be adapted accordingly

**Comment by serengil** [comment]
verify function returns the distance for this purpose. you can use that value is greater or less than a threshold instead of checking verified key.
