### ISSUE TITLE
Supress face detector output?

### ISSUE THREAD

**Issue by pjbh** [serengil/deepface#551]
Thank you so much for this amazing piece of work.  I downloaded the latest version to get the newly added models. Now the face detectors give an output, a lot of it in the case of mtcnn, which they did not do before. Is there a way to tell them not to?
Thanks, Peter

**Comment by serengil** [comment]
what do you mean exactly? can you share your program and output sample?

**Comment by pjbh** [comment]
DeepFace.verify(filelist[0], filelist[1], model_name = "Facenet")

1/1 [==============================] - 1s 887ms/step
1/1 [==============================] - 0s 39ms/step

It used not to give this output

**Comment by serengil** [comment]
You can use this arg: https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L95

**Comment by pjbh** [comment]
Like this?  Doesn't seem to have any effect

for file in filelist[1:len(filelist)]:
    result = DeepFace.verify(filelist[0], file, model_name = "ArcFace", prog_bar = False) 
    print(file + ' ' + str(result["verified"]) + ' ' + str(result["distance"]))

1/1 [==============================] - 0s 63ms/step
1/1 [==============================] - 0s 56ms/step
C:/Users/pjbh2/anaconda3/envs/deepface1\AnnaFriel0001.jpg True 0.376147657150524

**Comment by serengil** [comment]
interesting because it should work.

**Comment by serengil** [comment]
what is the content of file list?

**Comment by pjbh** [comment]
Just a few face jpg files, to test things out, so I can see what happens with different models and detectors. It's no biggie for me, just clutters up the output and used not to happen. I still have the old environment if I don't want the new models (Facenet512 appears to give identical results to Facenet, anyhow). To try this version, I set up a fresh env in Anaconda, using Python 3.9.13

**Comment by serengil** [comment]
if you pass just an image to verify function, then progress bar is silent. i think your trouble is coming from a dependency such as tqdm version. i am closing this issue because i cannot re-produce it.

**Comment by serengil** [comment]
i had this issue in tensorflow 2.10.0 and i could not resolve it

when i downgrade tensorflow to 2.7.4, then this is sorted.

**Comment by codenoid** [comment]
this is weird?, I'm on `tensorflow==2.15.0.post1` this log are still open

**Comment by codenoid** [comment]
https://github.com/ipazc/mtcnn/issues/121

**Comment by codenoid** [comment]
I found the solution

```
import keras
keras.utils.disable_interactive_logging()
```
anywhere on the python project (yours or the mtcnn lib)
https://github.com/ipazc/mtcnn/issues/121#issuecomment-1942708344
