### ISSUE TITLE
documents for deepface 

### ISSUE THREAD

**Issue by 13015517713** [serengil/deepface#553]
Is there a offical document for Deepface ?

**Comment by serengil** [comment]
just read me of this repo

**Comment by 13015517713** [comment]
Okay. It's a lightweight and very nice repository. Maybe I need to read source code in order to change some configurations, such as threshold when verifying.

**Comment by VlaDanilov** [comment]
I totally agree with the previous comment. You provide a lot of functionality, a lot of opportunities in face recognition task, but in the mean time the info you give is more like a demonstration, rather than a guide or description of the package.
