### ISSUE TITLE
Problem with model results

### ISSUE THREAD

**Issue by dparreslpb** [serengil/deepface#562]
Hi! I have tried the different DeepFace models and I do not get the LFW results presented in the table. What is the reason for this?

![image](https://user-images.githubusercontent.com/113662610/191472244-a12e7b4b-f23a-422b-a09a-bae0d1f1a24a.png)

**Comment by serengil** [comment]
these results are mentioned in the original studies. still, when i try i get 98% score on lfw with facenet512 and dlib.
