### ISSUE TITLE
unable to import SFace from from deepface.basemodels

### ISSUE THREAD

**Issue by loni9164** [serengil/deepface#564]
Below code is not working (Tried with python 3.7, 3.8, 3.9, 3.10)

from deepface.basemodels import SFace

Please refer attached error snap.

![chrome_QqBGnHwqfO](https://user-images.githubusercontent.com/101520804/192464743-2874563c-92a2-46f0-996c-163e8e15b6b5.png)

**Comment by serengil** [comment]
check your deepface version
