### ISSUE TITLE
Verify function not working (finished at 0%)

### ISSUE THREAD

**Issue by NickPauly** [serengil/deepface#569]
I'm running Python 3.6 with Deepface 0.0.31 and try to run this piece of code:

```

from deepface import DeepFace

img1_path = 'deepface/pictures/img1.jpg'
img2_path = 'deepface/pictures/img2.jpg'

model = "Facenet"

result = DeepFace.verify(img1_path=img1_path, img2_path=img2_path, model_name=model)
```

Which results in the following:

```
Using TensorFlow backend.
Using Facenet model backend cosine distance.
Verification:   0%|          | 0/1 [00:00<?, ?it/s]

Process finished with exit code 0
```

There is no error and I cannot find another problem like this online. Any idea what could be wrong. Thanks in advance.

**Comment by serengil** [comment]
it might be because of your dependent tensorflow installation, i cannot make a comment because no errors

**Comment by NickPauly** [comment]
Thank you for the quick answer I'll look into different installations, these are my current:

**Comment by NickPauly** [comment]
Thank you for the quick answer, these are the packages I installed:

numpy==1.14.5
pandas==0.23.4
gdown==3.10.1
tqdm==4.30.0
Pillow==5.2.0
opencv-python==3.4.4.19
tensorflow==1.9.0
keras==2.2.0
Flask==1.1.2
matplotlib==3.2.2
deepface==0.0.31

I think the issue indeed lies within the dependencies as the code is just copied from the github. This is the error I get from running the analyze function:

```
from deepface import DeepFace
img1_path = 'deepface/pictures/img1.jpg'
model_name = "Facenet"
obj = DeepFace.analyze(img_path = img1_path, actions = ['age', 'gender', 'race', 'emotion'])
```
Output:

```
Using TensorFlow backend.
Actions to do:  ['age', 'gender', 'race', 'emotion']
age_model_weights.h5 will be downloaded...
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\Thesis\main.py", line 8, in <module>
    obj = DeepFace.analyze(img_path = img1_path, actions = ['age', 'gender', 'race', 'emotion'])
  File "C:\Users\Admin\PycharmProjects\Thesis\venv\lib\site-packages\deepface\DeepFace.py", line 356, in analyze
    age_model = Age.loadModel()
  File "C:\Users\Admin\PycharmProjects\Thesis\venv\lib\site-packages\deepface\extendedmodels\Age.py", line 38, in loadModel
    gdown.download(url, output, quiet=False)
  File "C:\Users\Admin\PycharmProjects\Thesis\venv\lib\site-packages\gdown\download.py", line 77, in download
    res = sess.get(url, stream=True)
  File "C:\Users\Admin\PycharmProjects\Thesis\venv\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Admin\PycharmProjects\Thesis\venv\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Users\Admin\PycharmProjects\Thesis\venv\lib\site-packages\requests\sessions.py", line 453, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Admin\PycharmProjects\Thesis\venv\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Admin\PycharmProjects\Thesis\venv\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

Process finished with exit code 1
```

In the request.py file there is a function that sets the url to ' ' (nothing) which results in the missing schema error.

**Comment by serengil** [comment]
analyze function error is based on unavailable weights in your system. you can download them from here https://github.com/serengil/deepface_models/releases/tag/v1.0 to ~/.deepface/weights

verify function has no error. can you import tensorflow in another program?

**Comment by NickPauly** [comment]
Downloading the files seemed to fix analyze the problem. The verification still says 0% but otherwise gives the correct results when printing the result. Thank you very much for the help!

**Comment by serengil** [comment]
closed due to inactivity
