### ISSUE TITLE
Faces embeddings

### ISSUE THREAD

**Issue by lazrak-mouad** [serengil/deepface#57]
Hello, Thank you so much for the effort you put on this work.

So, I have already a faces dataset, which upon I apply some transformations and then I need to run the face verification system on both (original and transformed datasets) to see if the transformations were able to hide the identity or not.

In this case, I think that I should not use the OpenCV face detection model, this why I set enforce_detection = False.

I was just wondering if we set enforce_detection = False, how the face recognition model will get the face embeddings.

Will it use the whole image (since images contains already only faces) ?

**Comment by serengil** [comment]
If you set enforce_detection = False, then it will analyze all image.

I'm closing this issue.
