### ISSUE TITLE
dlib called with BGR instead of RGB?

### ISSUE THREAD

**Issue by Jille** [serengil/deepface#570]
I've been reading through your code and most detector backend wrappers convert the colorspace from BGR to RGB before calling the external detector.

However, the dlib wrapper doesn't seem to do that and AFAIK dlib does expect RGB. Is that a bug?

(also please take a look at https://github.com/serengil/deepface/pull/563#issuecomment-1257541112)

**Comment by serengil** [comment]
no because we are using opencv for other detectors, but dlib handles it with its way

**Comment by Jille** [comment]
All the image loading happens in functions.load_image, right? So that means all images loaded with cv2 there are loaded as BGR and should be converted to RGB for non-opencv detectors.

https://github.com/serengil/deepface/blob/63de372d52b1fb9b99af57c87f80f28b6d5b1f30/deepface/commons/functions.py#L92

I guess this is actually the same problem as https://github.com/serengil/deepface/issues/532 - image loading should be consistent in either BGR or RGB and all detectors can then assume they get it like that.
