### ISSUE TITLE
API misbehaves under concurrency

### ISSUE THREAD

**Issue by Jille** [serengil/deepface#571]
The API seems to somehow misbehave under concurrent requests. If I send one request at a time, I deterministically get the right result. However, when I send multiple requests at the same time, they return different, incorrect results.

Concurrent requests shouldn't affect the correctness of the API.

I haven't tested whether the problem lies in the library, its dependencies or the API.

**Comment by serengil** [comment]
you are using flask run to publish the api. flask run is not recommended for production purposes. this is probably related to flask run, too.

i strongly recommend you to run it via gunicorn. if it has issue with gunicorn or any other service, please re-open this issue.

**Comment by yannickschuchmann** [comment]
hey,
I am encountering similar issues. When there are two concurrent requests the service behaves randomly. For me I didn't experience different results rather python errors, e.g.

`/analyze with "actions": ["age", "emotion", "gender", "race"]`

`{
    "error": "Exception while analyzing: _set_mask_metadata() missing 1 required positional argument: 'build_graph' - Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/deepface/api/src/modules/core/service.py\", line 75, in analyze\n    demographies = DeepFace.analyze(\n  File \"/usr/local/lib/python3.8/site-packages/deepface/DeepFace.py\", line 253, in analyze\n    return demography.analyze(\n  File \"/usr/local/lib/python3.8/site-packages/deepface/modules/demography.py\", line 174, in analyze\n    apparent_age = modeling.build_model(\n  File \"/usr/local/lib/python3.8/site-packages/deepface/modules/modeling.py\", line 96, in build_model\n    cached_models[task][model_name] = model()\n  File \"/usr/local/lib/python3.8/site-packages/deepface/models/demography/Age.py\", line 32, in __init__\n    self.model = load_model()\n  File \"/usr/local/lib/python3.8/site-packages/deepface/models/demography/Age.py\", line 51, in load_model\n    model = VGGFace.base_model()\n  File \"/usr/local/lib/python3.8/site-packages/deepface/models/facial_recognition/VGGFace.py\", line 79, in base_model\n    model.add(Convolution2D(64, (3, 3), activation=\"relu\"))\n  File \"/usr/local/lib/python3.8/site-packages/tensorflow/python/trackable/base.py\", line 205, in _method_wrapper\n    result = method(self, *args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/usr/local/lib/python3.8/site-packages/keras/engine/base_layer_v1.py\", line 881, in __call__\n    self._set_mask_metadata(inputs, outputs, input_masks)\nTypeError: _set_mask_metadata() missing 1 required positional argument: 'build_graph'\n"
}`

Also when `/represent` is running and I POST to `/analyze` I get this one on the `/analyze` response, while the `/represent` is still processing:

`{
    "error": "Exception while analyzing: Exception encountered when calling layer 'conv2d' (type Conv2D).\n\nresource: Attempting to capture an EagerTensor without building a function.\n\nCall arguments received by layer 'conv2d' (type Conv2D):\n  • inputs=tf.Tensor(shape=(1, 226, 226, 3), dtype=float32) - Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/deepface/api/src/modules/core/service.py\", line 75, in analyze\n    demographies = DeepFace.analyze(\n  File \"/usr/local/lib/python3.8/site-packages/deepface/DeepFace.py\", line 253, in analyze\n    return demography.analyze(\n  File \"/usr/local/lib/python3.8/site-packages/deepface/modules/demography.py\", line 174, in analyze\n    apparent_age = modeling.build_model(\n  File \"/usr/local/lib/python3.8/site-packages/deepface/models/demography/Age.py\", line 38, in predict\n    age_predictions = self.model(img, training=False).numpy()[0, :]\n  File \"/usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1592, in convert_to_tensor\n    raise RuntimeError(\nRuntimeError: Exception encountered when calling layer 'conv2d' (type Conv2D).\n\nresource: Attempting to capture an EagerTensor without building a function.\n\nCall arguments received by layer 'conv2d' (type Conv2D):\n  • inputs=tf.Tensor(shape=(1, 226, 226, 3), dtype=float32)\n"
}`

---

When the requests run one after another everything is fine.
My api is based on the flask blueprint from this repo and starts with gunicorn:

```python
# app.py
import os

from flask import Flask, request, jsonify
from flask_cors import CORS

# project dependencies
from deepface import DeepFace
from deepface.api.src.modules.core.routes import blueprint
from deepface.commons.logger import Logger

logger = Logger()

# Define static API key
API_KEY = os.getenv("API_KEY", "test_key")

# App factory function
def create_app():
    app = Flask(__name__)
    CORS(app)

    # Register the blueprint
    app.register_blueprint(blueprint)

    # Add health check endpoint
    @app.route('/health')
    def health_check():
        return jsonify({
            "status": "healthy",
            "version": DeepFace.__version__
        }), 200

    @app.before_request
    def verify_api_key():
        # Skip API key check for OPTIONS requests (CORS preflight)
        if request.method == 'OPTIONS':
            return None
            
        # List of paths that don't require API key
        public_paths = ['/health']
        
        if request.path in public_paths:
            return None

        api_key = request.headers.get("x-api-key")
        if not api_key or api_key != API_KEY:
            return jsonify({"error": "Unauthorized: Invalid API Key"}), 401

    logger.info(f"Welcome to DeepFace API v{DeepFace.__version__}!")
    logger.info("Server running on http://0.0.0.0:8080")
    return app

```

```
# wsgi.py
from app import create_app
app = create_app()

```

```shell
// gunicorn cmd
gunicorn --worker-class gevent --workers 1 --access-logfile '-' --access-logformat '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(M)s' --bind 0.0.0.0:8080 wsgi:app --max-requests 10000 --timeout 60 --keep-alive 5 --log-level debug
```

---

It seems like a new request doesn't create a new instance of the module. Meaning multiple requests touch and modify the same instance? Python is not my homebase, so I don't know how things work under the hood. 


Any ideas what causes that? @serengil

**Comment by yannickschuchmann** [comment]
So, for now I get around the errors by removing the gevent worker-class from gunicorn. 

`gunicorn --workers 1 --access-logfile '-' --access-logformat '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(M)s' --bind 0.0.0.0:8080 wsgi:app --max-requests 10000 --timeout 60 --keep-alive 5 --log-level debug`
