### ISSUE TITLE
Verification issue

### ISSUE THREAD

**Issue by takis55** [serengil/deepface#576]
Hi there , 
i would like to ask you a question in the def verification section ,  i am newbie in computer science and i want to  print the input images into vectors and then a function that will take the 2 vectors and it will make the similarity . 

Can you help me ?? 

Thanks

**Comment by serengil** [comment]
deepface does it already! please read this tutorial: https://sefiks.com/2020/05/01/a-gentle-introduction-to-face-recognition-in-deep-learning/

**Comment by takis55** [comment]
You think if i split the code only in those 2 things (print the input images into vectors and then a function that will take the 2 vectors and it will make the similarity  ) without the others ( def detection , def detection  etc ) it will work fine ??

**Comment by serengil** [comment]
yes it will work fine

if you read the tutorial i shared, i already did it.
