### ISSUE TITLE
Could the real-time detect DeepFace.stream() work on webcam smoothly?

### ISSUE THREAD

**Issue by wujoho** [serengil/deepface#578]
Currently, the function DeepFace.stream() requires its parameters `time_threshold` and `frame_threshold` both to be at least 1, which makes the face on the webcam not moving smoothly, the frame image will stuck for X second(s) then show the movement, then stop for another X second(s).
What's the reason to apply such kind of limit?
How could I run the real-time face (age and gender) analysing continuously and smoothly?

This is another repo [https://github.com/smahesh29/Gender-and-Age-Detection](url) that could detect age and gender through webcam much faster than this project, it runs smoothly when I test it using my webcam, is it possible for deepface to reach similar speed?

**Comment by wujoho** [comment]
I think I found a similar question [https://github.com/serengil/deepface/issues/362](url)

**Comment by serengil** [comment]
the answer is no as mentioned in the similar question. if time_threshold is 1 and frame_threshold is 1, then it is real time but still you need to wait until your models are processed. so, if you invest a powerful hardware, it would be real time with this configuration.

**Comment by wujoho** [comment]
Hi @serengil thanks for your reply.
I was using my computer (i.e. same hardware) to compare your project vs. [this](https://github.com/smahesh29/Gender-and-Age-Detection) project speed of detecting age and gender, and noticed the other project was much faster, so thought there could be potential space to improve the speed in your project at code level instead of using better hardware.

**Comment by serengil** [comment]
this means the other project uses a more lightweight model. deepface uses more complex models. unfortunately, you cannot fasten it until investing a hardware.

**Comment by wujoho** [comment]
I see, thanks.
Would you mind to put more details here to explain why deepface needs to use complex/heavy models, what's the main benefits please?

**Comment by serengil** [comment]
it comes with accuracy
