### ISSUE TITLE
Error in finding distance between faces in real-time

### ISSUE THREAD

**Issue by MKJ52** [serengil/deepface#585]
I've created the embeddings and now running the script in real-time. 

Once the process reaches the part where it must find distance for face recognition this is the error i get:

    distance = dst.findCosineDistance(img1_representation, img2_representation)
  File "/Users/---/miniforge3/envs/faceitstf/lib/python3.8/site-packages/deepface/commons/distance.py", line 4, in findCosineDistance
    a = np.matmul(np.transpose(source_representation), test_representation)
ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

**Comment by serengil** [comment]
what are img1_representation and img2_representation in your case? please share their shapes.

**Comment by MKJ52** [comment]
> what are img1_representation and img2_representation in your case? please share their shapes.
img1_representation is (1,160,160,3) 
img2_representation is (1,160,160,3) 

embeddings were created using Facenet with ssd and cosine distance
realtime app is also using Facenet with ssd and cosine distance

**Comment by MKJ52** [comment]
> that is the problem. If you are using facenet, your representation should be a list consists of 128 items (128 dimensional vector). It seems that you are feeding the facial image itself to those functions.


Built model  Facenet
input shape is  (160, 160)
Finding embedding for xxxx.jpg:   0%|                 | 0/1 [00:00<?, ?it/s]
image resized shape is  (1, 160, 160, 3)
img_representation shape is... (128,)

the above is what i get in my representation when creating embedding

**Comment by serengil** [comment]
can you validate that img1_representation and img2_representation have same shapes?

if you share them here, i can comment

**Comment by serengil** [comment]
Error message is clear: Input operand 1 does not have enough dimensions

one of your representations is empty

**Comment by MKJ52** [comment]
> 

This is from the live run. I'm using try and except to stop the program from closing

input shape is.. (160, 160)
custom_face shape is.. (1, 160, 160, 3)
representation shape is... (128,)
matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)
