### ISSUE TITLE
How to speed up

### ISSUE THREAD

**Issue by thewh1teagle** [serengil/deepface#587]
Hi, 
I want to create a software which organize pictures by faces in the pictures
It will firstly extract the number of faces with `retinaface` and then I will compare the representation of each one with pre selected faces representation to compare (I will let the user tag first every face by name)
How can I make this process less CPU intensive and faster?
I don't mind if it will be less accurate, what matters is speed
Thanks

**Comment by serengil** [comment]
use ssd and facenet pair if you want to have the top speed but this facial recognition is a complex process and it might not satisfy your expectations

**Comment by thewh1teagle** [comment]
I found that this [package](https://github.com/Kagami/go-face) in go works very fast
It looks like it built on top of dlib.
