### ISSUE TITLE
Unable to open file error from api.py using provided Postman collection

### ISSUE THREAD

**Issue by christophervlapa** [serengil/deepface#588]
I'm exploring the Deepface API for analyze, but the postman "Facial attribute analysis - multiple items" API gives the error:

> Analyzing  3  instances
> Exception:  Unable to open file (truncated file: eof = 158859264, sblock->base_addr = 0, stored_eof = 537215296)
> [2022-11-02 23:28:50,420] ERROR in app: Exception on /analyze [POST]
> Traceback (most recent call last):
>   File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "api-stock.py", line 69, in analyze
>     resp_obj["trx_id"] = trx_id
> TypeError: 'tuple' object does not support item assignment
> 127.0.0.1 - - [02/Nov/2022 23:28:50] "POST /analyze HTTP/1.1" 500 -

I'm using the stock [API code](https://raw.githubusercontent.com/serengil/deepface/master/api/api.py), with the stock Postman collection from here: [deepface.postman_collection.json](https://github.com/serengil/deepface/blob/master/api/deepface.postman_collection.json). I find the other APIs in the collection seem to work fine 🤔 but the analyze API throws this error. 

Any help greatly appreciated!

**Comment by serengil** [comment]
can you activate the line 110 in api.py and share its output?

print(resp_obj)

**Comment by christophervlapa** [comment]
It doesn't seem to make it to that line, entire output from run to error:

> ❯ python3 api-stock.py
>  * Serving Flask app 'api-stock'
>  * Debug mode: off
> WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
>  * Running on all addresses (0.0.0.0)
>  * Running on http://127.0.0.1:5000
>  * Running on http://X.X.X.X:5000
> Press CTRL+C to quit
> Analyzing  3  instances
> Exception:  Unable to open file (truncated file: eof = 158859264, sblock->base_addr = 0, stored_eof = 537215296)
> [2022-11-03 09:32:40,914] ERROR in app: Exception on /analyze [POST]
> Traceback (most recent call last):
>   File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "api-stock.py", line 69, in analyze
>     resp_obj["trx_id"] = trx_id
> TypeError: 'tuple' object does not support item assignment
> 127.0.0.1 - - [03/Nov/2022 09:32:40] "POST /analyze HTTP/1.1" 500 -

**Comment by christophervlapa** [comment]
This happens outside the Postman / api.py, if I feed images made with terminal command `base64 example-images/sandra-bullock-smile.jpeg | pbcopy` (or any image, at all) and still fails with the same error.

**Comment by serengil** [comment]
the problem is that resp_obj seems a tuple but it should be a dict. that is why, i want to see its content but you did not share it yet.

**Comment by serengil** [comment]
can you share your base64 string as well?

**Comment by christophervlapa** [comment]
Base64 image of woman smiling, created with in mac zsh via `base64 example-images/sandra-bullock-smile.jpeg | pbcopy`. Note this string can be pasted into a browser and will display with no error:

https://gist.github.com/christophervlapa/b846de8fed4294bb58abad96c3c35c05

Lines 103 to 111 does not return `resp_obj` as the exception is thrown instead:

```
	try:
		resp_obj = DeepFace.analyze(instances, actions = actions)
	except Exception as err:
		print("Exception: ", str(err))
		return jsonify({'success': False, 'error': str(err)}), 205

	#---------------
	print(resp_obj)
	return resp_obj
```

Removing the exception wrapper and calling `DeepFace.analyze()` gives this error:

```
❯ python3 api-stock.py
 * Serving Flask app 'api-stock'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://x.x.x.x:5000
Press CTRL+C to quit
Analyzing  1  instances
[2022-11-04 17:54:32,932] ERROR in app: Exception on /analyze [POST]
Traceback (most recent call last):
  File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/name/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "api-stock.py", line 63, in analyze
    resp_obj = analyzeWrapper(req, trx_id)
  File "api-stock.py", line 104, in analyzeWrapper
    resp_obj = DeepFace.analyze(instances, actions = actions)
  File "/Users/name/Library/Python/3.8/lib/python/site-packages/deepface/DeepFace.py", line 360, in analyze
    models['race'] = build_model('Race')
  File "/Users/name/Library/Python/3.8/lib/python/site-packages/deepface/DeepFace.py", line 63, in build_model
    model = model()
  File "/Users/name/Library/Python/3.8/lib/python/site-packages/deepface/extendedmodels/Race.py", line 61, in loadModel
    race_model.load_weights(home+'/.deepface/weights/race_model_single_batch.h5')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 158859264, sblock->base_addr = 0, stored_eof = 537215296)
127.0.0.1 - - [04/Nov/2022 17:54:32] "POST /analyze HTTP/1.1" 500 -
```

**Comment by serengil** [comment]
oh i see. this file is not valid in your environment: home+'/.deepface/weights/race_model_single_batch.h5'

delete it manually and let deepface to re-download
