### ISSUE TITLE
Face could not be detected.

### ISSUE THREAD

**Issue by d2bugs** [serengil/deepface#590]
raise ValueError("**Face could not be detected.** Please confirm that the picture is a face photo or consider to set enforce_detection param to False.")

**Comment by serengil** [comment]
message is clear, this is not a bug!

**Comment by Brumbpo-Tungus** [comment]
Hey, I get this message as well. 
I used this command on my python script:
df = DeepFace.find(img_path = "img1.jpg", db_path = "C:/workspace/my_db")

For img path I used a webcam photo of myself, and other images from the internet. Then for the DB path I just used random images from the internet. I have tried different images for the img1.jpg - but cant seem to get it going?

I assume img1.jpg is the source image, then the db path is the location of the other images to compare with? Or have I got that wrong? Thanks in advance.
