### ISSUE TITLE
Input 0 of layer is incompatible with the layer: expected shape=(None, 160, 160, 3), found shape=(None, 160, 160, 4)

### ISSUE THREAD

**Issue by comrade001** [serengil/deepface#594]
```python
model = DeepFace.build_model("Facenet")
target_img = functions.preprocess_face(
  img, 
  target_size = (160, 160),
  grayscale = False,
  enforce_detection = True,
  detector_backend = 'opencv'
)
                
embedding = model.predict(target_img)[0].tolist()  
```

Input 0 of layer is incompatible with the layer: expected shape=(None, 160, 160, 3), found shape=(None, 160, 160, 4)

**Comment by serengil** [comment]
exception message is clear. your input img does not satisfy the expected input shape. you have to convert it to 160x160x3.

try to feed img[0] to preprocess_face.
