### ISSUE TITLE
Deepface.verify() get stuck on processing

### ISSUE THREAD

**Issue by saketSwabhav** [serengil/deepface#597]
```
nparr1 = np.frombuffer(base64.b64decode(_json["imgLog"]), np.uint8)
        nparr2 = np.frombuffer(base64.b64decode(_json["ogImg"]), np.uint8)
        print("nparr",type(nparr1))
        image1 = cv2.imdecode(nparr1, cv2.COLOR_BGR2GRAY)
        image2 = cv2.imdecode(nparr2, cv2.COLOR_BGR2GRAY)
        print("image",type(image1))
        try:
            print("verifying face")
            img_result = DeepFace.verify(image1, image2)
            print("done verifying face")
        except Exception as e:
            print("exception in deepface",e)
        print("imgresult",img_result)
```

It never reaches done verifying face stage.
Ps: I am running it inside docker and using gunicorn and i have tried deepface version 0.0.49 and 0.0.75 scenarios are same in both.
You can see my docker file below.

`FROM python:3.7.9-buster

RUN apt-get update \
    && apt-get install -y -qq \ 
    && apt install cmake -y \
    && apt-get install ffmpeg libsm6 libxext6  -y\
    && apt-get clean

RUN pip3 install --upgrade pip

# Install libraries
COPY ./requirements.txt ./
RUN pip install -r requirements.txt && \
    rm ./requirements.txt
# Setup container directories
RUN mkdir /app

# Copy local code to the container
COPY . /app

# launch server with gunicorn
WORKDIR /app
EXPOSE 8080
ENV PORT 8080

ENV FLASK_CONF config.ProductionConfig

# CMD ["gunicorn", "main:app", "--timeout=60", "--preload", \
#      "--workers=1", "--threads=4", "--bind :$PORT"]

CMD exec gunicorn --bind :$PORT main:app  --preload --workers 9 --threads 5 --timeout 120`

**Comment by saketSwabhav** [comment]
shortcut = tensorflow.keras.layers.Conv2D(filters, 1, strides=stride, use_bias=False, kernel_initializer='glorot_normal', name=name + '_0_conv')(x)

this line gets stuck in the block1 function in arcface.py file

**Comment by saketSwabhav** [comment]
@serengil any updates or solutions ?

**Comment by serengil** [comment]
no because this is docker dependent bug. you might ask this to docker topic in stackoverflow.
