### ISSUE TITLE
Save Video Using realtime.py

### ISSUE THREAD

**Issue by HamDan1999** [serengil/deepface#598]
Hi,

Thanks for sharing your interesting work. I would like to ask if it is possible to save a video after being detected and recognized using realtime.py in your repository without freezing the frames?

Simply, I want face detection and recognition in real-time without freezing and saving the file, if possible.

Also, how to not discard detecting small faces from the video + remove all the texts?

Thanks for your time.

**Comment by serengil** [comment]
of course you can do it but you need to customize the source code based on your requirements.
