### ISSUE TITLE
Using Online Images

### ISSUE THREAD

**Issue by abdiallo** [serengil/deepface#6]
Hi - I believe this package requires locally saved files. Is there a way to use image urls without modifying the package? I am using DeepFace.analyze() in a loop on mac OS and it is eating up my storage. I looked into the library files and I am not certain where the issue may be. There are many temp directories on mac and I believe this function is writing files to a temp directory.  I am testing on just 10 images and it is taking 8 gb. When I reset the kernel, my available storage goes back to normal.

The purpose for this is to use on about 23k images. I am only interested in race and gender. I can reduce the analyze() function to return just this and clean race.py and gender.py but this does not improve performance. 

So i found out that the issue really is due to having to generate the models over and over in the loop. Employing clear_session and del model helps in this case.

**Comment by serengil** [comment]
Oke I understand your problem. As you mentioned analyze and verify functions build model from scratch when they are called. I plan to add these function inputs as arrays and in this way I will build models once. This will solve your problem but you should wait the following version of deepface fw. 

BTW, single images run well, right?

**Comment by abdiallo** [comment]
Hi Yes, single images take some time to run as well. The main thing is that each run is costly to disk space. I made a few changes that improved performance for me:

1. - I silenced tqdm output.
2. - I setup gender_model and race_model outside of the analyze function and referenced them using global within the function
3. - I imported keras.backend and called keras.backend.clear_session() within the analyze function after predicting the gender and race for img
4. - I also used gc.collect() at the end of the analyze function 

2 & 3 were critical for me. Now the predictions run considerable faster and disk space isn't being eaten up.

**Comment by serengil** [comment]
This is a nice solution, I will add this approach in the following version of the framework. Thank you.

**Comment by serengil** [comment]
This is a new feature instead of an issue.

**Comment by serengil** [comment]
@abdiallo deepface 0.0.10 version is recently released. In this version, you can pass faces as inputs to verify and analyze functions. Read-me file will guide you how to use this.

Thank you for your feedback to improve the framework.
