### ISSUE TITLE
How to use DeepFace on a dataset of multiperson videos

### ISSUE THREAD

**Issue by venturaEffect** [serengil/deepface#604]
First of all congrats for your work!

I've been following several articles, videos,... and I'm really happy to find you :)

I've been trying using OpenCv and some Caffe pretrained models to predict the age and gender of some videos. The accuracy is horrendous.

Reading about DeepFace I see it has far more potential.

I'm using DeepFace.stream() and one of the parameters is db_path. As I understand, it should be a database of faces that some matches the faces appearing on the video. What if I don't want to match faces I just want to get the gender, race, age,... not if it matches faces from a dataset.

What I'm also curious seen some of your videos, is that the accuracy of gender and ages change on each frame. How can I get an estimation of all the outputs of each frame from each face?

Would really appreciate your connection and to learn more from your amazing work.

Wrote you and follow you on Twitter :)

**Comment by serengil** [comment]
if you set an empty folder to db_path argument, it will work as you want
