### ISSUE TITLE
how to group the unkown faces into lists by distance 

### ISSUE THREAD

**Issue by pengKiina** [serengil/deepface#61]
Hi Sefik,

import pandas as pd
df = DeepFace.find(img_path = image1,db_path = path)

when use the find all images in database simliar to image1, I am wondering if it is possible to group the rest images by distance? 

for example there are 10 images only found image 2 simlar to image 1, but image 3 and 4  also similar and image 5,6,7 are simlar.

how to group image  3,4 and image 5,6,7 into the same list?

thanks

**Comment by serengil** [comment]
Nope, this is very custom need. It is not adapted in deepface.
