### ISSUE TITLE
AttributeError: 'cv2.CascadeClassifier' object has no attribute 'setInput'

### ISSUE THREAD

**Issue by isa-tr** [serengil/deepface#611]
When calling FaceDetector.detect_faces() function like this:
faces = FaceDetector.detect_faces(detector_model, backend, frame_small, True)
and detector_model set as 'ssd' 
There is this error 
File "C:\Users\User\anaconda3\envs\loki_repo\lib\site-packages\deepface\detectors\SsdWrapper.py", line 72, in detect_face
    face_detector.setInput(imageBlob)
AttributeError: 'cv2.CascadeClassifier' object has no attribute 'setInput'

**Comment by serengil** [comment]
your opencv dependency seems not okay

**Comment by serengil** [comment]
Try to run `pip install opencv-contrib-python`

**Comment by isa-tr** [comment]
I already tried to run `pip install opencv-contrib-python` but is still not working and the error only occurs when using SSD

**Comment by serengil** [comment]
can you try to delete ssd related file in HOME/.deepface/weights? It might be interrupted while downloading. Because this is not a normal error.

**Comment by serengil** [comment]
closed due to inactivity
