### ISSUE TITLE
library does not recognise folder with '.png' images

### ISSUE THREAD

**Issue by onuh** [serengil/deepface#612]
Is there a way to set image extension for db folder? only a folder with .jpg images is recognised as a valid image folder for now

**Comment by ekkolon** [comment]
Hey @onuh, @serengil , I'd like to chime in on that.

If I'm not mistaken, this behavior comes from here: 

https://github.com/serengil/deepface/blob/13a21fe306ee39567f7f0b15422f8a3c1ce656de/deepface/commons/realtime.py#L32-L39

A simple fix would be changing that:
https://github.com/serengil/deepface/blob/13a21fe306ee39567f7f0b15422f8a3c1ce656de/deepface/commons/realtime.py#L35

to something like this:
```python
if ('.jpg' in file) or ('.png' in file):
```

And additionally, this line must be changed accordingly to replace .png extensions too
https://github.com/serengil/deepface/blob/13a21fe306ee39567f7f0b15422f8a3c1ce656de/deepface/commons/realtime.py#L379

@serengil in case you don't mind, I would create a PR to to fix this

**Comment by serengil** [comment]
yes please
