### ISSUE TITLE
faced IndexError on analyze function with specified image path and actions parameter 

### ISSUE THREAD

**Issue by younver** [serengil/deepface#615]
```
from deepface import DeepFace
DeepFace.analyze("test.jpg", actions=("emotion"))
```
```
resp_obj["region"][parameter] = int(region[i]) #int cast is for the exception - object of type 'float32' is not JSON serializable
IndexError: list index out of range
```

**Comment by serengil** [comment]
what was your test image? this happens for all tests or just for this input image?

**Comment by younver** [comment]
it was an image including face of a famous singer, in jpg format, which works like a charm when you use it in analyze function with default parameters. Haven't tried tests but just wanted to try analyze function with just emotion action.

**Comment by serengil** [comment]
can you share that image here?

**Comment by younver** [comment]
sure~~

![gerard](https://user-images.githubusercontent.com/69584310/206917056-91d90441-cdb1-448f-9f08-bd3a8099cbbe.jpg)

**Comment by younver** [comment]
issue solved, it was just behaviour of tuples in Python. 

Python treats `("emotion")` as `"emotion"`
in order to prevent this, we can pass `("emotion",)` (with additional comma at the end)

this is the final one~~ `DeepFace.analyze("test.jpg", actions=("emotion",))`

maybe simple handling inside analyze function would make it better.
