### ISSUE TITLE
How to use my own wights model?

### ISSUE THREAD

**Issue by mtcdultra** [serengil/deepface#618]
Hi, I'm using the MEAD dataset (https://wywu.github.io/projects/MEAD/MEAD.html) to analyze several images. I created a code to extract frames from videos and with this frames try to train using your implementation (https://github.com/serengil/tensorflow-101/blob/master/python/facial-expression-recognition.py). I´ve included line to save the h5 file.
![Screenshot 2022-12-14 at 16 59 38](https://user-images.githubusercontent.com/77461340/207659335-8e2df040-50c8-4da6-82e5-c0e3f9595702.jpg)

But, it's possible to use this model in DeepFace? 

By the way, I using the DeepFace to get emotions.

**Comment by serengil** [comment]
if your model structure satisfies this: https://github.com/serengil/deepface/blob/master/deepface/extendedmodels/Emotion.py

then you can overwrite the weights in `~/.deepface/weights`

if your model structure is different, you should modify the loadModel function.
