### ISSUE TITLE
ValueError when using DeepFace.verify() with full black image as ndarray to the img2_path parameter

### ISSUE THREAD

**Issue by leonspremo** [serengil/deepface#619]
I am using two parameters on DeepFace.verify() function, the first one is a human face and the second one is full black image and I have also put the parameter "enforce_detection=False". Because the black image is nd.array full of zeros when initialize_input(img1_path, img2_path) is called in Deepface.py project it has to pass a condition

(type(img2_path) == str and img2_path != None) #exact image path, base64 image or (isinstance(img2_path, np.ndarray) and img2_path.any())

The problem is that img2_path.any() returns False because all elements in img2_path are 0.
I dont know exactly how to fix it, maybe len(img2_path ) == 0 but I didnt look at code long enough to see all the dependencies of this condition. Also this is my first Issue reporting so this may not be the correct way to report this kind of stuff.

**Comment by serengil** [comment]
why do you need to compare an image with a black empty image?

**Comment by serengil** [comment]
you can try to create a black image and pass it to verify function to handle your issue instead of passing numpy array.
