### ISSUE TITLE
This model needs to be improved for Asian facial alignment and emotional interpretation

### ISSUE THREAD

**Issue by notjiangjiu** [serengil/deepface#620]
**this is align img**
![Figure_1 - 副本](https://user-images.githubusercontent.com/46511514/208671729-4bd04aeb-4ebc-40cc-936e-5a58377bb2f8.png)
**this is emotional result**：
{'emotion': {'angry': 36.847707629203796, 'disgust': 1.0891004542656901e-06, 'fear': 57.65697956085205, 'happy': 2.5300977751612663, 'sad': 2.965211495757103, 'surprise': 2.0838139173858005e-13, 'neutral': 2.2110226538529787e-06}, 'dominant_emotion': 'fear', 'region': {'x': 249, 'y': 186, 'w': 521, 'h': 521}}

**Thank you for bringing such a good project and look forward to your further optimization**

**Comment by serengil** [comment]
deepface covers many face detectors. i guess you are using default one (opencv). switch to retinaface or mtcnn.
