### ISSUE TITLE
Memory leak using API

### ISSUE THREAD

**Issue by yulizar** [serengil/deepface#622]
Hi, so I've been using this API for 3 months but always have a problem with memory usage (I'm using CPU computation not GPU) so API service will die if memory don't have enough free space. Each time I call API, memory always rise higher even afer I add some del command and TF clear session memory still not be freed and rose higher. Is there any other way to free memory usage or memory allocations ? 

Thank you

**Comment by serengil** [comment]
you can try to run this service via gunicorn server. flask api is not recommended for prod purposes.

still, deepface models are memory consuming ones. you will have those problems if you are not increasing the memory.
