### ISSUE TITLE
Analyze API-endpoint failing with example request from Postman-collection

### ISSUE THREAD

**Issue by epiespen** [serengil/deepface#624]
So, first of all, thanks for an amazing project!

I'm running the API with Docker and when I test the selection of api-requests in the postman collection, Analyze is the only one not working. The posted image data is the default from the collection. Am I missing something here?

![image](https://user-images.githubusercontent.com/10612746/211223966-91ac37ff-cd7c-4db8-8fda-d1ede649304a.png)

**Comment by serengil** [comment]
A recent PR changed analyze function output from dict to list. This causes this bug. I updated api.py.

You can pull the latest code and re-run.

Thank you for informing the bug.
