### ISSUE TITLE
FEATURE VECTOR

### ISSUE THREAD

**Issue by takis55** [serengil/deepface#625]
Hello there. I have a question.
After i extract all the feature vector with deep.analyze i want to use an average or a network to combine all of them. 

I know i can use average of them but i want to use a network. 

Is it possible to make it through deepface model ? Can you help ? 

Thanks a lot and you have done a great work.

**Comment by serengil** [comment]
analyze function does not return a vector. beyond this why you need to use a network for this?

**Comment by takis55** [comment]
sorry i mean deepFace.represent for extract vectors 
a need to use a network to combine all the vectors into one

**Comment by serengil** [comment]
you can concat these vectors, IMO you do not a need an additional network

**Comment by takis55** [comment]
thanks again.  Yes but the additional network theoretically will give better performance if you concat this with i.e. audio feature vector and the  introduce an CNN network with softmax to classify emotions.
