### ISSUE TITLE
How to load real time frames to model?

### ISSUE THREAD

**Issue by MarriamSiddiqui** [serengil/deepface#627]
I need to analyze the real time video using deepface. I came across the deepface.stream() which prints all the stats on the video and refreshes every five seconds. I want to input frames (every two seconds) in the function for analysis. Also, I want to get the statistics separately (perhaps in dictionary format) and not on the video screen. How can I use deepface.stream() or some other function of deepface for this?

**Comment by serengil** [comment]
Decrease the time_threshold and frame_threshold values. Default values are 5.

`def stream(db_path = '', model_name ='VGG-Face', detector_backend = 'opencv', distance_metric = 'cosine', enable_face_analysis = True, source = 0, time_threshold = 5, frame_threshold = 5):`
