### ISSUE TITLE
unable to install deep face using pypi 

### ISSUE THREAD

**Issue by sbagadhi** [serengil/deepface#63]
pip install deepface 
Collecting deepface   Using cached deepface-0.0.32-py3-none-any.whl (50 kB) Requirement already satisfied: pandas>=0.23.4 in /opt/anaconda3/lib/python3.7/site-packages (from deepface) (1.0.1) Requirement already satisfied: tensorflow>=1.9.0 in /opt/anaconda3/lib/python3.7/site-packages (from deepface) (2.2.0) Requirement already satisfied: keras>=2.2.0 in /opt/anaconda3/lib/python3.7/site-packages (from deepface) (2.3.1) Collecting gdown>=3.10.1   Using cached gdown-3.11.1.tar.gz (8.6 kB)   Installing build dependencies ... error   ERROR: Command errored out with exit status 1:    command: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/k0/j6lrj6ds039b1ylg967tx88m0000gp/T/pip-build-env-n6ls94ki/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel        cwd: None   Complete output (44 lines):   Traceback (most recent call last):     File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main       "__main__", mod_spec)     File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code       exec(code, run_globals)     File "/opt/anaconda3/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>       sys.exit(_main())     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main       command = create_command(cmd_name, isolated=("--isolated" in cmd_args))     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command       module = importlib.import_module(module_path)     File "/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module       return _bootstrap._gcd_import(name[level:], package, level)     File "<frozen importlib._bootstrap>", line 1006, in _gcd_import     File "<frozen importlib._bootstrap>", line 983, in _find_and_load     File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked     File "<frozen importlib._bootstrap>", line 677, in _load_unlocked     File "<frozen importlib._bootstrap_external>", line 728, in exec_module     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>       from pip._internal.cli.req_command import RequirementCommand, with_cleanup     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>       from pip._internal.index.package_finder import PackageFinder     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>       from pip._internal.index.collector import parse_links     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>       from pip._vendor import html5lib, requests     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>       from . import utils     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>       from . import certs     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>       from pip._vendor.certifi import where     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>       from .core import contents, where     File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>       from importlib.resources import read_text     File "/opt/anaconda3/lib/python3.7/importlib/resources.py", line 11, in <module>       from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401     File "/opt/anaconda3/lib/python3.7/site-packages/typing.py", line 1357, in <module>       class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):     File "/opt/anaconda3/lib/python3.7/site-packages/typing.py", line 1005, in __new__       self._abc_registry = extra._abc_registry   AttributeError: type object 'Callable' has no attribute '_abc_registry'   ---------------------------------------- ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/k0/j6lrj6ds039b1ylg967tx88m0000gp/T/pip-build-env-n6ls94ki/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by serengil** [comment]
that's all python related exceptions. could you try to downgrade your python version to 3.5.5.
