### ISSUE TITLE
How can I use Deepface directly with the AWS S3 bucket in sync

### ISSUE THREAD

**Issue by ShaileshSarda** [serengil/deepface#630]
Hi,
I would like to demonstrate the capability of the Deepface on AWS S3 bucket.
Because its not at all feasible to load the millions of face data on local machine.
Suggest?

**Comment by serengil** [comment]
i recommend you to read database options tutorial instead of s3: https://sefiks.com/2021/03/31/tech-stack-recommendations-for-face-recognition/
