### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by Shoichii** [serengil/deepface#631]
I use windows 11, 4 cores, 8 ram, python 3.9 and deepface with model facenet
I have 30 imgs and try to verify them. but time for that is 22sec. and if i will have 1000 imgs? it will be very slow.
Can you help me please?

**Comment by serengil** [comment]
I already explained this. If you need to run deepface on a large scale data set, you should use it with some a-nn tools. You should read this tutorial: https://sefiks.com/2021/03/31/tech-stack-recommendations-for-face-recognition/
