### ISSUE TITLE
deepface model: different input shape

### ISSUE THREAD

**Issue by ldiascarneiro** [serengil/deepface#634]
![image](https://user-images.githubusercontent.com/63213154/214882210-7347f629-0a9f-467c-b3cd-1d70f7d53206.png)

Good afternoon,
Running deepface model with LFW dataset, I got this message above. Then, downgrading to version 0.0.75 of deepface library, the code runs ok.

**Comment by serengil** [comment]
would you please share the code you are currently running?

**Comment by ldiascarneiro** [comment]
The error is o DeepID model

**Comment by serengil** [comment]
I realzied it from the shape. I need the code you are running.

**Comment by ldiascarneiro** [comment]
> 
Ok. Just a second

**Comment by serengil** [comment]
okay understand the bug. code is just updated. i will publish it soon on pip. meanwhile, you can use the source code instead of pip version.

**Comment by ldiascarneiro** [comment]
Ok. Thanks a lot

**Comment by serengil** [comment]
@chandniagarwal that function is retired. if you still need to find the input shape, use this function: functions.find_target_size

**Comment by chandniagarwal** [comment]
> @chandniagarwal that function is retired. if you still need to find the input shape, use this function: functions.find_target_size

thanks !! I will try
