### ISSUE TITLE
 module 'deepface.commons.functions' has no attribute 'find_input_shape'

### ISSUE THREAD

**Issue by chandniagarwal** [serengil/deepface#635]
I have used your code for face recognition and have applied on faces . Now It is showing  module 'deepface.commons.functions' has no attribute 'find_input_shape' error

**Comment by serengil** [comment]
because that function is retired in the recent release. how are you using deepface?

**Comment by chandniagarwal** [comment]
> because that function is retired in the recent release. how are you using deepface?

I am using in represent function in my code and using to find result for face recognition for diff models you mentioned. Now how to do?

**Comment by serengil** [comment]
if you need to use extract faces and represent respectively, you can use this as

```
from deepface import DeepFace
from deepface.commons import functions

model_name = "Facenet"
target_size = functions.find_target_size(model_name = model_name)

face_objs = DeepFace.extract_faces(img_path = "img1.jpg", detector_backend = "opencv", target_size = target_size)

for face_obj in face_objs:
   img = face_obj ["face"]
   embedding = DeepFace.represent(img_path = img)
```

**Comment by chhkg** [comment]
Hi @serengil , thanks for the codes. I have tried the **DeepFace.extract_faces** but it always returns **ValueError: Face could not be detected.**

However, if I use **RetinaFace.extract_faces** on the same picture, it can return the faces. Even if I change the **detector_backend** from opencv to retinaface, it does not help at all. 

May I have your help please? Thanks.

**Comment by serengil** [comment]
i need your input image

**Comment by chhkg** [comment]
![people-3104635__340](https://user-images.githubusercontent.com/33676321/217844071-82c9651b-4bfb-4ebe-a723-e207e8409b2e.jpg)

This is the image I use. Thanks @serengil . 

In fact, I have one more question. When I use **DeepFace.verify** to verify the below image, it can detect the face and give a correct result. However, when I use **DeepFace.find**, it returns Face could not be detected. My codes are as follows.

```
result = DeepFace.verify(img1_path="trial/target.png", img2_path="trial/target2.png") 

df = DeepFace.find(img_path="trial/target.jpg", db_path="facedb")
```

![target](https://user-images.githubusercontent.com/33676321/217845165-fd49d7b4-a465-4e41-8e29-257bd4d298ba.png)

**Comment by serengil** [comment]
which one is target and which one is target2?

**Comment by chhkg** [comment]
target and target2 are the same image of the guy

**Comment by chandniagarwal** [comment]
yes

**Comment by serengil** [comment]
Did you try enforce_detection argument?

`df = DeepFace.find(img_path="trial/target.jpg", db_path="facedb", enforce_detection = False)`

**Comment by chhkg** [comment]
I got the matched result finally by adding **enforce_detection = False**, thanks. From other issues, I saw that you mentioned 

> "it returns an exception. that argument avoids you to get that exception even if no faces available in the image. https://github.com/serengil/deepface/issues/541

> accuracy will be down. https://github.com/serengil/deepface/issues/441

So, I am wondering why putting this statement will return the correct result.

Besides, if the db_path contains group photos with multiple faces in each photo, would **DeepFace.find** be able to analyze multiple faces in one photo?

-----------------------------------
Also your help on this comment will be much appreciated.

> Hi @serengil , thanks for the codes. I have tried the **DeepFace.extract_faces** but it always returns **ValueError: Face could not be detected.**
> 
> However, if I use **RetinaFace.extract_faces** on the same picture, it can return the faces. Even if I change the **detector_backend** from opencv to retinaface, it does not help at all.
> 
> May I have your help please? Thanks.

The input of this part is this group photo.
![people-3104635__340](https://user-images.githubusercontent.com/33676321/218052425-c7031c8f-fd79-4e52-9e79-bc2d634c5685.jpg)

**Comment by serengil** [comment]
So, I am wondering why putting this statement will return the correct result > unfortunately no facial recognition model offers 100% accuracy. 

Besides, if the db_path contains group photos with multiple faces in each photo, would DeepFace.find be able to analyze multiple faces in one photo > yes, since version 0.0.78 it can do this

However, if I use RetinaFace.extract_faces on the same picture, it can return the faces. Even if I change the detector_backend from opencv to retinaface, it does not help at all. > confidence scores might be different.
