### ISSUE TITLE
detectFace module is not there

### ISSUE THREAD

**Issue by chandniagarwal** [serengil/deepface#636]
In deepface video detectFace function is giben which is not there now

**Comment by serengil** [comment]
please use extract_faces instead of it since the version 0.0.78

**Comment by chandniagarwal** [comment]
> chandniagarwal


AttributeError: module 'deepface.DeepFace' has no attribute 'extract_Faces'

**Comment by serengil** [comment]
extract_faces, not extract_Faces

**Comment by chandniagarwal** [comment]
> extract_faces, not extract_Faces

yes

**Comment by chandniagarwal** [comment]
> extract_faces, not extract_Faces

now plt.imshow(img1) giving error
Image data of dtype object cannot be converted to float

**Comment by serengil** [comment]
because extract_faces now returns an array. you can extract face object as shown below.

```python
img_objs = DeepFace.extract_faces(img_path=img2_path)
for img_obj in img_objs:
    plt.imshow(img_obj["face"])
    plt.show()
```

**Comment by chandniagarwal** [comment]
> ```python
> img_objs = DeepFace.extract_faces(img_path="img.jpg")
> for img_obj in img_objs:
>     plt.imshow(img_obj["face"])
>     plt.show()
> ```

Thanks for quick reply
{'verified': True,
 'distance': 0.2877410676566651,
 'threshold': 0.5932763306134152,
 'model': 'SFace',
 'detector_backend': 'opencv',
 'similarity_metric': 'cosine',
 'facial_areas': {'img1': {'x': 43, 'y': 56, 'w': 170, 'h': 170},
  'img2': {'x': 41, 'y': 54, 'w': 172, 'h': 172}},
 'time': 0.15}
1. How to change detector_backend here and similarity metric
2. I want to run this on 1500 images for target and predicted image. I have 1 target and 1 predicted image. when I am passing detector_backend parameter it is showing error because of extract_faces, Itried with MTCNN and got error. by default opencv is given. I am preparing comparative analysis of different FR models on my dataset.
3. I want to analyse accuracy also for the model and wish to run for the folder. 
You are gem dear. Pl help me asap in this regard.

**Comment by serengil** [comment]
To use mtcnn in extract_faces, you can use the following code block.

```
img_objs = DeepFace.extract_faces(img_path=img2_path, detector_backend="mtcnn", target_size=target_size)
for img_obj in img_objs:
    plt.imshow(img_obj["face"])
    plt.show()
```

Similarity metric is used to compare vectors. You can compare the results of represent function.

I recommend you to use verify function directly.

`DeepFace.verify(img1_path=img1_path, img2_path=img2_path, model_name = "Facenet", detector_backend="mtcnn", distance_metric = "euclidean")`
