### ISSUE TITLE
as a deepface user, i want to see the confidence score coming from detector

### ISSUE THREAD

**Issue by serengil** [serengil/deepface#643]
functions in deepface interface (verify, represent and find) returns detected face area in the response. also, confidence score is coming from detector but we are not using it. as a deepface user, i want to see the confidence score next to regions.

```python
facial_area: {
   "img1": {"x": 345, "y": 211, "w": 769, "h": 769, "confidence": 70}
}
```

**Comment by asadullahnaeem** [comment]
@serengil in `extract_faces()` in `DeepFace.py`, is there anything to change? As I made changes to the `extract_faces()` in `functions.py` directly and in order to pass tests I need to remove the check `assert "confidence" in img_obj.keys()` in `unit_tests.py`.

**Comment by asadullahnaeem** [comment]
take
