### ISSUE TITLE
 unexpected keyword argument 'prog_bar'

### ISSUE THREAD

**Issue by iulusoy** [serengil/deepface#644]
Not sure if this is intended, but after updating from version 0.0.75 to version 0.0.78, `DeepFace.analyze()` no longer recognizes the keyword `prog_bar`, as also obvious from [here](https://github.com/serengil/deepface/blob/24cc717620dfbebe7b09bec884591fce0f9a5e06/deepface/DeepFace.py#L190). I tried to find release notes but wasn't successful.

```
        # Run the full DeepFace analysis
        fresult.update(
>           DeepFace.analyze(
                img_path=face,
                actions=actions,
                prog_bar=False,
                detector_backend="skip",
            )
        )
E       TypeError: analyze() got an unexpected keyword argument 'prog_bar'
```

**Comment by Efim27** [comment]
Also i cant find model keyword in verify()

**Comment by serengil** [comment]
use silent argument for same functionality.
