### ISSUE TITLE
AttributeError: module 'deepface.commons.functions' has no attribute 'preprocess_face'

### ISSUE THREAD

**Issue by iammaylee123** [serengil/deepface#646]
I was trying to follow the tutorial: https://sefiks.com/2021/04/03/deep-face-recognition-with-neo4j/

And I got the attribute error for preprocessing_face.  Please kindly advice how I can proceed, many thanks in advance!

**Comment by serengil** [comment]
hey, this function is retired in the recent version of deepface. but blog post might still use retired functions. i updated this post. thank you for information.
