### ISSUE TITLE
TypeError: object of type '_io.BytesIO' has no len()

### ISSUE THREAD

**Issue by Developer404** [serengil/deepface#65]
I was using deepface to make an app using streamlit (python web app maker) and when I used streamlit's upload functionality to upload my own image, the line DeepFace.verify(uploaded_image, local_image) gave this error: "TypeError: object of type '_io.BytesIO' has no len()"  If you can help out, i would be very happy. Thanks!

	st.text("Built with streamlit and deepface") #import streamlit as st

	image_file = st.file_uploader("Upload Image", type="jpg")

	if image_file is not None:

		image = Image.open(image_file) 
		st.image(image, caption='Uploaded Image.')
            least_diff = DeepFace.verify('/Users/developer404/Projects/FaceApp/Actors/John-Abraham.jpg', image_file)["distance"]
		
		st.write("The distance: ", least_diff)

**Comment by Developer404** [comment]
I'm using python 3.7 and deepface 0.0.32

**Comment by serengil** [comment]
Verify function expects two input images. Here, you passed John-Abraham.jpg but there is no pair. Could you try the following code block?

```
img1 = '/Users/developer404/Projects/FaceApp/Actors/John-Abraham.jpg'
img2 = '/Users/developer404/Projects/FaceApp/Actors/John-Abraham.jpg'
least_diff = DeepFace.verify(img1, img2)
```

**Comment by Developer404** [comment]
I did pass two images, but the problem is with the `image file` in the code. The local images in my computer work perfectly fine but when I use streamlit's upload functionality, it doesn't work

**Comment by Developer404** [comment]
I'm using streamlit. Can you please install streamlit and run this code:


[test.py.zip](https://github.com/serengil/deepface/files/4913996/test.py.zip)

download it and run it using this:

`pip install streamlit`
`streamlit run test.py`

upload one of your own image and try it

**Comment by Developer404** [comment]
selfik, nice library but this doesn't accept BytesIO object

**Comment by serengil** [comment]
I'll fix this soon. That's why, the status of the issue is still open.

**Comment by serengil** [comment]
You need to convert pillow image to opencv as illustrated below, then it will work.


```
import streamlit as st
import os
from PIL import Image
import cv2
import numpy as np
from deepface import DeepFace

st.text("Built with streamlit and deepface") #import streamlit as s
image_file = st.file_uploader("Upload Image", type="jpg")

if image_file is not None:

	image = Image.open(image_file)
	st.image(image, caption='Uploaded Image.')
	
	open_cv_image = np.array(image) 
	open_cv_image = open_cv_image[:, :, ::-1].copy() # Convert RGB to BGR
	
	obj = DeepFace.verify('deepface/tests/dataset/img2.jpg', open_cv_image)
	
	print(obj)
	
	st.write("The distance: ", obj["distance"])
```

**Comment by Developer404** [comment]
THANKS SO MUCH!!!!!!!!
