### ISSUE TITLE
Unable to use DBSCAN clustering

### ISSUE THREAD

**Issue by alenpaulvarghese** [serengil/deepface#650]
Using the face encoding data from `DeepFace.representation`. I'm attempting to cluster faces using `DBSCAN`. I am unable to determine why it is not clustering properly.

**Comment by serengil** [comment]
deepface does not offer dbscan functionality?

**Comment by mevinbabuc** [comment]
he's trying to use the DBSCAN from scikit learn package. Although it's able to work with other embeddings from face_recognition library, It's not working with the embeddings created from DeepFace. Any pointers in the right direction would be helpful here.

**Comment by serengil** [comment]
okay, will write a blog post about this soon

**Comment by mevinbabuc** [comment]
Cool. That would be very helpful.

**Comment by fabiopedrosa** [comment]
@serengil I don't mean to derail the topic of this issue, but could you add something to the docs saying how `deepface` compares to `face_recognition`

**Comment by serengil** [comment]
@fabiopedrosa no because they are totally different libraries.

**Comment by mevinbabuc** [comment]
@serengil hey were you able to write a blog on using dbscan ? It would be very helpful for me.

**Comment by serengil** [comment]
i could implement this

```python
instances = []
for file_name in tqdm(file_names):
    embedding_objs = DeepFace.represent(img_path=file_name, model_name="Facenet", detector_backend="mtcnn")
    for embedding_obj in embedding_objs:
        embedding = embedding_obj["embedding"]
        instances.append([file_name, embedding])
# --------------------------
df = pd.DataFrame(instances, columns = ["file_name", "embedding"])
clustering = DBSCAN(eps=10, min_samples=2).fit(df["embedding"].values.tolist())
clustering.labels_
```

this clusters deepface unit test items to following classes

array([-1,  0,  0,  0,  0,  1,  2,  2,  2,  3,  3,  4,  4,  0,  5,  5,  6,
        6,  7,  7,  8,  8,  8,  9, 10,  9,  9, 11,  9,  9, 12, 12, 12, 12,
       13, 11, 13,  0, 13, 13,  8,  8,  8,  8,  8, 11, 14, 14, 14,  0, 14,
       14, 10,  1, 11, 11, 11, 10, 10,  2,  2,  3, 11,  0,  3,  3, 11,  4,
        0, 14, 14])
