### ISSUE TITLE
commons missing preprocess_face function definition

### ISSUE THREAD

**Issue by Ramy-Abdulazziz** [serengil/deepface#655]
Using stream function leads to an attribute error as `preprocess_face()` called in analysis is not defined in `deepface.functions.py`

**Comment by ekkolon** [comment]
Duplicate: #646 

You might be using a version of DeepFace < *0.0.78*.
The `preprocess_facee` function is no longer available since the last version update.

**Comment by serengil** [comment]
duplicated - https://github.com/serengil/deepface/issues/653
