### ISSUE TITLE
The reason why use opencv for preprocess_face

### ISSUE THREAD

**Issue by KIMS0YOUNG** [serengil/deepface#662]
Hi, thanks you for amazing work.
By the way, I have a question for realtime.py's analysis function.

for face recognition, custom_face has defined by `functions.preprocess_face()` in realtime.py line 340.
but in that code, you used fixed `detector_backend='opencv'` not `detector_backend=detector_backend`.
So when I use `DeepFace.stream("database", detector_backend='retinaface')`, custom_face's detector_backend isn't chaged.
Is there any reason why you used fixed detector_backend for preprocess_face() ?

Thanks.

**Comment by serengil** [comment]
hey, i think you are using out-of-the-date code

https://github.com/serengil/deepface/blob/master/deepface/commons/realtime.py

this one is not pubished on pip yet, you can use the source code instead of pypi version

**Comment by KIMS0YOUNG** [comment]
Thanks a lot.
