### ISSUE TITLE
 'deepface.commons.functions' has no attribute 'preprocess_face'

### ISSUE THREAD

**Issue by noonv** [serengil/deepface#663]
I'm trying to call DeepFace.stream() (library 0.0.78 installed from pip)
but get an error message 
```
AttributeError: module 'deepface.commons.functions' has no attribute 'preprocess_face'
```

**Comment by serengil** [comment]
this is sorted in the source code. i will publish it to pip soon. meanwhile, you can use source code instead of pip version.
