### ISSUE TITLE
extract_faces wont accept base64 and i get black images back

### ISSUE THREAD

**Issue by moerv9** [serengil/deepface#664]
Hi Sefik,
first of all, awesome work you've done here! having a lot of fun...

My problem is with the extract_faces method.
I have my face in a base64 encoded png image string like ('iVBORw0KGgoAAAANSUhEU...') and since it didn't work to give this to either verify and extract_faces method, I converted it into an ndarray.
With the verify function it worked but the extract_faces gives me a black image back...

Have you had this experience?
How does the base64 encoded image string need to look like?
Having a lot of trouble of converting all these base64 strings back and forth to ndarray....

Cheers Marvin

**Comment by serengil** [comment]
would you please share your input here?

**Comment by moerv9** [comment]
These are my functions. In the left tab the align_face function is given an ndarray that has first been converted from a base64 string... It would be the best if this step wasn't needed, but I have tried to apply the extract_faces ( and verify,too) function to base64 and it didn't work...
Thanks in advance :)

<img width="1871" alt="Screenshot 2023-02-10 at 12 36 06" src="https://user-images.githubusercontent.com/81798308/218083272-b850f049-e34f-40fd-8f79-c7a10427d29c.png">

**Comment by serengil** [comment]
base64 string must start with "data:image/" - you can check it here.

https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py#L65

**Comment by moerv9** [comment]
Oh wow! I must have not looked deep enough into the code... I will try it out later! Thanks!!!
