### ISSUE TITLE
Model is built each-time in represent, verify and analyze

### ISSUE THREAD

**Issue by asadullahnaeem** [serengil/deepface#667]
Unlike previous version of DeepFace  we cannot pass a prebuilt model using `build_model()` so the model is built every-time which is time taking.

**Comment by serengil** [comment]
built models are stored in the memory with singleton pattern [here](https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L56)

so, even if you create the model before calling verify function, then it is not going to be built again and you will not spend time for model building.
