### ISSUE TITLE
DeepFace.stream issues

### ISSUE THREAD

**Issue by Vasmar93** [serengil/deepface#668]
When calling this function and passing the path to a folder with .jpg images, I first got an error because the function "preprocess_face" does not exist. I then changed that to "extract_faces" (the only viable alternative in functions.py) and I'm now getting this error: 

ValueError: Failed to find data adapter that can handle input: (<class 'list'> containing values of types {'(<class \'list\'> containing values of types {"<class \'numpy.ndarray\'>", \'(<class \\\'dict\\\'> containing {"<class \\\'str\\\'>"} keys and {"<class \\\'int\\\'>"} values)\', "<class \'int\'>"})'}), <class 'NoneType'>

**Comment by serengil** [comment]
https://github.com/serengil/deepface/issues/662

**Comment by Vasmar93** [comment]
Sorry but I think I may have not explained my problem clearly since it's not a duplicate of what you linked.

The first problem I had was with functions.preprocess_face. I checked the git code and that function is nowhere to be found: https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py

That in itself is already an issue but I was able to solve it by using functions.extract_faces instead of functions.preprocess_face.

The issue I have now is that when I run DeepFace.stream I get the error I already specified:

ValueError: Failed to find data adapter that can handle input: (<class 'list'> containing values of types {'(<class 'list'> containing values of types {"<class 'numpy.ndarray'>", '(<class \'dict\'> containing {"<class \'str\'>"} keys and {"<class \'int\'>"} values)', "<class 'int'>"})'}), <class 'NoneType'>

The issue isn't my files since they're all .jpg, as they should be.

**Comment by Vasmar93** [comment]
It's not really a duplicate but the solution was indeed the same. Thanks!
