### ISSUE TITLE
resize image in case if detector_backend is skipped

### ISSUE THREAD

**Issue by asadullahnaeem** [serengil/deepface#669]
if `detector_backend="skip"` then image is not resized according to models. This can be used in case of already cropped images.

**Comment by serengil** [comment]
yes, we should consider this. i will fix this in the next release.

**Comment by serengil** [comment]
this is not true in the latest code: https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py#L108

it is resizing images even if skip picked as a detector.

**Comment by asadullahnaeem** [comment]
There is a bug in the `represent()` function: [Link](https://github.com/serengil/deepface/blob/fc3f607bf407ffa4485782774dc96d3f78fb3d4b/deepface/DeepFace.py#L643)
If `detector_backend="skip"` the image is not preprocessed according the models.

**Comment by serengil** [comment]
right, this is a bug

**Comment by serengil** [comment]
done in the source code - https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L664
