### ISSUE TITLE
Best split point

### ISSUE THREAD

**Issue by edwardnguyen1705** [serengil/deepface#67]
Dear @serengil ,

I follow the notebook you give `/tests/Fine-Tuning-Threshold.ipynb`, till the `Best Split Point` section, and I see this line:
`threshold = 0.3147 #comes from c4.5 algorithm`
But I do not know how can you get this number? Could you give a hint?

Thank you!

**Comment by serengil** [comment]
Hello, this is explained in this video: https://youtu.be/s7Ty-0zG5bA

If you still have a question after watching the video, do not hesitate to contact.
