### ISSUE TITLE
AttributeError: module 'deepface.commons.functions' has no attribute 'preprocess_face'.

### ISSUE THREAD

**Issue by xaverkruse** [serengil/deepface#671]
When using the DeepFace.stream() function the following error gets thrown for me on Mac OS

`Traceback (most recent call last):
  File "/Users/xaverkruse/Desktop/DeepFace/app.py", line 3, in <module>
    DeepFace.stream()
  File "/usr/local/lib/python3.10/site-packages/deepface/DeepFace.py", line 590, in stream
    realtime.analysis(db_path, model_name, detector_backend, distance_metric, enable_face_analysis
  File "/usr/local/lib/python3.10/site-packages/deepface/commons/realtime.py", line 205, in analysis
    gray_img = functions.preprocess_face(img = custom_face, target_size = (48, 48), grayscale = True, enforce_detection = False, detector_backend = 'opencv')
AttributeError: module 'deepface.commons.functions' has no attribute 'preprocess_face'. Did you mean: 'preprocess_input'?`

**Comment by ekkolon** [comment]
Duplicate:
https://github.com/serengil/deepface/issues/663#issuecomment-1420969154
https://github.com/serengil/deepface/issues/658#issuecomment-1415941874
#655
