### ISSUE TITLE
DeepFace.analyze: Two results

### ISSUE THREAD

**Issue by ZorkJ** [serengil/deepface#672]
After I update DeepFace, the result for **DeepFace.analyze** has been changed. Now it has two results. Which result should I choose?

![image](https://user-images.githubusercontent.com/31822431/218631074-694d61d6-ca40-4829-834c-5e213798c7ad.png)

**Comment by serengil** [comment]
Facial areas mentioned in the response with x, y, w, h. Choose whatever you want.

ps: old version was using the first one always
