### ISSUE TITLE
it uses build_model for every represent function

### ISSUE THREAD

**Issue by liveseongho** [serengil/deepface#675]
Hey, serengil.

I found you use build_model for every represent function.
But, it's really inefficient when one tries to use this library to get multiple image features (it were millions for me).

So, I called build_model before I use represent and pass the model to the function (it was quite simple).
I hope my experience can help many others and update this library.

**Comment by serengil** [comment]
How did you decide that is inefficient? Build_model uses singleton pattern. So, once it is built, then it will use pre-built one in the memory. So, you do not have to build it beforehand.
