### ISSUE TITLE
number of faces/images

### ISSUE THREAD

**Issue by Sekomer** [serengil/deepface#676]
Hi,

I need to detect many faces, something like 100 people, could using more than 1 image (for example 10) per user increase the total performance?

which detector/backend etc. do you suggest to me for the best accuracy for this problem?

thank you

**Comment by serengil** [comment]
Having more than one images is fine.

Retinaface is the best detector but it is slow. Choose mtcnn if you need both precision and speed. Choose retinaface if time is not important.

**Comment by Sekomer** [comment]
thank you, one more question:
which model(facenet etc.) and metrics(euclidian etc) do you suggest?

**Comment by serengil** [comment]
Facenet, mtcnn, euclidean
