### ISSUE TITLE
Redundant condition on functions.extract_faces()

### ISSUE THREAD

**Issue by wyalves** [serengil/deepface#679]
https://github.com/serengil/deepface/blob/ab8470f96f4d7d4575e110464fb83f94c99fa503/deepface/commons/functions.py#L130

![image](https://user-images.githubusercontent.com/28911639/220209312-c09965f0-a48d-48cd-bd96-7eb307f41796.png)
Isn't this `if` redundant? The same condition is checked on the outer `if`, so at this point in the code this is already assertively true.

**Comment by serengil** [comment]
Right. Same condition is checked twice. Luckily, this does not break anything. Will fix this in the next release. Thank you.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/911
