### ISSUE TITLE
Unable to access the model

### ISSUE THREAD

**Issue by KushRJ** [serengil/deepface#68]
I am trying to run the deepface package on an image for emotion recognition but it gives me the following error:

Actions to do:  ['age', 'gender', 'race', 'emotion']
facial_expression_model_weights.h5 will be downloaded...
Permission denied: https://drive.google.com/uc?id=13iUHHP3SlNg53qSuQZDdHDSDNdBP9nwy
Maybe you need to change permission over 'Anyone with the link'?
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-bf0a495ec2fe> in <module>()
      1 from deepface import DeepFace
----> 2 demography = DeepFace.analyze(crop_img, actions = ['age', 'gender', 'race', 'emotion'])
      3 print("Age: ", demography["age"])
      4 print("Gender: ", demography["gender"])
      5 print("Emotion: ", demography["dominant_emotion"])

2 frames
/usr/lib/python3.6/zipfile.py in __init__(self, file, mode, compression, allowZip64)
   1111             while True:
   1112                 try:
-> 1113                     self.fp = io.open(file, filemode)
   1114                 except OSError:
   1115                     if filemode in modeDict:

FileNotFoundError: [Errno 2] No such file or directory: '/root/.deepface/weights/facial_expression_model_weights.zip'

Could you please guide me how do I solve this? TIA

**Comment by serengil** [comment]
I can access the link in my browser. Could not you install it manually?

Link: https://drive.google.com/uc?id=13iUHHP3SlNg53qSuQZDdHDSDNdBP9nwy

**Comment by KushRJ** [comment]
So you're suggesting I download this file and store it in the directory mentioned, after installing the package via pip?

**Comment by serengil** [comment]
Yes, you can try this. You might access internet via proxy and it might block you to download directly. Downloading the file manually to the specified location will solve this issue.
