### ISSUE TITLE
Error while using DeepFace.analyze when trying to detect emotion

### ISSUE THREAD

**Issue by monumahali** [serengil/deepface#680]
I am getting the below error while trying to predict emotion using DeepFace.analyze

ValueError: Input 0 of layer sequential is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: (None, 48, 48)

**Comment by monumahali** [comment]
This the complete error:

facial_expression_model_weights.h5 will be downloaded...
Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/facial_expression_model_weights.h5
To: /home/ubuntu/.deepface/weights/facial_expression_model_weights.h5
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.98M/5.98M [00:00<00:00, 13.9MB/s]
Action: emotion:   0%|                                                                                                                                                               | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/deepface/DeepFace.py", line 277, in analyze
    emotion_predictions = models['emotion'].predict(img_gray, verbose=0)[0,:]
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/keras/engine/training.py", line 1751, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
    *args, **kwds))
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/keras/engine/training.py:1586 predict_function  *
        return step_function(self, iterator)
    /home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/keras/engine/training.py:1576 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/keras/engine/training.py:1569 run_step  **
        outputs = model.predict_step(data)
    /home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/keras/engine/training.py:1537 predict_step
        return self(x, training=False)
    /home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/keras/engine/base_layer.py:1020 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /home/ubuntu/AI/project_environments/retina_deep_face_env/lib/python3.6/site-packages/keras/engine/input_spec.py:234 assert_input_compatibility
        str(tuple(shape)))

    ValueError: Input 0 of layer sequential is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: (None, 48, 48)

**Comment by serengil** [comment]
Are you using gray scale image?

**Comment by monumahali** [comment]
No I am not using grayscale and the same image is giving correct o/p for other actions such as age, gender etc.

**Comment by serengil** [comment]
would you please share the image?

**Comment by monumahali** [comment]
![Shah_rukh](https://user-images.githubusercontent.com/16682568/220584604-b943a198-506a-433d-a18f-6e1e5e8f6b5b.jpg)

**Comment by serengil** [comment]
interesting. i am able to get emotion results.

```json
{
    "emotion": {
        "angry": 12.318268418312073,
        "disgust": 1.4325009658932686,
        "fear": 70.27139067649841,
        "happy": 0.6975821685045958,
        "sad": 9.985145181417465,
        "surprise": 0.24122511968016624,
        "neutral": 5.053892731666565
    },
    "dominant_emotion": "fear",
    "region": {
        "x": 121,
        "y": 74,
        "w": 116,
        "h": 116
    },
    "age": 45,
    "gender": {
        "Woman": 0.04243064031470567,
        "Man": 99.9575674533844
    },
    "dominant_gender": "Man",
    "race": {
        "asian": 2.141670323908329,
        "indian": 3.8179349154233932,
        "black": 1.2815571390092373,
        "white": 37.041547894477844,
        "middle eastern": 23.6214816570282,
        "latino hispanic": 32.09580481052399
    },
    "dominant_race": "white"
}
```

i am firstly using tensorflow==2.7.4.

besides, would you please use the source code instead of pip version?

```shell
$ git clone https://github.com/serengil/deepface.git
$ cd deepface
$ pip install -e .
```

**Comment by monumahali** [comment]
In my environment I have installed bot retina-face and deepface and installed tensorlow is 2.6.2.

Okay will try the installing it from source.
Thanks

**Comment by monumahali** [comment]
and python 3.6.8

**Comment by ekkolon** [comment]
@monumahali, also please check your Python version. 
Take a look at #674

**Comment by monumahali** [comment]
Thanks, @ekkolon and @serengil for your help. It was related to the python version... Changed the python version and it's working fine now.
