### ISSUE TITLE
Implementation of Darknet's Yolo in Deepface Detectors

### ISSUE THREAD

**Issue by Zaeem20** [serengil/deepface#682]
Hey serengil;

I am pretty much satisfied with your work, as I am using your library in my projects, while doing some research I got this, it seems that yoloface algorithm is much faster and more accurate than MTCNN and UltraLight, can you implement it in DeepFace too...

![image](https://user-images.githubusercontent.com/60778335/221401816-7f818b1c-a874-4fc1-acb3-179140395c3e.png)

**Comment by serengil** [comment]
found this tensorflow implementation - https://github.com/sthanhng/yoloface

will work to implement this dependency when i have time

**Comment by Zaeem20** [comment]
Ok is there any option currently to set detector_backend as yoloface or I just want to set my custom detector in DeepFace.verify()

**Comment by Zaeem20** [comment]
Waiting for answer @serengil

**Comment by serengil** [comment]
No you cannot use that backend now

**Comment by Zaeem20** [comment]
Any ETA for Next Release as you said for this yoloface implementation, By the way, I also implemented yoloface in detectors in my forked repo, but there is a problem with landmarks or facial features you can say, for alignment. I am unable to do that, but it may help you. Would you like me to make a pull request for it??? @serengil

**Comment by serengil** [comment]
Do not wait it to be implemented soon.

PRs are welcome but I cannot merge it if it is not working with alignment.

**Comment by Vincent-Stragier** [comment]
Hi @Zaeem20,

This is interesting, but it looks like it's not better than Retinaface (and the paper backing the repo you linked seems to contain [mistakes regarding the performances compared to SoA that have not yet been addressed by the authors](https://github.com/deepcam-cn/yolov5-face/issues/214)). Still, if there is a speed improvement, it can be useful.

Note that you can extract the faces with whatever fits your needs and then skip the face detection feature (`detector_backend = "skip"`) of some of this module functions and methods.
