### ISSUE TITLE
tensorflow-gpu package removed

### ISSUE THREAD

**Issue by Immodal** [serengil/deepface#684]
Hi there, I went through the closed issues to figure out how to enable ussage of the gpu and the advice was to install tensorflow-gpu. However the packages has been removed as it has been merged with tensorflow.

While it is possible to just install the older version of the library, is there a way to enable GPU acceleration now with the latest tensorflow versions?

https://pypi.org/project/tensorflow-gpu/

**Comment by serengil** [comment]
1- you should ask this question to tensorflow community directly. 
2- my guess is that gpu usage should be enabled if you have a gpu
