### ISSUE TITLE
low test accuracy on align images

### ISSUE THREAD

**Issue by xudou3** [serengil/deepface#69]
Hi, 

I have a private dataset and align to 112*112 by mtcnn. And I set enforce_detection=False in DeepFace.find() to test accuracy. It is close to 0 for all models I tested. Is there anything wrong to test in this way? 

Looking forward to your suggestion.

**Comment by serengil** [comment]
I have to see the data set.

**Comment by xudou3** [comment]
Sorry, it is a private dataset I can't send it to you. It contains 112*112 align face which looks like lfw.

**Comment by serengil** [comment]
So, I could not find a solution in this situation. Sorry.
