### ISSUE TITLE
deepface.stream() ERROR

### ISSUE THREAD

**Issue by Aditya00000000** [serengil/deepface#690]
i am using python 3.10.5 on vscode and getting this error and could not able to find any solution for this can u help me ........

code----

from deepface import DeepFace
DeepFace.stream(db_path=r"C:\Users\HP\Desktop\studies\coding\python\detection\database")

Error--

File "c:\Users\HP\Desktop\studies\coding\python\detection\streamdetection.py", line 36, in <module>
    DeepFace.stream(db_path=r'C:\Users\HP\Desktop\studies\coding\python\detection\database',model_name="VGG-Face")
  File "C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\deepface\DeepFace.py", line 590, in stream
    realtime.analysis(db_path, model_name, detector_backend, distance_metric, enable_face_analysis
  File "C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\deepface\commons\realtime.py", line 97, in analysis
    img = functions.preprocess_face(img = employee, target_size = (input_shape_y, input_shape_x), enforce_detection = False, detector_backend = detector_backend)
AttributeError: module 'deepface.commons.functions' has no attribute 'preprocess_face'. Did you mean: 'preprocess_input'?

**Comment by serengil** [comment]
Upgrade your deepface version to latest

**Comment by Aditya00000000** [comment]
thank you sir
