### ISSUE TITLE
[ Tutorial ] plt.imshow(img)

### ISSUE THREAD

**Issue by KomputerMaster64** [serengil/deepface#691]
Thank you for open-sourcing the work. I was going through the [YouTube tutorial](https://www.youtube.com/watch?v=WnUVYQP4h44&list=PLsS_1RYmYQQFdWqxQggXHynP1rqaYXv_E&index=2).

</br>While using `plt.imshow(img1)`, an error was given: `TypeError: Image data of dtype object cannot be converted to float`.
```
#   Define the Image paths for the `verify` function
img1_path = '/content/deepface/tests/dataset/img1.jpg'


#   Use the Image Detect function `detectFace`
# img1 = DeepFace.detectFace(img_path=img1_path)
#   ⚠️ Function detectFace is deprecated! Use extract_faces instead of this.
img1 = DeepFace.extract_faces(img_path=img1_path)


#   Plot the image
plt.imshow(img1)
```
</br> Can the error be attributed to the `DeepFace.extract_faces` method?

**Comment by KomputerMaster64** [comment]
The code works with `detectFace` method and prints the cropped image using `plt.imshow()`.
</br>
```
img1_ext = DF.detectFace(img1_path)
plt.imshow(img1_ext)
```

</br>However, it would be great if you could share what to do about the warning `⚠️ Function detectFace is deprecated! Use extract_faces instead of this.`.

</br>Using the `extract_face` method results in `plt.imshow()` giving the error as `TypeError: Image data of dtype object cannot be converted to float`.

**Comment by serengil** [comment]
Code snippets are shared in read me aleady

**Comment by FurkanGozukara** [comment]
> Code snippets are shared in read me aleady

how to save DeepFace.extract_faces result in an image file?
cant find anywhere any example

**Comment by FurkanGozukara** [comment]
> The code works with `detectFace` method and prints the cropped image using `plt.imshow()`.
> 
> ```
> img1_ext = DF.detectFace(img1_path)
> plt.imshow(img1_ext)
> ```
> 
> However, it would be great if you could share what to do about the warning `⚠️ Function detectFace is deprecated! Use extract_faces instead of this.`.
> 
> Using the `extract_face` method results in `plt.imshow()` giving the error as `TypeError: Image data of dtype object cannot be converted to float`.

how to save DeepFace.extract_faces result in an image file?
