### ISSUE TITLE
Display only name instead of displaying a picture from db when using stream function

### ISSUE THREAD

**Issue by juaone1** [serengil/deepface#692]
Hi thank you for this cool library, 
I wanted to ask how can I display only the name of the image instead of having a picture when a face is recognize when using the stream function?

**Comment by serengil** [comment]
You cannot do it as is. You should customize realtime.py.

**Comment by juaone1** [comment]
thank you for the very quick response can you point me on how I can do that?

**Comment by serengil** [comment]
Disable these lines
- https://github.com/serengil/deepface/blob/master/deepface/commons/realtime.py#L456
- https://github.com/serengil/deepface/blob/master/deepface/commons/realtime.py#L507
- https://github.com/serengil/deepface/blob/master/deepface/commons/realtime.py#L564
- https://github.com/serengil/deepface/blob/master/deepface/commons/realtime.py#L623
