### ISSUE TITLE
gender model has been compromised

### ISSUE THREAD

**Issue by Lucifer8181** [serengil/deepface#698]
All models are running good but gender model is compromised please correct _your_ gender model
![Screenshot 2023-03-14 153501](https://user-images.githubusercontent.com/59963193/224966584-8f9c3c47-ac48-4ed8-8fa9-03eec7f7adc6.jpg)

**Comment by serengil** [comment]
predicting your age incorrect does not make model incorrect. no ml models can offer 100% accuracy. as mentioned in its [tutorial](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/), age model comes with plus and minus 4 years mean absolute error.

**Comment by Lucifer8181** [comment]
Not age gender detection is incorrect

**Comment by serengil** [comment]
Similarly, gender prediction has [97% accuracy](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/). I cannot offer a model with 100% accuracy, unfortunately.

**Comment by Lucifer8181** [comment]
I have the model with 100℅ accuracy for gender detection if you I can give
you that model

**Comment by serengil** [comment]
then use it

if it reaches 100% then it is not ML
