### ISSUE TITLE
Deepface installation issue in windows 10

### ISSUE THREAD

**Issue by rahul1728jha** [serengil/deepface#701]
Hi,

I am trying to install deepface package in windows 10. 
Steps:

- Created a virtual environment version using pip.
- Run pip install deepface
- 

Error:
```
Installing collected packages: tensorflow-intel, tensorflow, mtcnn, retina-face, deepface
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\users\\abc.efg\\documents\\deepface_env\\Lib\\site-packages\\tensorflow\\include\\external\\com_github_grpc_grpc\\src\\core\\tsi\\alts\\zero_copy_frame_protector\\alts_grpc_integrity_only_record_protocol.h'
```

Can someone please help with the above. 
It is looking for alts_grpc_integrity_only_record_protocol.h inside the folder below -->

`deepface_env\\Lib\\site-packages\\tensorflow\\include\\external\\com_github_grpc_grpc\\src\\core\\tsi\\alts\\zero_copy_frame_protector 
`
Folder is present but the said file is missing. 

Do I need to install something else like the grpc package for python which is : pip install grpcio
As I am trying to keep the environment as light as possible, is it necessary to install grpcio or something else is needed altogether.

Any help would be much appreciated.

Thanks

**Comment by varunponda** [comment]
Hey @rahul1728jha, There are 2 work arounds, 
1) Have a smaller path like: C:/project/env
2) go to registry editor> filesystem>and change longPathsEnabled to1. 
Hope this helps
