### ISSUE TITLE
Processing time of face detector

### ISSUE THREAD

**Issue by Aave-maxine** [serengil/deepface#704]
This is my development environment.
```
NVIDIA GeForce RTX 3080
Cuda 11.4
Cudnn 8.2
Tensorflow-gpu 2.6.0
```

I checked the processing time of verify() with the function of Face Verification. 
The result is that the GPU is about 0.36 sec faster than the CPU.
https://github.com/serengil/deepface/blob/9d96dc0a4b957275069e7e423b4cab522b3d9552/deepface/DeepFace.py#L89

And, I checked the processing time of extract_faces() with the Face Detector function. The result is that the processing time of GPU and CPU is similar.
https://github.com/serengil/deepface/blob/9d96dc0a4b957275069e7e423b4cab522b3d9552/deepface/DeepFace.py#L750

Why not use Face Detector on GPU?

**Comment by serengil** [comment]
Try different detector such as mtcnn or retinaface. Default one is opencv and it seems not working on gpu.

**Comment by Aave-maxine** [comment]
As a result of checking, there are only two Face Detector models to which GPU is allocate, as you said, RetinaFace and MTCNN.

However, the improvement in the processing time of face detection is very poor even if the GPU is allocated.

Are there benchmarks comparing GPU and CPU performance for face detection and face recognition that I can refer to?
