### ISSUE TITLE
Question: sorry if wrong place to ask.

### ISSUE THREAD

**Issue by User1231300** [serengil/deepface#706]
Hi, sorry if this is the wrong place to ask,

I have a bunch of videos (about 1000) that contain various people, about 300 people.

I want to build an app that allows me to build a catalogue of the people that appear in every video, based on their faces, so that i can just ask, "In which videos does x person appear?" or "Which people appear in this video?"

I'm thinking of using this repo and the "live video" option seems appealing, as you can organize folders with example faces of every person, but is there a way to use that option for just video and not live video?

Also, would there be a way to "detect" new faces directly from the videos? How useful is it to provide multiple examples for a face? is it bad since it's one shot learning?

Thank you for your time.

Also, is there an option to make the process faster using GPU?

**Comment by serengil** [comment]
1- you can use deepface for this task
2- no out of the box function available for this. You should process frames of that video and call deepface.
3- gpu makes it faster

**Comment by User1231300** [comment]
Thank you for the insanely fast response. Where can i find informations on how to use gpu when running deepface?

**Comment by serengil** [comment]
If you install tensorflow-gpu first, the. It will use gpu automatically

**Comment by User1231300** [comment]
Thank you. Is there a way to confirm that it's using gpu?
