### ISSUE TITLE
Output type of find()

### ISSUE THREAD

**Issue by MinYoung-Lim** [serengil/deepface#707]
I have a problem about find().

I used find(), but I got list type, not dataframe..
How can I solve this problem?

![image](https://user-images.githubusercontent.com/52227367/229264162-f801b115-958b-49f6-bf3f-6a916b654e11.png)

**Comment by serengil** [comment]
This is not a problem. Find returns list of data frames as explained in read me.

**Comment by MinYoung-Lim** [comment]
Thank you for your answer.

However, I saw your demo video from YouTube. (https://www.youtube.com/watch?v=Hrjp-EStM_s)
In the video (2:18) , the type of df is pandas.core.frame.DataFrame. 

But in my case, the type of df is list, so I can not use 'df.iloc[0].identity'.

Can you help me..?

**Comment by serengil** [comment]
Find returns a list of data frames. Try this:

df[0].iloc[0].identity
