### ISSUE TITLE
Exception in DeepID on 0.0.79 version

### ISSUE THREAD

**Issue by fernandavborges** [serengil/deepface#708]
Good morning,
I was running the newest version of deepface models (0.0.79) with FG-NET dataset and I got this message when code arrives at DeepID. When I downgrade the version to 0.0.75 the code seems to run with no problems.

**Comment by fernandavborges** [comment]
I forgot to attach the print
![image](https://user-images.githubusercontent.com/58860628/229287225-c2d3e2fb-2889-4974-bb00-7beb43f649e1.png)

**Comment by serengil** [comment]
would you please try the source code instead of pip version?

```python
$ git clone https://github.com/serengil/deepface.git
$ cd deepface
$ pip install -e .
```

**Comment by fernandavborges** [comment]
I created a virtual environment and tried that way but got the same error.
![image](https://user-images.githubusercontent.com/58860628/229298072-db2cd8ad-6ae5-4c8c-98a3-a22add9ad12e.png)

**Comment by serengil** [comment]
ty, i know how to fix this. will let you know when it is ready.

**Comment by serengil** [comment]
just updated the source code. please try it now instead of pip version. will publish this if everything is okay for your side.
