### ISSUE TITLE
How to avoid black padding pixels?

### ISSUE THREAD

**Issue by xjtupanda** [serengil/deepface#709]
Thanks for the great work! I have a question about the face detector module.
The README.md mentions that 

> To avoid deformation, deepface adds black padding pixels according to the target size argument after detection and alignment.

If I don't want any padding pixels, what pre-processing steps should I do? Or is there any requirement on the shape if I want to skip the padding?

**Comment by serengil** [comment]
you can set detector backend to skip but this time is not going to focus on facial area.
