### ISSUE TITLE
is dlib Detector use gpu ?

### ISSUE THREAD

**Issue by Shamaseen-iotistic** [serengil/deepface#713]
Hello
I have tried Face recognition using (Facenet512 and dlib) on 300 images it takes 8 min.
And I have tried to install TensorFlow-GPU but the time is still 8 min. 

If use  (Facenet512 and ssd )for example it uses GPU but with using  (Facenet512 and dlib)  it's now.
#######
```
python version 3.9.16
TensorFlow-GPU version 2.11.1
```
#######
Any suggest for solving the problem ??

**Comment by serengil** [comment]
Just tf based models can use gpu

**Comment by Shamaseen-iotistic** [comment]
@serengil so dlib detector is mush slow than other detectors?
can i speed it up ?

**Comment by Shamaseen-iotistic** [comment]
since it takes a long time to process images.
