### ISSUE TITLE
Why is the memory still occupied after Deepface.find() method is executed?

### ISSUE THREAD

**Issue by fanandli** [serengil/deepface#716]
> Exception is clear. Your memory is not enough.

I understand that when I call Deepface.find(), the GPU memory usage will increase. 
However, shouldn't the GPU memory usage decrease after I finish executing this method? 
Why is it that after calling the find method once, the GPU memory usage remains high for a long time?

Thank you very much.

_Originally posted by @fanandli in https://github.com/serengil/deepface/issues/715#issuecomment-1502792005_

**Comment by serengil** [comment]
no, because gpus are applying greedy approach. once they allocated a memory, then they will not release.

recommend you to read this: https://sefiks.com/2019/03/20/tips-and-tricks-for-gpu-and-multiprocessing-in-tensorflow/

you can set allow_growth argument to avoid greedy approach
