### ISSUE TITLE
Installation via pip does not install Github version

### ISSUE THREAD

**Issue by eltrujo** [serengil/deepface#717]
This is the process I followed to find this:

1. Run `pip install deepface` (at writing time, it will install version 0.0.79)
2. Go into `deepface/commons/functions.py`
3. Check this line of code
```python
elif url_img is True:
    img = np.array(Image.open(requests.get(img, stream=True, timeout=60).raw).convert("RGB"))
```
4. According to GitHub version, it should be:
```python
if img.startswith("http"):
    return np.array(Image.open(requests.get(img, stream=True, timeout=60).raw).convert("RGB"))[
        :, :, ::-1
    ]
```
Basically, that line of code is different, so it means that either the version being installed via `pip` is not the same as the one shown in Github, or I'm missing something.

Doing this on Windows.

**Comment by serengil** [comment]
Yes, pip version comes after the source code. I have not published that change yet.

**Comment by eltrujo** [comment]
I understand, when do you think you will publish it?
