### ISSUE TITLE
One shot facial recognition from a set of different faces

### ISSUE THREAD

**Issue by cspearl** [serengil/deepface#719]
Hi, Deepface library is really useful and is giving good results.

But I want to do facial recognition as well as detection.  I have a database of different face images(one image for each face). How do I use deepface to detect(give bounding box) and also recognise the face on a set of unseen images(or a single image)? It is similar to your real time detection function Deepface.stream() but on still images not a live stream. 

Thanks!

**Comment by serengil** [comment]
Read this tutorial: https://sefiks.com/2021/02/06/deep-face-recognition-with-sql/
