### ISSUE TITLE
deepface docker build issue

### ISSUE THREAD

**Issue by WisamAbbasi** [serengil/deepface#720]
Hello,
I get the below error message when I try to build the deepface docker after cloning the repo:

 => ERROR [13/13] RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org -e .                                        2.2s
------
 > [13/13] RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org -e .:
#18 1.697 Obtaining file:///app
#18 1.699   Preparing metadata (setup.py): started
#18 1.906   Preparing metadata (setup.py): finished with status 'error'
#18 1.912   error: subprocess-exited-with-error
#18 1.912
#18 1.912   × python setup.py egg_info did not run successfully.
#18 1.912   │ exit code: 1
#18 1.912   ╰─> [6 lines of output]
#18 1.912       Traceback (most recent call last):
#18 1.912         File "<string>", line 2, in <module>
#18 1.912         File "<pip-setuptools-caller>", line 34, in <module>
#18 1.912         File "/app/setup.py", line 6, in <module>
#18 1.912           with open("requirements.txt", "r", encoding="utf-8") as f:
#18 1.912       FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
#18 1.912       [end of output]
#18 1.912
#18 1.912   note: This error originates from a subprocess, and is likely not a problem with pip.
#18 1.914 error: metadata-generation-failed
#18 1.914
#18 1.914 × Encountered error while generating package metadata.
#18 1.914 ╰─> See above for output.
#18 1.914
#18 1.914 note: This is an issue with the package mentioned above, not pip.
#18 1.914 hint: See above for details.
#18 2.109 WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
#18 2.109 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org -e .]: exit code: 1

**Comment by serengil** [comment]
in the past, requirements content copied into the setup.py. then, i started to requirements from setup but it seems i forget to add it into the image. just update the code. you can use it now.
