### ISSUE TITLE
Does GPU memory only decrease when the process dies? Will it not be reclaimed once allocated?

### ISSUE THREAD

**Issue by fanandli** [serengil/deepface#721]
no, because gpus are applying greedy approach. once they allocated a memory, then they will not release.

recommend you to read this: https://sefiks.com/2019/03/20/tips-and-tricks-for-gpu-and-multiprocessing-in-tensorflow/

you can set allow_growth argument to avoid greedy approach

_Originally posted by @serengil in https://github.com/serengil/deepface/issues/716#issuecomment-1502868743_

**Comment by fanandli** [comment]
Thank you very much for your reply. I have also modified the relevant logic according to the content of the article in the link you provided. 
```python
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU')
for gpu_instance in physical_devices:
    tf.config.experimental.set_memory_growth(gpu_instance, True)
```

GPU memory is no longer allocated 14GB at the first time, but gradually increases as I call the deepface.find interface more times, from 80M to 1000M to 3000M.... 
However, I am still a little worried, as I wrote in my title, if the GPU memory only increases gradually and does not automatically reclaim the allocated memory, won't the GPU memory be insufficient someday? 
What I understand is that the GPU driver will automatically reclaim the allocated but possibly unnecessary memory.

Thank you very much for your multiple replies.

**Comment by fanandli** [comment]
i use deepface.find() like this:
```python
df = DeepFace.find(img_path=final_file_list, db_path="/home/smart/Smartcity/FR/dataset/" + business + '/', model_name='ArcFace',
                      detector_backend='dlib', enforce_detection=False)
```

**Comment by serengil** [comment]
gpu can be insufficient anytime. that is coming from the nature of gpus. they cannot have same memory with your cpu.

you can try to run garbage collector but still it will not be a constant solution.

**Comment by fanandli** [comment]
Thank you for your reply 😄
