### ISSUE TITLE
Error in using Dlib 

### ISSUE THREAD

**Issue by saif0046** [serengil/deepface#722]
from deepface import DeepFace
import matplotlib.pyplot as plt
import pandas as pd

df = DeepFace.find(img_path='kavan1.jpg', db_path='/home/deftbox/Documents/30days_of_Python/Face_Recognition_using_DL/FR_YT/unknown_folder', model_name = 'Dlib', enforce_detection=False)
KeyError: 'content-type' 

I got an error when i run this code please check the code is right or not.

**Comment by serengil** [comment]
snippet seems right. your dlib installation might be missing. also, do not give your program deepface.py.
