### ISSUE TITLE
Output of find being truncated when running through CLI

### ISSUE THREAD

**Issue by TyrasNistru** [serengil/deepface#724]
I'm trying to make an application of mine (in C++) that calls the deepface CLI to recognize faces on a image, but when I call the CLI from my application, the output is truncated compared to the output from a terminal window. 

After some tests, looks like to me that deepface grabs the terminal window size and truncate based on that information, but that ends up cutting information such as the face rectangle information, filepath of the match, and the header.

The examples below were obtained by running the same command, but with different terminal window sizes and from my application:

Terminal window, 363 characters width:
`                                            identity  source_x  source_y  source_w  source_h  VGG-Face_cosine 0  /home/tyras/Tests/deepface/database/Zuzu/81387...       401       475       256       256     8.881784e-16`

Terminal Window, 66 characters width
`                                            identity  ...  VGG-Face_cosine 0  /home/tyras/Tests/deepface/database/Zuzu/81387...  ...     8.881784e-16  [1 rows x 6 columns]`

Terminal Window, 98 characters width
`                                            identity  source_x  ...  source_h  VGG-Face_cosine 0  /home/tyras/Tests/deepface/database/Zuzu/81387...       401  ...       256     8.881784e-16  [1 rows x 6 columns]`

Process output received by my application:
`                                            identity  ...  VGG-Face_cosine 0  /home/tyras/Tests/deepface/database/Zuzu/81387...  ...     8.881784e-16  [1 rows x 6 columns]`

Is there a way to avoid this behavior?

**Comment by TyrasNistru** [comment]
I looked the duplicated issue, but sadly I can't do what you suggested there, since my goal is not to run in a terminal shell, but inside my application, that will start it as a child process and read its output directly.

**Comment by serengil** [comment]
Unforunately, fire works like this. Nothing can be done.

I recommend you to get api up and call it in the background.
