### ISSUE TITLE
enforce_detection

### ISSUE THREAD

**Issue by karthikasuresh18** [serengil/deepface#725]
I'm getting error : Face could not be detected. Please confirm that the picture is a face photo "
            + "or consider to set enforce_detection param to False.
Even after changing the parameter enforce_detection to false in functions.py and DeepFace.py , I still get the same error

**Comment by serengil** [comment]
How you are calling?

**Comment by karthikasuresh18** [comment]
df = DeepFace.find(img_path='img1.jpg',db_path='facial')

**Comment by serengil** [comment]
So, you are not sending enforce detection arg.

**Comment by karthikasuresh18** [comment]
tried passing enforce detection arg in find() and it worked. 
could you tell what does region of image means? (in the output :source_x  source_y  source_w  source_h)

**Comment by serengil** [comment]
Means detected face area.

Closing this because there is no issue
