### ISSUE TITLE
Disable GPU 

### ISSUE THREAD

**Issue by woomurf** [serengil/deepface#73]
Hi, I developed flask server using deepface and api.py on docker.  

my flask server disable use GPU. 

but, I can see `DeepFace will run on GPU` on shell. 
![image](https://user-images.githubusercontent.com/39547624/88609416-05089180-d0bf-11ea-95b2-5fdfc771812a.png)

so I tried input command 
`import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"`
before import deepface. 
and 
`DeepFace.allocateMemory()`. 

but it's not working. 

![image](https://user-images.githubusercontent.com/39547624/88609490-35503000-d0bf-11ea-99b2-8f45512415ea.png)
here is nvidia-smi screenshot. 

how can I use GPU?

**Comment by serengil** [comment]
This import os os.environ["CUDA_VISIBLE_DEVICES"]="0" uses 0 index GPU

if you want to disable call this command import os os.environ["CUDA_VISIBLE_DEVICES"]=""

BTW, which version of deepface you are using?

**Comment by woomurf** [comment]
I use 0.0.33 version. 

The GPU is not available even though os.environ["CUDA_VISIBLE_DEVICES"]="0" was used. 

I want to DeepFace using GPU. 

![image](https://user-images.githubusercontent.com/39547624/88622258-63dd0380-d0dd-11ea-822a-87e86ba84404.png)

**Comment by serengil** [comment]
Hmmm, I think I understand. You have to install tensorflow-gpu instead of tensorflow, Please run the following commands respectively.

```
pip uninstall tensorflow
pip install tensorflow-gpu==1.9.0
pip install keras==2.2.0
pip install deepface --no-deps
```

**Comment by woomurf** [comment]
Thank you for your answer! I can use GPU on running DeepFace.
