### ISSUE TITLE
Deepface.find() give same face areas as original img

### ISSUE THREAD

**Issue by B4b4sh** [serengil/deepface#731]
Hi,
First thanks to your powerful lib !

I have unfortunately an "error" when using Deepface.find().

I call like this : dfs = DeepFace.find(img_path="MySearchFolder/01.jpg", db_path="MySearchFolder")
The result I have give same source_x, source_y.... as 01.jpg for all images found.

identity  source_x  source_y  source_w  source_h  Facenet_cosine
0  MySearchFolder/01.jpg       441       313       581       881        0.000000
1  MySearchFolder/11.jpg       441       313       581       881        0.244793
2  MySearchFolder/02.jpg       441       313       581       881        0.311949
3  MySearchFolder/10.jpg       441       313       581       881        0.313851
4  MySearchFolder/08.jpg       441       313       581       881        0.319859
5  MySearchFolder/07.jpg       441       313       581       881        0.333824
6  MySearchFolder/09.JPG       441       313       581       881        0.359747

Where Am I wrong ?

Thx in advance and sorry for disturbing

**Comment by serengil** [comment]
That is not a bug. It mentions regions for 01.jpg - your input image in all rows. We may add the regions for the compared images as an enhancement.

**Comment by B4b4sh** [comment]
> We may add the regions for the compared images as an enhancement.

Could be useful, thx again

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/911
