### ISSUE TITLE
DeepFace.find, force return unknown faces

### ISSUE THREAD

**Issue by CostanzoPablo** [serengil/deepface#733]
Hello. First of all, excellent project. Congratulations !

Is there a way to force "find" to return faces with score 0 ? 

I'm having to run DeepFace.represent along with DeepFace.find, when I could just run DeepFace.find if it would also return the faces that couldn't be identified

**Comment by serengil** [comment]
Unfortunately, response should be as short as it can be.

You can find the difference of current result and all items in the folder in the client side.
