### ISSUE TITLE
[Feature Request] Head Position

### ISSUE THREAD

**Issue by PaulSamuelsonSI** [serengil/deepface#737]
I have a feature request. Sorry if this is not the proper place to make requests.

I would like to get the estimated head position (Pitch, Roll, Yaw) from detected faces. I have seen and tried several samples using dlib landmarks or mediapipe facemesh landmarks. My challenge has been getting correct output in degrees for Pitch, Roll and Yaw. It would be really convenient to get it out of a function in DeepFace.

Thanks,

**Comment by serengil** [comment]
unfortunately, it is out of scope of this project.
