### ISSUE TITLE
DeepFace does not need to run on a GPU

### ISSUE THREAD

**Issue by greenkeeped** [serengil/deepface#742]
There are a lot of questions about GPUs among DeepFace issues.

however, some of the models used by deepface are implemented as tf, but the input data is treated as data in numpy arrays. Also, multidimensional arrays that are the output of the model are also computed with numpy.

Therefore, even if the tf model is assigned to the GPU, the input data, the data of the numpy array, is a structure that can only be assigned to the cpu.

In the end, the inference speed won't show a dramatic difference compared to the CPU.

**Comment by serengil** [comment]
I cannot see an issue here
