### ISSUE TITLE
Not An Issue Thread - I made a tutorial for how to install and utilize DeepFace

### ISSUE THREAD

**Issue by FurkanGozukara** [serengil/deepface#743]
I can make a pull request as well if you accept to add it as a tutorial to readme file. I would appreciate that very much

Thank you so much for this amazing Library 

[**How To Find Best Stable Diffusion Generated Images By Using DeepFace AI - DreamBooth / LoRA Training**](https://youtu.be/343I11mhnXs)

[!![image](https://user-images.githubusercontent.com/19240467/236293388-6254ff84-0866-4bd4-a5d4-2db3c42be3f0.png)](https://youtu.be/343I11mhnXs)

**Comment by serengil** [comment]
thank you but this does not fit for the readme. still if you share this social media, mention me please.
