### ISSUE TITLE
DeepFace.extract_faces is throwing an error KeyError: 'content-type'

### ISSUE THREAD

**Issue by ChamithDilshan** [serengil/deepface#744]
Hi! 
I used deepface (thanks creators for this great library) in a one of my projects and the code worked really well on the PC. (Ubuntu/windows both). 
Here I extract the faces in an image and I use "dlib" as the detector backend. When I try to iplement this on my NUC (which is also a windows pc) this is giving me an error "KeyError: 'content-type' "
I thought it maybe an issue from installation and tried on installing ubuntu on NUC and still not working, same error. 
But if I use mtcnn as the backend it works without any problem. I'm wondering that I can't even find 

---> 52         return self._store[key.lower()][1]

line in FaceDetector.py

Things I tried: 

- Installing deepface from git repo
- Installing deepface from pip
- Moving from windows to ubuntu
- At some points even though I installed deepface, dlib module was missing. So tried installing cmake and dlib from pip but pip install dlib was giving me an error.

![image](https://user-images.githubusercontent.com/73608973/236402900-3be3205e-19cc-4121-8937-fd8ddc36fe5c.png)

**Comment by ChamithDilshan** [comment]
Things I tried: 

- Installing deepface from git repo
- Installing deepface from pip
- Moving from windows to ubuntu
- At some points even though I installed deepface, dlib module was missing. So tried installing cmake and dlib from pip but pip install dlib was giving me an error.

**Comment by serengil** [comment]
this is dlib dependent bug, i recommend you to raise this ticket in dlib repo.

**Comment by ChamithDilshan** [comment]
> 

Okay I'll do. Thanks

**Comment by miawoltn** [comment]
> this is dlib dependent bug, i recommend you to raise this ticket in dlib repo.

I think it's gdown complaining about the content type. The file can be downloaded using urllib. 

If you like I can open a PR for that.
