### ISSUE TITLE
Couldnt install tensorflow

### ISSUE THREAD

**Issue by moerv9** [serengil/deepface#747]
Although this is more or less tensorflows problem, I could not get more information from their page, and the error relates to the deepface package.

When installing my requirements I cannot install tensorflow with `pip install tensorflow`... I get the following error:

`ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow`

I first thought it had something to do with the fact that I have recently got a Macbook with M2 chip and now apparently need to install tensorflow-macos and tensorflow-metal for it but the deepface package doesn't seem to use that or at least I don't know if that's the problem.

I have downgraded my python version and removed the package versions to let pip resolve the issue but its not working:

`The conflict is caused by:
    deepface 0.0.79 depends on tensorflow>=1.9.0`

Any ideas?

**Comment by serengil** [comment]
Duplicated - https://github.com/serengil/deepface/issues/606#issuecomment-1327190675
