### ISSUE TITLE
Question about DeepFace.detectFace()

### ISSUE THREAD

**Issue by Woisek** [serengil/deepface#748]
I just started to us this great tool and have now a script that uses DeepFace.detectFace(). When running, it says that this is deprecated, one should use extract_faces() instead. Could anyone explain how I can change the script accordingly?

Currently, I have this:
`detected_face = DeepFace.detectFace(org_image_path, detector_backend = 'opencv')`

The newer variant requires three arguments, instead of two AFAIKS. What do I have to do?

**Comment by serengil** [comment]
face_objs = DeepFace.extract_faces("img.jpg")

for face_obj in face_objs:
   print(face_obj["face"])

**Comment by Woisek** [comment]
I'm sorry for this complete late reply, I absolutely did not noticed that an answer was given.
Unfortunately, this helps me not as much as I hoped. Maybe with the code snipped I'm using:

```
# loop through the original images folder and detect faces using DeepFace
for org_image_file in os.listdir(org_images_folder_path):
    if org_image_file.endswith('.jpg') or org_image_file.endswith('.png') or org_image_file.endswith('.JPG'):
        org_image_path =        os.path.join(org_images_folder_path, org_image_file)
        generated_image_path =  os.path.join(generated_images_folder_path, org_image_file)
        org_image =             cv2.imread(org_image_path)
        org_images.append(org_image)
        
        # detect face using DeepFace
        detected_face =         DeepFace.detectFace(org_image_path, detector_backend = 'opencv')
        
        # save the detected face in the detected faces folder
        new_image_path =        os.path.join(detected_faces_folder_path, org_image_file)
        plt.imshow(detected_face)
        detected_face =         detected_face * 255
        cv2.imwrite(new_image_path, detected_face[:, :, ::-1])
        print("Detected face saved in: ", new_image_path)
```
How has detected_face =         DeepFace.detectFace(org_image_path, detector_backend = 'opencv') to be changed?
Thanks for the help!

**Comment by Woisek** [comment]
No one can help ... ? 😞
