### ISSUE TITLE
What is the training/validation dataset used for the model?

### ISSUE THREAD

**Issue by LionLion888** [serengil/deepface#751]
Hello~

Thanks for sharing the code, It is a good tool to do the face recognition.

Now I am trying to reproduce the result. Wounding what is the training and validation dataset used for the following models?

Models: "VGG-Face",   "Facenet",   "Facenet512",   "OpenFace", "DeepFace",   "DeepID", "ArcFace",   "Dlib",   "SFace"

Thanks.

**Comment by serengil** [comment]
you can follow the links in license section, this will redirect you to the original studies. you can find this information in there.

**Comment by LionLion888** [comment]
Hi Serengil,

Got it! I'll take a look.

Thanks.
