### ISSUE TITLE
Validate image is a face

### ISSUE THREAD

**Issue by arkkanoid** [serengil/deepface#76]
Hi, 
I'm analyzing thousands of images but sometimes it's not a face.
![image](https://user-images.githubusercontent.com/3811604/89106034-c6f4d000-d426-11ea-8df4-e5bc90a43c8b.png)
The image I attach is a sample of them. In this case, the result is:
emotion: neutral
gender:Man
race: white
race_ratio:99
age:31.

I'd like to filter this can of images, as it obviously is not a face.
Can I do it with DeepFace?

Thanks in advance

**Comment by serengil** [comment]
Could you share the code block you are running?

```
from deepface import DeepFace
obj = DeepFace.analyze("test-image.png")
print(obj)
```

When I pass the image you've attached, then it returns an error.

**ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.**

**Comment by arkkanoid** [comment]
Hi @serengil ,
`os.environ["CUDA_VISIBLE_DEVICES"]=""
models = {}
models["emotion"] = Emotion.loadModel()
models["age"] = Age.loadModel()
models["gender"] = Gender.loadModel()
models["race"] = Race.loadModel()
from deepface import DeepFace
from deepface.extendedmodels import Age, Gender, Race, Emotion
urllib.request.urlretrieve('https://user-images.githubusercontent.com/3811604/89106034-c6f4d000-d426-11ea-8df4-e5bc90a43c8b.png', "deepface/img.jpg")
res = DeepFace.analyze("deepface/img.jpg", actions = ['age', 'gender', 'race', 'emotion'], enforce_detection=False, models=models)`

**Comment by serengil** [comment]
Set enforce_detection argument to true. Its default value is true btw. If you don’t pass it, it will be true as well.

**Comment by arkkanoid** [comment]
Working! 
Thanks
