### ISSUE TITLE
Question and remarks about the quality of face comparison.

### ISSUE THREAD

**Issue by TheMoye** [serengil/deepface#761]
Hi Serengil, thank you for your work!

I have a question: I see that face comparisons are done using 'embeddings' vectors. Would it be possible to obtain these vectors from multiple photos instead of just one? Wouldn't the comparison be more accurate that way?
Below, I calculated the median of the vectors from these 5 photos in the 6th position: we can see that even though it's the same person, there are differences between the obtained 'embeddings'.

![embeddings](https://github.com/serengil/deepface/assets/46683101/b703c303-1dab-4bf7-b2c6-ca8e49a278ac)

Also, I noticed that the face comparison is not very accurate and sometimes produces false positives (depending on the model and distance metric used). Perhaps I'm not doing it correctly?
In the example below, metrics preceded by the character '✔' indicate that the 'Model / Backend / Metric' triplet finds a match between the two photos, while the character '✘' indicates that the faces belong to different individuals. We can see that in some cases, the 6th photo is associated with the other 5 photos even though it's not the same person. I also find that the 'percentage of face similarity' is not very high. Is there a way (maybe using a different model?) to improve all of this?

![faceMultiCompare](https://github.com/serengil/deepface/assets/46683101/2af5b9b9-750f-4f4f-8e81-79bc91365675)

Thank you! 😊

**Comment by serengil** [comment]
short answer is no. because this is one shot learning example. it is not designed to work with many faces.

you can try to find the average of many vectors, or concat vectors but it will not work.
