### ISSUE TITLE
GPU too slow when first build pkl

### ISSUE THREAD

**Issue by MiMi-Yup** [serengil/deepface#763]
I'm using laptop (i7-9850h, quadro t1000, 16gb ram) to demo app with flask. At first I planned to use pure windows but had an error in installing cuda, so I switched to wsl2. But when running with gpu in wsl2, the first time build pkl is too slower than build it in cpu. And after that (built pkl), gpu is faster than cpu, but not too much. 

My db_path includes 62 images, classified into 4 categories. I use Facenet512, mtcnn.

I would really appreciate someone explaining why and maybe give me some solution for this problem

Sorry about my English skills

**Comment by serengil** [comment]
this is not an issue!
