### ISSUE TITLE
a large number of face and person

### ISSUE THREAD

**Issue by ilovebioz** [serengil/deepface#764]
We want to utilize this projects for a large number of faces and persons (million of persons). Do you have any experiences to share.
About performance, speed ... 

Thank you

**Comment by serengil** [comment]
Check out the following tutorials:
- https://sefiks.com/2020/09/16/large-scale-face-recognition-with-spotify-annoy/
- https://sefiks.com/2020/09/17/large-scale-face-recognition-with-facebook-faiss/
- https://sefiks.com/2020/11/27/large-scale-face-recognition-with-elasticsearch/
- https://sefiks.com/2020/09/19/large-scale-face-recognition-with-nmslib/
