### ISSUE TITLE
how to resuing Face Embedding for verifying same face in different pictures

### ISSUE THREAD

**Issue by surapuramakhil** [serengil/deepface#766]
face verify method doesn't accept any embedding parameter by looking at the code we have replicate similar code to achieve this. Is there any out of the box method which does this.

**Comment by serengil** [comment]
if you want to find the embedding of an image, you can use represent function

if you have pre-calculated embeddings, then you can find the distance between them - https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L196

and then decide they are same person or not - https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L196
