### ISSUE TITLE
please find exception stacktrace - using arcface as model

### ISSUE THREAD

**Issue by surapuramakhil** [serengil/deepface#768]
```   
return DeepFace.find(img_path=img_path, db_path=config.tdes_images_location, align=align,
  File "/home/akhil/PycharmProjects/TDES-analytics/venv/lib/python3.10/site-packages/deepface/DeepFace.py", line 488, in find
    img_objs = functions.extract_faces(
  File "/home/akhil/PycharmProjects/TDES-analytics/venv/lib/python3.10/site-packages/deepface/commons/functions.py", line 105, in extract_faces
    img_region = [0, 0, img.shape[1], img.shape[0]]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by serengil** [comment]
message is clear. your input (most probably img_path or some item in db_path) cannot be load that is why its shape is none.

**Comment by surapuramakhil** [comment]
can I raise a MR for having clear message? @serengil

**Comment by bobbar17** [comment]
> ```
> return DeepFace.find(img_path=img_path, db_path=config.tdes_images_location, align=align,
>   File "/home/akhil/PycharmProjects/TDES-analytics/venv/lib/python3.10/site-packages/deepface/DeepFace.py", line 488, in find
>     img_objs = functions.extract_faces(
>   File "/home/akhil/PycharmProjects/TDES-analytics/venv/lib/python3.10/site-packages/deepface/commons/functions.py", line 105, in extract_faces
>     img_region = [0, 0, img.shape[1], img.shape[0]]
> AttributeError: 'NoneType' object has no attribute 'shape'
> ```

what was the decision of this problem? @surapuramakhil
