### ISSUE TITLE
KeyError: 'content-type' when extracting face with dlib

### ISSUE THREAD

**Issue by hungpham3112** [serengil/deepface#769]
Today is the first time I use this package, I want to extract the face from the image. 

Here is my code:
`detected_face = DeepFace.extract_faces("./obama.jpg", detector_backend = 'dlib')`

But then the issue appeared: 
![image](https://github.com/serengil/deepface/assets/75968004/fe0cf4c1-5442-4c6b-996e-3308d943d336)

![image](https://github.com/serengil/deepface/assets/75968004/7d7fd016-0159-4027-b6ab-cd25829b5102)

It seems that deepface was trying to download the model but it can't

OS: Pop-OS 22.04
Env: conda
Editor: jupyter notebook

**Comment by serengil** [comment]
This is covered here: https://github.com/serengil/deepface/blob/master/deepface/basemodels/DlibResNet.py#LL30C21-L30C43

And the target url is http://dlib.net/files/dlib_face_recognition_resnet_model_v1.dat.bz2

It is still alive. It seems you cannot access that url. Check your firewall or proxy.

**Comment by hungpham3112** [comment]
> This is covered here: https://github.com/serengil/deepface/blob/master/deepface/basemodels/DlibResNet.py#LL30C21-L30C43
> 
> And the target url is http://dlib.net/files/dlib_face_recognition_resnet_model_v1.dat.bz2
> 
> It is still alive. It seems you cannot access that url. Check your firewall or proxy.

The problem is http, I downloaded with firefox and it blocked. Is there any way to handle that with Python?

![image](https://github.com/serengil/deepface/assets/75968004/00512119-0274-4766-8e33-33d7f9e95013)

**Comment by serengil** [comment]
This is not happening in my env. Sorry.

**Comment by hungpham3112** [comment]
> This is not happening in my env. Sorry.

Can you provide more information about your environment? Are you using Linux or Windows?

**Comment by serengil** [comment]
Tested it on mac & debian.

**Comment by hungpham3112** [comment]
I found the problem and can fix this with PR

**Comment by serengil** [comment]
PRs are of course welcome but this is because of your env, not a bug.

**Comment by kennedyjosh** [comment]
I am also experiencing this issue on MacOS. I am able to download from the link in my browser, but not through the code. The PR from @hungpham3112 fixed the issue – what is the harm in accepting his approach, as this `'Content-Type'` field does not seem to be guaranteed?

**Comment by hungpham3112** [comment]
@kennedyjosh Can you look at the PR https://github.com/wkentaro/gdown/pull/302 if it solve downloading problem?
