### ISSUE TITLE
Resizing images for each model

### ISSUE THREAD

**Issue by fmarencic** [serengil/deepface#77]
Even though it's fixed here on git, when you install deepface through `pip install deepface` there's a problem in functions.py.

Code inside function detectFace:

		detected_face = cv2.resize(detected_face, (240, 240))
		
		img_pixels = image.img_to_array(detected_face)
		img_pixels = np.expand_dims(img_pixels, axis = 0)
		
		#normalize input in [0, 1]
		img_pixels /= 255
		
		return img_pixels

Should probably be:

            detected_face = cv2.resize(detected_face, target_size)

that's sent as a parameter of a function.

This causes warnings from tensorflow about incompatible image sizes.

**Comment by serengil** [comment]
The code repo and pypi versions include target_size as argument

Repo: https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py, line 303

Pip: https://pypi.org/project/deepface/0.0.33/#files -> deepface-0.0.33.tar.gz (43.8 kB)

What was your deepface version?

**Comment by fmarencic** [comment]
```
C:\Windows\system32>pip show deepface
Name: deepface
Version: 0.0.33
Summary: A Lightweight Face Recognition and Facial Attribute Analysis Framework (Age, Gender, Emotion, Race) for Python
Home-page: https://github.com/serengil/deepface
Author: Sefik Ilkin Serengil
Author-email: serengil@gmail.com
License: UNKNOWN
Location: c:\users\user\appdata\local\programs\python\python38\lib\site-packages
Requires: Flask, numpy, keras, gdown, tensorflow, pandas, opencv-python, Pillow, tqdm
Required-by:
```

I'm pretty sure I didn't change anything. Doesn't matter if it's fine for others, I just didn't want other people to spend 2 hours looking for a problem like I did.
Probably there was a mistake on my end, but still not sure where and why.

**Comment by serengil** [comment]
It is very interesting. Could you uninstall and reinstall deepface again? Then I would ask you to check that line in your deepface folder.

**Comment by fmarencic** [comment]
Sure will. But I'm doing a project right now with your framework and not really in the mood of risking anything again. 😄 

Will do it right after I'm done and I'll come back with an answer.
