### ISSUE TITLE
Deepface:Emotion,Age and Gender Detection Slow

### ISSUE THREAD

**Issue by Abkob** [serengil/deepface#772]
`hi Serengil , I'm a big fan of your work I am facing some problems with the fps output of the code when detecting faces i will link the code below for you to check ; I know i might be utilizing the library inefficiently i wanted your help .
😍😍🥰🥰🥰
[Detect_DEEPFACE.zip](https://github.com/serengil/deepface/files/11661006/Detect_DEEPFACE.zip)

**Comment by Abkob** [comment]
""import cv2
import numpy as np
import time
import cvlib as cv
from deepface import DeepFace
from threading import Thread

# open webcam
webcam = cv2.VideoCapture(0)

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

# function for face processing
def process_face(frame, startX, startY, endX, endY):
    # crop the detected face region
    face_crop = np.copy(frame[startY:endY, startX:endX])

    if (face_crop.shape[0]) < 10 or (face_crop.shape[1]) < 10:
        return

    # Extract the face region from the frame
    face = frame[startY:endY, startX:endX]

    # Analyze the face region for emotion and age
    result = DeepFace.analyze(img_path=face, actions=['emotion', 'age','gender'], enforce_detection=False)

    # Get the dominant emotion and age
    emotion = result[0]["dominant_emotion"]
    age = result[0]['age']
    gender = result[0]['dominant_gender']

    # Display emotion and age below the face box
    cv2.putText(frame, f"Emotion: {emotion}", (startX, endY + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
    cv2.putText(frame, f"Age: {age}", (startX, endY + 50), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
    text_width, text_height = cv2.getTextSize(gender, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2)[0]
    cv2.putText(frame, f"{gender}", (startX + (endX - startX) - text_width, startY - 10),        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

# function for processing frames in parallel
def process_frames():
    global frame_counter
    frame_counter = 0
    global skip_frames
    skip_frames = 2
    global max_processing_time
    max_processing_time = 0.1  # seconds
    prev_time = 0

    while webcam.isOpened():
        status, frame = webcam.read()

        if not status:
            print("Could not read frame")
            break

        frame_counter += 1

        if frame_counter % skip_frames == 1:
            continue

        start_time = time.time()

        face, confidence = cv.detect_face(frame)

        for idx, f in enumerate(face):
            (startX, startY) = f[0], f[1]
            (endX, endY) = f[2], f[3]

            cv2.rectangle(frame, (startX, startY), (endX, endY), (0, 255, 0), 2)

            process_face(frame, startX, startY, endX, endY)

        # Calculate and display the FPS
        curr_time = time.time()
        fps = 1 / (curr_time - prev_time)
        prev_time = curr_time
        cv2.putText(frame, f"FPS: {int(fps)}", (10, 30), cv2.FONT_HERSHEY_TRIPLEX, 0.7, (0, 255, 0), 2)

        cv2.imshow("gender detection", frame)
        end_time = time.time()
        processing_time = end_time - start_time

        if processing_time > max_processing_time:
            skip_frames += 1
        else:
            skip_frlames = max(1, skip_frames - 1)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    webcam.release()
    cv2.destroyAllWindows()

# run the processing loop in a separate thread
t = Thread(target=process_frames)
t.start()
t.join()
""

**Comment by Abkob** [comment]
```import cv2
import numpy as np
import time
import cvlib as cv
from deepface import DeepFace
from threading import Thread

# open webcam
webcam = cv2.VideoCapture(0)

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

# function for face processing
def process_face(frame, startX, startY, endX, endY):
    # crop the detected face region
    face_crop = np.copy(frame[startY:endY, startX:endX])

    if (face_crop.shape[0]) < 10 or (face_crop.shape[1]) < 10:
        return

    # Extract the face region from the frame
    face = frame[startY:endY, startX:endX]

    # Analyze the face region for emotion and age
    result = DeepFace.analyze(img_path=face, actions=['emotion', 'age','gender'], enforce_detection=False)

    # Get the dominant emotion and age
    emotion = result[0]["dominant_emotion"]
    age = result[0]['age']
    gender = result[0]['dominant_gender']

    # Display emotion and age below the face box
    cv2.putText(frame, f"Emotion: {emotion}", (startX, endY + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
    cv2.putText(frame, f"Age: {age}", (startX, endY + 50), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
    text_width, text_height = cv2.getTextSize(gender, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2)[0]
    cv2.putText(frame, f"{gender}", (startX + (endX - startX) - text_width, startY - 10),        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

# function for processing frames in parallel
def process_frames():
    global frame_counter
    frame_counter = 0
    global skip_frames
    skip_frames = 2
    global max_processing_time
    max_processing_time = 0.1  # seconds
    prev_time = 0

    while webcam.isOpened():
        status, frame = webcam.read()

        if not status:
            print("Could not read frame")
            break

        frame_counter += 1

        if frame_counter % skip_frames == 1:
            continue

        start_time = time.time()

        face, confidence = cv.detect_face(frame)

        for idx, f in enumerate(face):
            (startX, startY) = f[0], f[1]
            (endX, endY) = f[2], f[3]

            cv2.rectangle(frame, (startX, startY), (endX, endY), (0, 255, 0), 2)

            process_face(frame, startX, startY, endX, endY)

        # Calculate and display the FPS
        curr_time = time.time()
        fps = 1 / (curr_time - prev_time)
        prev_time = curr_time
        cv2.putText(frame, f"FPS: {int(fps)}", (10, 30), cv2.FONT_HERSHEY_TRIPLEX, 0.7, (0, 255, 0), 2)

        cv2.imshow("gender detection", frame)
        end_time = time.time()
        processing_time = end_time - start_time

        if processing_time > max_processing_time:
            skip_frames += 1
        else:
            skip_frlames = max(1, skip_frames - 1)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    webcam.release()
    cv2.destroyAllWindows()

# run the processing loop in a separate thread
t = Thread(target=process_frames)
t.start()
t.join()
```

**Comment by serengil** [comment]
These are very complex models and it is normal being slow.

**Comment by Abkob** [comment]
I'm still new to all of this it might mean I'm coding the process wring that's why i wanted your insight .I'm sorry for wasting your time.

**Comment by Abkob** [comment]
i meant isnt there a way to  make these models faster ?

**Comment by serengil** [comment]
no, unless you invest a powerful and expensive gpus
