### ISSUE TITLE
Backwards Compatibility for Ensemble Model

### ISSUE THREAD

**Issue by greenkode** [serengil/deepface#778]
Hi,

I'm revisiting this [discussion](https://github.com/serengil/deepface/issues/673) and I'm unable to re-open the question.

If the ensemble model is no longer supported is this because the individual models themselves are accurate enough?

One of the benefits of the ensemble model was the confidence score that it gave. How do I calculate that of just a single model? Is there any documentation on that?

Lastly it seems the older versions of deepface won't really work anymore due to the fact that the ensemble model is not downloadable. is it possible to still keep that online somewhere for sake of backwards compatibility?

Thanks

**Comment by falkaabi** [comment]
You can find it here: https://github.com/falkaabi/deepface/tree/master/deepface/models
