### ISSUE TITLE
Query: What is the difference between detector_backend and model_name in many of the functions in Deepface

### ISSUE THREAD

**Issue by anu1097** [serengil/deepface#780]
For example, 

find, stream etc. functions in Deepface have both detector_backend and model_name as arguments. 
I also tried to understand a little more by reading the codebase and some articles too https://viso.ai/computer-vision/deepface/

I didn't really get the difference. Also Dlib is both a detector_backend and model. Its confusing. 

Tried to search existing issues too, if its already been asked.

Sorry, if its a silly question. Good library, thanks for creating it.

Thanks

**Comment by serengil** [comment]
Firstly, these are explained in read me

Model name refers to face recognition models whereas detector backend refers to face detector models.

Dlib has its own face recognition model and face detector. That is why, it appears in both.

**Comment by anu1097** [comment]
Sorry I didn't get the difference between the two earlier, I tried to understand it as I mentioned, I read the readme, codebase and blogs by you.

But now its clear, since you used the terms `face recognition` vs `face detection`. Thanks for the clarification. It was just confusing and I couldn't get clarity anywhere. 

I'm basing my understanding based on this now - 

`While face detection trains a computer to pick out a human face, face recognition software will analyze the image. It will turn the image into a set of data about your facial features. This can include the distance between your eyes, forehead, and chin, and other geometric measurements.`

https://www.two-i.com/blog/face-detection-vs-facial-recognition-whats-the-difference#:~:text=While%20face%20detection%20trains%20a,chin%2C%20and%20other%20geometric%20measurements.

Thank you.
