### ISSUE TITLE
DeepFace: Enforce Detection

### ISSUE THREAD

**Issue by jsnleong** [serengil/deepface#782]
Hi serengil,

I have passport-like images (i.e portrait image with face) and am processing them. However, as some of the images are low-res, I encounter the exception error where the model is not able to detect a face. As such, I added enforce_detection=False.

However, I realized that adding that flag and vectorizing even the high res ones will result in a DIFFERENT vector as compared to when I didn't add that flag. Can you advice for my use-case, should I add the flag for ALL image to ensure consistency, or only add the flag for cases where it has error? Thanks!

**Comment by serengil** [comment]
The only usage point of enforce detection is here: https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py#L162

it throws exception if face cannot be detected. Setting this to false skipping this block. if you are working with low resolution images, then you have to set this to false.

if you suspect it returns different responses even if high resolution images, then set this to true and do try except block in your side.
