### ISSUE TITLE
DeepFace: BGR to RGB

### ISSUE THREAD

**Issue by jsnleong** [serengil/deepface#783]
Hi serengil!

For black/white images, does DeepFace/VGG handle the vectorization of such images?

Also, does the image need to conform to BGR or RGB format? Because I realized it affects the output vector for BGR-type and RGB-type images.

Thanks!

**Comment by serengil** [comment]
you have to pass RGB images.

**Comment by siasio** [comment]
In extract_faces function in DeepFace.py, there is a [docstring line](https://github.com/serengil/deepface/blob/0b8e5ca472e22f8c0dae1ad6ee39ccab90296031/deepface/DeepFace.py#L779) stating that we should pass BGR images: `img_path: exact image path, numpy array (BGR) or base64 encoded image`. But my experiments (with MediaPipe detector) suggest that we should pass RGB images. Is it a mistake in the docstring?
