### ISSUE TITLE
DeepFace: Identifying wrong facial area

### ISSUE THREAD

**Issue by jsnleong** [serengil/deepface#784]
Hi serengil!

There are several portrait images (each photo with only one individual), but the model detected two.

One is the actual facial area, and another is usually the area around the neck.

Any model that does better at detecting faces, and passing these coordinates to DeepFace for vectorization? Thanks!

**Comment by serengil** [comment]
default detector backend is opencv, you must use mtcnn or retinaface if you want to have high confidence as described in the read me.
