### ISSUE TITLE
package conflict between tensorflow and numpy

### ISSUE THREAD

**Issue by hyangai** [serengil/deepface#79]
I got the following error when install deepface with pip:

ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.1 which is incompatible.

**Comment by serengil** [comment]
deepface is tested for tensorflow==1.9.0, numpy==, 1.14.0, keras==2.2.0. You can find the versions of requirements here: https://github.com/serengil/deepface/blob/master/requirements.txt
