### ISSUE TITLE
getting slow over time

### ISSUE THREAD

**Issue by RichardErkhov** [serengil/deepface#791]
hi, if using the model on cpu for multiple images in the for loop, it's getting slower over time. 
It's speed goes from 2 it/s to 5 s/it after 1000 images. No higher RAM usage or anything like that 

I'm using this to analyze the images

```
import os
from deepface import DeepFace
import tqdm
results = []
for path in tqdm.tqdm(os.listdir("images")):
    result = DeepFace.analyze(path, actions = ['age', 'gender', 'race', 'emotion'], silent=1, enforce_detection=False)[0]
    results.extend(result)
```
over time this becomes slower and slower, any ideas ?

**Comment by serengil** [comment]
#697 - duplicated

Already a ticket available for this. You may need to call garbage collector in the loop.

**Comment by lemnet** [comment]
Hi,

Sorry to comment on a closed issue but I also have a small drifting in processing time in `verify` in a for loop.
I don't have a memory leak.
So same as @RichardErkhov but in `verify`

Calling the garbage collector in the loop doesn't change anything.
Trying to call K.clear_session() periodically makes it even slower.
