### ISSUE TITLE
.verify and .find difference

### ISSUE THREAD

**Issue by aperire** [serengil/deepface#792]
I am currently finding image that is the most similar to an input image. The searched dir contains 100k images.

Is .find method basically calling .verify recursively and storing the model? I am currently looping .find as it seems to be more accurate.

**Comment by serengil** [comment]
Find calls verify many times as mentioned in read me.

**Comment by serengil** [comment]
On the other hand, 100k is challenging. You may need to use some a-nn implementation with deepface such as faiss: https://sefiks.com/2020/09/17/large-scale-face-recognition-with-facebook-faiss/
