### ISSUE TITLE
Does the input image of DeepFace. analyze have to be passed in and processed by oneself?

### ISSUE THREAD

**Issue by jin1wang** [serengil/deepface#793]
My code:
DeepFace.analyze(self.crop_img, actions = ['age', 'gender', 'race', 'emotion'])

error:
ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (1, 48, 48)

**Comment by serengil** [comment]
is your input image RGB?

**Comment by jin1wang** [comment]
yes,i am sure. i installed deepface from pypi, version is 0.0.79.

**Comment by serengil** [comment]
please share crop_img here

**Comment by jin1wang** [comment]
```
cv2.imwrite('crop_img.jpg', self.crop_img)
print(self.crop_img.shape)     # this row print(552, 552, 3)
objs = DeepFace.analyze(self.crop_img, actions = ['age', 'gender', 'race', 'emotion'])
```

**Comment by jin1wang** [comment]
`photo_path = './image/photo_test3.jpg'
self.img = cv2.imread(photo_path)
self.crop_img = self.img[y:y+h, x:x+w]
objs = DeepFace.analyze(self.crop_img, actions = ['age', 'gender', 'race', 'emotion'])
`
![crop_img](https://github.com/serengil/deepface/assets/109585184/c83554bc-b01b-43e3-957b-64d1a308efca)

**Comment by jin1wang** [comment]
I found that I can run it with version 0.0.75.
There may be some issues with the pre processing of versions 0.0.78 and 0.0.79

**Comment by serengil** [comment]
What if you sent img instead of croped_img?

What are x and y values to crop?

**Comment by serengil** [comment]
closed due to inactivity
