### ISSUE TITLE
What should normalized pictures look like?

### ISSUE THREAD

**Issue by AnthraX1** [serengil/deepface#795]
I've been testing various normalization methods for Facenet512 model and it appears either "Facenet" and "Facenet2018" normalization method turned pictures into weird inverted colors or mostly black.

Here's before and after:
![5a9e936f1f7b6604e9ee26cf6e07afa56e7dd993_0](https://github.com/serengil/deepface/assets/4828355/91b80976-f71c-4588-9340-2290f2698e38) ![5a9e936f1f7b6604e9ee26cf6e07afa56e7dd993_1](https://github.com/serengil/deepface/assets/4828355/3a6195d1-2e28-48b6-a6a5-460ce0ca215d)
Both of them used the same output method and I only changed normalization method from "base" to "Facenet". Is it supposed to be like this or is there something wrong? My numpy version is 1.23.0

**Comment by serengil** [comment]
1- i am not using any normalization for facenet models. They are added by contributors.

2- these are the most robust models supported in deepface.
