### ISSUE TITLE
How to perform feature extraction on Facenet512?

### ISSUE THREAD

**Issue by dayahiman** [serengil/deepface#797]
Hi Serengil,

Thanks for maintaining this amazing project. It has simplified many areas in facial verification/recognition.

We have done some experiments with some of the models and like the performance of the Facenet512 on small specific dataset we have. We want to see if we can perform feature extraction on this model.

We're thinking to drop the classification block and get the output from layers above it like Block8_6_Conv2d_1x1. Is this good idea?
But the model doesn't support "include_top=False". So how can we achieve similar behavior ?

Here is what we have tried. But we're getting "Graph disconnected" error.

   weights_file = os.path.join(model_path, "facenet512_weights.h5")
    base_model = InceptionResNetV2(dimension=512)
    base_model.load_weights(weights_file)
    base_model.trainable = False
    
    inputs = tf.keras.Input(shape=imageSize+(3,))

	# apply random data augmentation
    x = data_augmentation(inputs)  

    x= base_model(x, training=False)

    x = base_model(x, training=False)
    
    # pass the extracted features through a number of trainable layers
    x = layers.GlobalAveragePooling2D()(base_model.layers[-5].output)
	
    # add more layers....
		
    outputs = layers.Dense(units=128)(x)

    # build the embedding model and return it
    embedding = keras.Model(inputs, outputs, name="embedding")

Here is the complete error:
ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, 160, 160, 3), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'") at layer "Conv2d_1a_3x3". The following previous layers were accessed without issue: []

**Comment by serengil** [comment]
I recommend you to read this tutorial: https://sefiks.com/2018/03/21/autoencoder-neural-networks-for-unsupervised-learning/

```python
def test_restoration(model):
 decoded_imgs = model.predict(x_test)
 get_3rd_layer_output = K.function([model.layers[0].input], [model.layers[1].output])
 
 for i in range(2):
 print("original: ")
 plt.imshow(x_test[i].reshape(28, 28))
 plt.show()
 #-------------------
 print("reconstructed: ")
 plt.imshow(decoded_imgs[i].reshape(28, 28))
 plt.show()
 #-------------------
 print("compressed: ")
 current_compressed = get_3rd_layer_output([x_test[i:i+1]])[0][0]
 plt.imshow(current_compressed.reshape(8, 4))
 plt.show()
```

here, get_3rd_layer_output variable stores the output of some early layer.

**Comment by dayahiman** [comment]
Ok, thanks for the quick response. Will try out the function.
