### ISSUE TITLE
Can handle images with multiple faces, and multiple resolutions?

### ISSUE THREAD

**Issue by QLaHPD** [serengil/deepface#8]
Does this framework can handle images with multiple faces and multiple resolutions? By multiple faces I mean, if it can compare "img_1.png" witch contains only the target face, and an array of images that may contain multiple faces including the target or no face at all.

Something like:

from deepface import DeepFace
dataset = ["img_2.png", "img_3.png"]
result = DeepFace.verify("img_1.png", dataset)

**Comment by serengil** [comment]
No, you should use it just shown below. img_1 should be duplicated.

```
dataset = [
   ["img_1.png", "img_2.png"],
   ["img_1.png", "img_3.png"]   
]
results = DeepFace.verify("img_1.png", dataset)
```
results variable returns json array. Then, you can check its verification results.

```
print(results[0]["verified"])
print(results[1]["verified"])
```

BTW, I close this issue.
