### ISSUE TITLE
name 'prediction_classes' is not defined in Ensemble-Face-Recognition.py class

### ISSUE THREAD

**Issue by khawar512** [serengil/deepface#80]
This file works fine and generate all graph with distances and YES and NO graph value. Afterwards, calculating recall, precision it gives an error.

#Evaluation
predictions = gbm.predict(x_test)
cm = confusion_matrix(y_test, prediction_classes)
print(cm) 

Error
cm = confusion_matrix(y_test, prediction_classes)
NameError: name 'prediction_classes' is not defined
Error in atexit._run_exitfuncs:

**Comment by serengil** [comment]
You need to transform predictions objects similar to [0.01, 0.99] to classes 1.

```
prediction_classes = []
for i in predictions:
   prediction_class = np.argmax(i)
   prediction_classes.append(prediction_class)
```
