### ISSUE TITLE
invalid detector_backend passed - yolov8

### ISSUE THREAD

**Issue by GoldDRoge** [serengil/deepface#803]
<img width="852" alt="Screen Shot 2023-07-18 at 17 20 28" src="https://github.com/serengil/deepface/assets/109260895/e780b2ab-9a96-4399-b30c-60d696a03e81">
Cant find backend yolov8

**Comment by serengil** [comment]
because that version is not pushed to pip yet. you can use source code instead of pip package until it is published.

```shell
$ git clone https://github.com/serengil/deepface.git
$ cd deepface
$ pip install -e .
```
