### ISSUE TITLE
The real-time video process speed

### ISSUE THREAD

**Issue by wuli66ly** [serengil/deepface#807]
thanks for your great work!
Maybe i meet a little peoblem.
when i use real-time video to detect gender, every pic costs 1.4s.
i find that：Because every time an image is read, the model（DeepFace.analyze   -- retinaface） is reloaded.
Is there a good solution？
The method I can think of is to load the model in advance and directly analyze each read image.But the Deepface library is too good, making changes is very troublesome.
best wishes!

**Comment by serengil** [comment]
Singleton pattern is being used. So, it is not built each time. Retrieves already built one from memory.

You cannot fasten it until you invest a powerful hardware.
