### ISSUE TITLE
DeepFace.stream("") : ValueError: ('There is no image in ' ' folder! Validate .jpg or .png files exist in this path.')

### ISSUE THREAD

**Issue by giri256** [serengil/deepface#809]
EDIT: Please close this issue, watched the demo video, it was helpful, but idk why does it require a source image to compare it just to give the emotion of a live webcam face.

Hi, 

to use to the deepface.stream() ,  i thought this function would connect to the PC's webcam directly and capture an image every 5 seconds. Do we need to manually configure our PC to output an image every 5 seconds into the db_path ourselves?

My usage scenario : I am trying to run this deepface to get a realtime emotional analysis of myself from my webcam

**Comment by mkchaitanya03** [comment]
According to my understanding, since there is a common api for verification, recognition and also demographic analysis, the api requires db_path as a parameter. Otherwise no source/reference images are required.
