### ISSUE TITLE
How to remove model from the Ensemble learning weights?

### ISSUE THREAD

**Issue by ElectricCarbon** [serengil/deepface#81]
Hello, I was wondering if it is possible to remove a specific model (for example VGG-Face) from the ensemble weights .TXT file, so I can have only Facenet, Openface and DeepFace.

**Comment by serengil** [comment]
This is not possible.

**Comment by ElectricCarbon** [comment]
@serengil Ok thanks! Will you look at supporting this in the future?

**Comment by serengil** [comment]
I have to train different models for every combination. Why would you need that kind of a feature?
