### ISSUE TITLE
Advice on trimming down package size?

### ISSUE THREAD

**Issue by delta42** [serengil/deepface#810]
I'd like to use deepface in an AWS Lambda but with deepface plus a few other things installed, my current docker container is at 10.7 GB, and the AWS limit is 10.0 GB.

Since I am only using MTCNN face alignment and nothing else, is there some easy place I can trim some dependencies or model files I don't need, post install?

From what I can see, `pip install deepface` consumed 2.44 GB, and then the `yum -y update && yum -y install mesa-libGL` (that I seem to require to obtain libGL.so) consumes an additional 0.5 GB or so. Intuitively I feel there must be at least 0.7 GB I can find and delete without losing functionality.

Thanks in advance.

**Comment by delta42** [comment]
Well, I came to the realization that there's not much that can be done with this package, since `tensorflow` alone makes up 2.2 GB. However, on the positive side of things, I managed to get my install of `torch` (yes I need both :-) down to minimal levels by excluding GPU support, via `pip install torch --extra-index-url https://download.pytorch.org/whl/cpu`. Mow my container is under 5GB!

Closing since this issue is not even related to deepface anymore...

**Comment by swayam1998** [comment]
@delta42 did you figure it out. Been trying to do the same thing but running into timeouts

**Comment by PrathamShelke** [comment]
Hey @delta42  can we connect,I also want to use deepface on AWS Lambda for inference for Face recognition task,But due high dependencies,I am not able to do it,Can you suggest some other ways like using AWS Sagemaker instead of this approach ?

**Comment by ebano-logsys** [comment]
Hi guys, were you able to fix this?
