### ISSUE TITLE
How to use deepface by GPU

### ISSUE THREAD

**Issue by glovenone** [serengil/deepface#814]
What's the way to use gpu for deepface?

The module of tensorflow-gpu is deprecated now and merged into tensorflow.

**Comment by serengil** [comment]
deepface does not do anything with gpu. if you use gpu with tf, then it will be used in deepface, too.

i was using tensorflow-gpu. if it is deprecated, then it can be used by default? i recommend you to ask this question in tf repo.

**Comment by glovenone** [comment]
> deepface does not do anything with gpu. if you use gpu with tf, then it will be used in deepface, too.
> 
> i was using tensorflow-gpu. if it is deprecated, then it can be used by default? i recommend you to ask this question in tf repo.

Thanks, this is the offical tips for tensorflow gpu: https://www.tensorflow.org/install/gpu

**Comment by Rhtyme** [comment]
@glovenone were you able to use the deepface library on gpu?
