### ISSUE TITLE
When I send a photo to extraxct_faces and then send it face to face to DeepFace.represent it tells me it doesn't detect faces

### ISSUE THREAD

**Issue by RafaelFerraria** [serengil/deepface#815]
While I was following your post https://sefiks.com/2021/02/06/deep-face-recognition-with-sql/ when I was doing it on my computer when I was sending the images to extract the faces from them and then represent his embeddings whenever he asked for the representation he said he couldn't find faces can you help me?
The ERROR:"Exception has occurred: ValueError
Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
  File "C:\Users\RafaDesk\Desktop\RFIGNEW\final_fotos_com_extract.py", line 29, in processar_fotos
    representacoes = DeepFace.represent(img_path = target_img, model_name = "Facenet")
  File "C:\Users\RafaDesk\Desktop\RFIGNEW\final_fotos_com_extract.py", line 66, in <module>
    processar_fotos(fotos)
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False."
```
def processar_fotos(fotos):
    instacias = []
    for i in tqdm(range(0, len(fotos))):
        target_img_path = PSTO+fotos[i]
        representacoes = None
        target_imgs = DeepFace.extract_faces(img_path = target_img_path)
        for i in range(len(target_imgs)):
            target_img = target_imgs[i]["face"]
            representacoes = DeepFace.represent(img_path = target_img, model_name = "Facenet")
            if representacoes == None:
                #remover a foto da variavel fotos e mover da pasta O para a pasta lixo
                os.rename(PSTO+fotos[i],PSTA+fotos[i])
                fotos.remove(fotos[i])

            else:
                for representacao in representacoes:
                    instacia = []
                    instacia.append(fotos[i])
                    instacia.append(representacao['embedding'])
                    instacias.append(instacia)
                    
                agora = datetime.datetime.now()
                codb = agora.strftime("%H%M%S%f")
                unique_name=codb+".jpg"

                foto_lida = cv2.imread(PSTO+fotos[i])
                foto_redimencionada = ft.redimensionar_imagem_sem_distortao(foto_lida)
                
                imagem = ft.codbarras(foto_redimencionada,codb)

                cv2.imwrite(PSTA+unique_name, imagem)
                os.remove(PSTO+fotos[i])

    df = pd.DataFrame(instacias, columns = ['img_name', 'embedding'])
    db.armazenar_df(df)
```

**Comment by serengil** [comment]
if you perform extract_faces beforehand, then set detector backend to skip in verify or represent function.

**Comment by RafaelFerraria** [comment]
Sorry I couldn't understand can you explain it in another way

**Comment by serengil** [comment]
```
representacoes = DeepFace.represent(img_path = target_img, model_name = "Facenet", detector_backend="skip")
```

**Comment by RafaelFerraria** [comment]
I don't know if I understood correctly when I was looking at the post did I understand that I had to do the extract_faces first or is that unnecessary?

**Comment by serengil** [comment]
if you perform extract_faces first, then you should set detector backend to skip. 

otherwise, you do not have to run extract faces beforehand.

**Comment by serengil** [comment]
no, but this query is not coming from my study

**Comment by RafaelFerraria** [comment]
yes you are correct I took your query and tried to pass it to mysql and put the names of the fields and tables that I have in my DB
