### ISSUE TITLE
Can't find face but able to analyze face in the example pic

### ISSUE THREAD

**Issue by rahmanshaber** [serengil/deepface#816]
Analyze function works really well, but find doesn't able to find any face in a pic. i am using the Angelina Joly pic that you have as demo in the readme. 
I know i can use `enforce_detection =False ` but that way it doesnæt detect and face at all and the matched pics are not correct. I think it just taking a random area in the pic and trying to match that area with the database pics. tried with different models also.

```
from deepface import DeepFace
from deepface.basemodels import VGGFace

import cv2
import matplotlib.pyplot as plt
import json

models = [
  "VGG-Face", 
  "Facenet", 
  "Facenet512", 
  "OpenFace", 
  "DeepFace", 
  "DeepID", 
  "ArcFace", 
  "Dlib", 
  "SFace",
]

metrics = ["cosine", "euclidean", "euclidean_l2"]


img_path = "img1.jpg"
img = cv2.imread(img_path)
plt.imshow(img[:, :, ::-1])


objs = DeepFace.analyze(img_path, 
        actions = ['age', 'gender', 'race', 'emotion']
)
print(objs)


#face recognition
dfs = DeepFace.find(img_path,
      db_path = "test" ,model_name = models[6], distance_metric = metrics[2]
)

print(dfs)
```

output

```
2023-08-07 17:57:55.311723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5023 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070 Ti Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
Action: age:   0%|                                                                                                                                                                                      | 0/4 [00:00<?, ?it/s]2023-08-07 17:57:57.239381: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8902
2023-08-07 17:57:57.531800: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
Action: emotion: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  4.96it/s]
[{'age': 32, 'region': {'x': 223, 'y': 284, 'w': 468, 'h': 468}, 'gender': {'Woman': 99.99996423721313, 'Man': 4.1066084577323636e-05}, 'dominant_gender': 'Woman', 'race': {'asian': 0.012747531517703053, 'indian': 0.017373798730460705, 'black': 0.0004678416086599688, 'white': 95.08633672161857, 'middle eastern': 3.197913608203696, 'latino hispanic': 1.6851560997776867}, 'dominant_race': 'white', 'emotion': {'angry': 2.301129228011278, 'disgust': 0.0002903363456925631, 'fear': 5.741350664657434, 'happy': 24.024182441733174, 'sad': 4.525689202629232, 'surprise': 8.805585957239384, 'neutral': 54.601777148458616}, 'dominant_emotion': 'neutral'}]
Finding representations:   0%|                                                                                                                                                                         | 0/41 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/shaber/stuff/nn/new/deep.py", line 52, in <module>
    dfs = DeepFace.find(img_path,
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaber/yes/envs/tf/lib/python3.11/site-packages/deepface/DeepFace.py", line 488, in find
    img_objs = functions.extract_faces(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaber/yes/envs/tf/lib/python3.11/site-packages/deepface/commons/functions.py", line 115, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.

```

**Comment by serengil** [comment]
it cannot detect a face in an image in test folder, not "img1.jpg".

**Comment by serengil** [comment]
just one image is available in test folder?

**Comment by rahmanshaber** [comment]
no, with several others.
![image](https://github.com/serengil/deepface/assets/30831735/d29b6d5d-959a-499b-ac15-82ac7a5c8641)

**Comment by serengil** [comment]
okay i am saying this already. it cannot detect the face of an image in that folder.

**Comment by rahmanshaber** [comment]
Hi again, Is there anything you can suggest to overcome this problem, thanks

**Comment by BACCMED** [comment]
Hi , I have the same issue
Is there a solution?
Thanks

**Comment by Bouy1053** [comment]
What is the source code for the deepface

**Comment by xuemingdi** [comment]
hi, I run the same sample code to test analyze, but report "Input 0 of layer sequential is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: (None, 48, 48)". I use the same img1.jpg in dataset directory, anyone has the same issue ? Thanks

**Comment by knoppmyth** [comment]
I ran into this issue as well. In my case, there was one subject in the image however the image was rotated so the subject's face wasn't upright. Correcting the rotation didn't resolve the issue. As the image was taken on a 24 megapixel mirror less camera, I wondered if the image was simply too big. I reduced it by half and the face was detected. Note, I tested this using Mediapipe as the detector.

**Comment by n2o** [comment]
I have the same problem that I can analyse an image, but I can't find them in my database.

My project structure:

<img width="242" alt="image" src="https://github.com/serengil/deepface/assets/1507474/33803465-da25-408c-b827-1ec1b16d1042">

Function Call:

<img width="910" alt="image" src="https://github.com/serengil/deepface/assets/1507474/e8df7812-9cad-4ba5-8b46-774da8be3581">

Moving the image from `img_path` out of the `data`-directory, does not change anything in the resulting error message.

`extract_faces` finds the face in the image:

<img width="608" alt="image" src="https://github.com/serengil/deepface/assets/1507474/ece475e2-381b-464f-b945-6a4d49882139">

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/911
