### ISSUE TITLE
no, but this query is not coming from my study

### ISSUE THREAD

**Issue by RafaelFerraria** [serengil/deepface#817]
no, but this query is not coming from my study

_Originally posted by @serengil in https://github.com/serengil/deepface/issues/815#issuecomment-1668212247_
The issue is close i dont now why but you can answer that "yes you are correct I took your query and tried to pass it to mysql and put the names of the fields and tables that I have in my DB"

**Comment by serengil** [comment]
because this is not an issue of this repo.
