### ISSUE TITLE
DeepFace.verify() in a loop is getting slower and slower over time

### ISSUE THREAD

**Issue by lemnet** [serengil/deepface#819]
I'm doing so testing and I find that, when in a loop, DeepFace.verify() is getting slower and slower over time.

I don't have a memory leak, at least not one I can detect...

Here are some tests i've done : 

- simple code

`from deepface import DeepFace`
`i = 0`
`while True:`
`    print(str(i).zfill(5) + ' : ' + str(DeepFace.verify(img1_path = r'pathtojpg1', img2_path = r'pathtojpg2', model_name='Facenet', detector_backend='retinaface', enforce_detection=False)))`
`    i += 1`

Result : 
>00000 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 9.39}
00001 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.06}
00002 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.03}
00003 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.06}
00004 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.03}
00005 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.03}
00006 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.0}
00007 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.98}
00008 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.93}
00009 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.95}
00010 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.98}
...
00099 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.02}
00100 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.0}
00101 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.99}
...
00200 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.22}
...
00300 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.55}
...
00400 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.78}
...
00500 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 3.74}
...
00600 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 6.3}

- with garbage collector : 

`import gc`
`from deepface import DeepFace`
`i = 0`
`while True:`
`    print(str(i).zfill(5) + ' : ' + str(DeepFace.verify(img1_path = r'pathtojpg1', img2_path = r'pathtojpg2', model_name='Facenet', detector_backend='retinaface', enforce_detection=False)))`
`    i += 1`
`    if i%50 == 0:`
`        gc.collect()`

Result : 
>00000 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 9.39}
00001 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.05}
00002 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.01}
00003 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.98}
00004 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.0}
00005 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.02}
00006 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.99}
00007 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.95}
00008 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.96}
00009 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.94}
00010 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.97}
...
00099 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.02}
00100 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.0}
00101 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.98}
...
00200 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.15}
...
00300 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.0}
...
00400 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.1}
...
00500 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.81}
...
00600 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 3.64}

- with clear_session() : 

`import tensorflow as tf`
`from deepface import DeepFace`
`i = 0`
`while True:`
`    print(str(i).zfill(5) + ' : ' + str(DeepFace.verify(img1_path = r'pathtojpg1', img2_path = r'pathtojpg2', model_name='Facenet', detector_backend='retinaface', enforce_detection=False)))`
`    i += 1`
`    if i%50 == 0:`
`        tf.keras.backend.clear_session()`

Result : 
>00000 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 9.15}
00001 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.06}
00002 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.03}
00003 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.02}
00004 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.02}
00005 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.0}
00006 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.01}
00007 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.97}
00008 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.01}
00009 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 1.98}
00010 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.0}
...
00099 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.16}
00100 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 3.42}
00101 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 2.69}
...
00200 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 3.91}
...
00300 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 3.75}
...
00400 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 3.84}
...
00500 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 4.17}
...
00600 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 5.84}
...
01000 : {'verified': False, 'distance': 0.6469936469234228, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'retinaface', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 54, 'y': 83, 'w': 205, 'h': 270}, 'img2': {'x': 36, 'y': 78, 'w': 136, 'h': 177}}, 'time': 5.62}

Is there a way to completely reset deepface ?

I can do more tests, if needed...

Any ideas or suggestions ?

Thank's

**Comment by serengil** [comment]
duplicated - https://github.com/serengil/deepface/issues/697

**Comment by lemnet** [comment]
The solution proposed in #697 (`calling clear_session()`) is not solving the problem...

**Comment by serengil** [comment]
that is why, it is still open

**Comment by lemnet** [comment]
Anyways, thank's for the great work !

**Comment by lemnet** [comment]
FYI...
Changing `embedding = model.predict(img, verbose=0)[0].tolist()` to `embedding = model.predict_on_batch(img)[0].tolist()` drastically improve performances.

Once again, thank's for the great work !

**Comment by programehr** [comment]
> FYI... Changing `embedding = model.predict(img, verbose=0)[0].tolist()` to `embedding = model.predict_on_batch(img)[0].tolist()` drastically improve performances.
> 
> Once again, thank's for the great work !

Hi,
Is `predict_on_batch` a deepface method? I couldn't find it in this repo.

Thanks

**Comment by lemnet** [comment]
> > FYI... Changing `embedding = model.predict(img, verbose=0)[0].tolist()` to `embedding = model.predict_on_batch(img)[0].tolist()` drastically improve performances.
> > Once again, thank's for the great work !
> 
> Hi, Is `predict_on_batch` a deepface method? I couldn't find it in this repo.
> 
> Thanks

No... It's a line I changed there : https://github.com/serengil/deepface/blob/f13aa34feb17ccd539eb67b671a42d7160d59298/deepface/DeepFace.py#L696 and https://github.com/serengil/deepface/blob/f13aa34feb17ccd539eb67b671a42d7160d59298/deepface/DeepFace.py#L699
