### ISSUE TITLE
Train Function

### ISSUE THREAD

**Issue by askinucuncu** [serengil/deepface#82]
Merhaba, ben bir adet train fonksiyonu yazmak istiyorum. Yapmak istediğim durum şöyle; her resim eklendiğinde train fonksiyonu çalışacak ve belirtilen klasör içerisine pkl dosyasını oluşturacak. Şuan bir resim eklendiğinde pkl dosyasının silinmesi gerekiyor. Ben bu uygulama yerine train fonksiyonunu çalıştırarak resimlerin olduğu yere değil de x klasöre pkl dosyasını oluşturmak istiyorum. Bu konuda yardımcı olabilir misiniz?

**Comment by serengil** [comment]
fonksiyona parametre göndererek yapılmasını sağlayabiliriz sonraki sürümde ama bu bir issue değil değişiklik olur. bu sebeple issue'yu kapatıyorum.
