### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by cvchongci** [serengil/deepface#820]
https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L683

        if len(img.shape) == 3:
            img = cv2.resize(img, target_size)
            img = np.expand_dims(img, axis=0). this line should be removed?
        # --------------------------------
        img_region = [0, 0, img.shape[1], img.shape[0]]  otherwise, this img_region will be wrong!!!
        img_objs = [(img, img_region, 0)]

**Comment by serengil** [comment]
why you are calling it is a bug?

if it is 4 dimensional, first if block makes it 3 dimensional, then the second if block will satisfy even if it is 3 or 4 dimensional in the beginning. at the end of process, it is going to be 4 dimensional.

```python
        if len(img.shape) == 4:
            img = img[0]  # e.g. (1, 224, 224, 3) to (224, 224, 3)
        if len(img.shape) == 3:
            img = cv2.resize(img, target_size)
            img = np.expand_dims(img, axis=0)
```
