### ISSUE TITLE
TypeError: verify() got an unexpected keyword argument 'model' in Ensemble-Face-Recognition.ipynb

### ISSUE THREAD

**Issue by oussaifi-majdi** [serengil/deepface#821]
resp_obj = DeepFace.verify(instances, model_name = model, distance_metric = metric), what should be the image path2 in this line, this is the code from ensemble method for face recognition

![image](https://github.com/serengil/deepface/assets/31904454/e80f8733-720a-40e0-baa8-46d722e862a0)

**Comment by serengil** [comment]
Interface of deepface is changed in newer versions. Instead of sending instances, you need to pass img1_path and img2_path.
