### ISSUE TITLE
analyze() detector_backends 'yolov8' and 'dlib' errors

### ISSUE THREAD

**Issue by Hipples** [serengil/deepface#824]
Hey! I was just trying to test out all of the available backend detectors for the analyze function. I have managed to get them all to run except for yolov8 and dlib. Here are the errors:

shape_predictor_5_face_landmarks.dat.bz2 is going to be downloaded
Detector: dlib Error: 'content-type'
-and-
Detector: yolov8 Error: invalid detector_backend passed - yolov8

Suggestions? 
For the yolov8 detector, as I passed the string copied directly from the DeepFace module which states it as an option. Curious if it's just a typo. Maybe no v8, or an n at the end or not actually valid and was just missed when documenting. Idk. I tried installing ultralytics, but it did not solve the issue, which makes sense. lol

For dlib, I pip installed the package, then even uninstalled and reinstalled copying the version from the optional requirements text file, it was the same anyway. Google showed that maybe it's a firewall issue? I'm not sure where to find the weights to download them myself nor how to resolve such a firewall issue.

**Comment by CodeWithEhtisham** [comment]
If you've installed DeepFace using pip, please note that the version available on pip might not always be the latest. The latest code and improvements may be available in the GitHub repository but not published on pip yet. You can consider directly using the latest code from the repository by cloning it and installing it locally.

Keep in mind that while the pip version might be stable, it's always a good idea to explore the repository for the most up-to-date features and fixes.

**Comment by Hipples** [comment]
I have the package installed via cloning. Issue persists. Repository explored to best of my ability.
