### ISSUE TITLE
Replicating ArcFace LFW Results

### ISSUE THREAD

**Issue by aidansmyth95** [serengil/deepface#827]
Hi Serengil,

Thanks for the fantastic library, I am really enjoying it.

I am struggling to get an accuracy close to the 99% on LFW, and I would like to know if it is the limitations of my test framework or DeepFace's ArcFace implementation.

Did you come close to the LFW results when testing the ArcFace model on LFW? Would you happen to have a test framework that you have used to validate the model accuracies reported in the table?

Thanks for everything.

**Comment by serengil** [comment]
I can reach 97% max with arcface.

**Comment by aidansmyth95** [comment]
I would definitely be happy with 97%. I am hitting 90% on LFW using the verify() method. May I double-check to see if I am calling/testing it differently than recommended? I think this may be the case because it is not only ArcFce that I am seeing less than expected LFW accuracy results.

I am evaluating according to the pairs in LFW dataset's pairs.txt file.

`
for dataset in datasets:
    hits = 0
    for pair_dict in tqdm(dataset):
        ver_dict = verify(img1_path=pair_dict['img_a'],
                          img2_path=pair_dict['img_b'],
                          model_name='ArcFace',
                          normalization='ArcFace',
                          detector_backend='retinaface',
                          distance_metric='euclidean_l2',
                          enforce_detection=False,
                          align=True)
        verified = ver_dict['verified']
        is_same = pair_dict['is_same']
        if (is_same and verified) or (not is_same and not verified):
            hits += 1 
        else:
            #print(ver_dict)
            #print(pair_dict['img_a'])
            #print(pair_dict['img_b'])
            pass
    print(hits/len(dataset))
`

Helper functions to prepare the LFW dataset by parsing the pairs.txt file:

`
import os
import re
import copy


def get_lfw_pairs(pairs_file, lfw_dir):

    assert os.path.exists(pairs_file)
    assert os.path.exists(lfw_dir)

    lines = []
    with open(pairs_file,'r') as email:
        # read the file with a for loop
        for line in email:
            # strip the newline character from the line and split by tabs
            line = re.split(r'\t+', line.strip())
            lines.append(line)

    num_sets, num_per_set = int(lines[0][0]), int(lines[0][1])

    datasets = [[] for _ in range(num_sets)]

    for line_idx, line in enumerate(lines[1:]):
        # decode img paths
        is_same = len(line) == 3
        if is_same:
            img_a = get_lfw_img_path(lfw_dir, line[0], line[1])
            img_b = get_lfw_img_path(lfw_dir, line[0], line[2])
        else:
            assert len(line) == 4
            img_a = get_lfw_img_path(lfw_dir, line[0], line[1])
            img_b = get_lfw_img_path(lfw_dir, line[2], line[3])
        example = {
            'img_a': img_a,
            'img_b': img_b,
            'is_same': is_same
        }
        assert os.path.exists(img_a)
        assert os.path.exists(img_b)
        # follow dataset splits
        dataset_idx = line_idx % num_sets
        datasets[dataset_idx].append(copy.deepcopy(example))

    return datasets

def get_lfw_img_path(base_dir, person, img_idx):
    ''' Decode LFW image. '''
    return os.path.join(base_dir, person, '{}_{:04d}.jpg'.format(person, int(img_idx)))
`

Thanks in advance for your help!

**Comment by aidansmyth95** [comment]
I am calling ArcFace as follows and achieving 90% accuracy - is there something from here that I am missing:

`
        ver_dict = verify(img1_path=pair_dict['img_a'],
                          img2_path=pair_dict['img_b'],
                          model_name='ArcFace',
                          normalization='ArcFace',
                          detector_backend='retinaface',
                          distance_metric='euclidean_l2',
                          enforce_detection=False,
                          align=True)
`
