### ISSUE TITLE
How to improve the prediction accuracy of facial atrribute in specific country person?

### ISSUE THREAD

**Issue by 9527-csroad** [serengil/deepface#830]
Thx for your wonderful job. As the title mentioned, I deployed the project and test with some images. It's not accurate, most of woman have been recongnized as man and the age of the person also not accurate.
I want to reduce the error of the project. Could you tell me how to imporve the performance? thx

**Comment by serengil** [comment]
you can follow this tutorial and re-train age & gender model for your custom dataset.

https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/
