### ISSUE TITLE
how to use find() correctly?

### ISSUE THREAD

**Issue by merasil** [serengil/deepface#834]
hi serengil,

thanks to your library i have been able to build an application to recognize faces from a surveillance camera stream (4MP, very sharp, a bit oblique from above, but almost frontal face shot). 

The recognition should be a part of a 2 factor authentication that runs automatically in the background. The goal is that our front door will only open if the numeric code is entered correctly (part 1) and the face recognition (part 2) confirms that it is one of the people in the database.

My database consists of 5-6 images each of me, my wife and my son. All pictures are frontal, with slight variations in the angle.

Unfortunately the thresholds don't seem to be set optimally for me, because for example my (6 year old) son or my wife always appear in the results when I walk into the picture.
I have tested it with other people... which look more similar to me and which should actually look completely different.
I would have expected in this case that either there is no recognition in the results, or that the threshold is "significantly" higher than when I am in the picture. Unfortunately, even unknown persons were sometimes recognized clearly false positive.
I know it's hard to tell when you don't see the images what that might be.

i have tried various mechanisms (only the first face from the find() result, all faces from the result and the one that occurs most often, etc.). The model and detector that works best seem to be vgg-face/facenet512 and yunet.
What would be the correct procedure in such a case? Especially the false positives from unknown persons should not appear.

**Comment by serengil** [comment]
i recommend you to store 1 image per person and use verify function. instead of checking its verified key in the respnse, check distance value. tune this according to your experiment. picking a smaller threshold will decrease false positives but it may increase false negatives which is okay for security purposes.
