### ISSUE TITLE
Can RetinaFace be used to detect faces?

### ISSUE THREAD

**Issue by FurkanGozukara** [serengil/deepface#841]
I was using face_recognition library and it turns out that it is very primitive

Then I switched to retina-face and much better results

Which face detection library currently used in this amazing project?

**Comment by serengil** [comment]
Opencv haarcascade by default. Retinaface is also wrappedbut you need to set detector_backend argument to retinaface. Because retinaface is much slower than opencv.

**Comment by FurkanGozukara** [comment]
> Opencv haarcascade by default. Retinaface is also wrappedbut you need to set detector_backend argument to retinaface. Because retinaface is much slower than opencv.

correct pretty slow but much accurate

how is the accuracy of haarcascade compared to Retinaface 

in some images face detection fails with deepface

**Comment by serengil** [comment]
Retinaface comes with much more accurate results. If the accuracy is more important than speed, then you should use retinaface.
