### ISSUE TITLE
Does the find method use multiple images for same identity of person or not?

### ISSUE THREAD

**Issue by tusharfire** [serengil/deepface#842]
What does the following statement mean the readme doc

`Even though face recognition is based on one-shot learning, you can use multiple face pictures of a person as well. 
`
Will the multiple images does not add any value/benefit in  recognition task here?

[Here](https://github.com/serengil/deepface/issues/776#issuecomment-1586780703) it was mentioned that it does not use multiple images.

**Comment by serengil** [comment]
One image for one identity is enough, still you can have many.
