### ISSUE TITLE
how to get similarity percentage instead of threshold and distance ?

### ISSUE THREAD

**Issue by OdiljonPy** [serengil/deepface#843]

**Comment by serengil** [comment]
There is no formula for this.

**Comment by OdiljonPy** [comment]
thanks for quick reply!

**Comment by kennedyjosh** [comment]
if you are using cosine distance, you can (sort of) calculate a similarity percentage as cosine distance is bounded [-1, 1] where -1 would be 0% similar and 1 would be 100% similar
