### ISSUE TITLE
Can't detect faces when calling represent trough API and Facenet detector

### ISSUE THREAD

**Issue by elisoncampos** [serengil/deepface#845]
Here's the image being used:

https://cdn.alboompro.com/5dc181967fac6b000152f3ae_650b3f428274300001d1815a/medium/whatsapp_image_2023-09-18_at_16-41-06.jpeg?v=1

I'm sending it to an API that running the dockerized image present in the repository on an EKS cluster (no GPU).  When I send a request to the represent endpoint with the given image as the img parameter and using Facenet as a face decetor (tested with VGG, same error) it gives me the following error:

```
20/Sep/2023:18:47:46 +0000] "POST /represent HTTP/1.1" 200 43 "-" "Insomnia/2023.5.6"
[2023-09-20 18:48:06,321] ERROR in app: Exception on /represent [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/routes.py", line 28, in represent
    obj = service.represent(
  File "/app/service.py", line 6, in represent
    embedding_objs = DeepFace.represent(
  File "/app/deepface/DeepFace.py", line 663, in represent
    img_objs = functions.extract_faces(
  File "/app/deepface/commons/functions.py", line 163, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
```

Any leads on how to improve face detection? Could it be a hardware limitation problem (like if can't detect face because lack of memory allocation or something). Not sure if disable enforce_detection is a option here.

**Comment by serengil** [comment]
message is clear, you need to set enforce_detection to false

https://github.com/serengil/deepface/blob/master/api/routes.py#L32

**Comment by elisoncampos** [comment]
> message is clear, you need to set enforce_detection to false
> 
> https://github.com/serengil/deepface/blob/master/api/routes.py#L32

But if we disable the face detection, the representation will be for the whole image, not for every face present in the image. That's why I said I don't think disabling face detection is an option here.

**Comment by serengil** [comment]
then you have to feed a better formed image

**Comment by elisoncampos** [comment]
That's fine, however could you point to what could be a better formed image? Higher resolution? Pre-processing in order to align faces (all faces in the example image are in an angle), normalizing colors (image with filters and weird coloring such as purple lightning)

I'm sorry if I'm missing something here but the documentation doesn't seem to indicate the need for pre processing or a minimum requirements for an image

**Comment by serengil** [comment]
basically face detector cannot find a face in the image you fed. 

ps: you may try to change the detector to more robust one such as mtcnn

**Comment by RashmiDeshpande21** [comment]
@serengil I have been trying mtcnn and it still gives the same error..
@elisoncampos Hey, did you find any solution?
