### ISSUE TITLE
Could not download shape_predictor_5_face_landmarks.dat.bz2 while using dlib in extract_faces

### ISSUE THREAD

**Issue by handflucht** [serengil/deepface#847]
I wanted to use `extract_faces` with `dlib`.

After 
```bash
sudo yum install python39-devel
pip install dlib
```
calling DeepFace.extract_faces led to the following error:

```
shape_predictor_5_face_landmarks.dat.bz2 is going to be downloaded
Traceback (most recent call last):
  File "/home/handflucht/Documents/github/vimg/main.py", line 26, in <module>
    face_objs = extract_faces(frame, detector_backend="dlib")
  File "/home/handflucht/Documents/github/vimg/imageprocessor.py", line 10, in extract_faces
    face_objs = DeepFace.extract_faces(frame, enforce_detection=False, detector_backend=detector_backend)
  File "/home/handflucht/Documents/github/vimg/venv/lib64/python3.9/site-packages/deepface/DeepFace.py", line 787, in extract_faces
    img_objs = functions.extract_faces(
  File "/home/handflucht/Documents/github/vimg/venv/lib64/python3.9/site-packages/deepface/commons/functions.py", line 110, in extract_faces
    face_detector = FaceDetector.build_model(detector_backend)
  File "/home/handflucht/Documents/github/vimg/venv/lib64/python3.9/site-packages/deepface/detectors/FaceDetector.py", line 36, in build_model
    face_detector = face_detector()
  File "/home/handflucht/Documents/github/vimg/venv/lib64/python3.9/site-packages/deepface/detectors/DlibWrapper.py", line 23, in build_model
    gdown.download(url, output, quiet=False)
  File "/home/handflucht/Documents/github/vimg/venv/lib64/python3.9/site-packages/gdown/download.py", line 178, in download
    if res.headers["Content-Type"].startswith("text/html"):
  File "/home/handflucht/Documents/github/vimg/venv/lib64/python3.9/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```

I outputted the values of vars of the falling call `gdown.download(url, output, quiet=False)` and they are the following:
```
url: http://dlib.net/files/shape_predictor_5_face_landmarks.dat.bz2 
output: /home/handflucht/.deepface/weights/shape_predictor_5_face_landmarks.dat.bz2
```

Workaround: I downloaded the file manually, extracted it and moved it to the output-location and it worked.

P.s.: Thanks for your great work!

**Comment by serengil** [comment]
url `http://dlib.net/files/shape_predictor_5_face_landmarks.dat.bz2` is live. so, you may have trouble with your proxy.

**Comment by upupzealot** [comment]
Same question here, I downloaded `http://dlib.net/files/shape_predictor_5_face_landmarks.dat.bz2` and place it to `weights` folder manually. But the same problem still accurs

**Comment by abasit-AEV** [comment]
To solve this issue, download this file http://dlib.net/files/shape_predictor_5_face_landmarks.dat.bz2 and copy it to your home/user/.deepface folder:
`
cp Downloads/shape_predictor_5_face_landmarks.dat.bz2 /home/user/.deepface/weights/shape_predictor_5_face_landmarks.dat.bz2
`
Where user is your login user name.
Then extract it to shape_predictor_5_face_landmarks.dat using the following code:
`import bz2
input_file = "/home/user/.deepface/weights/shape_predictor_5_face_landmarks.dat.bz2"
output_file = "/home/user/.deepface/weights/shape_predictor_5_face_landmarks.dat"

with bz2.open(input_file, 'rb') as f_in:
    with open(output_file, 'wb') as f_out:
        for data in iter(lambda: f_in.read(100 * 1024), b''):
            f_out.write(data)

print(f"{input_file} has been extracted to {output_file}")
`
This will extract the file that is required by DLib wrapper:
`    if os.path.isfile(home + "/.deepface/weights/shape_predictor_5_face_landmarks.dat") != True:
`

**Comment by bhuiyanmobasshir94** [comment]
> url `http://dlib.net/files/shape_predictor_5_face_landmarks.dat.bz2` is live. so, you may have trouble with your proxy.

Yet finding issue to download this. Though copy pasting worked for me

**Comment by driver4567** [comment]
As a work around, from the cmd line run the following:

```
   python
   from deepface.commons import functions
   functions.get_deepface_home()
```

from this you'll get the {home} directory where deepface stores the weights, so you want to download the weights you require directly from dlib (http://dlib.net/files/) and then place them uncompressed in the directory {home}/.deepface/weights/{file_name}
