### ISSUE TITLE
Can you help me to convert this code detectFace into this extract_faces code? 

### ISSUE THREAD

**Issue by FurkanGozukara** [serengil/deepface#850]
I am using below code and it is working great

```
            detected_face = DeepFace.detectFace(org_image_path, detector_backend='opencv')

            # save the detected face in the detected faces folder
            new_image_path = os.path.join(detected_faces_folder_path, org_image_file)
            plt.imshow(detected_face)
            detected_face = detected_face * 255
            cv2.imwrite(new_image_path, detected_face[:, :, ::-1])
            print("Detected face saved in:", new_image_path)
            org_images.append(org_image)
```

However it is giving the below warning

⚠️ Function detectFace is deprecated! Use extract_faces instead of this.

I couldn't convert it. How can I convert?

thank you

**Comment by serengil** [comment]
```python
face_objs = DeepFace.extract_faces(img_path="dataset/img11.jpg")
for face_obj in face_objs:
   detected_face = face_obj["face"]
```

If the image has more than one face, then detectFace is focusing on the 1st one and discarding others. On the other hand, extract_faces can handle many faces as shown.

**Comment by FurkanGozukara** [comment]
> ```python
> ["face"]
> ```

thanks

i tried like this  but colors are not correct

            for detected_face in detected_faces:
                new_image_path = os.path.join(detected_faces_folder_path, org_image_file)
                face_temp = detected_face["face"]
                face_temp = face_temp * 255
                cv2.imwrite(new_image_path, face_temp)
                print("Detected face saved in:", new_image_path)
            org_images.append(org_image)

![image](https://github.com/serengil/deepface/assets/19240467/c7fb5581-f00d-4a2f-95f0-31cc83257a82)

**Comment by serengil** [comment]
please try this:

```python
detected_face["face"][:, :, ::-1]
```

opencv reads image BGR instead of RGB. this will restore the order in correct order.

**Comment by FurkanGozukara** [comment]
> ```python
> detected_face["face"][:, :, ::-1]
> ```

thank you so much

which confidence should i aim?

some images like this

![image](https://github.com/serengil/deepface/assets/19240467/73af937a-bb72-430a-9aa6-84e223c63696)

**Comment by serengil** [comment]
opencv is not a robust detector. I recommend you to use more robust ones such as mtcnn or retinaface. retinaface is really slow but amazing.

```
detected_face = DeepFace.detectFace(org_image_path, detector_backend='mtcnn')
detected_face = DeepFace.detectFace(org_image_path, detector_backend='retinaface')
```

these detectors would not detect non face areas at all.

**Comment by FurkanGozukara** [comment]
> detected_face = DeepFace.detectFace(org_image_path, detector_backend='retinaface')

thank you so much

how about for this method can we set retinaface there too?

DeepFace.verify, img1, img2, model_name=model_name

**Comment by serengil** [comment]
In same way

```python
DeepFace.verify("img1.jpg", "img2.jpg", model_name = "Facenet", detector_backend='retinaface')
```

**Comment by FurkanGozukara** [comment]
> ```python
> , detector_backend='retinaface'
> ```

thank you so much

**Comment by serengil** [comment]
no problem, feel free to contact about anything about deepface. following your work as a fan!

**Comment by FurkanGozukara** [comment]
> no problem, feel free to contact about anything about deepface. following your work as a fan!

thank you so much for your amazing work

I just shared my script with also mentioning your project DeepFace. upgraded to retinaface backend also extract faces function 

I also added GPU install feature too

currently I am using Facenet512 to calculate distance / similarity between given faces

Do you think that is the best one or are there even better ones?

E.g. sorted images according to real images

![image](https://github.com/serengil/deepface/assets/19240467/c62b2547-d77e-4c85-9f0d-3aaa070a1aaf)

![image](https://github.com/serengil/deepface/assets/19240467/d0c2de79-e0a0-4c55-b5bf-ab5d15668211)

**Comment by serengil** [comment]
In my experiments, I feel Facenet is better than Facenet512.

Facenet512 seems better on just LFW data set. Not real world.

Besides, mtcnn is a robust detector and it is faster than retinaface. Of course, retinaface comes with more accurate results. You may consider to use it if you need speed and robustness together.

**Comment by FurkanGozukara** [comment]
> In my experiments, I feel Facenet is better than Facenet512.
> 
> Facenet512 seems better on just LFW data set. Not real world.
> 
> Besides, mtcnn is a robust detector and it is faster than retinaface. Of course, retinaface comes with more accurate results. You may consider to use it if you need speed and robustness together.
> 
> Aldo, in my experiments I see euclidean is better than cosine and euclidean_l2.

thank you so much i appreciate all reposenses 

what is meaning of LFW ?

**Comment by serengil** [comment]
Labeled faces in the wild dataset

**Comment by FurkanGozukara** [comment]
> Labeled faces in the wild dataset

I use this for sorting best AI generated images

they are usually realistic images but sometimes cartoon anime as well

I guess Facenet  is better than Facenet512

by the way how do we set distance algorithm?

currently this is my method call

                future = executor.submit(DeepFace.verify, org_image, generated_image, model_name=model_name,detector_backend='retinaface')
                distance_score = future.result()["distance"]

**Comment by serengil** [comment]
you can use distance_metric argument

```python
DeepFace.verify("img1.jpg", "img2.jpg", model_name = "Facenet", detector_backend='retinaface', distance_metric='euclidean')
```

BTW, docstring might be helpful: https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L112
