### ISSUE TITLE
Wearing glasses decrease accuracy of Arcface

### ISSUE THREAD

**Issue by HoangSang1510** [serengil/deepface#851]
I am using model Arcface to get 2 embedding vector of 1 person, with glasses and without glasses (same headpose and condition). Result cosine is 0.4 while using Facenet512 it only 0.19. Is everyone experiencing the same thing?

**Comment by serengil** [comment]
yes, accessories decrease the results. that is why, you are enforced to remove sunglasses and caps in passport control.
