### ISSUE TITLE
Load model locally

### ISSUE THREAD

**Issue by emigomez** [serengil/deepface#852]
Hello!
I am interested in using this project to detect faces with the function `extract_faces()` and to analyze them with `analyze()`. 
The problem is that by default the deep learning models are downloaded from the web in the first call, I would like to download them and use them locally. 
For that, I downloaded the model `retinaface.h5`, how should I call `extract_faces()` to use it without any download? 
How could I download the models of the analyze function? how could I make the same call with those models?

**Comment by serengil** [comment]
you can copy that weights into `~/.deepface/weights` folder manually.

or

set the folder you store that weight file to DEEPFACE_HOME environment variable.
