### ISSUE TITLE
Incorrect API Predictions in [DeepFace.verify]

### ISSUE THREAD

**Issue by RohanKittu** [serengil/deepface#853]
I am building a generic face similarity check application that should find whether a person in the two pictures is the same or different. In this quest, I found Deepface API. Firstly I would like to say thank you for making such an amazing code open source. However, I have observed a significant discrepancy in the face similarity predictions. I have tested with these VGG, Facenet and Facenet512 models as backbone models and for face detection, I used opencv rapper. Despite expectations of accurate recognition, the models are consistently producing inaccurate results. This is particularly concerning as it undermines the reliability and effectiveness of the face similarity feature. So my question is can I change the threshold manually as I already have access to the backend code or the thresholds which are mentioned in the code need to be followed for better [Verify API threshold for distance] results?

The results are shown below. where in the below case the two images given below are of the same person.
<img width="430" alt="Screenshot 2023-10-04 221613" src="https://github.com/serengil/deepface/assets/38404526/e6237ad0-3fea-40a4-9717-960b896fa021">
<img width="770" alt="Screenshot 2023-10-04 221700" src="https://github.com/serengil/deepface/assets/38404526/67722fa6-3f50-4a76-9687-00ae41a88441">

**Comment by serengil** [comment]
individual results do not make deepface unstable. you can find the recognition results on LFW dataset which is reaching and passing 99%.

as a human being, i would classify this pair as different person, too.

**Comment by RohanKittu** [comment]
Firstly Thank you for reverting @serengi. Only for the sake of showing as an example, I was displayed one result. However, in many cases, I found the model gives inconsistent results.  I think I should extract the features from the base models (FACENet etc) and use metric learning algorithms to improve the verification ability of the model for exceptional cases like the above.
