### ISSUE TITLE
Memory usage grow after call DeepFace.represent() method, gc.collect() won't help

### ISSUE THREAD

**Issue by Villyli** [serengil/deepface#855]
I used `memory_profiler` by `from memory_profiler import profile` in my code, and found that memory grows after call **`DeepFace.represent()`** method.The increment is about 15~25MB per call. 

Even I `del` its returns and use `gc.collect()` still don't work. Besides, it seems that it is unrelated to models and backends.

Is there any way or improvement I can do?

**Comment by Villyli** [comment]
Resolved!

`model.predict()` from `keras` caused this mem leak problem. It generates a loader or something else everytime when called.
catastrophic in loop

Use 
```python
from keras import backend

# after a period call and before the next call
backend.clear_session() 
```
    can temporary resolve for this time.


Maybe change `model.predict()` to `model.call()` or `model()` form can help?  @serengil

**Comment by serengil** [comment]
duplicated - https://github.com/serengil/deepface/issues/697
