### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by mtoranzo** [serengil/deepface#858]
The "routes.py" file does not have an entry point that receives images in Base64 string, so I can not complete this example of the video, (https://www.youtube.com/watch?v=HeKCQ6U9XmI) I managed to make it work but only with local files
In fact, this postman file is not the same as the video sample https://github.com/serengil/deepface/blob/master/api/deepface-api.postman_collection.json

**Comment by serengil** [comment]
you can send img1_path and img2_path content as base64 as well as exact image path
