### ISSUE TITLE
Build my face recognition with Deepface

### ISSUE THREAD

**Issue by HoangSang1510** [serengil/deepface#859]
Hello, i am using deepface to build a face recognition. My flow is using Dlib and Arcface to get embedding vector from only 1 frontal face image, then i store embedding vector to my database. I using cosine to find similar face with new embedding vector in my db. My problem is that with same person i have stored, when head pose is change (left, right, up, bottom, ...), my system may not recognition this person. How can i improve my system, do i need to train a classify model (like SVM) with those embedding vectors (left, front, right, ...) to predict person ?

**Comment by serengil** [comment]
you can just play with the configuration to create embeddings. i mean that try facenet instead of arcface, and try mtcnn instead of dlib.
