### ISSUE TITLE
Retreive data from stream function

### ISSUE THREAD

**Issue by astrid-net** [serengil/deepface#860]
I have successfully tested the stream function from DeepFace library to get real time face detection and analysis data from my webcam. I call this method:

`from deepface import DeepFace`

DeepFace.stream(db_path = "C:/User/Sefik/Desktop/database")
It works well and displays crucial data such as face recognized, emotions etc... I would like to use the data it displays in my code but I don't know how to retreive it, something like:
```

from deepface import DeepFace

otp = DeepFace.stream(db_path = "C:/User/Sefik/Desktop/database")
otp['is_there_any_face'], otp['face_recognizedì], otp['emotions_detected']
```
Is there any function to retreive these data on my code? Thank you!

**Comment by serengil** [comment]
No, stream function does not cover that functionality
