### ISSUE TITLE
[Feature Request]: Allow users to provide images of different formats other than "jpeg" and "png"

### ISSUE THREAD

**Issue by ekkolon** [serengil/deepface#862]
A long time ago I created a PR that would have refactored allowed image candidates (by format) 
within `db_path` directory.

Specifically these lines would have been subject to change:
https://github.com/serengil/deepface/blob/fb8924e9849a943943ebac992eb5d3e175504981/deepface/DeepFace.py#L477C1-L484C49

I don't see a reason for why we should restrict users to only be able to provide `png` and/or `jpeg`. Or is there a good reason I am not aware of?

**Comment by serengil** [comment]
which file types you want to use?

**Comment by ekkolon** [comment]
I was thinking of a more generic solution for accepting different image types (e.g webp, avif).
Right now the image extensions are hard-coded and as mentioned only png and jpeg are allowed.

Ideally, we would move the logic for reading the image paths to an util function and the allowed image extensions to a constant - would be easier to maintain/extend/test.

I'd be willing to follow up with a PR.

**Comment by serengil** [comment]
for instance, opencv cannot read images with .heic extension. besides, someone can put a non image file there. that is why, we should restrict the extensions.

**Comment by ekkolon** [comment]
Yes, I'm aware we should restrict file extensions to image files.

You are right, the current OpenCV version (4.5.5) in DeepFace doesn't seem to support `.heif` or `.avif` images. This is not true for the current version of OpenCV though (which DeepFace might use one day).


## This feature is still worth considering and should be re-opened for the following reasons:

Further details:
- [imdecode()](https://docs.opencv.org/4.5.5/d4/da8/group__imgcodecs.html#ga26a67788faa58ade337f8d28ba0eb19e)
- [imread()](https://docs.opencv.org/4.5.5/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56)

### Supported image formats per OpenCV docs (without additional dependencies):
_Windows & MacOS only_

- .png
- .bmp, .dib
- .hdr, .pic
- .jpeg, .jpg, .jpe
- .tiff
- .pbm, .pgm, .ppm .pxm, .pnm

> On Linux*, BSD flavors and other Unix-like open-source operating systems, OpenCV looks for codecs supplied with an OS image

**As far as I understood:**

- Users that want to decode image formats other than those mentioned above need to install dedicated codecs for their OS. DeepFace won't need to provide those dependencies because an exception is raised by OpenCV itself when attempting to decode images whose codecs are missing for the image format.
- Images are decoded by their content **AND NOT** by their extensions. Even if you provided a "non-image" file (that is purely determined by the file's extension) OpenCV would still be able to decode it if the contents of the file represents pixel values and/or if the encoding lib is installed.

---

The bottom-line is that it should be up to the user to decide what images they put in their `db_path` - of course based on the image formats supported by OpenCV version.

If a user is happy to only go with *jpg* | *png* images thats fine. If a user wants to throw in *webp*, for example, they may install *libwebp* or something like that.

> Linux distros either provide these codecs already or they need to be installed any way - this is also true for `jpg` and `png` by the way.

The implication of the current solution is that users are required to either use png or jpg images. What if a tool they use outputs webp or tiff images? They would need to go through another step of converting the images to the required formats.

Hope this provides more context for the feature request.
