### ISSUE TITLE
Representations are not created when  `enforce_detection=True`

### ISSUE THREAD

**Issue by slashtechno** [serengil/deepface#867]
When running `Deepface.find()`, representations are not created if no faces are detected in the passed image if `enforce_detection` is set to `True`.
It seems this is due to the `ValueError` being raised before the file is [written](https://github.com/serengil/deepface/blob/8eb8d96a54a1e8944be9ab12909f7bce767d95f8/deepface/DeepFace.py#L538). This significantly increases the time the next iteration of `Deepface.find()` takes due to representations needing to be generated again and possibly not written.

**Comment by serengil** [comment]
Duplicated - https://github.com/serengil/deepface/issues/816
