### ISSUE TITLE
Different results for same image deepface.analyze

### ISSUE THREAD

**Issue by haddyadnan** [serengil/deepface#869]
Hi, I am getting different results from the same image when I pass the image in as a path and as a numpy array

DeepFace.analyze(numpy_array, actions=["age"], detector_backend='mtcnn')
[{'age': 25, 'region': {'x': 506, 'y': 854, 'w': 693, 'h': 859}}]

DeepFace.analyze(image_path, actions=["age"], detector_backend='mtcnn')
[{'age': 29, 'region': {'x': 305, 'y': 457, 'w': 1036, 'h': 1378}},
 {'age': 32, 'region': {'x': 287, 'y': 844, 'w': 44, 'h': 52}}] #second detection is a false positive. only 1 face is present
 
 
 Another:
 DeepFace.analyze(numpy_img, actions=["age"], detector_backend='mtcnn')
[{'age': 27, 'region': {'x': 83, 'y': 41, 'w': 73, 'h': 98}}]

DeepFace.analyze(image_path, actions=["age"], detector_backend='mtcnn')
[{'age': 31, 'region': {'x': 85, 'y': 37, 'w': 73, 'h': 104}}]

I notice the bounding box are different too.
I used opencv for another test, I got different results also

How I loaded the img
img = cv2.imread("/content/imagefree.jpeg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

**Comment by serengil** [comment]
you should use image path

**Comment by haddyadnan** [comment]
oh, great!. 
I tested this just after this info you gave. If I feed in the numpy image as BGR instead of converting to RGB, I get the same result as passing an image path

**Comment by haddyadnan** [comment]
Taking a closer look:
In case someone else experiences this

base64 input loads as cv2.IMREAD which is expected to be BGR https://github.com/serengil/deepface/blob/8eb8d96a54a1e8944be9ab12909f7bce767d95f8/deepface/commons/functions.py#L74

numpy takes any channel passed https://github.com/serengil/deepface/blob/8eb8d96a54a1e8944be9ab12909f7bce767d95f8/deepface/commons/functions.py#L91

URL input is converted to RGB
https://github.com/serengil/deepface/blob/8eb8d96a54a1e8944be9ab12909f7bce767d95f8/deepface/commons/functions.py#L99 

img path takes in cv2.IMREAD
https://github.com/serengil/deepface/blob/8eb8d96a54a1e8944be9ab12909f7bce767d95f8/deepface/commons/functions.py#L109

the detectors also have different preprocessing
FastMtcnn, mtcnn converts from BGR to RGB as part of their preprocessing because it works better with RGB. 

if a numpy array is passed as input using any of the 2 detectors, the numpy array has to be converted to BGR

url input will probably have false/low prediction with fastmtcnn and mtcnn
