### ISSUE TITLE
enforce_detection=False creates a bogus embedding

### ISSUE THREAD

**Issue by David-OConnor** [serengil/deepface#872]
Example code:
```python
embedding_data = DeepFace.represent(
    img_path=frame,
    model_name=recognition_models[0],
    detector_backend=backends[0],
    enforce_detection=False  # Without this, we get a value error vice empty list.
)
```

Expected behavior when there is no face in frame: returns an empty list. (Because with 1 face, it returns a list of len=1, with 2 len=2 etc)

Actual behavior: Returns a list of len=1, with a bogus embedding.

Suggested fix: Remove the `enforce_detection` parameter, and the `ValueError` behavior, and always return a list of len=# detects.

**Comment by serengil** [comment]
throwing error in intentional behaviour. recommend you to use try catch mechanism.

```python
try:
   embeddingData = DeepFace.represent(
       img_path=frame,
       model_name=recognition_models[0],
       detector_backend=backends[0],
       enforce_detection=True
   )
except:
   embedding_data = []
```
