### ISSUE TITLE
how i can get response  deepface.find in json representation

### ISSUE THREAD

**Issue by bagusandrewijaya** [serengil/deepface#874]
i want response pathrl bestmatch
`
@app.post("/testimage")
async def insert_data(file: UploadFile = File(...), text=None):
    try:
        # Simpan file yang diunggah ke server dengan nama unik
        unique_filename = str(uuid.uuid4()) + "_" + text + ".png"
        face_image_path = os.path.join("tmpimage", unique_filename) 

        with open(face_image_path, "wb") as f:
            f.write(file.file.read())

        # Mencari data wajah dalam database
        dfs = DeepFace.find(img_path=face_image_path, 
                            db_path="/home/it/FaceDetector/db",
                            model_name="ArcFace",
                            distance_metric="euclidean_l2",
                            detector_backend="retinaface")
        
        # Cetak dfs untuk melihat datanya
        print(dfs)

        dfs_json = json.dumps(dfs, default=str)

        user_data = {
            "metadata": {
                "code": 200,
                "message": "berhasil"
            },
            "response": {
                "status": "terverifikasi-asli",
                "hasilgambar": {dfs_json}
            }
        }
        return user_data

    except Exception as e:
        return {"error": str(e)}`

**Comment by serengil** [comment]
find function returns list of data frames. you need to convert each item as shown below.

```python
results = []
for df in dfs:
   df_json = json.loads(df.to_json(orient='records'))
   results += df_json

print(result)
```

**Comment by bagusandrewijaya** [comment]
@serengil work thank you
now how to delete representations_vgg_face.pkl or representations_arcface.pkl where the file saved? 

but when i check in my db dir the file is undefined
WARNING: Representations for images in /home/it/FaceDetector/db folder were previously stored in representations_vgg_face.pkl. If you added new instances after the creation, then please delete this file and call find function again. It will create it again.
