### ISSUE TITLE
renew or delete model .pkl

### ISSUE THREAD

**Issue by bagusandrewijaya** [serengil/deepface#875]
how to delete or renew some model in deepface
 i tried this code 
 
 @app.post("/rebuildArcfacePkl")
async def rebuild_arcface():
    try:
        jalur_db = "/home/it/FaceDetector/db"

        representasi = []

        for nama_gambar in os.listdir(jalur_db):
            if nama_gambar.endswith('.png'):
                jalur_gambar = os.path.join(jalur_db, nama_gambar)

                fitur = DeepFace.represent(img_path = jalur_gambar,enforce_detection=False)
        return {"sukses": "berhasil dibangun ulang"}

    except Exception as e:
        return {"error": str(e)}

dfs_raw = DeepFace.find(img_path=face_image_path, db_path="/home/it/FaceDetector/db")

**Comment by serengil** [comment]
Find function creates pickle file in the db_path which is `/home/it/FaceDetector/db` in your case.

https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L461

you can run the following block before calling find

```python
if path.exists(db_path + "/" + file_name):
   os.remove(db_path + "/" + file_name)
```

**Comment by bagusandrewijaya** [comment]
Thanks mate you save my work @serengil 🫡
