### ISSUE TITLE
DeepFace.verify() always returning True

### ISSUE THREAD

**Issue by eldoncar** [serengil/deepface#876]
I've been testing DeepFace.verify() and it's always returning True even if images are different.
Essentially, I am taking a selfie and verifying against a saved profile picture.

This is the command I'm running
`python3.9 /path/to/Scripts/DeepFace/verify.py '/path/to/user_uploads/profile_pictures/IMG_20231027_WA0002.jpg' '/path/to/user_uploads/photo_verification/653d6ca7ab51d_selfie.jpg'`

VERIFY.PY
`result = DeepFace.verify(img1_path = img1_path, img2_path = img2_path, enforce_detection=False)`

No matter what images I select, it always returns verified:true.
I even tried to compare 2 images, one without a face, and it still returned True.

This is my LOG output
`[2023-10-28 16:19:03] production.DEBUG: array (
  0 => '
1/1 [==============================] - ETA: 0s
1/1 [==============================] - 1s 848ms/step',
  1 => '
1/1 [==============================] - ETA: 0s
1/1 [==============================] - 1s 716ms/step',
  2 => '{"verified": true, "distance": 0.2589801242333821, "threshold": 0.4, "model": "VGG-Face", "detector_backend": "opencv", "similarity_metric": "cosine"}',
) 
`
What could be wrong here?

Thanks

**Comment by serengil** [comment]
Do not set enforce_detection to False.

**Comment by eldoncar** [comment]
Thanks @serengil 

I did try that but I'm always getting this error
`[2023-10-29 13:45:57] production.DEBUG: array (
  0 => 'Error: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.',
  1 => 'None',
)  `

It actually asks me to set enforce_detection to False to be able to detect the face in the picture.

But then when I set it to False and compare photos of 2 different person it still return verified:true.

Any other suggestion would be much appreciated.

**Comment by eldoncar** [comment]
Hoping this can help someone else.

I was able to fix the issue by changing backend detector to MTCNN.

`result = DeepFace.verify(img1_path = img1_path, img2_path = img2_path, detector_backend = 'mtcnn')`
