### ISSUE TITLE
Question when using embeddings for vector search for faces wearing glasses

### ISSUE THREAD

**Issue by elisoncampos** [serengil/deepface#877]
Hi, Im using deepface represent in order to generate embeddings and store It in opensearch as a knn_vector so i can search for similar faces afterward using euclidean l2, It Works great but glasses, as expected, are a problem.

Is there a recomended model for generating embeddings of faces wearing glasses? I've been using Facenet and Facenet512 to benchmark the results and find a good distance treshold but it's either too permisive (every face with glasses are a match) or too restrictive (not every face of the person is found)

On other hand, is there a method that can Tell If the face IS wearing glasses?

**Comment by serengil** [comment]
wearing accessories decreases the accuracy. this is known. that is why, you are enforced to use images with no accessories in passport images.

secondly, i do not know anything about wearing glasses classification.
