### ISSUE TITLE
About SFace.

### ISSUE THREAD

**Issue by zhanjiahui** [serengil/deepface#878]
Thank you for your wonderful work.
May I ask which paper is the source of the `SFace` model? Is it “_SFace: Sigmoid-Constrained Hypersphere Loss for Robust Face Recognition_” inTIP 2021?

**Comment by serengil** [comment]
I think so. It is added by a contributor from opencv.

**Comment by zhanjiahui** [comment]
> I think so. It is added by a contributor from opencv.

Thank you very much for your answer.
