### ISSUE TITLE
Issue in using Stream - Real time face recognition

### ISSUE THREAD

**Issue by rathishkumar** [serengil/deepface#88]
Hi,

Thank you for this awesome work!!!

I am getting error, while trying to run the below code:

```
from deepface import DeepFace
DeepFace.stream("D:\vision\recognition\images")
```
Error message:

```
  File "stream.py", line 3, in <module>
    DeepFace.stream("D:\vision\recognition\images")
  File "D:\Anaconda\envs\ml-engine\lib\site-packages\deepface\DeepFace.py", line 858, in stream
    realtime.analysis(db_path, model_name, distance_metric, enable_face_analysis)
  File "D:\Anaconda\envs\ml-engine\lib\site-packages\deepface\commons\realtime.py", line 356, in analysis
    custom_face = functions.detectFace(custom_face, (input_shape_y, input_shape_x))
UnboundLocalError: local variable 'input_shape_y' referenced before assignment
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-n4ekh6o5\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
```

Looks like variable scope issue. I am analysing code to understand this error. Please look into it.

**Comment by Arash-HR** [comment]
@rathishkumar 
I have the same problem as you ,
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    DeepFace.stream("database")
  File "E:\Users\Arash\anaconda3\envs\virenv\lib\site-packages\deepface\DeepFace.py", line 858, in stream
    realtime.analysis(db_path, model_name, distance_metric, enable_face_analysis)
  File "E:\Users\Arash\anaconda3\envs\virenv\lib\site-packages\deepface\commons\realtime.py", line 354, in analysis
    custom_face = functions.detectFace(custom_face, (input_shape_y, input_shape_x))
UnboundLocalError: local variable 'input_shape_y' referenced before assignment
[ WARN:1] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-k8sx3e60\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
```

**Comment by serengil** [comment]
Could you try to call the stream command like this?

`DeepFace.stream("D:/vision/recognition/images")`

There are .jpg files in this folder, right?

**Comment by rathishkumar** [comment]
@serengil It is working now with modified '/'. Thank you.

However, face recognition is not happening, only emotion analysis is working.

Yes, the directory contains .jpg files.

**Comment by rathishkumar** [comment]
> @rathishkumar
> I have the same problem as you ,
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 2, in <module>
>     DeepFace.stream("database")
>   File "E:\Users\Arash\anaconda3\envs\virenv\lib\site-packages\deepface\DeepFace.py", line 858, in stream
>     realtime.analysis(db_path, model_name, distance_metric, enable_face_analysis)
>   File "E:\Users\Arash\anaconda3\envs\virenv\lib\site-packages\deepface\commons\realtime.py", line 354, in analysis
>     custom_face = functions.detectFace(custom_face, (input_shape_y, input_shape_x))
> UnboundLocalError: local variable 'input_shape_y' referenced before assignment
> [ WARN:1] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-k8sx3e60\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
> ```

@Arash-HR Changing to '/' working for me, try and see.

**Comment by serengil** [comment]
@rathishkumar if face recognition is not working, then that's the result of face recognition algorithm. you might use higher resolution images.

I will add a control block if source folder has no image. This will warn people use \ instead of /.

**Comment by rathishkumar** [comment]
Thank you, @serengil .

Anyone facing the similar issue, the FR working now, after creating a folder with my name inside 'images' directory and adding images under that folder. Earlier, I tried with adding .jpg files directly under the 'images' folder.
