### ISSUE TITLE
Ensemble loadModel() issue

### ISSUE THREAD

**Issue by rm8631** [serengil/deepface#89]
df = (DeepFace.find('frame.jpg', db_path = db_path, model_name = 'Ensemble', model=model, enforce_detection=False))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/deepface/DeepFace.py", line 648, in find
    for j in model_names:
UnboundLocalError: local variable 'model_names' referenced before assignment

This is the error I get. I am trying to pre-load all the models using a dictionary and then pass it to the find function along with model_name = "Ensemble"

**Comment by serengil** [comment]
Thank you for informing about the issue. I fixed this in the 0.0.35 version of deepface. Please update your deepface relase.

`pip install deepface==0.0.35`

**Comment by serengil** [comment]
I will be happy if you share that your tests are working in this version.

**Comment by rm8631** [comment]
Thank you !! It works in this version.
