### ISSUE TITLE
Problem with dlib operation via visual test launch

### ISSUE THREAD

**Issue by Ruziy** [serengil/deepface#899]
![image](https://github.com/serengil/deepface/assets/107850684/39afe48d-07e9-427d-97e4-0c67d682fa6f)
All networks loaded on their own, except dlib, I downloaded version 19.20.0 on my own using conda, but the error remained.
[package_conda.txt](https://github.com/serengil/deepface/files/13498400/package_conda.txt)

**Comment by Ruziy** [comment]
Thanks, I'll try it

**Comment by Ruziy** [comment]
After installing dlib:
![image](https://github.com/serengil/deepface/assets/107850684/8d23a663-f38d-4774-a040-4ec1525b10ab)

**Comment by serengil** [comment]
this is coming from DeepId and this is sorted in the current source code. Try source code instead of pip version.

**Comment by Ruziy** [comment]
I'm sorry, I'm a novice programmer, couldn't tell you how it is implemented

**Comment by Ruziy** [comment]
should I remove deepface from pip and build the project using visual code? But I will have the error that there is no deepface :)

**Comment by serengil** [comment]
Run the following commands respectively

```shell
pip uninstall deepface
git clone https://github.com/serengil/deepface.git
cd deepface
pip install -e .
```

**Comment by Ruziy** [comment]
I work just the same according to such instructions and get such an error, I repeated the process, everything turned out the same...
![image](https://github.com/serengil/deepface/assets/107850684/f2277b48-dbb8-4fdd-9943-27a7e5148579)
![image](https://github.com/serengil/deepface/assets/107850684/484576f5-6541-4169-bcf1-ee1106779663)
![image](https://github.com/serengil/deepface/assets/107850684/6427b71a-3661-4e38-a8ac-5574350ef0e0)

**Comment by serengil** [comment]
Comment line 10 in visual_tests: https://github.com/serengil/deepface/blob/master/tests/visual-test.py#L10

**Comment by Ruziy** [comment]
![image](https://github.com/serengil/deepface/assets/107850684/24ee0eef-a908-49b3-95a6-c5000791e083)

**Comment by serengil** [comment]
Now, you cannot download some other dlib file: https://github.com/serengil/deepface/blob/master/deepface/detectors/DlibWrapper.py#L14 - do it manually

**Comment by serengil** [comment]
seems dlib_face_recognition_resnet_model_v1.dat is corrupted. target file is in bz2 format. did you unzip it? 

https://github.com/serengil/deepface/blob/master/deepface/basemodels/DlibResNet.py#L29
