### ISSUE TITLE
About a RGB format question of load_image(img)

### ISSUE THREAD

**Issue by nigue3025** [serengil/deepface#904]
Hi,
I am greatly inspired from your work a lot, but I get something confused.

In the function load_image(img) of the file deepface/commons/functions.py

I found out that the image with url is to be converted to RGB (something like .convert("RGB"))

However, for the image encoded as base64 or represented as filepath, I found nothing related to the conversion of RGB.

For fear that getting the face with BGR format, should something like "img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)" be added additionally for either the section of base64 or file path?

Thanks in advance

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/911
