### ISSUE TITLE
No information on ArcFace model weight source.

### ISSUE THREAD

**Issue by pleshro** [serengil/deepface#905]
Can you please add information on the source for the weights for the ArcFace recognition model? The only information I can find in this repository is that they came from a "Keras re-implementation of ArcFace." Specifically, I am looking for the training details, such as what data was used for training. Thank you.

**Comment by serengil** [comment]
follow license section in readme. you will be redirected to the source repos.

**Comment by pleshro** [comment]
Terrific. Which Resnet32 set of weights were used? The linked implementation has two different sets available. Was "Resnet34 trained on CASIA,E40" or "r34 converted trained on Glint360k" used? 
https://github.com/leondgarse/Keras_insightface/tree/master

**Comment by serengil** [comment]
Resnet34 trained on CASIA,E40
