### ISSUE TITLE
how do I use process_face from deepface.commons?

### ISSUE THREAD

**Issue by Developer404** [serengil/deepface#91]
I get this error message: AttributeError: module 'deepface.commons.functions' has no attribute 'preprocess_face'

**Comment by Developer404** [comment]
I tried from deepface.commons.functions import preprocess_face
and it gave ImportError: cannot import name 'preprocess_face'

**Comment by serengil** [comment]
Please give me more details. Did you try it as shown below?

```
from deepface.commons import functions
img = functions.preprocess_face(img = "img1.jpg", detector_backend = 'opencv')
```

**Comment by Developer404** [comment]
yes

**Comment by serengil** [comment]
could you import just deepface?

`from deepface import DeepFace`

**Comment by serengil** [comment]
You got  ImportError: cannot import name 'preprocess_face' because you imported preprocess_face. You should import functions. preprocess_face is a function under functions.py. You are sure that you are importing as shown below? Please share your code.

```
from deepface.commons import functions
img = functions.preprocess_face(img = "img1.jpg", detector_backend = 'opencv')
```

**Comment by Developer404** [comment]
yes

**Comment by Developer404** [comment]
you check it yourself

**Comment by Developer404** [comment]
`from deepface.commons import functions
img = functions.preprocess_face(img = "Actors/Ram Charan.jpg", detector_backend = 'opencv')

`

**Comment by Developer404** [comment]
`AttributeError: module 'deepface.commons.functions' has no attribute 'preprocess_face'
`

**Comment by Developer404** [comment]
> could you import just deepface?
> 
> `from deepface import DeepFace`

what do u mean

**Comment by serengil** [comment]
what was your deepface version? It should be 0.0.37.

https://pypi.org/project/deepface/

**Comment by Developer404** [comment]
ohhh yes I was using 0.0.34 all this time, I'll try now

**Comment by serengil** [comment]
pip install deepface==0.0.37 (the latest)

**Comment by Developer404** [comment]
ITS WORKING NOW THANKS SO MUCH SEFIK!
