### ISSUE TITLE
the facenet model

### ISSUE THREAD

**Issue by dumbogeorge** [serengil/deepface#915]
Would it be possible to get access to facenet_weights.h5 ? I am unable to find it anywhere, which make some parts of your code less useful.

I think you shared your gdrive link (https://drive.google.com/file/d/1971Xk5RwedbudGgTIrGAL4F7Aifu7id1/view?usp=sharing) - which does not seem work anymore.

Thanks

**Comment by serengil** [comment]
Google drive is out of the date source. Current one is here: https://github.com/serengil/deepface/blob/master/deepface/basemodels/Facenet.py#L1625

**Comment by dumbogeorge** [comment]
Hi Serengil, 
Thanks for your quick help. I was able to download facenet_weights.h5. How Can I can specify this file along with this path to Facenet.loadModel() ?
