### ISSUE TITLE
dlib installation fails to download necessary files

### ISSUE THREAD

**Issue by antonalley** [serengil/deepface#919]
I am on windows 11, and for running dlib I downloaded Visual Studio to work with cmake. But I noticed when downloading the weights, there is some error on line 22 of DlibWrapper.py: gdown.download(url, output, quiet=False). It worked when I manually downloaded those files and commented out that line so it still unzipped them all

**Comment by serengil** [comment]
possible proxy or firewall issue not related to deepface
