### ISSUE TITLE
Getting Error Loading Image to DeepFace

### ISSUE THREAD

**Issue by mahamatnoumai** [serengil/deepface#92]
Hi Mr Sefik, thanks for this awesome deepface 

Current DeepFace version am using is deepface==0.0.37 tried with many different versions, and it's still giving me the same error. 

I also get similar errors when testing https://github.com/serengil/deepface/blob/master/tests/Ensemble-Face-Recognition.py

here are the following images showing the errors that am going through.
there are some issues in https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py

 
https://github.com/serengil/deepface/blob/5ffeaa436ee3e8c36fe71e652058960ad00e3e8e/deepface/commons/functions.py#L104

<img width="1375" alt="Screenshot 2020-09-16 at 1 57 35 PM" src="https://user-images.githubusercontent.com/17758399/93298171-531b5500-f825-11ea-8526-55ba2b0dfeea.png">

<img width="1379" alt="Screenshot 2020-09-16 at 1 57 12 PM" src="https://user-images.githubusercontent.com/17758399/93298081-2cf5b500-f825-11ea-9426-ad64223bf5bb.png">

Idk what am doing wrong here, i got similar error while testing model in here too https://github.com/serengil/tensorflow-101/blob/master/python/openface-real-time.py and same to this one and other https://github.com/serengil/tensorflow-101/blob/master/python/fb-deepface-real-time.py

**Comment by serengil** [comment]
Exception message says everything. There is not target.jpg in the first one, and face area could not be detected in target.jpg in the second one. You can set enforce_detection = False as mentioned in the message.

BTW, is there a _ character in My Drive folder? If there is not, please add.

**Comment by mahamatnoumai** [comment]
I've set enforce_detection = False as well. it's still the same issues. 
it could be there is some issues in my end. bc i tried couple of different way it's the same issues. I haven't tested on the same datasets that you provided on here https://github.com/serengil/deepface/tree/master/tests/dataset and still get some issues 

this is the issues i got into 

<img width="1433" alt="Screenshot 2020-09-16 at 3 02 39 PM" src="https://user-images.githubusercontent.com/17758399/93303288-d04ac800-f82d-11ea-8429-5931ea65644c.png">


perhaps you could tell me how to avoid these two issues raised by https://github.com/serengil/deepface/blob/5ffeaa436ee3e8c36fe71e652058960ad00e3e8e/deepface/commons/functions.py#L104


1-  `ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.` 
2- attached picture 
3- `ValueError: ('Confirm that ', 'target.jpg', ' exists')`


perhaps u could share if u do have sample data that i could test without getting this kind of errors as well


Thanks.

**Comment by serengil** [comment]
Is this really exists? "your current directory/deepface/tests/dataset/img1.jpg"

**Comment by mahamatnoumai** [comment]
Yes it does exist Sir  


<img width="1178" alt="Screenshot 2020-09-16 at 5 40 04 PM" src="https://user-images.githubusercontent.com/17758399/93320686-f5e2cc00-f843-11ea-8d7c-4a765950cb30.png">

**Comment by mahamatnoumai** [comment]
fixed thanks for response 👌🏾👌🏾
