### ISSUE TITLE
Unable to find good face match with deepface and Annoy

### ISSUE THREAD

**Issue by dumbogeorge** [serengil/deepface#924]
Hi 
I am using following code from Serengil's tutorial (you tube), for finding best face match. The embeddings are from deepface and Annoy's ANNS based search is used for find best matching face. 

This code does not give good matching face, as was hightlighted in Serengil's you tube video.

Looking for help about why this code would not give best matching face.

Thanks

import os
from deepface.commons import functions
from keras_facenet import FaceNet
from deepface.basemodels import Facenet
from annoy import AnnoyIndex
import matplotlib.pyplot as plt
import random
import time

facial_images = []
for root, directories, files in os.walk("../../deepface/deepface/tests/dataset"):
    for file in files:
        if ('.jpg' in files):
            exact_path = root + files
            facial_images.append(exact_path)

embedder = FaceNet()
model = Facenet.loadModel()

representations = []
min = 100000000000
max = -10000000000
for face in facial_images:    
    img = functions.preprocess_face(img = face, target_size = (160,160))
#    embedding = embedder.embeddings(img)
    embedding = model.predict(img)[0,:]
    temp = embedding.min()
    if (min > temp):
        min = temp
    temp = embedding.max()
    if (max < temp):
        max = temp

    representation = []
    representation.append(img)
    representation.append(embedding)
    representations.append(representation)

#synthetic data to enlarge data size
for i in range(len(representations), 100000):
    filename = "dummy_%d.jpg" % i
    vector = [random.gauss(min, max) for z in range(128)]
    dummy_item = []
    dummy_item.append(filename)
    dummy_item.append(vector)
    representations.append(dummy_item)

t = AnnoyIndex(128, 'euclidean')
for i in range(len(representations)):
    vector = representations[i][1]
    t.add_item(i, vector)

t.build(3)

idx = 0
k   = 2

start = time.time()
neighbors = t.get_nns_by_item(idx,k)
end = time.time()
print ("get_nns_by_item took " , end-start, " seconds");
print (neighbors)

**Comment by serengil** [comment]
ML models are probabilistic. So, having a bad result for a custom set does not make it stable. Need to have same instances with you to make a comment.

**Comment by dumbogeorge** [comment]
Hi Serengil,
I downloaded the model from the pointer shared by you earlier - https://github.com/serengil/deepface/blob/master/deepface/basemodels/Facenet.py#L1625

Would this mean that I am using same instance of model as shared by you in the tutorial video ?

Thanks
