### ISSUE TITLE
Issue with dockerized version

### ISSUE THREAD

**Issue by medichops1** [serengil/deepface#927]
Hi,

I'm really sorry to bother you again.....

I have dockerized and all went well.  Container is up and URL answers.

I send the following curl:

curl -X POST http://127.0.0.1:5000/analyze \  
--header 'Content-Type: application/json' \
--data '{
    "img_path": "/tmp/mark2.jpg",
    "actions": ["age", "gender", "emotion", "race"]
}'

but I get the following response:

<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Any idea what could be the issue?

Also, the CLI does not seem to install anywhere.  What am I doing wrong?  I have followed the docs.

Thanks.

**Comment by serengil** [comment]
/tmp/mark2.jpg is available in docker image?

**Comment by medichops1** [comment]
Ah no, I presumed the image would be sent up with the post.

**Comment by kkolge** [comment]
Send it as base64 encoded 

Sent from Yahoo Mail on Android 
 
  On Wed, 20 Dec 2023 at 23:19, Mark ***@***.***> wrote:   


Ah no, I presumed the image would be sent up with the post.

**Comment by medichops1** [comment]
Using:

curl -X POST --location 'http://127.0.0.1:5000/analyze' \
--header 'Content-Type: application/json' \
--data '{
    "img_path": "'${face_data}'",
    "actions": ["age", "gender", "emotion"]
}'

Returns an error asking me to check that the base64 string (in full) exists.

**Comment by serengil** [comment]
what is "'${face_data}'" ? if you try to pass something outside of docker,

1- you may consider to copy it into docker

```shell
docker cp ~/.Desktop/img.jpg <CONTAINER_ID>:/tmp/img.jpg
```

2- or pass base64 encoded image as

"img_path": "data:image/jpeg;base64,/9j/4AAQ..."

base64 encoded image must start with this pattern "data:image/jpeg;base64,"
