### ISSUE TITLE
Custom model for Ensemble

### ISSUE THREAD

**Issue by rm8631** [serengil/deepface#93]
Hi, I was just wondering how to go about using my own custom trained GBM model instead of the default "face-recognition-ensemble-model.txt" file. So I have trained a GBM ensemble model on my own custom dataset and was wondering how to use that in DeepFace.find or Deepface.analyze or any other functions. Thanks in advance.

**Comment by serengil** [comment]
Ensemble model is totally hard-coded. You cannot pass a custom model to it unfortunately. But I can add this feature in the next release.

Could you explain more about your custom model. What are features e.g.?

**Comment by rm8631** [comment]
Hi, 
Thanks for the reply. So i followed this link of yours and instead of using the provided dataset in the "tests/dataset/" directory, I used my own dataset of around 10-15k pairs of positive and negative faces and found representations for the same. After that I trained a LightGBM model and saved the gbm model as "face-recognition-ensemble-model-custom.txt". So now instead of using the default "face-recognition-ensemble-model.txt" file, how can I use this custom txt file of mine

**Comment by rm8631** [comment]
Here is the link I followed : https://sefiks.com/2020/06/03/mastering-face-recognition-with-ensemble-learning/

**Comment by serengil** [comment]
if your features are same with this tutorial, then you can modify the content of face-recognition-ensemble-model-custom.txt

This file is stored in HOME/.deepface/weights/. For example, exact path is "C:\Users\Sefik\.deepface\weights" in my environment. If the name of this file stays same but you can update the content of this file.

**Comment by rm8631** [comment]
Yes the features remain the same, only the dataset changes if i am not wrong. Great, I will try this and see if it works and let you know.

**Comment by serengil** [comment]
you can delete that file if something is broken, it recovers the base file in this case.

**Comment by rm8631** [comment]
Okay Thank you !!!
