### ISSUE TITLE
Line 52: AttributeError: 'list' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by raspcode** [serengil/deepface#930]
This is my code. I have files for each person in a separate directory and I browse through them. Everything starts fine then I get the error below:
`To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:35<00:00,  1.53s/it]
  0%|                                                                                                                       | 0/23 [00:00<?, ?it/s]img_nameimages\Amira\i380.jpg
  0%|                                                                                                                       | 0/23 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "c:\Users\sedky\Documents\Python Scripts\opencv_project\learn.py", line 52, in <module>
    insert_args = (index, img_name, embeddings.tobytes())
                                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'tobytes'`

My full code is below:

import cv2
import numpy as np

import os 

file_path = "images"
facial_img_paths = []
with os.scandir(file_path) as entries:
    for entry in entries:
        if entry.is_dir():
            current_path = file_path + '\\' + entry.name
            
            print("Directory: " + current_path)
            with os.scandir(current_path) as sub_dirs:
                for sub_entry in sub_dirs:
                    if sub_entry.is_file():
                        if '.jpg' in sub_entry.name:
                            facial_img_paths.append(current_path + '\\' + sub_entry.name)
                            print(current_path + '\\' + sub_entry.name)
            print("-------")

from tqdm import tqdm
from deepface import DeepFace

import pandas as pd
from deepface.commons import functions
 
instances = []
for i in tqdm(range(0, len(facial_img_paths))):
    facial_img_path = facial_img_paths[i]
    embedding = DeepFace.represent(img_path = facial_img_path, model_name = "Facenet")[0]["embedding"]
     
    #store
    instance = []
    instance.append(facial_img_path)
    instance.append(embedding)
    instances.append(instance)
 
df = pd.DataFrame(instances, columns = ['img_name', 'embedding'])

import sqlite3

conn = sqlite3.connect('images\\facial.db')
cursor = conn.cursor()

for index, instance in tqdm(df.iterrows(), total=df.shape[0]):
    img_name = instance['img_name']
    embeddings = instance['embedding']
     
    print('img_name' + img_name)
    insert_statement = 'INSERT INTO face_meta (ID, IMG_NAME, EMBEDDING) VALUES (?, ?, ?)'
    insert_args = (index, img_name, embeddings.tobytes())
    cursor.execute(insert_statement, insert_args)
     
    for i, embedding in enumerate(embeddings):
        insert_statement = 'INSERT INTO face_embeddings (FACE_ID, DIMENSION, VALUE) VALUES (?, ?, ?)'
        insert_args = (index, i, str(embedding))
        cursor.execute(insert_statement, insert_args)
 
conn.commit()

**Comment by serengil** [comment]
embedding is a list. Try bytes(embedding) or convert it to numpy first as np.array(embeddings).to_bytes()
