### ISSUE TITLE
Load yolov8n-face.pt model in production environment using ONNX model

### ISSUE THREAD

**Issue by fn-hide** [serengil/deepface#931]
I have used deepface for face recognition with a backend detector using yolov8. but I found several weaknesses, namely:
- inference time will be faster if the model is loaded using `.onnx` rather than `.pt`
- loading models using `YOLO(modelpath)` will not be optimal in production. I have tried it and done a stress test. The result will be several errors when there are many threads at one time.

So, with the views and research that I have done. I would like to suggest changing the yolov8 model load method from using YOLO ultralytics to onnx. reference for load can be seen in this repository [https://github.com/hpc203/yolov8-face-landmarks-opencv-dnn](url)

Please also note that, I encountered an error when using OpenCV as a backend detector to make many requests at one time.

Correct me if I was wrong.

**Comment by serengil** [comment]
Existing yolo model was added by a contributor. I do not have any experience on the model. Will switch when I have time. Thank you for the feedback.

**Comment by fn-hide** [comment]
Thank you for your response. Can I make pull request? But, this is my first time. So, the code may not good as expected.

**Comment by serengil** [comment]
@fn-hide Of course you can, I will add my comment fast once you created a PR.

**Comment by serengil** [comment]
Closed due to inactivity
