### ISSUE TITLE
The problem with using Yolov8 as a detector.(TensorFlow)

### ISSUE THREAD

**Issue by Ruziy** [serengil/deepface#936]
Hi, I'm trying to connect Yolov8 as a detector, obviously there was a mistake - Too many users have recently viewed or downloaded this file. I managed to download it from the link and put it in /.deepface/weights/yolov8n-face.pt. But after the launch, an error related to TensorFlow comes out.

Problem:2023-12-26 23:25:45.753053: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by serengil** [comment]
this is an external dependency. you may consider to raise this issue in the original repo - https://github.com/derronqi/yolov8-face
