### ISSUE TITLE
DeepFace.analyze()  working very slow

### ISSUE THREAD

**Issue by Vishaldolase** [serengil/deepface#937]
@serengil ,

I am using Jetson xavier nx
Jetpack version 4.6.1
tensorflow >>> tf.__version__
'2.7.0'
python 3.6.1

I tried to use DeepFace, but it is taking around 20 seconds to process one frame
Can you provide any suggestions ?

**Comment by serengil** [comment]
The most of the time is spending on building model. When you build a model once, then 2nd predictions will be much faster. In the initialization of your application, you can perform a prediction task, or build those models manually. In that way, in runtime it will be faster always.
