### ISSUE TITLE
have to install dlib

### ISSUE THREAD

**Issue by Developer404** [serengil/deepface#94]
please don't make it mandatory for dlib, it is very big in size. Please import the dlib library where you are using  it (in the DeepFace.py file)

**Comment by serengil** [comment]
you are right. It does not appear in setup.py. I removed dlib, mtcnn and lightgbm in dependencies.txt as well.

**Comment by Developer404** [comment]
but using DeepFace class will give an import error because of this line in DeepFace.py

Please insert that line where you're using it

<img width="536" alt="Screenshot 2020-09-17 at 11 05 48 PM" src="https://user-images.githubusercontent.com/31384337/93506851-784db780-f93a-11ea-8e35-0b4e2ae843ce.png">

**Comment by serengil** [comment]
you are right. please update deepface to 0.0.38

`pip install deepface==0.0.38`
