### ISSUE TITLE
Can you dynamically update the pickle file?

### ISSUE THREAD

**Issue by ntnz** [serengil/deepface#942]
In my implementation I'm dynamically updating the facial database fairly often. When running `find()`, I think it warns me to delete the pickle each time I add to the database:
```
⚠️  Representations for images in <PATH> folder were previously stored in representations_vgg_fae.pkl. If you added new instances after the creation, then please delete this file and call find function again. It will create it again.
```
Doing this means the next time the database is used, it regenerates the pickle, which seems resource intensive.

Is there a way to dynamically update the pickle instead of regenerating the entire thing each time?

**Comment by serengil** [comment]
Cons of updating pickle instead of re-create is that if an image is updated with same name, then we will still use its old embedding. That is why, I prefer to expect user to delete that pickle manually.
