### ISSUE TITLE
Dinamically update the faces database

### ISSUE THREAD

**Issue by Martini002** [serengil/deepface#946]
Hello

Is there any way to update the faces database dinamically?
I understand there could be an issue with duplicated names, but I would like to take care about it, so I can have some kind of database that prevents it, so, if there is any method that can allow me to push new faces into the pickle file, would really appreciate it.

[](https://github.com/serengil/deepface/issues/942)

Thank you

**Comment by serengil** [comment]
Unfortunately, if your database is updated, then you need to delete the pickle manually and wait deepface to re-create it.

**Comment by serengil** [comment]
Will give a try to do this

**Comment by Martini002** [comment]
thank you, keep us updated please

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/959
