### ISSUE TITLE
setting detector_backend to 'skip' gives error 

### ISSUE THREAD

**Issue by Mostafa-Alavi** [serengil/deepface#952]
Hi, setting detector_backend to 'skip' gives error : 
"""Cannot cast ufunc 'divide' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'"""

it's because this line of code  in Deepface.py (lin 719): 

img/=255

and should be changed to :
 
img = (img/255).astype(np.float32)

**Comment by serengil** [comment]
Current code is different than you shared: https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L744

```python
img = img.astype(np.float32) / 255.0
```

Still, I am adding to convert it to np float 32
