### ISSUE TITLE
About yolov8n-face.pt

### ISSUE THREAD

**Issue by zdjk104tan** [serengil/deepface#954]
I want use it in Ascend 310B1. And I transform it to yolov8n-face.om. Now, the model output while one picture is (1,20,8400). I think the 8400 is the number of object. and 20 is the parameters like x1,x2,y1,y2,score.... However, I don't know how to deal it without know the train config. I hope you can give some tips.
![image](https://github.com/serengil/deepface/assets/135097828/5abb3088-d24e-430b-bba1-dab9feaef430)

**Comment by zdjk104tan** [comment]
Can I use the mindyolo to deal the output?

**Comment by serengil** [comment]
I cannot understand this is relation to deepface
