### ISSUE TITLE
cv2.dnn issue with using SDD in deepface.analyze()

### ISSUE THREAD

**Issue by DianaDaInLee** [serengil/deepface#956]
I have the most recent opencv-python version 4.9.0.80 and it seems to cause an issue when I try to run DeepFace.analyze():

```
DeepFace.analyze('Img.jpg', ['race'], detector_backend = 'ssd', enforce_detection= False, silent = False)
```

```
File ~/anaconda3/lib/python3.11/site-packages/deepface/detectors/SsdWrapper.py:46, in build_model()
     42     output = home + "/.deepface/weights/res10_300x300_ssd_iter_140000.caffemodel"
     44     gdown.download(url, output, quiet=False)
---> 46 face_detector = cv2.dnn.readNetFromCaffe(
     47     home + "/.deepface/weights/deploy.prototxt",
     48     home + "/.deepface/weights/res10_300x300_ssd_iter_140000.caffemodel",
     49 )
     51 eye_detector = OpenCvWrapper.build_cascade("haarcascade_eye")
     53 detector = {}

AttributeError: module 'cv2.dnn' has no attribute 'readNetFromCaffe'
```

Is there a way around this issue?

**Comment by serengil** [comment]
Would you please install this dependency

```shell
pip install opencv-contrib-python
```

This is an optional library. So, I should throw a meaningful exception message about the missing dependency anyway.

**Comment by DianaDaInLee** [comment]
Thank you for the suggestion. I installed this package but it's still causing the same issue unfortunately.

**Comment by serengil** [comment]
that must be the error, confirm that opencv-contrib-python is installed on the current environment

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/959
