### ISSUE TITLE
DetectFace gives an empty array

### ISSUE THREAD

**Issue by rm8631** [serengil/deepface#96]
When I try and run DeepFace.detectFace("img.jpg", detector_backend = 'mtcnn') it gives me an array of zeros of shape (224,224,3) for any images. What could be the reason?

**Comment by serengil** [comment]
It is very interesting.

```
from deepface import DeepFace
img = "img1.jpg" #94 https://github.com/serengil/deepface/blob/master/tests/dataset/img1.jpg
obj = DeepFace.detectFace(img, detector_backend = 'mtcnn')
print(obj.shape)
print(obj)
```

I just run this code. The result is shown below. 

(tensorflow) C:\Users\IS96273\Desktop>python test.py
Using TensorFlow backend.
(224, 224, 3)
[[[0.19607843 0.20392157 0.2       ]
  [0.20392157 0.20392157 0.20784314]
  [0.2        0.20392157 0.2       ]
  ...

Could you share the input image you are running? Besides please try the image I tested - I writo the link as well.

Besides, what were your tf and keras versions?

**Comment by rm8631** [comment]
So, I just used pip install deepface on a google colab and ran it so i am guessing the versions are the latest ones. Also, when I try the image you provided, it runs perfectly fine. I am sharing the image I am trying to run. do let me know what results you get. 
![test1](https://user-images.githubusercontent.com/14879321/93855586-5905b000-fcd5-11ea-9def-09677856ca91.jpg)

**Comment by rm8631** [comment]
Also when i use cv2_imshow(obj) with the image you provided, I get nothing but a black image. Strange

**Comment by serengil** [comment]
There is no problem. I saved your image as img2.jpg.

```
import numpy as np
from deepface import DeepFace
#obj = DeepFace.detectFace("img.jpg", detector_backend = 'mtcnn')
obj = DeepFace.detectFace("img2.jpg", detector_backend = 'mtcnn')

print(obj.shape)
print(obj)
print("max: ",np.max(obj))
print("min: ",np.min(obj))
```

It returns the following result. You see lots of 0 values but the maximum value is 1 in the obj.

(tensorflow) C:\Users\IS96273\Desktop>python test.py
Using TensorFlow backend.
(224, 224, 3)
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]

max:  0.99607843
min:  0.0

**Comment by rm8631** [comment]
Oh yes got it !! My bad. Sorry for the trouble. Thank you so much

**Comment by serengil** [comment]
Seeing lots of zeros confused me as well. I had to imshow it with matplotlib.

PS: you can support this study if you star the repo

**Comment by rm8631** [comment]
Yes I will do it right away. This project has helped me a lot so thank you
