### ISSUE TITLE
Can't seem to use model in Deepface.verify

### ISSUE THREAD

**Issue by Demonbane18** [serengil/deepface#968]
Deepface.verify produces a type error when I add model on the parameters because it is missing in the parameters. Is there a way to be able to use it?

![image_2024-01-24_184521774](https://github.com/serengil/deepface/assets/65271203/f17af79a-6355-4657-bd83-2d8eb68739b7)

**Comment by serengil** [comment]
because, model is not an argument for deepface anymore. setting model_name is enough. it can be checked here: https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L53
