### ISSUE TITLE
Analyze method is legal to use for commercial purpose?

### ISSUE THREAD

**Issue by Hassaan68** [serengil/deepface#970]
It looks like that Age,Gender etc analysis are using VGG-Face model and VGG-Face model is not for commercial use. can we use analysis method for commercial use?

**Comment by Hassaan68** [comment]
@serengil can you answer quickly please if you are available?

**Comment by serengil** [comment]
This is already mentioned in the license section

```
DeepFace wraps some external face recognition models: [VGG-Face](http://www.robots.ox.ac.uk/~vgg/software/vgg_face/), [Facenet](https://github.com/davidsandberg/facenet/blob/master/LICENSE.md), [OpenFace](https://github.com/iwantooxxoox/Keras-OpenFace/blob/master/LICENSE), [DeepFace](https://github.com/swghosh/DeepFace), [DeepID](https://github.com/Ruoyiran/DeepID/blob/master/LICENSE.md), [ArcFace](https://github.com/leondgarse/Keras_insightface/blob/master/LICENSE), [Dlib](https://github.com/davisking/dlib/blob/master/dlib/LICENSE.txt), and [SFace](https://github.com/opencv/opencv_zoo/blob/master/models/face_recognition_sface/LICENSE). Besides, age, gender and race / ethnicity models were trained on the backbone of VGG-Face with transfer learning. Licence types will be inherited if you are going to use those models. Please check the license types of those models for production purposes.
```

**Comment by serengil** [comment]
If you follow the links in readme, you will get the answer. 

Detailed tutorial: https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/

Long story short:
1- Structure of VGG-Face is being used except it final layer.
2- Weights of base VGG-Face model copied as is
3- Just the last layer's weights trained from scratch with imdb-wiki dataset

So, all layers except the last one were trained by VGG-Face dataset already.
