### ISSUE TITLE
Request for Enhancement: Customizable Thresholds in Deepface.find Function

### ISSUE THREAD

**Issue by RicaredoAndrade** [serengil/deepface#972]
## Description

I've been using Deepface for testing anonymization solutions and have found it to be a powerful tool. However, I've encountered a limitation in the `Deepface.find` function that I believe could significantly enhance its usability.

### Issue

In the current implementation, the face recognition model thresholds are predefined and cannot be manually selected. This limitation poses challenges when computing the Cumulative Match Characteristic, particularly when comparing an image with all testing identities, as the predefined threshold restricts the computation of the rank for each identity.

### Enhancement Request

I propose adding a feature to the `Deepface.find` function that allows users to manually define the face recognition model threshold. This enhancement would not only expedite the computation of the Cumulative Match Characteristic but also provide users with the flexibility to test different threshold values, improving overall testing capabilities.

### Solution

Add a new parameter to the function https://github.com/serengil/deepface/blob/88814e6d2bf3a419ee09ac6b6fc23dad550e943a/deepface/DeepFace.py#L185
```python
threshold = None
```

Add it to the return https://github.com/serengil/deepface/blob/88814e6d2bf3a419ee09ac6b6fc23dad550e943a/deepface/DeepFace.py#L229
```python
threshold = None
```

Add the parameter to the function
https://github.com/serengil/deepface/blob/88814e6d2bf3a419ee09ac6b6fc23dad550e943a/deepface/modules/recognition.py#L20
```python
threshold = None
```

Adjust the threhsold value https://github.com/serengil/deepface/blob/88814e6d2bf3a419ee09ac6b6fc23dad550e943a/deepface/modules/recognition.py#L254
```python
if threshold == None:
    threshold = dst.findThreshold(model_name, distance_metric)
```

**Comment by serengil** [comment]
Seems a fair request. Will do it in a couple of days.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/974
