### ISSUE TITLE
Using GPU, detector_backend = yunet,Argument 'score_threshold' can't be treated as a float

### ISSUE THREAD

**Issue by rs0d** [serengil/deepface#973]
File "/home/admin/.local/lib/python3.10/site-packages/deepface/detectors/YuNet.py", line 86, in detect_faces
    self.model.setScoreThreshold(score_threshold)
TypeError: Argument 'score_threshold' can't be treated as a float

There is no problem with other detector_backend

**Comment by serengil** [comment]
Seems that I broken it when I want to make it clearer. Will fix it asap.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/974
