### ISSUE TITLE
Use logging level

### ISSUE THREAD

**Issue by MattPChoy** [serengil/deepface#975]
I have noticed #654 and your work to switch to use logging and really appreciate it. However, I think it would be best if you wrote your own custom logger which inherits from the python Logging module or used the python module directly. For example, I was trying to disable warning loggings, and the traditional method of setting the log level for the logger didn't work as a result of the custom implementation.

Alternatively, you should set your logging level using the effectiveLogLevel method for the logger. For the moment, I have been able to solve this by executing the following code before importing the deepface module.

```python
import logging
import os
os.environ['DEEPFACE_LOG_LEVEL'] = str(logging.ERROR)
```

**Comment by serengil** [comment]
You can manage this with current logger with setting env var. not plan to do this (soon at least)
