### ISSUE TITLE
OpenVino or other inference server

### ISSUE THREAD

**Issue by santicomp2014** [serengil/deepface#979]
HI, I'm exploring openvino and was wondering if deepface can be executed in a converted model.

Kind of what they do with huggingface optimum.

Sorry maybe the question is kind of silly.

Since there is some inference servers, I wanted to know if I can run it that way.
I was thinking openvino inference server or even  roboflow inference server.

Or directly deploy this example docker and just access the gpu for faster inference.

Thank you for any clarification.

**Comment by serengil** [comment]
No experience on openvino. You may consider to ask this in its forum.
