### ISSUE TITLE
cv:resize issue for functions.extract_faces

### ISSUE THREAD

**Issue by fechnologies-d** [serengil/deepface#980]
Hi, there seems to be an issue with the `functions.extract_faces` method (using ssd).

```
File C:\ProgramData\anaconda3\Lib\site-packages\deepface\commons\functions.py:211, in extract_faces(img, target_size, detector_backend, grayscale, enforce_detection, align)
    205 factor = min(factor_0, factor_1)
    207 dsize = (
    208     int(current_img.shape[1] * factor),
    209     int(current_img.shape[0] * factor),
    210 )
--> 211 current_img = cv2.resize(current_img, dsize)
    213 diff_0 = target_size[0] - current_img.shape[0]
    214 diff_1 = target_size[1] - current_img.shape[1]

error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'

```

**Comment by serengil** [comment]
Please share your input image.

**Comment by fechnologies-d** [comment]
Hi,

Thanks for your prompt response. For privacy reasons, I cannot share the
image. I would blur it, but that defeats the purpose.

Something I can share is the size : 729 x 384 px.

I was trying to detect face with SSD.

Thanks

**Comment by serengil** [comment]
I cannot help you then if I cannot reproduce the issue.

**Comment by serengil** [comment]
i investigated this error a little bit. The line throwing exception is trying to resize the image and it is in an if statement checking x and y dimension sizes are greater than 0: https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py#L203

So, as mentioned in the exception message `inv_scale_x > 0 in function 'cv::resize'` cannot be possible.

I found [this](https://stackoverflow.com/questions/71808474/opencv-error-215assertion-failed-inv-scale-x-0-in-function-cvresize) thread in stackoverflow. It says:

`We observed this particular error & CV Out of memory error randomly even though input image data is provided correctly`

**Comment by fechnologies-d** [comment]
Thanks a lot, I'll look into it. Seems the issue is with CV. Would
appreciate a None check in the future.

Thanks again.

**Comment by serengil** [comment]
If img is None, then we cannot access its shape arguments. It must not be None if this block is satisfied.

https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py#L203

**Comment by fechnologies-d** [comment]
Oh ok. I've added a try except block to avoid the error. Some threads
suggest it's a memory issue but the error seems to be exclusive to that one
image in my dataset.


Anyway, I guess it's not an issue with your package . Thanks

**Comment by Merligus** [comment]
Hi, when running DeepFace.find(), one of the images in my database (db/) was detected with a shape of (1, 294, 3) (height=1px, width=294px). This causes the resize factor calculation (line 88 in deepface/modules/preprocessing.py) to produce dsize=(160, 0):

```py
factor = min(160 / 294, 160 / 1)  # = min(0.54, 160) → 0.54
dsize = (294 * 0.54, 1 * 0.54)    # = (160, 0)
```

Calling cv2.resize(img, dsize=(160, 0)) then fails because dsize cannot have a zero dimension.

The error was caused running the following code:

```py
dfs = DeepFace.find(
    img_path="image.png",
    db_path="./db/",
    model_name="Facenet512",
    detector_backend="ssd",
    enforce_detection=False,
    align=False,
)
```

I don't know if it makes sense but here is a suggestion to add before the resize:

```py
if 0 in dsize:
    dsize = (max(1, dsize[0]), max(1, dsize[1])
```
