### ISSUE TITLE
similar group faces

### ISSUE THREAD

**Issue by rajkabariya-dignizant** [serengil/deepface#981]
Hello sir,
currently, I developing a system like Google's similar face group, but the time to generate a face representation embedding file is too high. so is it possible instead of deleting the representation file when a new image or entity is uploaded in db, we can add new representation embedding data in the old file so time will decrease?
if yes, then also mention the method.

**Comment by serengil** [comment]
You do not have to delete the datastore anymore.

**Comment by rajkabariya-dignizant** [comment]
no, sir my question is not about datastore but about embedding pickle file.

**Comment by serengil** [comment]
Okay embedding pickle = datastore. You don't have to delete it manually anymore. DeepFace now handles adding removing new images into a folder.

**Comment by serengil** [comment]
It should update pickle automatically. Can you share print screens?
