### ISSUE TITLE
race_model_single_batch.h5 architecture and dataset 

### ISSUE THREAD

**Issue by ahmadsadeed** [serengil/deepface#992]
Could you please provide some details on the model and dataset used to train the race classifier? Appreciate it.

**Comment by serengil** [comment]
Follow the links in read me of the repo. It has its own tutorial.

**Comment by ahmadsadeed** [comment]
Thanks, I was able to find that you trained a VGG-Face model on FairFace dataset. One question about using different backends: why do you think using one backend instead of another one leads to different race classification? For example, on the same image, using "retinaface" vs "mtcnn" as backend, gives two different race for a person (one says Asian, another gives Black). Could it be just because we get different types of bounding boxes and the extracted 224x224 face is a bit different? How do you think we could improve this?
