### ISSUE TITLE
Using service.verify() on the same picture will result in different distances

### ISSUE THREAD

**Issue by helloliu01** [serengil/deepface#995]
I want to handle multiple photos in the same http request。For example, upload 5 photos (img1, img2, img3, img4, img5) and compare img2, img3, img4, img5 with img1 respectively. I modified the routes.py code so that it can do this in the thread pool. 
However, using multi-threading will cause the distance of some pictures to be unstable. 
For example, I tested the two pictures in the picture twice, but the results were inconsistent. The results of the other four and three pictures were consistent. 
<img width="1918" alt="verify_result" src="https://github.com/serengil/deepface/assets/55915175/c164302b-17f8-48d4-a6ee-682771e4cab5">

Below is my modified code.

import json
from flask import Blueprint, request
import service
from concurrent.futures import ThreadPoolExecutor
import logging
from logging.handlers import TimedRotatingFileHandler

log_path = "/home/shared/log/deepface_verify.log"
logger = logging.getLogger(__name__)
handler = TimedRotatingFileHandler(log_path, when='midnight', interval=1, backupCount=14)
handler.setFormatter(logging.Formatter('%(asctime)s %(name)s %(levelname)s %(message)s', datefmt='%Y-%m-%d %H:%M:%S'))
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)

blueprint = Blueprint("routes", __name__)

pool = ThreadPoolExecutor(max_workers=2)

ret_format = '{"code": %d, "message": "%s", "data": %s}'

@blueprint.route("/")
def home():
    return "<h1>Welcome to DeepFace API!</h1>"

@blueprint.route("/represent", methods=["POST"])
def represent():
    input_args = request.get_json()

    if input_args is None:
        return {"message": "empty input set passed"}

    img_path = input_args.get("img")
    if img_path is None:
        return {"message": "you must pass img_path input"}

    model_name = input_args.get("model_name", "VGG-Face")
    detector_backend = input_args.get("detector_backend", "opencv")
    enforce_detection = input_args.get("enforce_detection", True)
    align = input_args.get("align", True)

    obj = service.represent(
        img_path=img_path,
        model_name=model_name,
        detector_backend=detector_backend,
        enforce_detection=enforce_detection,
        align=align,
    )

    return obj

def verify_single_image(img1_path, img2_path, model_name, detector_backend, distance_metric, enforce_detection, align,
                        threshold):
    result = 0
    try:
        res = service.verify(
            img1_path=img1_path,
            img2_path=img2_path,
            model_name=model_name,
            detector_backend=detector_backend,
            distance_metric=distance_metric,
            align=align,
            enforce_detection=enforce_detection,
        )
        distance = res['distance']
        logger.info(f'verify res:{res}')
        logger.info(f'{img2_path} distance={distance}')
        result = 1 if distance < threshold else 0
    except Exception:
        logger.error(f"exception raised.{img2_path}")
    return result

@blueprint.route("/verify", methods=["POST"])
def verify():
    input_args = request.get_json()

    if input_args is None:
        return {"message": "empty input set passed"}

    img1_path = input_args.get("img1_path")
    img2_paths = input_args.get("img2_paths")

    if img1_path is None:
        return {"message": "you must pass img1_path input"}

    if img2_paths is None:
        return {"message": "you must pass img2_path input"}

    model_name = input_args.get("model_name", "ArcFace")
    detector_backend = input_args.get("detector_backend", "yolov8")
    enforce_detection = input_args.get("enforce_detection", True)
    distance_metric = input_args.get("distance_metric", "euclidean_l2")
    align = input_args.get("align", True)
    threshold = input_args.get("threshold", 1.2)
    image_result = {}
    image_future = {}
    for img in img2_paths:
        image_future[img] = pool.submit(verify_single_image,
                                        img1_path=img1_path,
                                        img2_path=img,
                                        model_name=model_name,
                                        detector_backend=detector_backend,
                                        distance_metric=distance_metric,
                                        align=align,
                                        enforce_detection=enforce_detection,
                                        threshold=threshold
                                        )

    for key, value in image_future.items():
        image_result[key] = value.result()

    img_res_json = json.dumps(image_result)
    logger.error(f'result: {img_res_json}')
    return ret_format % (0, 'success', img_res_json)

@blueprint.route("/analyze", methods=["POST"])
def analyze():
    input_args = request.get_json()

    if input_args is None:
        return {"message": "empty input set passed"}

    img_path = input_args.get("img_path")
    if img_path is None:
        return {"message": "you must pass img_path input"}

    detector_backend = input_args.get("detector_backend", "opencv")
    enforce_detection = input_args.get("enforce_detection", True)
    align = input_args.get("align", True)
    actions = input_args.get("actions", ["age", "gender", "emotion", "race"])

    demographies = service.analyze(
        img_path=img_path,
        actions=actions,
        detector_backend=detector_backend,
        enforce_detection=enforce_detection,
        align=align,
    )

    return demographies

**Comment by serengil** [comment]
Can you get same results if you run this service many times with the original version of routes.py?

**Comment by helloliu01** [comment]
> Can you get same results if you run this service many times with the original version of routes.py?

This problem will not occur if you use the original routes.py.

**Comment by serengil** [comment]
would you please test this for detector_backend="skip"

if results become same in this experiment, then issue is coming from opencv
otherwise, it is coming from tensorflow.

**Comment by serengil** [comment]
Closed due to inactivity
